// Races, part 2: Horde, and other peoples of the world.
window.RACES = window.RACES || [];
window.RACES.push(
{id:'orcs',n:'Orcs',f:'horde',tag:'Core race \u00b7 2004',home:'Draenor',cap:'Orgrimmar',lead:'Thrall; the Horde is now led by a council',
 s:"Shamanistic clans from the world of Draenor. Kil'jaeden, working through Gul'dan, corrupted them with demon blood and turned them into the Horde that invaded Azeroth. After their defeat they were held in internment camps until Thrall freed them, broke the blood curse and built a new Horde in Kalimdor.",
 h:[['Before \u221210',"Orc clans live on Draenor as hunters and shamans, beside the draenei."],
    ['\u221210 to \u22123',"Gul'dan's warlocks and Mannoroth's blood corrupt the clans, and they slaughter the draenei."],
    ['Year 0 onward',"The Horde invades Azeroth, wins the First War and loses the Second. Survivors are held in internment camps."],
    ['Year 20',"Thrall frees the orcs and founds Durotar. Grom breaks the blood curse by killing Mannoroth."],
    ['Mists of Pandaria',"Garrosh's tyranny ends in the Siege of Orgrimmar."],
    ['Battle for Azeroth',"Saurfang's duel ends Sylvanas's rule. A council now leads the Horde."]],
 fig:['thrall','durotan','draka','orgrim','grom','garrosh','guldan','nerzhul','blackhand','saurfang','aggra','garona'],
 more:['Eitrigg','Rexxar (half-orc champion)'],
 kin:[['maghar','Orcs who escaped corruption'],['ogres','Old neighbors on Draenor'],['draenei','Old neighbors, then victims']],
 wiki:'Orc'},
{id:'forsaken',n:'Forsaken',f:'horde',tag:'Core race \u00b7 2004',home:'Tirisfal Glades',cap:'Undercity (lost)',lead:'The Desolate Council',
 s:"Undead who broke free of the Lich King when his hold weakened. Sylvanas led them out of the Scourge, made the ruins of Lordaeron their home and brought them into the Horde. After she abandoned them, they chose to govern themselves.",
 h:[['Year 20',"The plague kills the people of Lordaeron, and they rise as the Scourge."],
    ['Year 21',"The Lich King's grip weakens. Sylvanas frees the Forsaken and takes Lordaeron."],
    ['Wrath of the Lich King',"Grand Apothecary Putress unleashes a plague at the Wrathgate, and the dreadlord Varimathras seizes the Undercity."],
    ['Cataclysm',"Val'kyr let Sylvanas raise new Forsaken, and they invade Gilneas."],
    ['Battle for Azeroth',"The Undercity is lost in the Battle for Lordaeron. Sylvanas later abandons the Horde."],
    ['After Battle for Azeroth',"The Forsaken form the Desolate Council to govern themselves."]],
 fig:['sylvanas','nathanos','calia','arthas'],
 more:['Lilian Voss','Grand Apothecary Putress'],
 kin:[['humans','Most were humans of Lordaeron']],
 wiki:'Forsaken'},
{id:'tauren',n:'Tauren',f:'horde',tag:'Core race \u00b7 2004',home:'Mulgore',cap:'Thunder Bluff',lead:'High Chieftain Baine Bloodhoof',
 s:"Huge, peaceful nomads who revere the Earth Mother. Long hunted by the centaur, the Bloodhoof tribe found a home in Mulgore with Thrall's help and joined the Horde, where they have often been its conscience.",
 h:[['\u221210,000',"Tauren led by Huln Highmountain fight beside the night elves in the War of the Ancients."],
    ['Year 20',"Cairne Bloodhoof's tribe, hunted by centaur, settles Mulgore with Thrall's help and joins the Horde."],
    ['Cataclysm',"Cairne dies in his duel with Garrosh. Baine wins back Thunder Bluff from the Grimtotem tribe."],
    ['Battle for Azeroth',"Sylvanas imprisons Baine for helping Jaina's family."]],
 fig:['cairne','baine'],
 more:['Hamuul Runetotem (archdruid)','Magatha Grimtotem'],
 kin:[['highmountain','Cousins from the Broken Isles']],
 wiki:'Tauren'},
{id:'trolls',n:'Trolls',f:'horde',tag:'Core race \u00b7 2004',home:'The Echo Isles',lead:'The Darkspear tribe',
 s:"Among Azeroth's oldest peoples, trolls once ruled vast empires such as the Zandalari, Gurubashi and Amani. The playable trolls are the Darkspear tribe. Thrall saved them, and their leader Vol'jin later became warchief.",
 h:[['Before \u221210,000',"Troll empires rule ancient Kalimdor. Trolls who settle by the Well of Eternity become the night elves."],
    ['\u22122,800',"The Amani are defeated by humans and elves in the Troll Wars."],
    ['Year 20',"Thrall rescues the Darkspear, and they join the Horde."],
    ['Mists of Pandaria',"Vol'jin leads the rebellion against Garrosh and becomes warchief."],
    ['Legion',"Vol'jin dies after the Broken Shore."]],
 fig:['voljin','talanji'],
 more:["Sen'jin (Vol'jin's father)",'Rokhan',"Zul'jin (Amani warlord)"],
 kin:[['zandalari','The oldest tribe, keepers of troll history'],['nightelves','Descendants'],['haranir','Ancestors, says Elder Hagar']],
 wiki:'Troll'},
{id:'bloodelves',n:'Blood elves',nn:"Sin'dorei",f:'horde',tag:'Core race \u00b7 2007',home:"Quel'Thalas",cap:'Silvermoon City',lead:"Regent Lord Lor'themar Theron",
 s:"Descendants of the Highborne exiled from Kalimdor, who founded Quel'Thalas around the Sunwell as the high elves. When the Scourge destroyed their kingdom, the survivors took the name blood elves to honor the dead, followed Kael'thas to Outland and later joined the Horde.",
 h:[['\u22127,300',"The Highborne are exiled from Kalimdor and sail east."],
    ['\u22126,800',"They found Quel'Thalas and create the Sunwell."],
    ['\u22122,800',"They help humans win the Troll Wars and teach them magic."],
    ['Year 20',"Arthas destroys Silvermoon and uses the Sunwell to raise Kel'Thuzad."],
    ['The Burning Crusade',"The blood elves join the Horde. M'uru's essence relights the Sunwell."],
    ['Midnight',"The elves defend the Sunwell against Xal'atath, and it is reborn as the Dawnwell."]],
 fig:['anasterian','kaelthas','lorthemar','liadrin','sylvanas','alleria','vereesa','muru'],
 more:["Grand Magister Rommath"],
 kin:[['nightelves','Ancestors'],['voidelves','An exiled offshoot'],['nightborne','Highborne cousins'],['humans','Old allies'],['haranir','Distant ancestors, says Elder Hagar']],
 wiki:'Blood elf'},
{id:'goblins',n:'Goblins',f:'horde',tag:'Core race \u00b7 2010',home:'Kezan',cap:'Bilgewater Harbor',lead:'Trade Prince Gazlowe',
 s:"Clever, money-loving inventors from the isle of Kezan. They were slaves of the Zandalari, mining an ore called kaja'mite that sharpened their minds. Most goblins sell to anyone, but the Bilgewater Cartel joined the Horde.",
 h:[['Ancient',"The Zandalari enslave the goblins to mine kaja'mite on Kezan. The ore makes them cunning."],
    ['Second War',"Goblin cartels sell their machines to the Horde."],
    ['Cataclysm',"Kezan's volcano erupts. Thrall takes in the Bilgewater Cartel, and they join the Horde."],
    ['The War Within',"Heroes face Gallywix in the Liberation of Undermine."]],
 fig:[],
 more:['Jastor Gallywix (trade prince)','Gazlowe'],
 kin:[['zandalari','Their former masters']],
 wiki:'Goblin'},
{id:'nightborne',n:'Nightborne',nn:"Shal'dorei",f:'horde',tag:'Allied race \u00b7 2018',home:'Suramar, Broken Isles',cap:'Suramar City',lead:'First Arcanist Thalyssra',
 s:"Highborne who turned against the Legion during the War of the Ancients and sealed their city of Suramar under a shield for ten thousand years. Their dependence on the magical Nightwell slowly changed them. When Elisande sided with the Legion, Thalyssra's rebellion freed them and they joined the Horde.",
 h:[['\u221210,000',"Elisande and the Highborne of Suramar turn on the Legion and create the Nightwell."],
    ['\u221210,000 to Legion',"A shield hides Suramar for ten thousand years, and the elves grow dependent on the Nightwell."],
    ['Legion',"Elisande allies with the Legion. Thalyssra's rebels overthrow her."],
    ['Battle for Azeroth',"The Nightborne join the Horde as an allied race."],
    ['Midnight',"Thalyssra brings an arcan'dor fruit to help form the Dawnwell."]],
 fig:['thalyssra','elisande'],
 more:[],
 kin:[['nightelves','Highborne who never left'],['bloodelves','Highborne cousins']],
 wiki:'Nightborne'},
{id:'highmountain',n:'Highmountain tauren',f:'horde',tag:'Allied race \u00b7 2018',home:'Highmountain, Broken Isles',cap:'Thunder Totem',lead:'Mayla Highmountain',
 s:"Antlered tauren of the Broken Isles, descended from Huln Highmountain, who fought beside the night elves in the War of the Ancients. Cenarius blessed his people with their moose-like antlers. During Legion three of their four tribes reunited after the Bloodtotem defected to the Legion, and they joined their Kalimdor cousins in the Horde.",
 h:[['\u221210,000',"Huln Highmountain helps the night elf resistance and receives Cenarius's blessing."],
    ['Legion',"The drogbar steal the Hammer of Khaz'goroth and split the four tribes. Heroes help the Highmountain, Rivermane and Skyhorn reunite, while the Bloodtotem join the Legion."],
    ['Battle for Azeroth',"They join the Horde as an allied race."]],
 fig:['cenarius'],
 more:['Huln Highmountain (ancient hero)','Mayla Highmountain'],
 kin:[['tauren','Cousins']],
 wiki:'Highmountain tauren'},
{id:'maghar',n:"Mag'har orcs",f:'horde',tag:'Allied race \u00b7 2018',home:'Draenor (Nagrand)',lead:"Overlord Geya'rah",
 s:"Mag'har means \"uncorrupted.\" These brown-skinned orcs never drank demon blood. The playable Mag'har come from the alternate Draenor, where Garrosh's meddling kept the clans free of the Legion. When Yrel's Lightbound drove them out, they came to Azeroth and joined the Horde.",
 h:[['Before Year 0',"On Draenor, Geyah quarantines orcs sick with the red pox in Garadar, so they never drink demon blood."],
    ['The Burning Crusade',"Thrall meets the Mag'har of Nagrand, including his grandmother Geyah."],
    ['Warlords of Draenor',"On an alternate Draenor, Garrosh's Iron Horde refuses the Legion."],
    ['Battle for Azeroth',"Yrel's Lightbound drive them out. Led by Geya'rah, they join the Horde."]],
 fig:['grom','garrosh','yrel','durotan','draka'],
 more:["Geya'rah (Overlord, daughter of Durotan on alternate Draenor)"],
 kin:[['orcs','The same people, uncorrupted']],
 wiki:"Mag'har orc"},
{id:'zandalari',n:'Zandalari trolls',f:'horde',tag:'Allied race \u00b7 2019',home:'Zandalar',cap:"Dazar'alor",lead:'Queen Talanji',
 s:"The oldest and proudest troll empire, keepers of troll history and masters of the loa spirits. They once ruled the ancient world and enslaved the goblins. After King Rastakhan fell defending his city, his daughter Talanji led Zandalar into the Horde.",
 h:[['Ancient',"The first trolls build the temple city of Zuldazar and fight the aqir."],
    ['After the Sundering',"The Zandalari explore the new seas, enslave the goblins and twice battle the blood god Hakkar."],
    ['Mists of Pandaria',"King Rastakhan's Zandalari attack Pandaria to restore the troll empires."],
    ['Battle for Azeroth',"Rastakhan dies in the Battle of Dazar'alor. Talanji leads Zandalar into the Horde."]],
 fig:['talanji','ghuun'],
 more:['King Rastakhan','Zul the Prophet'],
 kin:[['trolls','The oldest tribe'],['goblins','Their former slaves'],['vulpera','Desert neighbors in Zandalar']],
 wiki:'Zandalari troll'},
{id:'vulpera',n:'Vulpera',f:'horde',tag:'Allied race \u00b7 2020',home:"Vol'dun, Zandalar",lead:'Kiro, caravan leader',
 s:"Nomadic fox people of the deserts of Vol'dun, who travel in caravans and live by scavenging and trading. Long hunted and enslaved by the snake-like sethrak, they fought back with the Horde's help and then joined it.",
 h:[['Before Battle for Azeroth',"The sethrak hunt and enslave the vulpera caravans."],
    ['Battle for Azeroth',"With Horde help the vulpera fight back, and they later join the Horde as an allied race."]],
 fig:[],
 more:[],
 kin:[['zandalari','Neighbors in Zandalar']],
 wiki:'Vulpera'},

// Other peoples of the world
{id:'dragons',n:'Dragons',f:'other',tag:'Dragonflights',home:'The Dragon Isles',cap:'Valdrakken',lead:'Alexstrasza, the Dragon Queen',
 s:"Five dragonflights, each led by an Aspect empowered by the titans to protect Azeroth: red for life, blue for magic, green for dreams, bronze for time and black for the earth. The black Aspect's betrayal as Deathwing shaped ten thousand years of history. In Dragonflight a sixth Aspect, Vyranoth, became the Aspect of Storms.",
 h:[['Ancient',"The proto-dragon Galakrond is destroyed. The titans' keepers make five dragons into Aspects."],
    ['\u221210,000',"Neltharion betrays the other Aspects with the Dragon Soul, and the dragons leave the Dragon Isles."],
    ['Second War',"The Dragonmaw clan enslaves Alexstrasza and her red dragons."],
    ['Cataclysm',"The Aspects spend their powers to destroy Deathwing."],
    ['Dragonflight',"The dragons return to the Dragon Isles, and the Aspects are restored."]],
 fig:['alexstrasza','deathwing','ysera','nozdormu','malygos','kalecgos','korialstrasz','onyxia','nefarian','wrathion','sindragosa','murozond','fyrakk','chromie'],
 more:['Sabellian (black dragon)','Galakrond (proto-dragon)'],
 kin:[['dracthyr','Made from dragon essence']],
 wiki:'Dragon'},
{id:'eredar',n:'Eredar',nn:"Man'ari when corrupted",f:'other',tag:'Demons of the Legion',home:'Argus',
 s:"A gifted, magical people of Argus. Their leaders Kil'jaeden and Archimonde accepted Sargeras's offer and became demons, the commanders of the Burning Legion. Velen refused and fled with his followers, who became the draenei.",
 h:[['\u2248 \u221213,000',"Sargeras offers the eredar power. Kil'jaeden and Archimonde accept; Velen flees."],
    ['Ever since',"Corrupted eredar lead the Legion's armies across countless worlds."],
    ['Legion',"Sargeras is imprisoned and the Legion is broken, though fighting on Argus goes on."]],
 fig:['kiljaeden','archimonde','velen','sargeras'],
 more:[],
 kin:[['draenei','Those who refused Sargeras']],
 wiki:'Eredar'},
{id:'naga',n:'Naga',f:'other',tag:'Servants of the Old Gods',home:"Nazjatar, under the sea",cap:"Nazjatar",lead:'Queen Azshara',
 s:"Serpent-like descendants of the Highborne who sank with Azshara in the Sundering. N'Zoth saved them from drowning in exchange for their service and twisted their bodies into new forms.",
 h:[['\u221210,000',"Drowning with their queen, the Highborne accept N'Zoth's pact and become naga."],
    ['Year 21',"Lady Vashj's naga serve Illidan in Outland."],
    ['Battle for Azeroth',"Azshara rises from Nazjatar and is defeated in the Eternal Palace."]],
 fig:['azshara','nzoth','illidan'],
 more:['Lady Vashj'],
 kin:[['nightelves','Former Highborne']],
 wiki:'Naga'},
{id:'aqir',n:'Aqir',f:'other',tag:'Insect empires of the Old Gods',home:"Azjol-Nerub, Ahn'Qiraj, Pandaria and Azj-Kahet",
 s:"An ancient insect empire that served the Old Gods and warred with the first trolls. After its defeat it split into separate peoples: the nerubians, the qiraji and the mantid. Each has troubled Azeroth in its own era.",
 h:[['Ancient',"The aqir serve the Old Gods and fight the troll empires."],
    ['Ancient',"Defeated, they split into the nerubians of Azjol-Nerub, the qiraji of Ahn'Qiraj and the mantid of Pandaria."],
    ['\u2212975',"The War of the Shifting Sands seals the qiraji behind the Scarab Wall."],
    ['Before Year 20',"The Lich King conquers Azjol-Nerub and raises Anub'arak."],
    ['The War Within',"Queen Ansurek's nerubians of Azj-Kahet fall under Xal'atath's influence."]],
 fig:['cthun','anubarak','ansurek'],
 more:['Grand Empress Shek\u2019zeer (mantid)'],
 kin:[],
 wiki:'Aqir'},
{id:'vrykul',n:'Vrykul',f:'other',tag:'Titan-forged giants',home:'Northrend and Stormheim',
 s:"Towering warriors made by the titans' Keepers at the Forge of Wills. The Curse of Flesh made them mortal, and their cursed, smaller children who were hidden away became the ancestors of humanity. Many vrykul served the Lich King; others follow the keeper Odyn or the dark Helya.",
 h:[['Ancient',"The titans' Keepers make the vrykul. The Curse of Flesh makes them mortal."],
    ['Ancient',"King Ymiron orders cursed infants killed. Those hidden away become the first humans."],
    ['Wrath of the Lich King',"Many vrykul serve the Lich King in Northrend."],
    ['Legion',"In Stormheim, vrykul serve Odyn's Halls of Valor or Helya's Helheim."]],
 fig:['arthas'],
 more:['King Ymiron','Odyn (keeper)','Helya'],
 kin:[['humans','Descendants']],
 wiki:'Vrykul'},
{id:'ogres',n:'Ogres',f:'other',tag:'Clans of Draenor and Azeroth',home:'Draenor',
 s:"Hulking, often two-headed brutes descended from Draenor's gronn giants. They once ruled the Gorian Empire on Draenor. Many came to Azeroth with the Horde, where Gul'dan created many more of their two-headed ogre magi.",
 h:[['Ancient (Draenor)',"Ogres descend from the gronn and build the Gorian Empire."],
    ['Second War',"Gul'dan uses an old ogre ritual to create many more ogre magi."],
    ['Today',"Ogre clans like the Stonemaul and Gordunni live across Azeroth."]],
 fig:['chogall','guldan'],
 more:[],
 kin:[['orcs','Old neighbors on Draenor']],
 wiki:'Ogre'},
{id:'ethereals',n:'Ethereals',f:'other',tag:'Traders from K\u2019aresh',home:"K'aresh",
 s:"Beings of pure energy wrapped in cloth bandages. Their homeworld K'aresh was ravaged by the voidlord Dimensius, and the arcane shields meant to protect its people turned them into beings of energy. Most now roam as traders and collectors.",
 h:[['Ancient',"Dimensius invades K'aresh. Arcane shields turn its people into beings of energy, and a secret circle called the Ravel destroys the planet to stop him."],
    ['The Burning Crusade',"Ethereal traders such as the Consortium appear in Outland."],
    ['The War Within',"Heroes return to K'aresh and defeat Dimensius in Manaforge Omega."]],
 fig:['dimensius','xalatath'],
 more:['Nexus-Prince Haramad','Locus-Walker'],
 kin:[],
 wiki:'Ethereal'}
);
