// Cosmology tab. Six cosmic forces in three opposed pairs, laid out as on Blizzard's cosmology chart.
// Each force: id, n, alt, pair (its opposite), place (position on the chart), realm, s, beings[], chars[], races[], events[], text[], wiki
window.COSMOS = {
  intro: [
    "The Warcraft universe runs on six cosmic forces. They come in three opposed pairs: Light and Void, Order and Disorder, and Life and Death. Each force has a realm of its own, great powers that embody it, and a kind of magic that mortals can use. The Light reaches the world as holy magic, the Void as shadow magic, Order as arcane magic, Disorder as fel magic, Life as nature magic and Death as necromancy.",
    "Nearly every great power in the story belongs to one of them. The naaru serve the Light, and the void lords and their Old Gods serve the Void. The titans embody Order, and the demons of the Burning Legion embody Disorder. The Wild Gods belong to Life, and the Eternal Ones of the Shadowlands rule Death. When these powers collide, mortals pay the price. Fel corrupted the orcs, death magic forged the Lich King, and the night elves' arcane Well of Eternity drew the Legion to Azeroth.",
    "The forces also explain why Azeroth matters so much. Inside the planet sleeps a world-soul, an unborn titan. The Void wants to corrupt her, the Legion wanted to burn her, and the Jailer tried to drain her. The Worldsoul Saga, the story World of Warcraft is telling now, turns on her fate.",
    "The picture is still incomplete. Chronicle, Blizzard's illustrated history, says the Light came first and the Void grew from its absence. Shadowlands added the First Ones, mysterious makers who designed all six forces. Blizzard has not said how the two accounts fit together."
  ],
  chart: "Blizzard's cosmology chart, first printed in World of Warcraft: Chronicle Volume 1 and updated in Chronicle Volume 4, which covers Shadowlands, puts the Light (holy magic and the naaru) at the top and Shadow (the Void, the void lords and the Old Gods) at the bottom. Life (nature and the Wild Gods) sits at the upper left and Death (necromancy, labeled the Undead in Volume 1 and the Eternal Ones in Volume 4) at the lower right, while Disorder (fel and the Burning Legion) sits at the upper right and Order (arcane and the titans) at the lower left, so each pair faces across the center. The center circle is Reality, the physical universe, with the Emerald Dream and the Shadowlands beside it and an inner ring of six elemental circles for Spirit, Fire, Air, Decay, Earth and Water. In-universe the chart is called the titans' skewed view, and a different chart in Grimoire of the Shadowlands and Beyond puts Death at the top and the Great Cycle at the center.",
  forces: [
    {id:'light', n:"The Light", alt:"Holy Light", pair:'void', place:'top',
     realm:"A boundless sea of living energy outside the borders of reality",
     s:"The first force in Chronicle's telling, a sea of living energy that feeds holy magic and the naaru and has warred with the Void since before time.",
     beings:["Naaru", "Lightforged", "Lightspawn", "Priests and paladins"],
     chars:['xera','velen','muru','turalyon','liadrin','arator','yrel','uther'],
     races:['draenei','lightforged','humans','bloodelves','tauren'],
     events:['cosmos-5','wow-1','wow-6','wow-11'],
     text:[
      "Chronicle tells the oldest version of creation. Before the universe existed there was only the Light, a boundless sea of living energy with no time or space. As it spread, cold empty pockets opened, and from them the Void was born. The clash between the two blew open the physical universe. Shards of Light flew across the new worlds and gave them the spark of life. The first living things they woke were the elementals.",
      "Pure Light cannot exist inside the physical universe. What mortals touch is holy magic, a shade of it. Priests and paladins call on it through faith and willpower to heal, shield and smite. It burns the undead and demons. The Light does not judge who uses it. Lore describes it as a primal force that cannot tell love from hatred, so its morality comes from the one who wields it. It seeks one path and rejects all others as lies.",
      "Its best-known servants are the naaru, beings of holy energy that formed where shards of Light gathered into clouds. Lore calls them the purest known expression of the Light in the universe. The naaru K'ure saved Velen and the draenei from Sargeras. The prime naaru Xe'ra led the Army of the Light, whose warriors became the Lightforged draenei and fought the Legion for thousands of years. The captive naaru M'uru later relit the Sunwell. Mortals also found the Light on their own. Humans founded the Church of the Holy Light, and the tauren honor the sun as An'she.",
      "The Light's champions are not always gentle. Xe'ra tried to force the Light on Illidan, and he destroyed her. On an alternate Draenor, Yrel's Lightbound forced their faith on the orcs. Believers often speak of the Light's will, yet nobody knows whether it has one. Fans have also asked whether the Light has rulers to match the void lords. No such beings have appeared.",
      "In Midnight the Light stands at the center of the war. When Xal'atath attacked the Sunwell, Lady Liadrin prayed for help, and the Vanguard of the Light arrived through the well. The one who answered her was Azeroth herself. Later Xal'atath turned the Sunwell into a font of Void called the Darkwell. The united elves cleansed it with holy Light and gifts from each of their peoples, including a Void crystal to keep it in balance, and it became the Dawnwell."
     ],
     wiki:'Light'},

    {id:'void', n:"The Void", alt:"Shadow", pair:'light', place:'bottom',
     realm:"The Void, outside the borders of reality, ruled by the void lords",
     s:"The hungry darkness born where the Light dimmed, ruled by void lords who made the Old Gods to turn a sleeping titan into a dark titan.",
     beings:["Void lords", "Old Gods", "Faceless ones", "Voidwalkers", "Fallen naaru", "Domanaar"],
     chars:['xalatath','dimensius','nzoth','yshaarj','cthun','yogg','lura','alleria'],
     races:['voidelves','ethereals','aqir','naga'],
     events:['cosmos-3','wow-7','wow-10','wow-11'],
     text:[
      "The Void, also called Shadow, is the Light's opposite. Chronicle says it formed in cold pockets where the Light had dimmed, a vampiric force that wants to devour all energy and turn creation in on itself. Like the Light, it lies outside the borders of reality. Inside the universe it appears as shadow magic. That power is real, but it breeds a hunger for more, and the Void is hostile to life and sanity. Lore still calls it a primal force. Shadow priests and the void elves use it without serving the void lords.",
      "The void lords rule the Void. They are beings of pure shadow who want to devour all matter and energy. Only the strongest can enter the physical universe, and only weakened and for a short time, because their energy seeps away. Dimensius the All-Devouring, who ravaged the ethereals' world of K'aresh, was one of them. Even he was described as a mere fragment of a true void lord's power.",
      "Because they cannot stay in reality, the void lords wanted an agent. They had failed to corrupt any awake titan, so they made the Old Gods and flung them across the cosmos, hoping some would strike worlds that held sleeping world-souls. A corrupted world-soul would wake as a dark titan able to devour creation. Four Old Gods struck Azeroth: Y'Shaarj, C'Thun, Yogg-Saron and N'Zoth. All four are now dead, along with G'huun, whom the titans made by accident.",
      "The Void's servants do not always agree. Xal'atath, once the herald of Dimensius, fought the Old Gods and later helped Azeroth's heroes defeat her old master so she could take his power. The Void is also said to see every possible future and to accept every path as true. Its servants call Death the true enemy, because Death would end all those possibilities. N'Zoth once spoke of six seats at a high table and six hungry mouths, one of which would consume the rest.",
      "Fallen naaru show how close the two opposites run. A naaru that loses its Light becomes a creature of the Void. L'ura fell this way, and on Argus Alleria Windrunner took in its essence. In Midnight Xal'atath tore L'ura out of Alleria and used it to corrupt the Sunwell. Alleria and her husband Turalyon were lost to the Void at the Voidspire, and their fate is unknown."
     ],
     wiki:'Void'},

    {id:'order', n:"Order", alt:"Arcane", pair:'disorder', place:'lower-left',
     realm:"The ordered systems of the physical universe; titan souls are hinted to return to a plane of Order",
     s:"The force of structure and arcane magic, embodied by the titans, who order worlds while they search for sleeping world-souls.",
     beings:["Titans", "Keepers and other titan-forged", "Constellar", "Arcane elementals"],
     chars:['amanthul','aggramar','azeroth','malygos','kalecgos','khadgar','azshara','elisande'],
     races:['earthen','dwarves','gnomes','nightborne'],
     events:['cosmos-1','cosmos-4','ancients-0','wow-12'],
     text:[
      "Order governs the structure of the physical universe. Mortals meet it as arcane magic, a cold and precise power that bends time and space and controls the flow of mana. It is extremely volatile and takes great focus to wield. Ley lines carry it through Azeroth like blood vessels. Even time is described as a construct of Order. The titan language uses the same word for created and ordered, and to the titans' servants nothing truly exists until it has been ordered.",
      "The titans are Order's great powers. Each is a living world made of arcane energy and the raw matter of creation, born when a world-soul wakes. Arcane is their lifeblood. The Well of Eternity was Azeroth's own arcane blood, pooled in a wound in her surface. Titans are described as unable to conceive of evil, and mature titans cannot be corrupted by the void lords. Their weakness is fel, the arcane's opposite. Sargeras used it to destroy the bodies of his own Pantheon.",
      "The Pantheon of Order, led by Aman'Thul, ordered world after world. It calmed elementals, shaped land and seeded life to draw out hidden world-souls. It left behind titan-forged servants and machines that could wipe a world clean if it fell into disorder. On Azeroth the keepers built Ulduar, and the earthen built the Worldcore, the vault that shields the world-soul. Dwarves and gnomes descend from titan-forged reshaped by Yogg-Saron's Curse of Flesh.",
      "Order shaped mortal magic too. The Highborne of the night elves grew obsessed with the Well's power, and their reckless use of it drew the Burning Legion. The high elves and the humans of Dalaran later built kingdoms on arcane study. The titan Norgannon gave the blue dragons their mastery of magic through Malygos, and Kalecgos later became their Aspect.",
      "Shadowlands complicated the titans' image. The First Ones gave the titans gifts in a realm called Zereth Ordus, and the keeper Odyn hid this from mortals. Brokers of the Shadowlands accuse the titans of taking credit for a cosmos they only inherited. The Last Titan, the next expansion, promises a conspiracy that challenges what mortals believe about the titans' intentions and Azeroth's true nature. What the Pantheon really wants with Azeroth has not been revealed."
     ],
     wiki:'Order'},

    {id:'disorder', n:"Disorder", alt:"Fel", pair:'order', place:'upper-right',
     realm:"The Twisting Nether, the chaotic astral plane between worlds",
     s:"The force of chaos, felt as fel magic and embodied by demons, most of them gathered into Sargeras's Burning Legion.",
     beings:["Demons", "Burning Legion", "Man'ari eredar", "Pit lords", "Entropic elementals"],
     chars:['sargeras','kiljaeden','archimonde','mannoroth','illidan','guldan','grom','kaelthas'],
     races:['eredar','orcs','bloodelves'],
     events:['cosmos-2','ancients-1','kingdoms-8','wow-6'],
     text:[
      "Disorder, also called Chaos, is the opposite of Order. In the physical universe it appears as fel magic, the green fire of demons and warlocks. Fel is destructive and addictive. It draws its power from the life of living beings and consumes their souls. Those who use it often change, growing horns, spikes or glowing eyes, and some become demons outright.",
      "Disorder's home is the Twisting Nether, the astral plane between worlds. Chronicle says it formed from the most unstable energies of creation, where Light and Void bled together. Its chaos gave birth to the first demons. A demon slain in the physical world returns to the Nether and in time takes a new body, memories intact. It can only truly die in the Nether or where the Nether's energy leaks into the world. Some demons are neutral. Observers, for example, serve anyone who lets them study the mysteries of the universe.",
      "Most demons were once mortal. Sargeras, the fallen champion of the titans, gathered them into the Burning Legion to burn every world before the Void could corrupt it. The eredar of Argus became its commanders under Kil'jaeden and Archimonde. Fel let Sargeras overpower his own family, because the titans are made of arcane and are uniquely vulnerable to its opposite.",
      "Azeroth's history is full of the Legion's work. Queen Azshara opened the way for it during the War of the Ancients. Kil'jaeden corrupted the orcs of Draenor, who drank Mannoroth's blood and came through the Dark Portal. The Legion created the Lich King and invaded Azeroth three times in all. Illidan Stormrage took demonic power to fight demons, and his demon hunters still wield fel. Azeroth is the only world the Legion is known to have failed to conquer.",
      "The Burning Crusade ended on Argus. Azeroth's heroes and the Army of the Light freed the titans' spirits, and the restored Pantheon imprisoned Sargeras in the Seat of the Pantheon. As a last act he drove his sword into Azeroth at Silithus and wounded the world-soul. The Legion has had no structured leadership since, though demons and fel remain. In Midnight, a dungeon beneath Silvermoon reveals blood elves still hiding fel relics and demons from the Burning Crusade era."
     ],
     wiki:'Disorder'},

    {id:'life', n:"Life", alt:"Nature", pair:'death', place:'upper-left',
     realm:"The Emerald Dream and the Realms of Life",
     s:"The force of growth and renewal, felt as nature magic and tied to the Emerald Dream, the Wild Gods and the moon goddess Elune.",
     beings:["Wild Gods", "Ancients", "Druids", "Dryads and keepers of the grove", "Green dragonflight"],
     chars:['elune','eonar','cenarius','malfurion','tyrande','ysera','alexstrasza'],
     races:['nightelves','tauren','worgen','trolls','haranir'],
     events:['cosmos-4','ancients-2','wars-9','wow-9'],
     text:[
      "Life promotes growth and renewal in all things. In the physical universe it appears as nature magic, the power of druids, who use it to heal and to keep the world in balance. Its great realm on Azeroth is the Emerald Dream, a spirit world that shows how the planet might look if thinking beings had never changed it. Druids walk the Dream for years at a time while their bodies sleep.",
      "The Wild Gods are Life's guardians in the physical world. Most look like enormous animals, such as Goldrinn the wolf, Ursoc the bear and Aviana, mistress of birds. Cenarius, the forest lord, taught Malfurion Stormrage the druid's path. The troll loa and the August Celestials of Pandaria are counted among these great spirits. On Azeroth many emerged from the enclaves of the keeper Freya, who bound their spirits to the Emerald Dream at Mount Hyjal. Wild Gods live on other worlds too, with no titan help. When one dies, its spirit rests in Ardenweald in the Shadowlands, then returns through the Dream to be reborn.",
      "Life and Death are bound together. The Emerald Dream and Ardenweald are described as two blooms on one tree. The Dream holds the spring and summer of life, and Ardenweald its autumn and winter. The brokers of the Shadowlands believe the First Ones made this endless cycle the center of their design.",
      "Elune, the night elves' moon goddess, is the most mysterious figure tied to Life. The Primus called her the sister and counterpart of the Winter Queen, ruler of Ardenweald, and said she dwells in the Realms of Life. Lore names a Pantheon of Life, but it has never been shown. Her moonlight works as holy magic, and Tyrande teaches that the Light of Elune and the Holy Light are closely related. Velen once suggested Elune might be a naaru, and Khadgar found a tome hinting that she made the prime naaru. None of this is confirmed.",
      "The titans valued Life but did not fully trust it. Eonar, the titan of life, blessed Alexstrasza and Ysera as Aspects. She also planted a branch of Elune's Mother Tree on Azeroth. Aman'Thul had it destroyed, because to him Life was uncontrolled chaos. In Dragonflight the stirring world-soul raised new life on the Dragon Isles, and the new World Tree Amirdrassil bloomed."
     ],
     wiki:'Life'},

    {id:'death', n:"Death", alt:"Necromancy", pair:'life', place:'lower-right',
     realm:"The Shadowlands, beyond the Veil at the edge of reality",
     s:"The force of endings and entropy, felt as necromancy and ruled from the Shadowlands by the Eternal Ones.",
     beings:["Eternal Ones", "Kyrian", "Necrolords", "Night fae", "Venthyr", "Undead"],
     chars:['jailer','arbiter','winterqueen','denathrius','sylvanas','arthas','bolvar','kelthuzad'],
     races:['forsaken','vrykul'],
     events:['cosmos-0','wars-4','wars-7','wow-8'],
     text:[
      "Death balances Life. It pushes everything toward decay and oblivion, and it breeds despair in mortal hearts. Seen from the cosmos it is more than an ending. Death is an eternal force that also offers new beginnings. In the physical universe it appears as necromantic magic, which raises and commands the dead. The undead are its main presence among the living. Their souls are only loosely bound to their bodies, which is also why the Light burns them.",
      "Its realm is the Shadowlands, an endless plane of afterlives behind a barrier called the Veil. When a mortal dies, the kyrian carry the soul to Oribos, where the Arbiter judges it and sends it to an afterlife. Souls bring anima, the essence of a life's deeds, and anima keeps every realm of the Shadowlands alive. Some souls go elsewhere. Demons return to the Nether, Wild Gods pass through Ardenweald to the Emerald Dream, and liches return to their phylacteries.",
      "Death also stands apart from time. Time is a construct of Order, while Death deals in eternity. A soul in the Shadowlands can feel ages pass while only months go by among the living. The Shadowlands is the cosmic realm mortals have seen most closely, so it offers the clearest view of how the First Ones built things.",
      "Death reached deep into Azeroth's history through the Jailer. Zovaal, the first Arbiter, was locked in the Maw, and from there he worked through others. Sire Denathrius made the nathrezim, the dreadlords, who posed as demons of the Legion while secretly serving Death. They filled the world-soul of Argus with death magic, and when Argus died its soul broke the Arbiter. The Lich King, forged with the Helm of Domination, also served the Jailer's plan. Domination itself is a death magic, a runic language the Primus invented to imprison his brother.",
      "Death clashes with the other forces too. The forces of the Light once attacked Revendreth after catching nathrezim spies in their ranks, and the scorched battlefield is still called the Ember Ward. The Void once attacked the Shadowlands and badly damaged Bastion before the kyrian held it off. After Zovaal fell, the kyrian Pelagos became the new Arbiter and the cycle resumed. Death remains a mystery to most of Azeroth's people, since few of them went to the Shadowlands and not all who did came back."
     ],
     wiki:'Death'}
  ],
  sections: [
    ["How the forces meet and clash", [
      "Blizzard tells two creation stories. Chronicle, written in-universe from records kept by the titans' servants, begins with the Light alone. The Void grew from its absence, and their clash made the physical universe and the Twisting Nether. Shadowlands added an older layer. The Eternal Ones believe the universe began with six First Ones: Light, Shadow, Order, Disorder, Life and Death. They fought until their battle settled into balance, and each gave part of itself to a shared pattern. The broker Firim read the First Ones' writings the same way. In his view, other things grew where the forces intersect, and the forces stay locked in jealous conflict because each received only part of the gifts. A Shadowlands broker even calls Chronicle titan propaganda. Blizzard has not said which account is closer to the truth.",
      "Each pair has its own scope. Light and Void dwell outside reality and reach the universe only as shades of themselves. Order and Disorder govern the universe's systems. Life and Death hold sway over every living thing. Opposites counter each other. Fel and arcane cancel each other out, and holy magic burns the undead. The four elements of fire, air, earth and water build all matter, joined by Spirit, which binds living things together, and Decay.",
      "The forces rarely line up neatly. Sargeras, champion of Order, turned to Disorder to fight the Void. The nathrezim of Death steered both the Legion and the Void. The naaru fight the Void and Disorder, and they also work to keep Death in its place.",
      "Several questions stay open. Some Shadowlands sources hint at a seventh force. Firim wrote of a force he called the fractals, and a relic in Korthia whispers that a seventh covets what the six hold. Firim also feared that Zovaal's attack weakened the pattern that holds the six in balance. The threat Zovaal claimed to foresee has never been named."
    ]],
    ["Titans and world-souls", [
      "A titan begins as a world-soul. World-souls were spun out at the birth of the universe and drifted until they found the warmth of a sun. A planet formed around each one to shield it. The soul sleeps for ages in the planet's fiery core and fills the world with Spirit energy while life rises and falls on its surface. When it finally wakes, it becomes a titan, a living world of arcane power. Aman'Thul was the first known to wake, and he gathered the others into the Pantheon of Order. Only a small number of planets hold world-souls, and the titans found fewer as their search went on.",
      "World-souls are the prize every force wants. The void lords hoped their Old Gods would twist one into a dark titan. Sargeras chose to destroy world-souls before the Void could reach them. The Jailer turned the soul of Argus into a weapon against the Arbiter and later tried to drain Azeroth's life force to remake reality. The world-soul of K'aresh seemed lost in the war against Dimensius, until the broker Ve'nari helped restore it.",
      "Azeroth is the greatest of them. When the titan Aggramar found her, the Old Gods already ruled her surface, but the titan inside was untouched. The Pantheon judged her the most powerful world-soul ever found and believed she might one day be strong enough to defeat the void lords. Her arcane blood once formed the Well of Eternity, and Sargeras's sword later made her bleed azerite. She speaks through Magni Bronzebeard, her Speaker, and lately through visions called the Radiant Song. The haranir knew her song long before, under the name Aln'hara.",
      "The First Ones blur this picture. They designed the pantheons of every force, so some fans wonder whether world-souls are really nascent titans at all. Nothing in the story has settled it, and The Last Titan is expected to address what the titans truly intend for Azeroth."
    ]],
    ["The forces in the Worldsoul Saga", [
      "The Worldsoul Saga spans three expansions: The War Within in 2024, Midnight in March 2026, and The Last Titan, due no earlier than 2027. Blizzard built it around the fate of Azeroth's world-soul, the true intentions of the Pantheon of Order and a possible final showdown between the Light and the Void.",
      "In The War Within, the Void struck first. People across Azeroth heard the Radiant Song, warnings sent by the world-soul. Xal'atath destroyed Dalaran by draining its magic into an artifact called the Dark Heart. Deep underground, the Arathi of Hallowfall lived beneath Beledar, a great crystal that had begun shifting between Light and Void after Sargeras's sword struck the world. The chapter ended on K'aresh, where heroes allied with Xal'atath to stop Dimensius. She then took the void lord's power for herself.",
      "Midnight brought the Void to Quel'Thalas. Xal'atath and her Devouring Host attacked the Sunwell, and the Light answered through the Vanguard of the Light, summoned by Azeroth herself. At the Voidspire, Xal'atath tore the fallen naaru L'ura from Alleria Windrunner and turned the Sunwell into the Darkwell. Alleria and Turalyon were lost. The elves of Azeroth then united, defeated L'ura and cleansed the well into the Dawnwell, with a Void crystal set beside the Light to balance it. Sylvanas Windrunner reached out from the Maw to strike at Xal'atath, who retreated down the Darkwell's beam into the depths of the world.",
      "As of October 2026, Xal'atath is somewhere deep beneath Azeroth's surface, closer than ever to the world-soul. Upcoming Midnight updates are named for the Worldcore, the titan vault that shields Azeroth, so the next clash is expected at the heart of the world. The Last Titan will then take the story to Northrend, where the titans return at Ulduar. Whether they come as saviors, rivals or something else is the saga's biggest open question."
    ]]
  ]
};
