// Characters, part 2: Legion, Scourge, Void, Dragons, Titans, Shadowlands, Naaru & Draenei.
window.CHARS = window.CHARS || [];
window.CHARS.push(
// The Burning Legion
{id:'sargeras',n:'Sargeras',r:'Titan',t:'The Dark Titan',g:'legion',a:'fallen',i:3,s:'Imprisoned',b:"Once the greatest champion of the Titan Pantheon. When he learned the Void lords meant to corrupt an unborn titan, he decided the universe had to be burned clean and founded the Burning Legion. After the Pantheon imprisoned him on Argus, his last act was to drive a colossal sword into Azeroth."},
{id:'kiljaeden',n:"Kil'jaeden",r:'Eredar (demon)',t:'The Deceiver',g:'legion',a:'villain',i:2,s:'Killed over Argus',b:"An eredar leader who accepted Sargeras's offer when his friend Velen refused. He corrupted the orcs and created the Lich King. Driven back at the Sunwell, he was chased from the Tomb of Sargeras into the Twisting Nether and killed over Argus."},
{id:'archimonde',n:'Archimonde',r:'Eredar (demon)',t:'The Defiler',g:'legion',a:'villain',i:2,s:'Killed (twice)',b:"Supreme commander of the Legion's armies. He led the invasion of Kalimdor in the Third War and was torn apart by the wisps of Mount Hyjal. He returned to lead the Legion's invasion of the alternate Draenor and was destroyed for good in the Twisting Nether after Hellfire Citadel."},
{id:'mannoroth',n:'Mannoroth',r:'Pit lord',t:'The Destructor',g:'legion',a:'villain',i:1,s:'Killed by Grom',b:"The pit lord whose blood bound the orcs to the Legion. Grom killed him in Ashenvale at the cost of his own life."},
{id:'malganis',n:"Mal'Ganis",r:'Dreadlord',t:'Nathrezim lord',g:'legion',a:'villain',i:1,s:'Defeated in the Sepulcher; fate unknown',b:"The dreadlord who spread the plague of undeath and lured Arthas to Northrend. Dreadlords were made in Revendreth by Denathrius and lent to the Legion."},

// The Scourge
{id:'arthas',n:'Arthas Menethil',r:'Human (death knight)',t:'The Lich King',g:'scourge',a:'fallen',i:3,s:'Killed at Icecrown',b:"Crown prince of Lordaeron and a paladin trained by Uther. Obsessed with stopping the plague, he purged Stratholme, took the cursed runeblade Frostmourne, murdered his father and merged with Ner'zhul to become the Lich King. Tirion and the heroes of Azeroth defeated him in Icecrown Citadel."},
{id:'bolvar',n:'Bolvar Fordragon',r:'Human (undead)',t:'Highlord of the Ebon Blade',g:'scourge',a:'hero',i:2,s:'Undead',b:"Regent of Stormwind, burned by dragonfire at the Wrathgate. After Arthas fell he took the Helm of Domination to keep the Scourge under control. When Sylvanas shattered the helm he was freed, and he now leads the Knights of the Ebon Blade."},
{id:'kelthuzad',n:"Kel'Thuzad",r:'Human (lich)',t:'Archlich',g:'scourge',a:'villain',i:2,s:'Destroyed',b:"A Dalaran archmage who founded the Cult of the Damned. Arthas killed him and later raised him as a lich. He served the Jailer in the Shadowlands until he was destroyed in the Sanctum of Domination."},
{id:'anubarak',n:"Anub'arak",r:'Nerubian (undead)',t:'The Traitor King',g:'scourge',a:'villain',i:1,s:'Destroyed',b:"Last king of Azjol-Nerub. He died resisting the Lich King and was raised as his champion."},
{id:'sindragosa',n:'Sindragosa',r:'Blue dragon (frost wyrm)',t:'Queen of the Frostbrood',g:'scourge',a:'villain',i:1,s:'Destroyed',b:"Malygos's consort, killed long ago and raised by Arthas as a frost wyrm to serve the Lich King. Her soul finally found rest in Dragonflight."},
{id:'darion',n:'Darion Mograine',r:'Human (death knight)',t:'Former Highlord of the Ebon Blade',g:'scourge',a:'redeemed',i:1,s:'Undead',b:"Son of the Ashbringer. He drove the Ashbringer through his own heart to free his father's soul, and was raised as a death knight. He broke with the Lich King at Light's Hope, founded the Knights of the Ebon Blade, and later passed its leadership to Bolvar."},

// Old Gods and the Void
{id:'xalatath',n:"Xal'atath",r:'Void entity',t:'Harbinger of the Void',g:'void',a:'villain',i:3,s:'At large',b:"A Void being who once served the voidlord Dimensius. The Old Gods defeated her and sealed her inside a dagger, the Blade of the Black Empire. Now free and in a body of her own, she used Queen Ansurek and left her to die, and helped the heroes defeat Dimensius, then took the voidlord's power for herself. In Midnight she invaded Quel'Thalas to claim the Sunwell and escaped through the Darkwell."},
{id:'dimensius',n:'Dimensius',r:'Voidlord',t:'The All-Devouring',g:'void',a:'villain',i:2,s:'Defeated',b:"The voidlord who invaded the ethereals' homeworld of K'aresh, whose people destroyed their own planet to stop him. He was first fought in Outland's Netherstorm. He was the final boss of The War Within in Manaforge Omega, where heroes allied with Xal'atath to stop him. She absorbed his power."},
{id:'lura',n:"L'ura",r:'Naaru (Void)',t:'The fallen naaru',g:'void',a:'villain',i:1,s:'Defeated',b:"A naaru who collapsed into the Void. Alleria took in her dark essence at the Seat of the Triumvirate on Argus. She returned in service to Xal'atath as the final foe of the March on Quel'Danas raid in Midnight."},
{id:'cthun',n:"C'Thun",r:'Old God',t:"The Old God of Ahn'Qiraj",g:'void',a:'villain',i:2,s:'Killed',b:"Old God sealed beneath Ahn'Qiraj, master of the insectoid qiraji. Night elves and dragons walled his armies in during the War of the Shifting Sands. Adventurers killed him in Classic."},
{id:'yogg',n:'Yogg-Saron',r:'Old God',t:'The Beast with a Thousand Maws',g:'void',a:'villain',i:2,s:'Killed',b:"Old God imprisoned by the titans beneath Ulduar in Northrend. Its whispers corrupted the titans' keepers, and heroes killed it in Ulduar."},
{id:'nzoth',n:"N'Zoth",r:'Old God',t:'The Corruptor',g:'void',a:'villain',i:2,s:'Killed',b:"Old God imprisoned by the titans in the deep ocean, ruler of the city of Ny'alotha, and master of the Emerald Nightmare and of Azshara's naga. He corrupted Neltharion into Deathwing. Released at the end of Battle for Azeroth, he was killed in Ny'alotha."},
{id:'yshaarj',n:"Y'Shaarj",r:'Old God',t:'The Old God of Pandaria',g:'void',a:'villain',i:1,s:'Killed by the titans',b:"Strongest of the Old Gods, torn apart by the titans. His last breath became the sha of Pandaria, and Garrosh used his still-beating heart."},
{id:'ghuun',n:"G'huun",r:'Blood god',t:'The Blood God',g:'void',a:'villain',i:1,s:'Killed',b:"The titans' failed attempt to understand the Old Gods by making one. Sealed in Uldir and worshipped by blood trolls, it was killed in Battle for Azeroth."},
{id:'chogall',n:"Cho'gall",r:'Two-headed ogre',t:"Leader of the Twilight's Hammer",g:'void',a:'villain',i:1,s:'Killed',b:"Ogre mage of Gul'dan's Shadow Council who gave himself to the Old Gods. His Twilight's Hammer cult served Deathwing in the Cataclysm."},
{id:'ragnaros',n:'Ragnaros',r:'Fire elemental',t:'The Firelord',g:'void',a:'villain',i:1,s:'Killed',b:"Elemental lord who once served the Old Gods. The Dark Iron dwarves summoned him in the War of the Three Hammers. He allied with Deathwing and was killed in the Firelands."},
{id:'ansurek',n:'Queen Ansurek',r:'Nerubian',t:'Queen of Azj-Kahet',g:'void',a:'villain',i:1,s:'Killed',b:"Nerubian queen who bargained with Xal'atath for power. Xal'atath used her and left her to die when heroes stormed Nerub-ar Palace."},

// The Dragonflights
{id:'deathwing',n:'Deathwing (Neltharion)',r:'Black dragon',t:'Aspect of Earth, the Destroyer',g:'dragons',a:'fallen',i:3,s:'Killed',b:"Aspect of the black dragonflight, corrupted by the Old Gods. He forged the Dragon Soul and turned on the other Aspects in the War of the Ancients, then broke the world in the Cataclysm. The other Aspects gave up their powers to destroy him."},
{id:'alexstrasza',n:'Alexstrasza',r:'Red dragon',t:'The Life-Binder, Dragon Queen',g:'dragons',a:'hero',i:2,s:'Alive',b:"Aspect of life and queen of dragonkind. The Dragonmaw clan enslaved her for the Horde's war until Rhonin and Korialstrasz freed her. Her powers were restored in Dragonflight."},
{id:'korialstrasz',n:'Korialstrasz (Krasus)',r:'Red dragon',t:"Alexstrasza's consort",g:'dragons',a:'hero',i:1,s:'Died at Wyrmrest',b:"Alexstrasza's favorite consort, who walked among mortals as the mage Krasus. He died destroying dragon eggs that the Twilight's Hammer had corrupted beneath Wyrmrest Temple."},
{id:'ysera',n:'Ysera',r:'Green dragon',t:'Former Aspect of the Dream',g:'dragons',a:'hero',i:1,s:'Reborn in Ardenweald',b:"Aspect of the Emerald Dream and Alexstrasza's sister. The Nightmare corrupted her and she was killed in Legion. Her soul was reborn in Ardenweald in the Shadowlands."},
{id:'nozdormu',n:'Nozdormu',r:'Bronze dragon',t:'The Timeless One',g:'dragons',a:'hero',i:1,s:'Alive',b:"Aspect of time, who long believed he was fated to become Murozond, lord of the Infinite Dragonflight, until Chromie and the heroes showed that future could be fought."},
{id:'murozond',n:'Murozond',r:'Bronze dragon',t:'Lord of the Infinite Dragonflight',g:'dragons',a:'villain',i:1,s:'Defeated',b:"A future, corrupted Nozdormu who tries to rewrite history."},
{id:'malygos',n:'Malygos',r:'Blue dragon',t:'The Spell-Weaver',g:'dragons',a:'fallen',i:1,s:'Killed',b:"Aspect of magic, driven mad after Deathwing nearly wiped out his flight. He waged the Nexus War to take magic away from mortals and was killed in the Eye of Eternity."},
{id:'kalecgos',n:'Kalecgos',r:'Blue dragon',t:'Aspect of Magic',g:'dragons',a:'hero',i:1,s:'Alive',b:"A kind young blue dragon who became Aspect after Malygos, lost those powers after Deathwing fell, and had them restored by Azeroth in Dragonflight. He and Jaina were close for years."},
{id:'onyxia',n:'Onyxia',r:'Black dragon',t:'Broodmother of the Black Flight',g:'dragons',a:'villain',i:1,s:'Killed',b:"Deathwing's daughter, who infiltrated Stormwind as Lady Katrana Prestor."},
{id:'nefarian',n:'Nefarian',r:'Black dragon',t:'Lord of Blackrock',g:'dragons',a:'villain',i:1,s:'Killed',b:"Deathwing's son, who ran cruel experiments on dragons beneath Blackrock Spire."},
{id:'wrathion',n:'Wrathion',r:'Black dragon',t:'The Black Prince',g:'dragons',a:'grey',i:1,s:'Alive',b:"Of Deathwing's line, most likely his grandson, though he calls Deathwing father. He was cleansed of corruption before he hatched. A schemer who does whatever he thinks will save Azeroth, he now serves as diplomat to the black Aspect, Ebyssian."},
{id:'fyrakk',n:'Fyrakk',r:'Proto-dragon',t:'The Blazing',g:'dragons',a:'villain',i:1,s:'Killed',b:"A primal proto-dragon who burned his way into the Emerald Dream to seize the new World Tree, Amirdrassil. Heroes stopped him there."},
{id:'chromie',n:'Chromie',r:'Bronze dragon',t:'Keeper of time',g:'dragons',a:'hero',i:1,s:'Alive',b:"A bronze dragon in gnome form who guides heroes through key moments in history to keep the timeline intact."},

// Titans and the world-soul
{id:'amanthul',n:"Aman'Thul",r:'Titan',t:'Highfather of the Pantheon',g:'titans',a:'hero',i:1,s:'Spirit',b:"Leader of the Titan Pantheon, which searches the cosmos for world-souls to awaken as new titans. Sargeras destroyed the Pantheon's bodies, but their spirits later rose to imprison him."},
{id:'aggramar',n:'Aggramar',r:'Titan',t:'The Avenger',g:'titans',a:'hero',i:1,s:'Spirit',b:"Sargeras's student and his successor as the Pantheon's champion. Sargeras captured and corrupted his soul and bound it into a new body to guard Antorus."},
{id:'eonar',n:'Eonar',r:'Titan',t:'The Life-Binder',g:'titans',a:'hero',i:1,s:'Spirit',b:"Titan of life, who blessed Alexstrasza and Ysera as Aspects. Heroes defended her spirit on Argus."},
{id:'azeroth',n:'Azeroth',r:'World-soul',t:'The unborn titan',g:'titans',a:'hero',i:2,s:'Wounded, stirring',b:"A titan growing inside the planet itself, perhaps the most powerful world-soul ever found. The Void wants to corrupt her and the Legion wanted to destroy her. Sargeras's sword left her bleeding azerite. Her awakening is the subject of the Worldsoul Saga."},

// The Shadowlands
{id:'jailer',n:'Zovaal, the Jailer',r:'Eternal One',t:'Lord of the Maw',g:'shadowlands',a:'villain',i:3,s:'Destroyed',b:"The first Arbiter of the Shadowlands, locked in the Maw by the other Eternal Ones for trying to remake reality. For thousands of years he manipulated Sylvanas, Denathrius and the Lich King's creation from his prison. Heroes defeated him in the Sepulcher of the First Ones."},
{id:'denathrius',n:'Sire Denathrius',r:'Venthyr',t:'Master of Revendreth',g:'shadowlands',a:'villain',i:1,s:'Freed; whereabouts unknown',b:"Lord of Revendreth, who hoarded anima for the Jailer. He created the dreadlords and sent them into the living worlds."},
{id:'arbiter',n:'The Arbiter',r:'Eternal One',t:'Judge of souls',g:'shadowlands',a:'grey',i:1,s:'Destroyed; succeeded by Pelagos',b:"The Eternal who sends every soul to its afterlife. The Jailer's forces silenced her, so every soul began falling into the Maw. Zovaal later absorbed her essence, and the kyrian Pelagos became the new Arbiter."},
{id:'winterqueen',n:'The Winter Queen',r:'Eternal One',t:'Ruler of Ardenweald',g:'shadowlands',a:'hero',i:1,s:'Alive',b:"The Eternal who tends the rebirth of nature spirits. Ysera's soul was reborn in her realm."},

// Naaru and Draenei
{id:'velen',n:'Velen',r:'Draenei',t:'Prophet of the draenei',g:'light',a:'hero',i:2,s:'Alive',b:"The eredar leader who refused Sargeras and fled Argus with his followers, guided by the naaru. He has led the draenei for thousands of years and used M'uru's heart to cleanse the Sunwell."},
{id:'xera',n:"Xe'ra",r:'Naaru',t:'Mother of the Light',g:'light',a:'grey',i:1,s:'Destroyed by Illidan',b:"The naaru who led the Army of the Light and believed Illidan was marked from birth to end the Legion. When she tried to force the Light on him, he destroyed her."},
{id:'muru',n:"M'uru",r:'Naaru',t:'The captive naaru',g:'light',a:'hero',i:1,s:'Sacrificed',b:"A naaru captured by Kael'thas and drained by the blood elves. Its essence relit the Sunwell with holy Light."},
{id:'yrel',n:'Yrel',r:'Draenei (alternate Draenor)',t:'High Exarch of the Lightbound',g:'light',a:'fallen',i:1,s:'Alive',b:"A young draenei on the alternate Draenor who led her people to victory, then forced her Lightbound faith on the orcs. The Mag'har who refused fled to Azeroth."}
);
