// Characters, part 1: Alliance, Guardians, Old Horde, Horde, Quel'Thalas, Kalimdor elves.
// Fields: id, n name, r race, t title, g group, a alignment, i importance (1-3), s status, b bio
window.CHARS = window.CHARS || [];
window.CHARS.push(
// The Alliance
{id:'anduin',n:'Anduin Wrynn',r:'Human',t:'High King of the Alliance',g:'alliance',a:'hero',i:3,s:'Alive',b:"Son of Varian, and a priest of the Light who would rather make peace than war. The Jailer forced him to wear the Helm of Domination in the Shadowlands. He came back badly shaken, set the crown aside, and found his faith again during The War Within."},
{id:'varian',n:'Varian Wrynn',r:'Human',t:'King of Stormwind',g:'alliance',a:'hero',i:2,s:'Died on the Broken Shore',b:"Llane's son. Onyxia's magic split him into two people, and he was later made whole and took back his throne. He died holding the line on the Broken Shore so his soldiers could escape the Legion."},
{id:'llane',n:'Llane Wrynn',r:'Human',t:'King of Stormwind',g:'alliance',a:'hero',i:1,s:'Assassinated in the First War',b:"King of Stormwind when the orcs came through the Dark Portal. Garona killed him, and his kingdom fell soon after."},
{id:'lothar',n:'Anduin Lothar',r:'Human',t:'The Lion of Azeroth',g:'alliance',a:'hero',i:1,s:'Killed in the Second War',b:"Stormwind's champion and the last known heir of the ancient Arathi kings in the Eastern Kingdoms. He led the refugees north to Lordaeron and commanded the Alliance in the Second War. Orgrim Doomhammer killed him at Blackrock Spire."},
{id:'jaina',n:'Jaina Proudmoore',r:'Human',t:'Lord Admiral of Kul Tiras',g:'alliance',a:'hero',i:3,s:'Alive',b:"A prodigy of Dalaran who once loved Arthas. She founded Theramore as a bridge to Thrall's Horde. She turned bitter after Garrosh destroyed the city with a mana bomb, and later made peace with her past and her homeland."},
{id:'daelin',n:'Daelin Proudmoore',r:'Human',t:'Lord Admiral of Kul Tiras',g:'alliance',a:'grey',i:1,s:'Killed at Theramore',b:"Jaina's father, a hero of the Second War who never stopped hating orcs. He sailed to Kalimdor to wipe out the new Horde, and his daughter chose peace over him. He died in the fighting at Theramore."},
{id:'terenas',n:'Terenas Menethil II',r:'Human',t:'King of Lordaeron',g:'alliance',a:'hero',i:1,s:'Murdered by his son',b:"The king who founded the Alliance of Lordaeron. His son Arthas came home from Northrend carrying Frostmourne and killed him on his throne."},
{id:'calia',n:'Calia Menethil',r:'Human (undead)',t:'Priestess of the Light',g:'horde',a:'hero',i:1,s:'Undead',b:"Arthas's older sister, who hid for years after Lordaeron fell. She died and rose again as undead touched by the Light, and now helps lead the Forsaken on the Desolate Council."},
{id:'uther',n:'Uther the Lightbringer',r:'Human',t:'First Paladin of the Silver Hand',g:'alliance',a:'hero',i:2,s:'Killed by Arthas',b:"Founder of the Knights of the Silver Hand and Arthas's teacher. He refused to purge Stratholme, and Arthas later killed him. His soul went to Bastion in the Shadowlands and was drawn into the Jailer's war."},
{id:'tirion',n:'Tirion Fordring',r:'Human',t:'Highlord of the Argent Crusade',g:'alliance',a:'hero',i:2,s:'Killed by the Legion',b:"A paladin stripped of his title for defending an orc. He led the Argent Crusade to Icecrown, shattered Frostmourne and ended Arthas's reign. He was captured in the Legion's attack on the Broken Shore and died of his wounds after his rescue."},
{id:'turalyon',n:'Turalyon',r:'Human (Lightforged)',t:'High Exarch of the Army of the Light',g:'alliance',a:'hero',i:2,s:'Missing',b:"Lothar's lieutenant, who took command after him and later led the expedition through the Dark Portal. He fought the Legion across worlds with the Army of the Light for centuries of subjective time, came home with Alleria during Legion, and vanished with her in the Voidstorm at the end of Midnight."},
{id:'arator',n:'Arator the Redeemer',r:'Half-elf',t:'Son of Alleria and Turalyon',g:'alliance',a:'hero',i:1,s:'Alive',b:"Raised on Azeroth while his parents were lost in the Nether. He finally met them late in Legion, and at the end of Midnight he was with them at the Voidspire when they were lost to the Void. Umbric teleported him to safety."},
{id:'genn',n:'Genn Greymane',r:'Human (worgen)',t:'Former King of Gilneas',g:'alliance',a:'hero',i:1,s:'Alive',b:"He walled Gilneas off from the world, then lost it to the worgen curse and the Forsaken. Cursed as a worgen himself, he rejoined the Alliance and has never forgiven Sylvanas, whose arrow killed his son Liam. After Gilneas was reclaimed, he passed the crown to his daughter Tess."},
{id:'magni',n:'Magni Bronzebeard',r:'Dwarf',t:'Former King of Ironforge',g:'alliance',a:'hero',i:2,s:'Alive',b:"King of Ironforge until a ritual during the Cataclysm turned him to living diamond. For years the world-soul Azeroth spoke through him as her Speaker. In The War Within he was restored to flesh, and he is no longer sure he still speaks for her."},
{id:'moira',n:'Moira Thaurissan',r:'Dwarf',t:'Queen of the Dark Iron',g:'alliance',a:'grey',i:1,s:'Alive',b:"Magni's daughter, who married the Dark Iron emperor. After her father turned to diamond she claimed Ironforge for her son, and she now shares rule on the Council of Three Hammers."},
{id:'muradin',n:'Muradin Bronzebeard',r:'Dwarf',t:'High Thane of the Bronzebeard clan',g:'alliance',a:'hero',i:1,s:'Alive',b:"Magni's brother and Arthas's old sword teacher. He was with Arthas when Frostmourne was taken and was struck down by the blade's curse, losing his memory for years."},

// Guardians and the Kirin Tor
{id:'aegwynn',n:'Aegwynn',r:'Human',t:'Guardian of Tirisfal',g:'magi',a:'hero',i:1,s:'Deceased',b:"Guardian of Tirisfal for more than a thousand years. She destroyed an avatar of Sargeras and buried it in the Tomb of Sargeras, not knowing his spirit had hidden inside her and would pass to her son."},
{id:'medivh',n:'Medivh',r:'Human',t:'The Last Guardian',g:'magi',a:'redeemed',i:2,s:'Returned from death',b:"Aegwynn's son, born with Sargeras hiding in his soul. Under that influence he helped Gul'dan open the Dark Portal, until Khadgar and Lothar killed him. He came back years later as the Prophet to warn the living about the Burning Legion."},
{id:'khadgar',n:'Khadgar',r:'Human',t:'Archmage',g:'magi',a:'hero',i:2,s:'Alive',b:"Medivh's apprentice, who helped end his master's madness. A spell aged him decades in an instant. He led the Alliance on Draenor and defended Dalaran against the Legion. Medivh named him Azeroth's Guardian, though Khadgar refused the old Guardian's power."},
{id:'antonidas',n:'Antonidas',r:'Human',t:'Grand Magus of Dalaran',g:'magi',a:'hero',i:1,s:'Killed by Arthas',b:"Leader of the Kirin Tor and Jaina's teacher. He ignored the Prophet's warnings, and Arthas killed him when the Scourge sacked Dalaran."},
{id:'rhonin',n:'Rhonin',r:'Human',t:'Leader of the Kirin Tor',g:'magi',a:'hero',i:1,s:'Died at Theramore',b:"A reckless mage who freed Alexstrasza from the Dragonmaw clan and married Vereesa Windrunner. He died holding back the mana bomb that destroyed Theramore, saving Jaina."},

// The Old Horde of Draenor
{id:'nerzhul',n:"Ner'zhul",r:'Orc',t:'Elder shaman, first Lich King',g:'oldhorde',a:'fallen',i:2,s:'Destroyed in the Maw',b:"The orcs' spiritual leader, whom Kil'jaeden tricked into turning his people against the draenei. After he fled Draenor, Kil'jaeden tore his spirit from his body and sealed it in the Frozen Throne as the Lich King."},
{id:'guldan',n:"Gul'dan",r:'Orc',t:'Warlock, master of the Shadow Council',g:'oldhorde',a:'villain',i:3,s:'Killed (twice)',b:"Ner'zhul's apprentice, who sold the orcs to the Legion for power, fed them demon blood and helped Medivh open the Dark Portal. He died hunting the Tomb of Sargeras. A Gul'dan from an alternate Draenor later brought the Legion back to Azeroth and was killed in the Nighthold."},
{id:'blackhand',n:'Blackhand',r:'Orc',t:'First Warchief of the Horde',g:'oldhorde',a:'villain',i:1,s:'Killed by Orgrim',b:"A brutal puppet warchief controlled by the Shadow Council. Orgrim Doomhammer killed him and took the Horde."},
{id:'orgrim',n:'Orgrim Doomhammer',r:'Orc',t:'Warchief of the Horde',g:'oldhorde',a:'grey',i:2,s:'Died beside Thrall',b:"Durotan's best friend. He overthrew Blackhand, led the Horde through the Second War and killed Lothar. Years later he escaped captivity on his own and joined the young Thrall; he died fighting at Thrall's side and left him his armor and hammer."},
{id:'durotan',n:'Durotan',r:'Orc',t:'Chieftain of the Frostwolf clan',g:'oldhorde',a:'hero',i:1,s:'Murdered',b:"The Frostwolf chieftain who refused Gul'dan's demon blood. He was exiled, then killed with his mate Draka by assassins of Gul'dan's Shadow Council. Humans found their infant son and named him Thrall."},
{id:'draka',n:'Draka',r:'Orc',t:'Frostwolf warrior, Margrave of the House of the Chosen',g:'oldhorde',a:'hero',i:1,s:'Soul in the Shadowlands',b:"Durotan's mate and Thrall's mother. In the Shadowlands her soul went to Maldraxxus, where she rose to lead its armies against the Jailer."},
{id:'grom',n:'Grommash Hellscream',r:'Orc',t:'Chieftain of the Warsong clan',g:'oldhorde',a:'redeemed',i:2,s:'Died killing Mannoroth',b:"The first orc to drink Mannoroth's blood, which doomed his people to demonic bloodlust. In the Third War he drank it again and fell, then broke free and killed Mannoroth, dying in the act. Garrosh is his son."},
{id:'garona',n:'Garona Halforcen',r:'Half-orc',t:'Assassin',g:'oldhorde',a:'grey',i:1,s:'Alive',b:"Gul'dan's spy in Medivh's household. Under his control she assassinated King Llane, then spent years breaking free of that manipulation. She and Medivh had a son, Med'an."},

// The Horde
{id:'thrall',n:"Thrall (Go'el)",r:'Orc',t:'Former Warchief of the Horde',g:'horde',a:'hero',i:3,s:'Alive',b:"Durotan's son, raised as a gladiator slave by humans. He escaped, freed the imprisoned orcs, broke their demonic bloodlust and founded Durotar in Kalimdor. He later stepped down to heal the world as a shaman, and returned to fight the Jailer."},
{id:'aggra',n:'Aggra',r:"Orc (Mag'har)",t:'Shaman',g:'horde',a:'hero',i:1,s:'Alive',b:"A Mag'har shaman who helped Thrall find his balance during the Cataclysm. She became his wife and the mother of his children."},
{id:'garrosh',n:'Garrosh Hellscream',r:'Orc',t:'Warchief of the Horde',g:'horde',a:'fallen',i:2,s:'Killed by Thrall',b:"Grom's son, whom Thrall named warchief. He destroyed Theramore with a mana bomb and used the heart of the Old God Y'Shaarj, which led to the Siege of Orgrimmar. He escaped his trial into an alternate Draenor, where Thrall killed him."},
{id:'cairne',n:'Cairne Bloodhoof',r:'Tauren',t:'High Chieftain of the tauren',g:'horde',a:'hero',i:2,s:'Killed in a duel',b:"The tauren elder who helped Thrall settle in Kalimdor. He challenged Garrosh to a ritual duel, and died because Magatha Grimtotem had secretly poisoned Garrosh's axe."},
{id:'baine',n:'Baine Bloodhoof',r:'Tauren',t:'High Chieftain of the tauren',g:'horde',a:'hero',i:1,s:'Alive',b:"Cairne's son and an honorable voice in the Horde. He secretly helped Jaina's family during the war with Kul Tiras, and Sylvanas imprisoned him for it."},
{id:'voljin',n:"Vol'jin",r:'Troll',t:'Warchief of the Horde',g:'horde',a:'hero',i:2,s:'Spirit awaiting rebirth',b:"Darkspear chieftain who led the rebellion against Garrosh and became warchief. A demon mortally wounded him on the Broken Shore. Dying in Orgrimmar, he named Sylvanas his successor, urged on by a voice later revealed to be the Jailer's agent. His spirit now waits in Ardenweald to be reborn."},
{id:'saurfang',n:'Varok Saurfang',r:'Orc',t:'High Overlord',g:'horde',a:'hero',i:2,s:'Killed by Sylvanas',b:"A veteran of every war, haunted by his son's death at Icecrown and by the burning of Teldrassil. He challenged Sylvanas to a duel outside Orgrimmar and died, but his stand ended her hold on the Horde."},
{id:'sylvanas',n:'Sylvanas Windrunner',r:'High elf (undead)',t:'The Banshee Queen',g:'horde',a:'fallen',i:3,s:'Atoning in the Maw',b:"Ranger-General of Silvermoon, killed by Arthas and raised as a banshee. She broke free, founded the Forsaken and became warchief. In secret she served the Jailer: she burned Teldrassil and shattered the Helm of Domination. She turned on him at the end and was sentenced to free lost souls from the Maw."},
{id:'nathanos',n:'Nathanos Blightcaller',r:'Human (undead)',t:"Champion of the Banshee Queen",g:'horde',a:'villain',i:1,s:'Killed by Tyrande',b:"The only human ranger lord of Quel'Thalas and Sylvanas's most loyal servant. Tyrande, as the Night Warrior, killed him in revenge for Teldrassil."},
{id:'talanji',n:'Talanji',r:'Troll (Zandalari)',t:'Queen of Zandalar',g:'horde',a:'hero',i:1,s:'Alive',b:"The Zandalari princess who brought her empire into the Horde. After her father Rastakhan died in the Battle of Dazar'alor, she took the throne."},

// Elves of Quel'Thalas
{id:'anasterian',n:'Anasterian Sunstrider',r:'High elf',t:"King of Quel'Thalas",g:'quel',a:'hero',i:1,s:'Killed by Arthas',b:"The elf king who fought beside humanity in the Second War and then left the Alliance. Arthas killed him when the Scourge took Silvermoon. His crown helped form the Dawnwell in Midnight."},
{id:'kaelthas',n:"Kael'thas Sunstrider",r:'Blood elf',t:"Prince of Quel'Thalas",g:'quel',a:'fallen',i:2,s:"Killed at Magisters' Terrace",b:"Anasterian's son, a Kirin Tor mage who loved Jaina. He led the surviving elves, renamed them blood elves and joined Illidan in Outland. He fell to the Legion and tried to summon Kil'jaeden through the Sunwell."},
{id:'lorthemar',n:"Lor'themar Theron",r:'Blood elf',t:"Regent Lord of Quel'Thalas",g:'quel',a:'hero',i:2,s:'Alive',b:"Once second-in-command to Ranger-General Sylvanas. He rebuilt Silvermoon after the Scourge and led the defense of Quel'Thalas against Xal'atath in Midnight."},
{id:'liadrin',n:'Lady Liadrin',r:'Blood elf',t:'Matriarch of the Blood Knights',g:'quel',a:'hero',i:1,s:'Alive',b:"First of the Blood Knights, who drew the Light from the captive naaru M'uru, believing she had taken it by force. She later found real faith through Velen and led the elves' defenders in Midnight."},
{id:'alleria',n:'Alleria Windrunner',r:'High elf (Void-touched)',t:'Ranger of the Void',g:'quel',a:'hero',i:2,s:'Missing',b:"Eldest of the Windrunner sisters. She followed Turalyon through the Dark Portal and fought the Legion across worlds for centuries. She took the Void into herself on Argus and learned to wield it. At the end of Midnight she was lost to the Void at the Voidspire."},
{id:'vereesa',n:'Vereesa Windrunner',r:'High elf',t:'Co-founder of the Silversun Compact',g:'quel',a:'hero',i:1,s:'Alive',b:"Youngest Windrunner sister and Rhonin's widow. She once plotted with Sylvanas against Garrosh and then backed out. In Midnight she brought the crown of King Anasterian to help form the Dawnwell, then disbanded the Silver Covenant and founded the Silversun Compact with Aethas Sunreaver."},
{id:'umbric',n:'Magister Umbric',r:'Void elf',t:"Leader of the Ren'dorei",g:'quel',a:'redeemed',i:1,s:'Alive',b:"A blood elf magister exiled for studying the Void. Alleria taught him and his followers to control their transformation into void elves, and they joined the Alliance."},

// Elves of Kalimdor
{id:'malfurion',n:'Malfurion Stormrage',r:'Night elf',t:'Archdruid',g:'kaldorei',a:'hero',i:3,s:'Alive',b:"The first mortal druid, taught by Cenarius. He led the fight against Azshara in the War of the Ancients and slept for millennia in the Emerald Dream. Husband of Tyrande and twin brother of Illidan."},
{id:'tyrande',n:'Tyrande Whisperwind',r:'Night elf',t:'High Priestess of Elune',g:'kaldorei',a:'hero',i:3,s:'Alive',b:"Leader of the night elves for ten thousand years, until she and Malfurion stepped down after Dragonflight. After Teldrassil burned she became the Night Warrior, Elune's avatar of vengeance, and killed Nathanos."},
{id:'illidan',n:'Illidan Stormrage',r:'Night elf (demon)',t:'The Betrayer',g:'kaldorei',a:'redeemed',i:3,s:'Guarding Sargeras',b:"Malfurion's twin, who loved Tyrande and hungered for power. His deals with demons earned him the name Betrayer; he ruled Outland and was killed at the Black Temple. Brought back in Legion, he rejected the naaru Xe'ra's belief that he had been marked from birth to end the Legion, and fought it on his own terms. He now stands guard over the imprisoned Sargeras."},
{id:'azshara',n:'Queen Azshara',r:'Night elf (naga)',t:'Queen of the Highborne',g:'kaldorei',a:'villain',i:3,s:'Escaped',b:"Ruler of the ancient night elf empire who invited Sargeras into Azeroth, causing the Sundering. She survived under the sea through a pact with N'Zoth, who turned her people into naga. She slipped away after her defeat in the Eternal Palace."},
{id:'cenarius',n:'Cenarius',r:'Demigod',t:'Lord of the Forest',g:'kaldorei',a:'hero',i:1,s:'Alive',b:"A demigod of nature and teacher of the first druids. Grom's orcs killed him in the Third War. He later returned from the Emerald Dream."},
{id:'shandris',n:'Shandris Feathermoon',r:'Night elf',t:'Leader of the night elves',g:'kaldorei',a:'hero',i:1,s:'Alive',b:"Tyrande's adopted daughter and commander of her armies. Tyrande and Malfurion named her leader of the night elves when they stepped down. She brought moonwell water to help form the Dawnwell in Midnight."},
{id:'maiev',n:'Maiev Shadowsong',r:'Night elf',t:'The Warden',g:'kaldorei',a:'grey',i:1,s:'Alive',b:"Illidan's jailer for ten thousand years. She hunted him across worlds after his escape and helped bring him down at the Black Temple."},
{id:'xavius',n:'Xavius',r:'Satyr',t:'The Nightmare Lord',g:'kaldorei',a:'villain',i:1,s:'Defeated; fate uncertain',b:"Azshara's counselor and the first satyr. As the Nightmare Lord he corrupted the Emerald Dream for N'Zoth until heroes destroyed him."},
{id:'fandral',n:'Fandral Staghelm',r:'Night elf',t:'Archdruid',g:'kaldorei',a:'fallen',i:1,s:'Killed in the Firelands',b:"A grieving archdruid who lost his son to C'Thun's armies. He planted Teldrassil and, influenced by Xavius, kept Malfurion trapped in the Dream. He ended as a servant of Ragnaros."},
{id:'elune',n:'Elune',r:'Goddess',t:'The Mother Moon',g:'kaldorei',a:'hero',i:1,s:'Divine',b:"Goddess of the night elves, whose true nature is still a mystery. She granted Tyrande the power of the Night Warrior."},
{id:'thalyssra',n:'Thalyssra',r:'Nightborne',t:'First Arcanist of Suramar',g:'kaldorei',a:'hero',i:1,s:'Alive',b:"Leader of the Suramar resistance, who freed the Nightborne from the Legion and brought them into the Horde. She contributed an arcan'dor fruit to the Dawnwell in Midnight."},
{id:'elisande',n:'Elisande',r:'Nightborne',t:'Grand Magistrix of Suramar',g:'kaldorei',a:'villain',i:1,s:'Killed',b:"Ruler of Suramar, who pledged her city to the Legion to keep it alive. She was defeated in the Nighthold."}
);
