// Relationships: [from, to, type, description]
// Directed types (from acts on to): mentor, slew, corrupt, serves.
window.LINKS = [
// Family
['llane','varian','family','Father and son'],
['varian','anduin','family','Father and son'],
['arthas','calia','family','Brother and sister'],
['terenas','calia','family','Father and daughter'],
['daelin','jaina','family','Father and daughter. Jaina chose peace with the Horde over his war.'],
['aegwynn','medivh','family','Mother and son. Sargeras passed from her into him.'],
['durotan','thrall','family','Father and son'],
['draka','thrall','family','Mother and son'],
['grom','garrosh','family','Father and son'],
['cairne','baine','family','Father and son'],
['anasterian','kaelthas','family','Father and son'],
['alleria','sylvanas','family','Sisters'],
['alleria','vereesa','family','Sisters'],
['sylvanas','vereesa','family','Sisters'],
['alleria','arator','family','Mother and son'],
['turalyon','arator','family','Father and son'],
['magni','moira','family','Father and daughter'],
['magni','muradin','family','Brothers'],
['malfurion','illidan','family','Twin brothers who became bitter enemies'],
['tyrande','shandris','family','Adoptive mother and daughter'],
['deathwing','onyxia','family','Father and daughter'],
['deathwing','nefarian','family','Father and son'],
['onyxia','nefarian','family','Twin siblings'],
['deathwing','wrathion','family','Father and son. Wrathion was cleansed of his father\u2019s corruption before hatching.'],
['alexstrasza','ysera','family','Sisters'],

// Love
['durotan','draka','romance','Mates'],
['thrall','aggra','romance','Married'],
['alleria','turalyon','romance','Married, and lost together in the Voidstorm'],
['vereesa','rhonin','romance','Married'],
['malfurion','tyrande','romance','Married after ten thousand years'],
['illidan','tyrande','romance','Illidan\u2019s love for Tyrande went unanswered; she chose Malfurion'],
['arthas','jaina','romance','Young lovers who parted at Stratholme'],
['kaelthas','jaina','romance','Kael\u2019thas loved Jaina, who did not return it'],
['kalecgos','jaina','romance','A brief romance after Theramore'],
['alexstrasza','korialstrasz','romance','Her favorite consort'],
['malygos','sindragosa','romance','Consorts'],
['garona','medivh','romance','Parents of Med\u2019an'],

// Mentor / creator
['medivh','khadgar','mentor','Master and apprentice'],
['antonidas','jaina','mentor','Taught Jaina magic in Dalaran'],
['nerzhul','guldan','mentor','Gul\u2019dan was Ner\u2019zhul\u2019s apprentice before betraying him'],
['orgrim','thrall','mentor','Named Thrall his heir and left him the Doomhammer'],
['lothar','turalyon','mentor','Turalyon was Lothar\u2019s second-in-command and successor'],
['cenarius','malfurion','mentor','Taught him druidism'],
['alleria','umbric','mentor','Taught the void elves to control the Void'],
['velen','liadrin','mentor','Helped her find true faith in the Light'],
['velen','anduin','mentor','Anduin studied the Light under Velen'],
['xera','turalyon','mentor','Made him Lightforged'],
['korialstrasz','rhonin','mentor','As Krasus, he sent Rhonin on the mission to free Alexstrasza'],
['eonar','alexstrasza','mentor','Blessed her as Aspect of life'],
['sargeras','aggramar','mentor','Aggramar was Sargeras\u2019s student'],
['denathrius','malganis','mentor','Denathrius created the dreadlords'],

// Allies
['thrall','jaina','ally','An unlikely friendship that built peace in Kalimdor'],
['thrall','cairne','ally','Cairne helped the orcs settle in Kalimdor'],
['thrall','voljin','ally','The Darkspear joined Thrall\u2019s Horde'],
['thrall','grom','ally','Thrall freed Grom from demonic bloodlust'],
['durotan','orgrim','ally','Best friends'],
['khadgar','lothar','ally','Fought together in both wars'],
['llane','lothar','ally','Childhood friends; Lothar was his champion'],
['anduin','baine','ally','Close friends across faction lines'],
['baine','jaina','ally','He helped her family during the war with Kul Tiras'],
['baine','saurfang','ally','Rebelled against Sylvanas together'],
['varian','genn','ally','Allies after Gilneas rejoined the Alliance'],
['bolvar','varian','ally','Ruled Stormwind as regent in Varian\u2019s absence'],
['bolvar','darion','ally','Brothers of the Ebon Blade'],
['uther','tirion','ally','Brothers of the Silver Hand'],
['tirion','darion','ally','Turned on the Lich King together at Light\u2019s Hope'],
['muradin','arthas','ally','Friend and teacher; the curse of Frostmourne nearly killed him'],
['lorthemar','liadrin','ally','Leaders of Silvermoon'],
['lorthemar','sylvanas','ally','He served under her when she was Ranger-General'],
['lorthemar','kaelthas','ally','Ruled as regent while Kael\u2019thas was in Outland'],
['kaelthas','illidan','ally','Allied as masters of Outland'],
['umbric','arator','ally','Umbric teleported Arator to safety at the end of Midnight'],
['velen','muru','ally','Used M\u2019uru\u2019s spark to relight the Sunwell'],
['velen','xera','ally','The naaru guided the draenei out of Argus'],
['guldan','medivh','ally','Opened the Dark Portal together'],
['rhonin','alexstrasza','ally','He freed her from the Dragonmaw clan'],
['anduin','wrathion','ally','Became friends in Pandaria'],
['kalecgos','malygos','ally','Succeeded him as Aspect of magic'],
['malfurion','ysera','ally','Walked the Emerald Dream together for millennia'],
['winterqueen','ysera','ally','Ysera\u2019s soul was reborn in Ardenweald'],
['ragnaros','deathwing','ally','Allies in the Cataclysm'],
['ragnaros','fandral','ally','Fandral fought for the Firelord'],
['cthun','nzoth','ally','Fellow Old Gods'],
['yogg','nzoth','ally','Fellow Old Gods'],
['xalatath','nzoth','rival','The Old Gods defeated her and sealed her inside a dagger'],
['amanthul','azeroth','ally','The Pantheon wants the world-soul to awaken'],
['voljin','sylvanas','ally','With his dying words he named her warchief'],

// Rivals and enemies
['illidan','maiev','rival','Prisoner and jailer for ten thousand years'],
['illidan','arthas','rival','Fought for the Frozen Throne; Arthas won'],
['illidan','guldan','rival','Illidan took power from Gul\u2019dan\u2019s skull; Gul\u2019dan later held Illidan\u2019s body'],
['illidan','sargeras','rival','Illidan now stands guard over the imprisoned Sargeras'],
['malfurion','azshara','rival','Led the war against her in the War of the Ancients'],
['malfurion','fandral','rival','Fandral kept him trapped in the Emerald Dream'],
['aegwynn','sargeras','rival','Destroyed his avatar and buried it in the Tomb of Sargeras'],
['velen','kiljaeden','rival','Once close friends; Velen refused Sargeras and fled'],
['sylvanas','tyrande','rival','Sylvanas ordered Teldrassil burned'],
['sylvanas','genn','rival','Her arrow killed his son Liam'],
['sylvanas','bolvar','rival','She shattered the Helm of Domination he wore'],
['bolvar','arthas','rival','Took up the Helm of Domination after Arthas fell'],
['garrosh','voljin','rival','Garrosh sent an assassin after Vol\u2019jin'],
['garrosh','jaina','rival','He destroyed her city, Theramore'],
['thrall','daelin','rival','Daelin tried to wipe out Thrall\u2019s Horde'],
['deathwing','alexstrasza','rival','He betrayed the other Aspects'],
['deathwing','malygos','rival','He nearly wiped out the blue dragonflight'],
['nozdormu','murozond','rival','Nozdormu fights his own fated future self'],
['alexstrasza','fyrakk','rival','Enemies in the Primalist war over the Dragon Isles'],
['thalyssra','elisande','rival','Led the rebellion against her'],
['yrel','grom','rival','Her Lightbound drove Grom\u2019s Mag\u2019har from alternate Draenor'],
['fandral','cthun','rival','C\u2019Thun\u2019s qiraji killed Fandral\u2019s son'],
['talanji','ghuun','rival','Zandalar fought the Blood God\u2019s cult'],
['draka','jailer','rival','Led Maldraxxus against the Jailer'],
['jailer','arbiter','rival','He was the first Arbiter before his imprisonment'],
['alleria','lura','rival','Took the fallen naaru\u2019s Void essence into herself on Argus'],
['alleria','xalatath','rival','Fought her to the edge of the Voidstorm in Midnight'],
['lorthemar','xalatath','rival','Defended the Sunwell against her invasion'],
['anduin','xalatath','rival','Fought her across Khaz Algar in The War Within'],
['magni','xalatath','rival','Guards Azeroth\u2019s heart from her'],
['xalatath','dimensius','rival','Uneasy allies against him; she stole his power at the end'],
['xalatath','azeroth','rival','She wants to corrupt the world-soul'],
['yogg','azeroth','rival','The Old Gods fester inside the world-soul'],
['sargeras','azeroth','rival','Drove his sword into the planet as he was imprisoned'],

// Killed
['arthas','terenas','slew','Murdered his father on the throne of Lordaeron'],
['arthas','uther','slew','Killed his old teacher'],
['arthas','anasterian','slew','Killed him as Silvermoon fell'],
['arthas','antonidas','slew','Killed him when Dalaran was sacked'],
['arthas','sylvanas','slew','Killed her and raised her as a banshee'],
['arthas','kelthuzad','slew','Killed him in Andorhal, then raised him as a lich'],
['tirion','arthas','slew','Shattered Frostmourne and ended his reign at Icecrown'],
['garona','llane','slew','Assassinated him under Gul\u2019dan\u2019s control'],
['lothar','medivh','slew','Killed the possessed Guardian with Khadgar\u2019s help'],
['orgrim','blackhand','slew','Killed him and took the Horde'],
['orgrim','lothar','slew','Killed him at Blackrock Spire'],
['guldan','durotan','slew','His assassins killed Durotan and Draka'],
['grom','mannoroth','slew','Grom first drank his blood; years later he killed him, dying in the act'],
['grom','cenarius','slew','Killed him in Ashenvale under the demon blood\u2019s influence'],
['garrosh','cairne','slew','Killed him in a duel; Magatha Grimtotem had poisoned the axe'],
['garrosh','rhonin','slew','His mana bomb destroyed Theramore and Rhonin with it'],
['thrall','garrosh','slew','Named him warchief, then killed him on Draenor years later'],
['thrall','deathwing','slew','Wielded the Dragon Soul against Deathwing with the Aspects'],
['sylvanas','saurfang','slew','Killed him in their duel outside Orgrimmar'],
['tyrande','nathanos','slew','Killed him as the Night Warrior'],
['malfurion','archimonde','slew','Unleashed the wisps of Nordrassil to destroy him'],
['illidan','xera','slew','Destroyed her when she tried to force the Light on him'],
['sargeras','amanthul','slew','Destroyed the Pantheon\u2019s physical forms'],

// Corrupted / manipulated
['sargeras','medivh','corrupt','Hid inside Medivh\u2019s soul from birth'],
['sargeras','kiljaeden','corrupt','Turned him into a demon'],
['sargeras','archimonde','corrupt','Turned him into a demon'],
['kiljaeden','nerzhul','corrupt','Deceived him, then made him the Lich King'],
['guldan','garona','corrupt','Controlled her mind'],
['nerzhul','arthas','corrupt','Lured Arthas to Frostmourne; they merged into one Lich King'],
['malganis','arthas','corrupt','Lured him to Northrend'],
['nzoth','azshara','corrupt','Saved her people by turning them into naga'],
['nzoth','deathwing','corrupt','Drove Neltharion mad'],
['xavius','fandral','corrupt','Whispered to him through the Nightmare'],
['xavius','ysera','corrupt','Dragged her into the Nightmare'],
['onyxia','varian','corrupt','Split him into two people'],
['kaelthas','muru','corrupt','Captured the naaru and drained its Light'],
['yshaarj','garrosh','corrupt','Garrosh drew on the Old God\u2019s heart'],
['xalatath','ansurek','corrupt','Promised her power and used her'],
['jailer','anduin','corrupt','Forced him to wear the Helm of Domination'],

// Served
['guldan','kiljaeden','serves','Sold the orcs to the Legion'],
['kaelthas','kiljaeden','serves','Tried to summon him through the Sunwell'],
['elisande','guldan','serves','Pledged Suramar to the Legion'],
['azshara','sargeras','serves','Opened the way for his Legion'],
['xavius','azshara','serves','Her counselor'],
['xavius','nzoth','serves','Nightmare Lord in N\u2019Zoth\u2019s name'],
['kelthuzad','archimonde','serves','Summoned him to Azeroth'],
['kelthuzad','jailer','serves','Served him in the Shadowlands'],
['anubarak','arthas','serves','Champion of the Lich King'],
['sindragosa','arthas','serves','Raised as his frost wyrm'],
['darion','arthas','serves','Served him until he rebelled at Light\u2019s Hope'],
['nathanos','sylvanas','serves','Her most loyal champion'],
['sylvanas','jailer','serves','Secretly allied with him, then turned on him at the end'],
['denathrius','jailer','serves','Sent him the anima of Revendreth'],
['chogall','guldan','serves','Member of the Shadow Council'],
['chogall','deathwing','serves','His cult served Deathwing'],
['lura','xalatath','serves','Returned as her servant in Midnight'],
['magni','azeroth','serves','Azeroth speaks through him'],
['tyrande','elune','serves','High Priestess, and later her Night Warrior'],
['chromie','nozdormu','serves','Serves the bronze flight\u2019s Aspect']
];
