// Factions: organizations and orders that cut across races (not the Alliance/Horde, not races).
// Fields: id, n name, kind, align (hero|villain|grey), founded, base, status, leaders[] and members[] (CHARS ids),
// races[] (RACES ids), events[] (timeline ids), related[] (ORGS ids), s summary, story [[heading,[paragraphs]]],
// wiki (Warcraft Wiki title), other[] (notable people not on the site).
// Status reflects the Midnight era (October 2026). Sources: warcraft.wiki.gg.
window.ORGS = [

{id:'kirintor', n:'Kirin Tor', kind:'Order of mages', align:'hero', founded:'After \u22122,700', base:'Dalaran (destroyed)', status:'Decentralized after the fall of Dalaran',
 leaders:['antonidas','rhonin','jaina','khadgar'], members:['kelthuzad','kaelthas','korialstrasz','kalecgos'], races:['humans','bloodelves','gnomes'],
 events:['wars-6','wow-2','wow-4','wow-10'], related:['tirisfal','silvercovenant','cult'],
 s:"The ruling council of mages in Dalaran and for centuries the most powerful school of magic in the world. After Xal'atath destroyed their city, the survivors started over as a looser network of mages.",
 story:[
  ["Origin and purpose", [
   "The Kirin Tor began in Dalaran, a city founded by mages of the human empire of Arathor after the Troll Wars. As Dalaran became the main center of learning for spellcasters, its rulers formed the Kirin Tor to catalog and study every spell, artifact and magical item known to humanity. In time its inner council, the Council of Six, replaced the old rulers and governed Dalaran itself. The head of the Six led the city.",
   "The order was human at its core, but high elves of Quel'Thalas studied and served in Dalaran for about two thousand years. Gnomes, dwarves and half-elves joined too. Dragons hid among the mages in mortal form as well. Young blue dragons sought membership, and the red dragon Korialstrasz sat on the Council as Krasus. The Kirin Tor kept its secrets and stayed out of ordinary politics, though Dalaran joined the Alliance of Lordaeron in the Second War."]],
  ["Key moments", [
   "Before the Third War, Archmage Antonidas caught Kel'Thuzad, a member of the Six, studying necromancy. Kel'Thuzad left and founded the Cult of the Damned. When a strange plague spread through the north, the Kirin Tor sent young Jaina Proudmoore to investigate. Soon after, Arthas and the Scourge stormed Dalaran, killed Antonidas and used the Book of Medivh to summon the demon lord Archimonde, who leveled the city.",
   "The survivors rebuilt under a great magical dome, and Rhonin became their leader. In Wrath of the Lich King they lifted the whole city into the sky over Northrend, fought the blue Dragon Aspect Malygos in the Nexus War and helped lead the battle against the Old God Yogg-Saron in Ulduar. Dalaran declared itself neutral and welcomed both the Alliance and the Horde.",
   "Rhonin died at Theramore when Garrosh Hellscream's mana bomb destroyed the city, and Jaina took his place. After learning that blood elf Sunreavers had helped the Horde steal a powerful relic, she purged the Horde from Dalaran and tied the city to the Alliance. During Legion the Council outvoted her and let the Horde return. Jaina left, Khadgar became leader, and Dalaran became the meeting point for the war against the Burning Legion."]],
  ["Where it stands now", [
   "In The War Within the Council teleported Dalaran to Khaz Algar. One of the Six, Archmage Drenden, had been dead for years, and Xal'atath had been wearing his face. She set the nerubians on the city, drained its power into her artifact, the Dark Heart, and destroyed Dalaran over the Isle of Dorn. Many mages died. Khadgar was trapped inside the Dark Heart until Alleria Windrunner damaged it and freed him.",
   "Khadgar mourned the Kirin Tor as finished. Later he and Jaina told the survivors to start over with no council, no ranks and no floating cities, and to stop meddling in world affairs. The Kirin Tor now works as a small, scattered group that studies magic, trains students and gives advice. Jaina, Aethas Sunreaver and Meryl Felstorm are among its key figures. During Midnight, Khadgar still sent rare reagents from the order's reserves to help the defense of Quel'Thalas."]]],
 wiki:'Kirin Tor', other:['Modera (archmage)','Aethas Sunreaver (archmage, leader of the Sunreavers)','Meryl Felstorm (ancient archmage)','Ansirem Runeweaver (archmage)']},

{id:'tirisfal', n:'Order of Tirisfal', kind:'Secret council of mages', align:'hero', founded:'About \u22122,680', base:'Tirisfal Glades (secret meetings)', status:'Broken after Medivh; no Guardian chosen since',
 leaders:[], members:['aegwynn','medivh','jaina'], races:['humans','bloodelves','gnomes'],
 events:['kingdoms-4','wars-0','wars-1'], related:['kirintor','shadowcouncil'],
 s:"A secret order of human and high elf mages that gave its combined power to one champion, the Guardian of Tirisfal, to fight demons in hiding. The line of Guardians ended with Medivh.",
 story:[
  ["Origin and purpose", [
   "About 2,680 years before the Dark Portal, careless spellcasting in young Dalaran drew the attention of the Burning Legion. Small demons slipped into the city. Its rulers feared a panic, so they quietly asked Quel'Thalas for help, and the high elves sent their best magi. Together the human and elven mages formed a secret order to hunt the demons and to teach other mages the dangers of reckless magic. They met in a hidden vale in Tirisfal Glades, which gave the Council of Tirisfal its name.",
   "At first the Council poured its power into one fighter called the Spearhead, but its members had to stay close by to channel it. A half-elf mage named Alodi and the council member Meryl reworked the spell so the link held at any distance, and Alodi became the first Guardian of Tirisfal. Only one Guardian served at a time. Guardians lived for centuries, so only a few are known by name. A gnome named Indus was among the early members."]],
  ["Key moments", [
   "The most famous Guardian was Aegwynn. She destroyed an avatar of the dark titan Sargeras and buried it in the Tomb of Sargeras, unaware that his spirit had hidden inside her. She came to distrust the Council, believing it meddled in the politics of the human kingdoms, and refused to give up her power. The Council formed an elite mage guard, the Tirisgarde, to hunt her. One of its members, Nielas Aran, fell in love with her instead.",
   "Aegwynn chose her own heir and placed the Guardian's power in their son, Medivh. Sargeras's spirit passed into him as well. As an adult, Medivh helped Gul'dan open the Dark Portal and secretly killed members of the order, several of them mages of the Kirin Tor. The Council and the Kirin Tor sent the apprentice Khadgar to watch him, and Khadgar helped Anduin Lothar end his master's madness. After Medivh's death the order decided no one could resist the Guardian's power, and it chose no successor."]],
  ["Where it stands now", [
   "In a comic story set during the war in Northrend, Aegwynn, Jaina Proudmoore and Meryl Felstorm formed a New Council of Tirisfal to fight Cho'gall. Its Guardian was Med'an, the son of Medivh and Garona. Blizzard later said Med'an's role as Guardian is not canon, though most of the comic's events still stand. That council drifted apart after Cho'gall's defeat.",
   "In Legion, Meryl Felstorm revived the Tirisgarde in the Hall of the Guardian, and mages from across Azeroth, including members of the Kirin Tor, joined it to fight the Legion. Medivh's spirit later called Khadgar a true Guardian, but Khadgar refused the title. No new Guardian has been named since."]]],
 wiki:'Council of Tirisfal', other:['Alodi (first Guardian)','Meryl Felstorm (founding member)','Scavell (Guardian before Aegwynn)','Nielas Aran (member of the Tirisgarde, father of Medivh)','Indus (gnome member)']},

{id:'silverhand', n:'Knights of the Silver Hand', kind:'Order of paladins', align:'hero', founded:'Year 5', base:'Stratholme, later the Sanctum of Light', status:'Active',
 leaders:['uther','tirion'], members:['turalyon','arthas','liadrin','arator'], races:['humans','dwarves','draenei','bloodelves','tauren'],
 events:['wars-2','wars-6','wars-7','wow-6'], related:['argent','scarlet','bloodknights','armylight'],
 s:"The first order of human paladins, warriors who wield the Holy Light. It nearly died with Lordaeron, was reborn to fight the Burning Legion, and still serves today.",
 story:[
  ["Origin and purpose", [
   "In Year 5, during the Second War, the new Alliance of Lordaeron needed champions that every human could rally behind. Archbishop Alonsus Faol of the Church of the Holy Light offered Anduin Lothar a new kind of soldier, a knight trained for war who could also wield the Light. Faol trained the first five and named them paladins. They were Uther, Saidan Dathrohan, Tirion Fordring, Turalyon and Gavinrad. The order took its name and symbol from the silver hand of Tyr, an ancient hero remembered for his sacrifice.",
   "The paladins healed soldiers and struck down orcs and death knights. Uther earned the name Lightbringer, and Turalyon led the Alliance to victory after Lothar fell. After the war the order kept the peace in Lordaeron from its base in Stratholme, while branches in Stormwind and Ironforge trained human and dwarf paladins."]],
  ["Key moments", [
   "The order's darkest years came with the Third War. When Arthas, Uther's former student, decided to kill the plague-ridden people of Stratholme, Uther refused. Arthas suspended the order and sent the paladins away. Later, as a death knight, he killed Uther at Andorhal. Highlord Alexandros Mograine kept the survivors fighting with the holy blade Ashbringer until his own son murdered him. Without him the remnant in Lordaeron split. Fanatics became the Scarlet Crusade, and others founded the Argent Dawn.",
   "Tirion Fordring, once stripped of his rank for defending an orc, gathered the remaining knights again. After the second battle at Light's Hope Chapel he merged them with the Argent Dawn to form the Argent Crusade. When Tirion died after the Broken Shore in Legion, he passed the Ashbringer to a new champion. Every paladin order then united as the reformed Silver Hand under this new Highlord. The Stormwind and Ironforge paladins, the Argent Crusade, the draenei Hand of Argus, the blood elf Blood Knights and the tauren Sunwalkers all joined. They fought the Legion from the Sanctum of Light beneath Light's Hope Chapel."]],
  ["Where it stands now", [
   "The union did not last. At the start of the Fourth War the Silver Hand sided with the Alliance again, while the Blood Knights and Sunwalkers fought for the Horde. The order now guards dangerous relics in the Sanctum of Light and keeps training new paladins.",
   "In Midnight, Azeroth itself called the order to defend the Sunwell, and the whole Silver Hand answered. Its knights fought Xal'atath's Void armies on the Isle of Quel'Danas beside priests and paladins of many races, and helped pour their power into the Sunwell to hold back the Voidstorm."]]],
 wiki:'Knights of the Silver Hand', other:['Alonsus Faol (founder)','Saidan Dathrohan (one of the first paladins)','Gavinrad the Dire (one of the first paladins)','Alexandros Mograine (Highlord, wielder of the Ashbringer)','Maxwell Tyrosus (senior lord of the order)']},

{id:'argent', n:'Argent Crusade', kind:'Holy order, open to all races', align:'hero', founded:'Year 22 (as the Argent Dawn)', base:"Light's Hope Chapel, Eastern Plaguelands", status:'Active; holds the line against the Scourge',
 leaders:['tirion'], members:['darion'], races:['humans','dwarves','forsaken'],
 events:['wow-0','wow-2','wow-6'], related:['silverhand','scarlet','ebonblade','cult'],
 s:"A neutral order of holy warriors that welcomes every race to fight the undead and demons. It began as the Argent Dawn and became the Crusade under Tirion Fordring.",
 story:[
  ["Origin and purpose", [
   "The Argent Dawn grew out of the ruin of the Silver Hand in Lordaeron around Year 22. After Highlord Alexandros Mograine was murdered, many surviving paladins hardened into the fanatical Scarlet Crusade. Others, such as Lord Maxwell Tyrosus, saw their old comrades losing their way and suspected a dark force behind the Scarlet leaders. They left and founded the Argent Dawn, which kept to the teachings of the Light and accepted members of every race. Lord Raymond George led it first, and Tyrosus took over after his death.",
   "The Dawn stayed out of politics. It treated the Alliance and the Horde as allies, built camps across the Plaguelands and kept agents in Stormwind, Darnassus and Everlook. Its main base was Light's Hope Chapel, where a thousand fallen heroes of the Light lie buried."]],
  ["Key moments", [
   "When the Scourge launched invasions from Kel'Thuzad's floating necropolis, Naxxramas, the Argent Dawn organized the defense and helped point heroes at the source. Darion Mograine, Alexandros's younger son, fought with the Dawn and gave his life at Light's Hope to free his father's soul. The Scourge later took his body and made him a death knight.",
   "In Year 27 Darion led ten thousand undead against the chapel's three hundred defenders. Tirion Fordring stepped in, the Lich King appeared in person, and Tirion purified the corrupted Ashbringer and drove him off. Tirion then joined the Dawn with the last of the Silver Hand in Lordaeron and named the new order the Argent Crusade. He wanted all peoples to fight together and never let the order slide into blind zealotry.",
   "In Northrend the Crusade and Darion's Knights of the Ebon Blade led the push on Icecrown. Tirion held the Argent Tournament to pick a small strike force, and the two orders united as the Ashen Verdict to storm Icecrown Citadel. At the Frozen Throne, Tirion shattered Frostmourne and Arthas fell."]],
  ["Where it stands now", [
   "In Legion the Crusade led the first assault on the Broken Shore and was nearly destroyed. Gul'dan dropped the captured Tirion into lava. He survived as a prisoner of the demons but died of his torture after his rescue. Under Maxwell Tyrosus the survivors joined the reformed Silver Hand.",
   "The Crusade rebuilt. When Sylvanas destroyed the Helm of Domination and the Scourge ran loose, it guarded Stormwind, Orgrimmar and its posts in Northrend. Since the Jailer's fall it has kept strong forces in Northrend to hold back the masterless undead, and the old tournament grounds in Icecrown now serve as its training camp. In Midnight many of its paladins were called to defend the Sunwell."]]],
 wiki:'Argent Crusade', other:['Raymond George (first leader of the Argent Dawn)','Maxwell Tyrosus (leader after Tirion)','Eligor Dawnbringer (leader of the Brotherhood of the Light)','Mariel Trueheart (justicar in Icecrown)']},

{id:'scarlet', n:'Scarlet Crusade', kind:'Fanatical holy order', align:'villain', founded:'Year 22', base:'Scarlet Monastery, Tirisfal Glades', status:'Broken; zealot remnants keep returning',
 leaders:[], members:[], races:['humans'],
 events:['wow-0'], related:['silverhand','argent','ebonblade'],
 s:"Zealots who grew out of the broken Silver Hand and swore to burn every trace of undeath from Lordaeron. Demons secretly steered them, and they came to hate anyone who was not human.",
 story:[
  ["Origin and purpose", [
   "The Scarlet Crusade grew from paladins of the Silver Hand who survived the fall of Lordaeron in the Third War. They gathered at Hearthglen and fought the Scourge under Saidan Dathrohan and Highlord Alexandros Mograine. During a battle in Stratholme, Dathrohan was killed and the dreadlord Balnazzar took his body. No one noticed. Balnazzar and his brother Varimathras wanted Mograine and his blade, the Ashbringer, out of the way. Posing as Dathrohan, Balnazzar turned Mograine's son Renault against him, and Renault stabbed his father in the back.",
   "Without Mograine the remnant broke apart. The possessed Dathrohan reorganized the hardliners as the Scarlet Crusade, while more moderate paladins left to form the Argent Dawn. A faction led by General Abbendis had already wanted Lordaeron kept for humans alone, and that view won out."]],
  ["Key moments", [
   "From the Scarlet Monastery, Hearthglen, Tyr's Hand and a bastion in Stratholme, the crusaders fought the Scourge and the Forsaken. They grew paranoid and treated every outsider as a possible plague carrier. They burned villages they believed infected and killed their own deserters. Grand Inquisitor Isillien murdered Highlord Taelan Fordring when Taelan tried to leave and rejoin his father, Tirion. Heroes later unmasked Grand Crusader Dathrohan as Balnazzar.",
   "When the death knights of Acherus attacked the Scarlet Enclave, High General Brigitte Abbendis declared the Crusade finished and sailed to Northrend with her most faithful troops as the Scarlet Onslaught. Another dreadlord, Mal'Ganis, was hiding among its leaders there. Back in Lordaeron, Balnazzar killed the crusaders left in Stratholme and raised them as undead, the Risen. The Argent Crusade took Hearthglen, and the order shrank to the Monastery."]],
  ["Where it stands now", [
   "Heroes killed High Inquisitor Sally Whitemane in the Monastery during Mists of Pandaria. In Legion the Knights of the Ebon Blade stormed it and wiped out the garrison so they could raise Whitemane as a death knight. The ideology survived anyway. A group calling itself the Scarlet Brotherhood claims to be hiding an heir of the Menethil line.",
   "In Dragonflight the crusaders attacked the Forsaken in Silverpine and then tried to hold Gilneas, until King Genn Greymane drove them out. Some later joined the Red Dawn, a human supremacist plot in the Arathi Highlands. In Midnight they had occupied the Monastery again, until Alonsus Faol, Arator and a band of heroes fought through it to recover holy relics for the defense of the Sunwell."]]],
 wiki:'Scarlet Crusade', other:['Saidan Dathrohan (Grand Crusader, secretly the dreadlord Balnazzar)','Brigitte Abbendis (founder, later led the Scarlet Onslaught)','Sally Whitemane (High Inquisitor)','Renault Mograine (Scarlet Commander)','Taelan Fordring (Highlord)','Isillien (Grand Inquisitor)']},

{id:'ebonblade', n:'Knights of the Ebon Blade', kind:'Order of death knights', align:'grey', founded:'Year 27', base:'Acherus: The Ebon Hold', status:'Active; guards Icecrown Citadel',
 leaders:['darion','bolvar'], members:[], races:['humans','orcs','bloodelves','nightelves'],
 events:['wow-2','wow-6','wow-8'], related:['argent','cult','silverhand'],
 s:"Death knights who broke free of the Lich King and turned on him. They fight to protect the living, though they still use the dark methods they learned in the Scourge.",
 story:[
  ["Origin and purpose", [
   "The order began as the Death Knights of Acherus, an army the Lich King trained in the floating necropolis Acherus to destroy the Scarlet Crusade and the Argent Dawn in the Plaguelands. In Year 27 Highlord Darion Mograine led ten thousand undead against Light's Hope Chapel, and Tirion Fordring defeated him there. When the Lich King arrived and showed he had treated his own knights as expendable, Darion turned on his master and handed Tirion the corrupted Ashbringer. Tirion purified it and drove the Lich King away, and the death knights' minds were their own again.",
   "Darion named his freed knights the Knights of the Ebon Blade and swore to destroy Arthas. They seized Acherus from the Scourge. He sent his death knights back to their old peoples with letters from Tirion, and King Varian Wrynn and Warchief Thrall agreed to accept them."]],
  ["Key moments", [
   "In Northrend the Ebon Blade and the Argent Crusade led the war on Icecrown after the Alliance and Horde turned on each other at the Wrathgate. The two orders formed the Ashen Verdict to assault Icecrown Citadel, and Darion helped forge the runeblade Shadowmourne for the fight. After Arthas fell, Bolvar Fordragon took his place as Lich King to hold the Scourge in check.",
   "In Legion the knights made a pact with Bolvar. They would serve him against the demons, and he would keep the Scourge contained. They raised a new Four Horsemen, among them the orc general Nazgrim, King Thoras Trollbane and Sally Whitemane, slaughtering the Scarlet Monastery to get her. When Bolvar chose Tirion as the last Horseman, they raided his tomb at Light's Hope, and the Light itself drove them back. Darion died covering their escape, and Bolvar raised him again. In the Fourth War the Horsemen gathered fallen soldiers of both factions to become new death knights."]],
  ["Where it stands now", [
   "When Sylvanas destroyed the Helm of Domination, Bolvar was freed and became Highlord of the order. The knights helped hold back the loose Scourge, then followed Bolvar into the Shadowlands, where many were lost in the Maw. After the Jailer's defeat they came home.",
   "Their task now is to keep the masterless Scourge in check across Northrend and to guard Icecrown Citadel. In Midnight, Maxwell Tyrosus asked for help when Scourge remnants attacked Light's Hope Chapel. Darion agreed, saying he owed the paladins for his raid on the chapel, and sent Thassarian, Koltira Deathweaver and the Four Horsemen."]]],
 wiki:'Knights of the Ebon Blade', other:['Thassarian (death knight commander)','Koltira Deathweaver (death knight commander)','Nazgrim (orc general raised as a Horseman)','Sally Whitemane (raised as a Horseman)','Thoras Trollbane (raised as a Horseman)']},

{id:'cult', n:'Cult of the Damned', kind:'Cult of the Lich King', align:'villain', founded:'Years 15 to 18', base:'Scholomance, Caer Darrow', status:'Scattered cells, still active',
 leaders:['kelthuzad'], members:[], races:['humans','orcs','bloodelves'],
 events:['wars-6','wars-7','wow-0','wow-2'], related:['kirintor','argent','ebonblade'],
 s:"A secret religion of living people who worship the Lich King and hope to be raised as undead. Its plague created the Scourge.",
 story:[
  ["Origin and purpose", [
   "After Year 15 the Lich King, trapped in the Frozen Throne in Northrend, reached out with his mind for followers. Kel'Thuzad, an archmage on Dalaran's Council of Six, answered. He had been censured for studying necromancy and was close to exile. He traveled to Northrend, swore himself to the Lich King and came home with orders to build a following in Lordaeron.",
   "Over about three years he preached a new faith. To the poor he promised equality and eternal life. To nobles he offered power and immortality. Only trusted members learned the real goal. The cult made its headquarters beneath Caer Darrow, where the noble Barov family struck a deal with Kel'Thuzad. There he founded the Scholomance, a school of necromancy, and refined a plague that worked slowly enough to spread before anyone noticed."]],
  ["Key moments", [
   "By the Third War the cult held sway across the Eastweald, including Andorhal, the region's grain hub. Cultists shipped plagued grain throughout northern Lordaeron, and the dead rose as the army Kel'Thuzad named the Scourge. Prince Arthas killed Kel'Thuzad at Andorhal, but that was part of the plan. Arthas later carried his remains to the Sunwell, where he rose again as a lich. When Arthas murdered his father, masked cultists attacked inside the palace. Kel'Thuzad then used the Book of Medivh to summon the demon lord Archimonde.",
   "Members stay alive on purpose. Undeath is a reward they must earn, and living agents can slip into Alliance and Horde towns. Recruits drink a potion that binds them to the Lich King and carry an orb that disguises them. After the war Kel'Thuzad ran the cult from Naxxramas above the Plaguelands. In Northrend it spread plague, raised frost wyrms and attacked the Argent Tournament. Its Supreme Overseer, the lich Lady Deathwhisper, helped defend Icecrown Citadel against the final assault."]],
  ["Where it stands now", [
   "After Arthas fell, the cult lost its master and split into scattered groups. Darkmaster Gandling held the Scholomance for years, and others kept trying to spread blight in the Plaguelands. In Legion the necromancers of Caer Darrow still held the Book of Medivh, and handed it over only when Shadow Council warlocks threatened force. Kel'Thuzad himself ended up serving the Jailer in the Shadowlands and was destroyed there. When Sylvanas shattered the Helm of Domination, the cult rose again across Azeroth, stirred up by a herald of the Jailer who promised that the Banished One would claim the world. The Argent Crusade later reported cultists still active on Caer Darrow."]]],
 wiki:'Cult of the Damned', other:['Baron Rivendare (early member)','Darkmaster Gandling (leader at the Scholomance)','Lady Deathwhisper (Supreme Overseer at Icecrown Citadel)','Grand Widow Faerlina (cult leader in Naxxramas)']},

{id:'shadowcouncil', n:'Shadow Council', kind:'Cabal of warlocks', align:'villain', founded:'Year \u22127', base:'Black Temple, later Blackrock Spire', status:'Broken up; small cells still serve demons',
 leaders:['guldan'], members:['chogall','garona'], races:['orcs','ogres'],
 events:['kingdoms-8','wars-0','wars-1'], related:['twilight','tirisfal'],
 s:"Gul'dan's secret circle of orc warlocks, which ruled the Horde from the shadows for the Burning Legion. Its survivors later became a loose web of demon-worshipping cults.",
 story:[
  ["Origin and purpose", [
   "In Year \u22127, Gul'dan pushed aside his old teacher Ner'zhul and became the spiritual leader of the orcs, serving the demon lord Kil'jaeden. To control the clans, he made Blackhand of the Blackrock clan Warchief as a public face and gathered warlocks, necrolytes and chieftains into a hidden council that held the real power. Its purpose was to keep the Horde united in the war on the draenei and to spread fel magic. The two-headed ogre Cho'gall became Gul'dan's top apprentice, and the half-orc Garona became his assassin.",
   "Gul'dan flattered Blackhand that he would rule both the Horde and the Council, while using him as a puppet. The Council worked from Hellfire Citadel and then from the captured draenei temple of Karabor. During the attack on Karabor, Gul'dan ignored the warnings of the Shadowmoon clan and called down a Void being known as the Dark Star, which drove many defenders mad and darkened the temple for good. It became the Black Temple, the Council's seat. Its warlocks fed the blood of the pit lord Mannoroth to the clans, binding the orcs to the Legion. Not every orc warlock joined. Some, such as Drek'Thar, stayed loyal to their clans."]],
  ["Key moments", [
   "When Kil'jaeden withdrew, Medivh came to Gul'dan as a hooded stranger and offered him the Tomb of Sargeras. Gul'dan's warlocks drained the lives of draenei prisoners to power the Dark Portal, and the Horde poured into Azeroth. In the First War the Council hid in Blackrock Spire. After Medivh died, Gul'dan fell into a coma. Orgrim Doomhammer killed Blackhand, had Garona tortured until she revealed the hideout, and slaughtered most of the Council.",
   "Gul'dan bought his life by promising new weapons. He put the spirits of dead Council warlocks into the corpses of human knights and created the first death knights, led by Teron Gorefiend. The survivors split into Gul'dan's Stormreaver clan, Cho'gall's Twilight's Hammer and the death knights. Gul'dan later abandoned the Horde to raise the Tomb of Sargeras from the sea and was killed by the demons guarding it."]],
  ["Where it stands now", [
   "After the Great Wars the name lived on as a loose network of cults, open to any race that served the Legion. Groups such as the Burning Blade, the Searing Blade and the Cabal of Auchindoun in Outland counted as parts of it. In Legion, an alternate Gul'dan rallied hidden members to recover the Book of Medivh and the Eye of Dalaran. With the Legion defeated, only small cells remain. In Dragonflight, Maiev Shadowsong and night elf heroes destroyed Shadow Hold in Felwood, an old Council stronghold that new demon worshippers had seized."]]],
 wiki:'Shadow Council', other:['Teron Gorefiend (warlock, later the first death knight)','Grandmaster Vorpil (leader of the Cabal in Outland)','Lord Banehollow (dreadlord who led the Council in Felwood)']},

{id:'twilight', n:"Twilight's Hammer", kind:'Doomsday cult of the Old Gods', align:'villain', founded:'Before Year 0, on Draenor', base:'Grim Batol and the Twilight Highlands', status:"Reformed as the Twilight's Blade, serving Xal'atath",
 leaders:['chogall'], members:[], races:['orcs','ogres','humans','darkiron'],
 events:['wars-2','wow-0','wow-3'], related:['shadowcouncil','earthenring','cenarion'],
 s:"An apocalyptic cult that serves the Old Gods and wants to end all life. It began as an orc clan led by the ogre mage Cho'gall.",
 story:[
  ["Origin and purpose", [
   "The cult began on Draenor with the Pale, exiled orcs who lived beneath Oshu'gun and drew power from the Void. They believed in a prophecy called the Hour of Twilight, when shadow would swallow all life. Gul'dan sent his apprentice, the two-headed ogre mage Cho'gall, to bring them into the Horde. Cho'gall told them the Horde was the weapon that would bring that hour, and they joined as a new clan, the Twilight's Hammer.",
   "On Azeroth the Pale heard the whispers of the Old Gods, ancient evils imprisoned beneath the earth, and saw it as destiny. Cho'gall became their chieftain and, in time, a true believer. He kept them obedient to the Horde while they served their real masters in secret. He wrote their prophecies on pages cut from the skin of Pale orcs, a book called the Twilight Canticle."]],
  ["Key moments", [
   "In the Second War Cho'gall followed Gul'dan to the Tomb of Sargeras, and Orgrim Doomhammer turned on the traitors. Cho'gall survived and sailed west to Kalimdor. In Silithus his cultists performed a ritual that broke the bonds holding the Old God C'Thun, though most of them died doing it. C'Thun then sent Cho'gall to recruit, and the cult spread quietly into every city. It grew into a large group of many races, gathering outside Ahn'Qiraj and in places like Blackfathom Deeps. Before the war in Northrend, Cho'gall slipped into Ulduar and weakened the chains of the Old God Yogg-Saron.",
   "The cult's peak came with the Cataclysm. Many frightened people joined as Deathwing burned the world. Cultists had forged the armor plates that held his torn body together, and the Hammer took Grim Batol and the Twilight Highlands as its base. It attacked Mount Hyjal, Deepholm and the sea of Vashj'ir and raised twilight dragons. Cho'gall died in the Bastion of Twilight. A leader called the Twilight Father, secretly Archbishop Benedictus of Stormwind, carried on until heroes defeated him at Wyrmrest Temple."]],
  ["Where it stands now", [
   "After Deathwing's death the cult shrank to scattered cells. Remnants tried to wake old monsters in Blackfathom Deeps, Deepholm, Silithus and Darkshore, and a cultist ogre started a Deathwing cult on the Dragon Isles. During The War Within the remaining members reformed as the Twilight's Blade, now devoted to Xal'atath and forbidden to use the old hammer symbol. In Midnight its agents ambush, kidnap and sacrifice in and around Quel'Thalas."]]],
 wiki:"Twilight's Hammer", other:['Twilight Father (Archbishop Benedictus)','Twilight Lord Kelris (cult leader in Blackfathom Deeps)','Jedoga Shadowseeker (cult leader in Azjol-Nerub)','Zeryxia (twilight drake who led the remnants)']},

{id:'cenarion', n:'Cenarion Circle', kind:'Order of druids', align:'hero', founded:'About \u22129,300', base:'Nighthaven, Moonglade', status:'Active',
 leaders:['malfurion','fandral','cenarius'], members:[], races:['nightelves','tauren','trolls','worgen'],
 events:['kingdoms-3','wow-0','wow-3'], related:['sentinels','earthenring','twilight'],
 s:"The worldwide order of druids, who guard nature and keep the balance of life. Night elves founded it, and it now includes tauren, trolls, worgen and others from both factions.",
 story:[
  ["Origin and purpose", [
   "Malfurion Stormrage was the first mortal druid, taught by the forest demigod Cenarius. After the Sundering other night elves followed his path. During the War of the Satyr, about 9,300 years before the Dark Portal, a group of druids lost themselves to the rage of the wolf form and killed friend and foe alike. Malfurion called a meeting in the Moonglade and, with Cenarius's blessing, founded the Cenarion Circle to set rules and traditions so it would not happen again. The maddened wolf druids, the first worgen, were sealed away in the Emerald Dream.",
   "For thousands of years the druids slept for decades at a time, walking the Emerald Dream with the green dragon Ysera and healing the scars the Legion had left on the world. Almost all of them were night elf men."]],
  ["Key moments", [
   "Archdruid Fandral Staghelm planted cuttings from the World Tree without the Circle's approval. One of them, Andrassil in Northrend, was poisoned by the Old God Yogg-Saron and had to be cut down, and it opened a path for the Emerald Nightmare. In the War of the Shifting Sands, Fandral led druids and Sentinels against the qiraji, and the druids helped raise the Scarab Wall. The Circle then founded Cenarion Hold in Silithus to keep watch.",
   "After the Third War, Malfurion fell into a mysterious sleep and Fandral led the Circle. He planted Teldrassil and, misled by the Nightmare's lord Xavius, kept Malfurion trapped in the Dream. Meanwhile the Circle opened its ranks to women and to other races, starting with the tauren. It called on the Alliance and Horde to stop C'Thun's armies at Ahn'Qiraj. When Malfurion returned, Fandral was exposed and imprisoned. When the Dark Portal reopened, the Circle sent the Cenarion Expedition to explore Outland, and it grew into a large, fairly independent group. In the Cataclysm, Fandral escaped to serve the Firelord Ragnaros. The druids rallied the ancient Wild Gods to Mount Hyjal, found Cenarius's spirit in the Emerald Dream and brought him back, and helped defeat Ragnaros and Fandral in the Firelands."]],
  ["Where it stands now", [
   "Today Cenarius, Malfurion and several archdruids, among them the tauren Hamuul Runetotem, lead the Circle together. Its home is still Nighthaven in the Moonglade. In Legion the druids gathered in the Dreamgrove and helped defeat Xavius and his Nightmare. During the Fourth War the Circle mostly stayed neutral and joined the Earthen Ring to heal the wound Sargeras left in Silithus. In Dragonflight it helped protect the new World Tree, Amirdrassil. The Circle answers to no government."]]],
 wiki:'Cenarion Circle', other:['Hamuul Runetotem (first tauren archdruid)','Remulos (son of Cenarius)','Broll Bearmantle (archdruid)']},

{id:'earthenring', n:'Earthen Ring', kind:'Order of shamans', align:'hero', founded:'About \u2212230', base:'The Maelstrom', status:'Active',
 leaders:['thrall'], members:['aggra'], races:['tauren','orcs','trolls','draenei','dwarves','goblins'],
 events:['wow-3','wow-6'], related:['cenarion','twilight'],
 s:"The leading order of shamans, who keep the elements of earth, air, fire and water in balance. It began among the tauren and now draws shamans from both factions.",
 story:[
  ["Origin and purpose", [
   "The Earthen Ring was founded by tauren some time before Year \u2212230 to lead their people wisely and keep the elemental spirits in harmony. Its first Farseer had a vision of a future Farseer who would lead the order through a terrible crisis and unite the elements. Shamans of the Ring ask the elements for help and bargain for their power. The Ring even banned the summoning of molten giants, fearing that such force could anger the elements into disaster.",
   "The Ring's Council of Elders guides the order. For centuries it was a tauren tradition, and its shamans helped their people through the upheavals that shook Kalimdor."]],
  ["Key moments", [
   "After the Third War the Ring began admitting orc and Darkspear troll shamans from Thrall's Horde. Its elders even persuaded Thrall and Cairne Bloodhoof to accept the Forsaken into the Horde, believing shamanism might ease their condition. When the Dark Portal reopened, draenei and Broken shamans taught by the farseer Nobundo joined to heal Outland. Wildhammer dwarves and goblins came later.",
   "When Deathwing burst out of the elemental realm of Deepholm, he tore a wound between the worlds at the Maelstrom and shattered the World Pillar. The Earthen Ring gathered at the Maelstrom and called on the Alliance and Horde for help. Its shamans repaired the World Pillar, aided the water lord Neptulon's servants in Vashj'ir and fought the Twilight's Hammer wherever it appeared. Thrall stepped down as warchief to work with them, beside the Mag'har shaman Aggra, who became his wife. After Deathwing's death, Muln Earthfury stepped down and Thrall became the Ring's main leader."]],
  ["Where it stands now", [
   "In Legion the Ring was nearly broken on the Broken Shore, and its survivors gathered at the Heart of Azeroth beneath the Maelstrom. Thrall handed leadership to a new Farseer, a shaman hero Nobundo believed was the one from the old prophecy. The Farseer won over all four Elemental Lords to fight the Legion. The Ring helped raise Thunderaan as the new lord of air and backed Smolderon as the new Firelord. Smolderon later turned on the shamans and joined the Primalists in Dragonflight.",
   "In the Fourth War the Ring worked with the Cenarion Circle and Magni Bronzebeard to heal the wound Sargeras left in Silithus. It still watches over the Maelstrom and sent advisers to the Dragon Isles. In Dragonflight, Aggra was named a far seer and invited Dragonmaw orcs into the order."]]],
 wiki:'Earthen Ring', other:['Muln Earthfury (leader during the Cataclysm)','Nobundo (Broken farseer)',"Drek'Thar (elder far seer)",'Rehgar Earthfury (shaman)']},

{id:'illidari', n:'Illidari', kind:'Army of demon hunters', align:'grey', founded:'About Year 22', base:'The Black Temple, later the Fel Hammer', status:'Active; still hunting demons',
 leaders:['illidan'], members:['kaelthas'], races:['nightelves','bloodelves','naga','draenei','voidelves'],
 events:['wars-11','wow-1','wow-6'], related:['watchers','armylight'],
 s:"Illidan Stormrage's followers, above all his demon hunters, who take demonic power into themselves to destroy the Burning Legion. Once enemies in Outland, they became allies against the Legion.",
 story:[
  ["Origin and purpose", [
   "Illidan Stormrage became the first demon hunter ten thousand years ago, when Sargeras burned out his eyes and marked his body. After the Third War the demon lord Kil'jaeden ordered him to destroy the Lich King. Illidan called Lady Vashj and her naga from the sea and allied with Prince Kael'thas and his blood elves. When his attack on the Frozen Throne failed, he fled to Outland, overthrew the pit lord Magtheridon and made himself its lord. Akama's Ashtongue Broken, the fel orcs and many demons joined his army, and he took the Black Temple.",
   "Night elves who had lost everything to the Legion sought him out, and Illidan trained them as demon hunters, warriors who bind demonic power into their own bodies. A few blood elves were trained too. He also freed the demons in his service from their hunger for fel magic."]],
  ["Key moments", [
   "Illidan led his demon hunters against Legion worlds. They destroyed Nathreza, the home of the dreadlords, and stole the location of Argus, the Legion's seat. When the Alliance and Horde reached Outland they saw Illidan as an enemy. Kael'thas turned to the Legion, and Akama betrayed Illidan to the heroes and to Maiev Shadowsong. Illidan died in the Black Temple. His demon hunters returned from a mission on the world Mardum and were locked in the Vault of the Wardens with his body.",
   "Years later, when the Legion attacked the vault, Maiev had to free them. The Illidari won trust by exposing demon assassins at the funerals of Varian and Vol'jin, and both factions accepted them. From a captured Legion ship, the Fel Hammer, they fought beside the other orders. Illidan's spirit named a demon hunter hero, the Slayer, to lead in his place. Illidan himself returned, killed Gul'dan and fought on Argus, then stayed behind as Sargeras's jailer."]],
  ["Where it stands now", [
   "The Illidari still use the Fel Hammer as their base and hunt demons that survived the Legion's fall, in Outland and on Azeroth. Some have joined the Alliance or the Horde as individuals. In Midnight the demon hunter Allari the Souleater trained Leona Darkstrider and other void elves, who learned to bind the Void the way the Illidari bind fel. Demon hunters also broke a ring smuggling Legion relics into Silvermoon and joined the void elves in striking Xal'atath's forces on other worlds."]]],
 wiki:'Illidari', other:['Kayn Sunfury (demon hunter commander)','Altruis the Sufferer (demon hunter commander)','Akama (leader of the Ashtongue Broken)',"Lady Vashj (leader of Illidan's naga)",'Allari the Souleater (demon hunter)']},

{id:'armylight', n:'Army of the Light', kind:'Crusade against the Burning Legion', align:'hero', founded:'About \u221213,000', base:'The Vindicaar', status:'Active; badly weakened after the Voidspire',
 leaders:['xera','turalyon'], members:['alleria'], races:['draenei','lightforged'],
 events:['cosmos-5','wow-6','wow-11'], related:['silverhand','illidari'],
 s:"A crusade of Light-wielding warriors led by the naaru Xe'ra that fought the Burning Legion for millennia. Its veterans, the Lightforged, now fight for the Alliance.",
 story:[
  ["Origin and purpose", [
   "About 13,000 years ago the naaru rescued Prophet Velen and his followers when the rest of the eredar fell to Sargeras. The naaru promised that these exiles, the draenei, would one day be part of a great force against the Legion. The survivors split between two dimensional ships. Velen's people took the Genedar, which later crashed on Draenor. The finest warriors followed the prime naaru Xe'ra aboard the Xenedar to fight the Legion across the Twisting Nether.",
   "The most devoted soldiers became Lightforged, their bodies infused with the Holy Light and made nearly immortal. For ages they struck at the Legion's homeworld, Argus, in quick raids. Other enemies of the Legion joined along the way, including Lothraxion, a dreadlord who turned to the Light."]],
  ["Key moments", [
   "After Draenor was torn apart, Lothraxion brought Turalyon and Alleria Windrunner into the Army. Time moves differently in the Nether, and while twenty years passed on Azeroth they fought for more than five hundred. Xe'ra made Turalyon Lightforged, and he rose to High Exarch. Alleria turned to the Void on Argus and went her own way. Near defeat, Turalyon recorded a plea for help in Xe'ra's Light's Heart and sent it toward Azeroth.",
   "Xe'ra also believed the Void was a greater enemy than the Legion, and she had marked Illidan Stormrage as a hero destined to lead the fight against it. The plea arrived. In Legion the Highlord of the Silver Hand freed Lothraxion from a Legion prison world, and his forces helped the paladins defeat the dreadlord Balnazzar. Then the heroes of Azeroth reached Argus on the draenei ship Vindicaar. The Xenedar was shot down, but Turalyon survived and joined them. Xe'ra tried to force Illidan to accept the destiny she had seen for him, and he destroyed her. The Army fought on and held the line at Antorus while the titans' Pantheon imprisoned Sargeras. With the Legion beaten, the Lightforged came to Azeroth aboard the Vindicaar and pledged themselves to the Alliance."]],
  ["Where it stands now", [
   "The Army fought for the Alliance in the Fourth War, and some of its forces kept battling demon remnants on Argus. Its soldiers came to Khaz Algar to fight Xal'atath. In Midnight Azeroth summoned it to defend the Sunwell. During the failed siege of the Voidspire, Turalyon was lost to the Void, and many Lightforged were killed or badly wounded. Captain Fareeya now commands what remains. She sent Lightforged troops, with help from the Lightveil ethereals, to join the void elves' counterattack on Xal'atath's forces on distant worlds."]]],
 wiki:'Army of the Light', other:['Lothraxion (dreadlord turned to the Light)','Captain Fareeya (commander after Turalyon)']},

{id:'bloodknights', n:'Blood Knights', kind:'Order of paladins', align:'hero', founded:'Year 25', base:'Hall of Blood, Silvermoon City', status:'Active',
 leaders:['liadrin'], members:[], races:['bloodelves'],
 events:['wow-1','wow-11'], related:['silverhand','silvercovenant'],
 s:"The blood elf order of paladins. It began by draining the Light from a captive naaru and now draws its power from the restored Sunwell.",
 story:[
  ["Origin and purpose", [
   "After the Scourge ravaged Quel'Thalas, many blood elves felt the Light had abandoned them, and they lost their holy powers. Prince Kael'thas sent a captured naaru, M'uru, home to Silvermoon. In Year 25 the master mages Rommath and Astalor Bloodsworn subdued it and planned a new order of warriors who would command the Light through willpower alone.",
   "They offered command to Liadrin, a former priestess who had come to scorn the Light. She became the first Blood Knight and Matriarch of the order. Many recruits were former priests or members of the Royal Guard. The Farstriders and many ordinary elves found the method immoral, and Regent Lord Lor'themar Theron had doubts. Drawing on M'uru was often painful. The Lich King, curious about Light-wielders with no moral code, sent the traitor Dar'Khan Drathir and his undead to destroy them. The knights beat him back in the Ghostlands, and such victories slowly won the public over."]],
  ["Key moments", [
   "The Blood Knights helped bring the blood elves into the Horde. Thrall and Cairne noted their power but disliked their methods. To show they were the true masters of the Light, the knights defiled the founding chapel of the Silver Hand. Then Kael'thas, now serving the Legion, returned and took M'uru from beneath their headquarters. Liadrin learned from the naaru A'dal that M'uru had known his fate and had let himself be used. She pledged the order to the Shattered Sun Offensive, which defeated Kael'thas and his master Kil'jaeden at the Sunwell. Prophet Velen used M'uru's heart to restore the Sunwell as a source of both arcane magic and Light.",
   "From then on the knights drew their power from the Sunwell and asked for the Light's blessing, a far gentler bond. In Legion, Liadrin joined the reformed Silver Hand, and many knights followed. In the Fourth War they returned to the Horde's side. After the war against the Jailer, Liadrin and her adopted daughter Salandria led the knights against a Scourge revival in the Ghostlands and destroyed its leader, the vampire lord Vorath."]],
  ["Where it stands now", [
   "The order is one of the three pillars of Silvermoon, beside the Magisters and the Farstriders. In Midnight, when Xal'atath struck at the Sunwell, most of the city's knights were sent to pour their power into it, which left Silvermoon thinly defended. Liadrin led the defense of the city, healed the wounded on both sides after a clash with the Amani trolls and began helping the Amani reconnect with their gods. The Blood Knights then fought to retake the Isle of Quel'Danas."]]],
 wiki:'Blood Knights', other:['Rommath (Grand Magister, co-founder)','Astalor Bloodsworn (magister, co-founder)','Mehlar Dawnblade (former pupil of Uther)',"Salandria (Liadrin's adopted daughter)","Solanar Bloodwrath (Liadrin's right hand)"]},

{id:'sentinels', n:'Sentinels', kind:'Night elf army', align:'hero', founded:'About \u22129,400', base:"Bel'ameth, on the World Tree Amirdrassil", status:'Active',
 leaders:['tyrande','shandris'], members:[], races:['nightelves','worgen'],
 events:['kingdoms-3','wars-9','wow-7'], related:['cenarion','watchers'],
 s:"The army of the night elves, built from the warrior priestesses of Elune. For ten thousand years it has guarded kaldorei lands, mostly with women in its ranks.",
 story:[
  ["Origin and purpose", [
   "In the War of the Ancients the night elf army proved weak. Its officers held rank by birth, and few knew tactics. Afterward High Priestess Tyrande Whisperwind turned to her Sisterhood of Elune, which had survived largely intact and whose members were trained in combat and healing. About 9,400 years before the Dark Portal she created the Sentinels from its ranks to protect the new night elf society, with the Sisterhood directing the army.",
   "The Sentinels were warrior women who fought and healed in Elune's name. Archers formed the front rank, huntresses rode nightsaber panthers, and hippogryph riders scouted the skies. Tyrande's adopted daughter Shandris Feathermoon became their general. Nearly every kaldorei town had a Sentinel garrison."]],
  ["Key moments", [
   "The Sentinels fought in the War of the Satyr and, 975 years before the Dark Portal, marched under Fandral Staghelm against the qiraji in Silithus at heavy cost. In the Third War they fought the orcs who killed Cenarius and then the Legion. At Mount Hyjal they stood with humans and orcs while Malfurion's trap destroyed Archimonde. Their losses were so heavy that the night elves began letting more men into the ranks. Soon after, Sentinels sailed with Tyrande and Malfurion to the Broken Isles and Lordaeron to help Maiev hunt Illidan.",
   "From Darnassus and Feathermoon Stronghold, the Sentinels fought the Horde over Ashenvale for years and served across the world as part of the Alliance. They brought siege engines to help evacuate Gilneas, and the Moonclaw worgen joined their ranks. At the Siege of Orgrimmar, Tyrande led mounted Sentinels who broke through the city's main gate. At the start of the Fourth War much of the army sailed for Silithus, where a Horde campaign turned out to be a ruse. The Horde struck Ashenvale and Darkshore instead, and Sylvanas burned Teldrassil. The surviving Sentinels fought on and joined the attack on Lordaeron."]],
  ["Where it stands now", [
   "After Teldrassil fell, Tyrande's people lived on Mount Hyjal. In Dragonflight the Sentinels followed her into the Emerald Dream to fight Fyrakk. When the new World Tree, Amirdrassil, bloomed, they took up guard over it and its city of Bel'ameth, with Arlithrien Lodge as their headquarters. Tyrande and Malfurion then stepped down and named Shandris leader of the night elves. The Sentinels went to Khaz Algar with the Alliance to fight Xal'atath."]]],
 wiki:'Sentinels', other:['Delaryn Summermoon (captain who died defending Darkshore)',"Myara Nightsong (commander at Bel'ameth)"]},

{id:'watchers', n:'Watchers', kind:'Night elf jailers and marshals', align:'grey', founded:'After \u221210,000', base:'Vault of the Wardens, Broken Isles', status:'Active',
 leaders:['maiev'], members:[], races:['nightelves'],
 events:['ancients-5','wars-11','wow-1','wow-6'], related:['illidari','sentinels'],
 s:"The night elves' jailers and bounty hunters, created to guard Illidan Stormrage. Their leader, Maiev Shadowsong, holds the rank of Warden and grants it only to the best.",
 story:[
  ["Origin and purpose", [
   "Shortly after the Great Sundering, Malfurion Stormrage sentenced his twin Illidan to prison for creating a new Well of Eternity. Illidan was too dangerous for one or two guards. Malfurion asked Maiev Shadowsong, a senior Sister of Elune who had already guarded Illidan, to gather volunteers from the Sisterhood. He called them the Watchers. Maiev answered to High Priestess Tyrande Whisperwind.",
   "Tyrande later widened their duties. The Watchers became the jailers and marshals of night elf society, running barrow prisons and hunting dangerous criminals across Azeroth. They belonged to neither the Sentinels nor the Sisterhood. Maiev held the rank of Warden and gave it to a few others of exceptional skill. In Azsuna they carved the Vault of the Wardens, where they locked away their worst prisoners for millennia."]],
  ["Key moments", [
   "In the Third War Tyrande decided Illidan had served his time and might help against the Legion. The Watchers refused to release him, and her soldiers fought them to free him. Maiev took most of the Watchers on the hunt. In the Tomb of Sargeras, Illidan flooded a chamber and drowned many of them, including her lieutenant Naisha. Maiev chased him to Lordaeron and then to Outland, captured him once and lost him again.",
   "In Outland only about thirty Watchers remained. They recruited draenei and Broken, but Illidan ambushed them, killed them all and took Maiev prisoner. Akama freed her, and she helped the heroes kill Illidan in the Black Temple. She sealed his body and his demon hunters in the Vault. In the novel Wolfheart, a broken Maiev turned her new Watchers against the Highborne, yet later stories still show her leading the order. In the Cataclysm, Watchers guarded the barrow prisons beneath Mount Hyjal. When the fallen archdruid Fandral Staghelm escaped them, their Shadow Wardens followed his Druids of the Flame into the Firelands to hunt them down."]],
  ["Where it stands now", [
   "In Legion, Gul'dan stormed the Vault with help from the traitor Cordana Felsong, killed most of the Wardens and stole Illidan's body. The survivors rebuilt and hunted down the escaped prisoners, and Maiev joined the Armies of Legionfall alongside Illidan's demon hunters. In the Fourth War some Wardens were raised by the Forsaken and turned on their own people as Dark Wardens.",
   "Since then the Watchers have contained the threats inside the Vault and kept guard at the Tomb of Sargeras. In Dragonflight, Maiev purged a demon cult from Felwood and asked for volunteers to serve as Wardens of Bel'ameth."]]],
 wiki:'Watchers', other:["Naisha (Maiev's first lieutenant)",'Sira Moonwarden (interim leader, later a Dark Warden)','Cordana Felsong (warden who betrayed the order)','Califax (keeper of the grove who guarded Illidan)']},

{id:'silvercovenant', n:'Silver Covenant and Sunreavers', kind:'Rival elven factions of Dalaran', align:'grey', founded:'Year 27 (Wrath of the Lich King)', base:"Dalaran (the Silver Enclave and Sunreaver's Sanctuary)", status:'Disbanded; united as the Silversun Compact',
 leaders:['vereesa'], members:[], races:['bloodelves'],
 events:['wow-2','wow-4','wow-10','wow-11'], related:['kirintor','bloodknights'],
 s:"Two elven factions that represented the Alliance and the Horde in Dalaran. The high elf Silver Covenant and the blood elf Sunreavers feuded for years, then united in Midnight as the Silversun Compact.",
 story:[
  ["Origin and purpose", [
   "Elves of Quel'Thalas had studied and served in Dalaran for two thousand years. After the Third War that bond broke. The Alliance commander Garithos sentenced Kael'thas and his blood elves to death in Dalaran's dungeons, and many elves blamed the Kirin Tor. Quel'Thalas later joined the Horde.",
   "When the Kirin Tor needed Quel'Thalas's help against Malygos in Wrath of the Lich King, Archmage Aethas Sunreaver, a blood elf on the Council of Six, worked to bring his people back into the Kirin Tor. His followers took his name and gave the Horde a sanctuary in the city. Alliance-loyal high elves would not accept this. Led by Vereesa Windrunner, youngest of the Windrunner sisters, they formed the Silver Covenant as a guard against Horde treachery. Each side held its own district of Dalaran."]],
  ["Key moments", [
   "Both factions fought the Lich King in Northrend, and the Sunreavers won readmission to the Kirin Tor. In the Cataclysm, Vereesa and the Covenant answered a call from Quel'Thalas's Ranger-General to fight the Amani trolls, against the wishes of the regent lord. Then the Sunreaver mage Thalen Songweaver turned out to be Garrosh Hellscream's spy at Theramore and helped create the bomb that killed Vereesa's husband, Rhonin. Later a Sunreaver portal let Garrosh's agents steal the Divine Bell from Darnassus. Jaina Proudmoore, now leader of the Kirin Tor, purged the Horde from Dalaran. The Silver Covenant killed Sunreavers who resisted, and innocent blood elves died in the carnage. Grand Magister Rommath raided the city to rescue Aethas and his people. Back home, the Sunreavers fought for Lor'themar Theron as the Sunreaver Onslaught and raced the Covenant's allies for the Isle of Thunder.",
   "In Legion, Aethas helped recover the Sunstrider sword Felo'melorn and won back his place in Dalaran, though the Covenant kept a close watch on the Sunreavers. In The War Within both groups defended Dalaran together when Xal'atath's nerubians attacked, and their survivors were stranded on the Isle of Dorn when the city fell."]],
  ["Where it stands now", [
   "In Midnight, Vereesa led what remained of the Covenant to Quel'Thalas to help against the Void, still haunted by the Purge. Aethas met her at Silvermoon's gates and called her people murderers. Arator Windrunner urged unity, and the Covenant came bearing the ashes of slain Sunreavers for burial and relics of King Anasterian's reign. During the fight to retake Quel'Danas, Aethas and Vereesa agreed their wounded factions could no longer fight each other. They disbanded both and founded the Silversun Compact, an elven union outside the Alliance and the Horde, sworn to share magic and strength against common threats."]]],
 wiki:'Silver Covenant', other:['Aethas Sunreaver (archmage, leader of the Sunreavers)','Thalen Songweaver (Sunreaver who betrayed Theramore)','Rommath (Grand Magister, opposed and later rescued the Sunreavers)']},

{id:'si7', n:'SI:7', kind:'Spy agency of Stormwind', align:'grey', founded:'Before the Third War (date unknown)', base:'Old Town, Stormwind City', status:'Active',
 leaders:[], members:[], races:['humans','gnomes','goblins'],
 events:[], related:['twilight'],
 s:"Stormwind's secret intelligence service, a network of spies and assassins that serves the king and the Alliance. Spymaster Mathias Shaw has led it for many years.",
 story:[
  ["Origin and purpose", [
   "SI:7, short for Stormwind Intelligence, works from a building in Stormwind's Old Town and answers to the kingdom's ruler. Its agents are mostly rogues trained in spying, sabotage, stealth and assassination. Current lore does not say when it was founded. Its earliest recorded work came before the Third War, when King Varian Wrynn sent an elite agent to spy on Lordaeron and look into rumors of a plague. The old Warcraft roleplaying books gave it a longer history, founded by Mathias Shaw's grandmother, but those books are not canon.",
   "Mathias Shaw, its spymaster, is a master rogue who once trained his childhood friend Edwin VanCleef. The agency recruits widely. Shaw's favorite source of new spies is Tinker Town in Ironforge, because gnomes are clever, curious and small, and the goblin Renzik served as his second in command."]],
  ["Key moments", [
   "In the early World of Warcraft years SI:7 watched the Defias Brotherhood, rooted out traitors among the nobles and investigated the undead. It failed to see through Onyxia, the black dragon who ruled Stormwind's court in disguise and clouded Shaw's mind with magic. Before the Cataclysm, eighteen SI:7 assassins went with Varian into Ironforge to break Moira Thaurissan's hold on the city. In the Twilight Highlands, Shaw ran operations against the Twilight's Hammer and lost a whole team of reinforcements to Cho'gall. Agents later found the shipwrecked Prince Anduin on Pandaria and stirred up trouble for Garrosh outside Orgrimmar.",
   "Its worst failure came in Legion. Before the battle on the Broken Shore, the dreadlord Detheroc captured Shaw and took his place, and he had agent Amber Kearnen killed to hide the truth. The rogues of the Uncrowned uncovered the plot, freed Shaw and killed Detheroc. Shaw now makes every new agent learn Detheroc's name as a warning."]],
  ["Where it stands now", [
   "After Legion, SI:7 spied on the Forsaken during the peace talks known as the Gathering. In Battle for Azeroth it kept so many spies in Orgrimmar that the Horde could not root them all out, and Shaw worked closely with the blood elf rogue Valeera Sanguinar in the Alliance war effort. Under King Anduin it helped clean corruption out of the House of Nobles. In Dragonflight it kept watch on the dracthyr and on Wrathion's agents. In The War Within, Shaw carried Renzik's ashes back to Undermine after the goblin died helping free its people. SI:7 remains active with Shaw at its head."]]],
 wiki:'SI:7', other:['Mathias Shaw (spymaster)','Renzik "The Shiv" (goblin agent, Shaw\'s second in command)','Amber Kearnen (agent killed by the dreadlord Detheroc)','Elling Trias (senior agent)']}

];
