// Races, part 1: Alliance and races open to both factions.
// Fields: id, n name, nn native name, f faction group, tag (playable since / allied race), home, cap, lead,
// s summary, h history [[when, text]], fig character ids on the map, more other notable figures,
// kin [[race id, relation]], wiki page title
window.RACES = window.RACES || [];
window.RACES.push(
{id:'humans',n:'Humans',f:'alliance',tag:'Core race \u00b7 2004',home:'Eastern Kingdoms',cap:'Stormwind City',lead:'High King Anduin Wrynn',
 s:"Short-lived and ambitious, humans descend from the vrykul, giants made by the titans' Keepers. The Arathi tribe united them into the empire of Arathor, and the high elves taught them magic. Arathor later split into seven kingdoms. Humans founded the Alliance, lost Lordaeron to the Scourge, and today rally around Stormwind.",
 h:[['Ancient',"Vrykul children born small and mortal under the Curse of Flesh are hidden in the south. They become the first humans."],
    ['\u22122,800',"Thoradin unites the human tribes as Arathor. Fighting beside the high elves, they win the Troll Wars and learn magic."],
    ['After the Troll Wars',"Arathor splits into the Seven Kingdoms: Stormwind, Lordaeron, Gilneas, Kul Tiras, Alterac, Stromgarde and Dalaran."],
    ['First War',"The Horde destroys Stormwind. Survivors flee north, and the Alliance of Lordaeron is formed."],
    ['Year 20',"The plague and the Scourge destroy Lordaeron. Stormwind becomes the heart of humanity."],
    ['Legion',"Varian dies on the Broken Shore and Anduin becomes king."]],
 fig:['llane','lothar','varian','anduin','terenas','arthas','calia','jaina','uther','tirion','turalyon','khadgar','medivh','antonidas'],
 more:['Thoradin (first king of Arathor)'],
 kin:[['vrykul','Ancestors'],['kultirans','A seafaring human kingdom'],['worgen','Gilnean humans under the worgen curse'],['forsaken','Most were once humans of Lordaeron'],['bloodelves','Allies who taught them magic']],
 wiki:'Human'},
{id:'dwarves',n:'Dwarves',f:'alliance',tag:'Core race \u00b7 2004',home:'Khaz Modan',cap:'Ironforge',lead:'The Council of Three Hammers',
 s:"Sturdy miners, smiths and explorers descended from the earthen, beings of living stone made by the titans. The Curse of Flesh turned the earthen into mortal dwarves. A civil war split them into three clans: the Bronzebeards of Ironforge, the Wildhammers of the Hinterlands and the Dark Irons.",
 h:[['Ancient',"The titans' keepers make the earthen to shape the deep places of the world. Over time the Curse of Flesh turns most of them into dwarves."],
    ['\u2212230',"The War of the Three Hammers splits the Bronzebeard, Wildhammer and Dark Iron clans."],
    ['Second War',"The Horde invades Khaz Modan, and the dwarves join the Alliance of Lordaeron."],
    ['Cataclysm',"A ritual turns King Magni to diamond. His daughter Moira claims the throne, and the three clans agree to rule together."],
    ['The War Within',"The dwarves meet their earthen ancestors in Khaz Algar."]],
 fig:['magni','muradin','moira'],
 more:['Brann Bronzebeard (explorer)','Falstad Wildhammer'],
 kin:[['earthen','Ancestors, made of stone'],['darkiron','A sister clan'],['gnomes','Neighbors and closest allies']],
 wiki:'Dwarf'},
{id:'nightelves',n:'Night elves',nn:"Kaldorei",f:'alliance',tag:'Core race \u00b7 2004',home:'Kalimdor',cap:'Darnassus, until Teldrassil burned',lead:'Shandris Feathermoon, since Tyrande and Malfurion stepped down',
 s:"The first elves, descended from trolls who settled beside the Well of Eternity. Their empire's abuse of magic brought the Legion and the Sundering. Afterward they gave up arcane magic, turned to druidism and the moon goddess Elune, and guarded the forests for ten thousand years.",
 h:[['Before \u221210,000',"Trolls living by the Well of Eternity are changed by its power into the first night elves."],
    ['\u221210,000',"Queen Azshara brings the Legion into the world. The Well collapses in the Sundering."],
    ['After \u221210,000',"They plant Nordrassil, gain immortality, ban the arcane and exile the Highborne who refuse."],
    ['Year 21',"Archimonde is destroyed at Mount Hyjal. The sacrifice of Nordrassil costs the night elves their immortality."],
    ['Battle for Azeroth',"Sylvanas burns Teldrassil and their capital with it. Tyrande becomes the Night Warrior."],
    ['Dragonflight',"A new World Tree, Amirdrassil, blooms on the Dragon Isles, and the night elves settle its city of Bel'ameth. Tyrande and Malfurion step down and name Shandris leader."]],
 fig:['malfurion','tyrande','illidan','azshara','maiev','shandris','fandral','cenarius','elune','xavius'],
 more:['Jarod Shadowsong'],
 kin:[['trolls','Ancestors'],['haranir','Distant ancestors, say the haranir'],['bloodelves','Descendants of the exiled Highborne'],['nightborne','Highborne who stayed in Suramar'],['naga','Highborne who sank with Azshara'],['worgen','The worgen curse began with night elf druids']],
 wiki:'Night elf'},
{id:'gnomes',n:'Gnomes',f:'alliance',tag:'Core race \u00b7 2004',home:'Dun Morogh',cap:'Gnomeregan (contaminated)',lead:'King Gelbin Mekkatorque',
 s:"Brilliant, small tinkers descended from the mechagnomes, titan-made machines that the Curse of Flesh turned into living beings. They lost their underground city of Gnomeregan to an invasion and a traitor's sabotage, and have spent years winning it back.",
 h:[['Ancient',"The mechagnomes made by the keeper Mimiron fall to the Curse of Flesh and become gnomes."],
    ['Second War',"Gnomes join the Alliance and supply its machines."],
    ['Before World of Warcraft',"Troggs invade Gnomeregan. On the advice of the traitor Sicco Thermaplugg, Mekkatorque floods the city with radiation, and most gnomes flee to Ironforge."],
    ['Cataclysm',"Operation: Gnomeregan wins back part of the city."],
    ['Battle for Azeroth',"Gnomes find the lost kingdom of Mechagon, founded by a former gnome king, and help overthrow him. Mekkatorque becomes king of all gnomes."]],
 fig:[],
 more:['Gelbin Mekkatorque (High Tinker, now king)','Sicco Thermaplugg (the traitor)'],
 kin:[['mechagnomes','Gnomes of Mechagon, now reunited with Gnomeregan'],['dwarves','Neighbors and closest allies']],
 wiki:'Gnome'},
{id:'draenei',n:'Draenei',f:'alliance',tag:'Core race \u00b7 2007',home:'Argus, then Draenor',cap:'The Exodar',lead:'Prophet Velen',
 s:"Eredar who refused Sargeras and fled their homeworld of Argus with Velen and the naaru. Hunted by the Legion for thousands of years, they settled on Draenor, where the corrupted orcs nearly wiped them out. Their ship, the Exodar, later crashed on Azeroth and they joined the Alliance.",
 h:[['\u2248 \u221213,000',"Velen refuses Sargeras's offer and flees Argus with the naaru."],
    ['\u2212200',"The draenei settle on Draenor beside the orc clans."],
    ['\u221210 to \u22123',"The corrupted orcs slaughter them, and the city of Shattrath falls."],
    ['The Burning Crusade',"The Exodar crashes on Azuremyst Isle, and the draenei join the Alliance."],
    ['Legion',"They return to Argus and see the Legion broken."]],
 fig:['velen','yrel','xera','muru'],
 more:['Akama (leader of the Broken)','Maraad (vindicator)'],
 kin:[['eredar','The same people; those who stayed became demons'],['lightforged','Crusaders of the Army of the Light']],
 wiki:'Draenei'},
{id:'worgen',n:'Worgen',f:'alliance',tag:'Core race \u00b7 2010',home:'Gilneas',cap:'Gilneas City',lead:'Queen Tess Greymane',
 s:"Humans of Gilneas who carry the worgen curse, which turns them into wolf-like beasts. The curse began long ago with night elf druids. Gilneas walled itself off from the world, then fell to the curse and to the Forsaken. With night elf help, the worgen learned to keep their minds and rejoined the Alliance. In Dragonflight they finally won their homeland back.",
 h:[['After \u221210,000',"Night elf druids of the Pack use the Scythe of Elune to take on wolf forms. The worgen curse begins."],
    ['After the Second War',"Gilneas builds the Greymane Wall and leaves the Alliance."],
    ['Before World of Warcraft',"Archmage Arugal summons worgen to fight the Scourge, and the curse spreads."],
    ['Cataclysm',"The curse breaks out inside Gilneas and the Forsaken invade. Liam Greymane dies, and the survivors join the Alliance."],
    ['Dragonflight',"Gilneas is reclaimed with help from the Forsaken, and Genn passes the crown to his daughter Tess."]],
 fig:['genn','sylvanas'],
 more:['Darius Crowley','Tess Greymane','Liam Greymane (killed by Sylvanas)'],
 kin:[['humans','The same people, cursed'],['nightelves','The curse began with night elf druids']],
 wiki:'Worgen'},
{id:'voidelves',n:'Void elves',nn:"Ren'dorei",f:'alliance',tag:'Allied race \u00b7 2018',home:'Telogrus Rift',lead:'Magister Umbric, since Alleria was lost in the Void',
 s:"Blood elves exiled from Silvermoon for studying the Void. In Telogrus Rift, void creatures tried to strip away their flesh. Alleria Windrunner rescued them and taught them to control their new powers, and they joined the Alliance.",
 h:[['Legion',"Magister Umbric and his followers are exiled from Silvermoon for studying the Void."],
    ['Legion',"Void ethereals in Telogrus Rift transform them. Alleria rescues them and teaches them control."],
    ['Battle for Azeroth',"They join the Alliance as an allied race."],
    ['Midnight',"Umbric places a Void crystal in the Sunwell to help form the Dawnwell."]],
 fig:['umbric','alleria'],
 more:[],
 kin:[['bloodelves','Former kin who exiled them']],
 wiki:'Void elf'},
{id:'lightforged',n:'Lightforged draenei',f:'alliance',tag:'Allied race \u00b7 2018',home:'Argus and the Twisting Nether',cap:'The Vindicaar',lead:'Captain Fareeya, since Turalyon was lost in the Void',
 s:"Draenei of the Army of the Light who fought the Legion across the Twisting Nether for millennia. The most devoted underwent a ritual that infused their bodies with the Light itself. After the victory on Argus, they pledged themselves to the Alliance.",
 h:[['For millennia',"Draenei join Xe'ra's Army of the Light and fight the Legion across the Nether."],
    ['Legion',"They fight beside Azeroth's heroes on Argus."],
    ['Battle for Azeroth',"Under Turalyon they join the Alliance as an allied race."]],
 fig:['turalyon','xera'],
 more:['Captain Fareeya'],
 kin:[['draenei','The same people']],
 wiki:'Lightforged draenei'},
{id:'darkiron',n:'Dark Iron dwarves',f:'alliance',tag:'Allied race \u00b7 2018',home:'Blackrock Mountain',cap:'Shadowforge City',lead:'Queen-Regent Moira Thaurissan',
 s:"The fiery dwarven clan that lost the War of the Three Hammers. Their sorcerer-thane summoned Ragnaros, who enslaved them for centuries. Moira Thaurissan, Magni's daughter and widow of their emperor, brought them back into the dwarven fold and the Alliance.",
 h:[['\u2212230',"Defeated in the War of the Three Hammers, Sorcerer-Thane Thaurissan summons Ragnaros, who enslaves the Dark Irons."],
    ['World of Warcraft',"Shadowforge City serves the Firelord inside Blackrock Mountain."],
    ['Cataclysm',"Moira takes a seat on Ironforge's Council of Three Hammers."],
    ['Battle for Azeroth',"The Dark Irons join the Alliance as an allied race."]],
 fig:['moira','ragnaros','magni'],
 more:['Dagran Thaurissan II (Moira\u2019s son)'],
 kin:[['dwarves','A sister clan']],
 wiki:'Dark Iron dwarf'},
{id:'kultirans',n:'Kul Tirans',f:'alliance',tag:'Allied race \u00b7 2019',home:'Kul Tiras',cap:'Boralus',lead:'Lord Admiral Jaina Proudmoore',
 s:"The broad-shouldered seafarers of Kul Tiras, once the richest human kingdom and the Alliance's navy. After Daelin Proudmoore's death the island nation withdrew from the world, until his daughter Jaina came home and brought it back into the Alliance.",
 h:[['After the Troll Wars',"Kul Tiras is founded as an Arathorian city-state and becomes a great sea power."],
    ['Second War',"Daelin Proudmoore commands the Alliance fleet."],
    ['Year 21',"Daelin dies attacking the new Horde, and Kul Tiras turns inward."],
    ['Battle for Azeroth',"Jaina returns home, uncovers plots by House Ashvane and the drust witches, and Kul Tiras rejoins the Alliance."]],
 fig:['jaina','daelin'],
 more:['Katherine Proudmoore (Jaina\u2019s mother)','Derek Proudmoore (Jaina\u2019s brother)'],
 kin:[['humans','A branch of humanity']],
 wiki:'Kul Tiran'},
{id:'mechagnomes',n:'Mechagnomes',f:'alliance',tag:'Allied race \u00b7 2020',home:'Mechagon Island',lead:'King Gelbin Mekkatorque, advised by Prince Erazmin',
 s:"Gnomes of Mechagon Island who rebuilt their bodies with machinery. Their ancestors followed King Mechagon, a gnome king who left Gnomeregan long ago, and they named themselves after the titan-forged mechagnomes that Mimiron built, the true ancestors of all gnomes. When their king tried to force his machines on all life, they rebelled and joined the Alliance.",
 h:[['Ancient',"The keeper Mimiron builds the titan-forged mechagnomes. The Curse of Flesh turns most of them into gnomes."],
    ['Centuries ago',"A gnome king leaves Gnomeregan with his followers, founds Mechagon and begins replacing flesh with machinery."],
    ['Battle for Azeroth',"Prince Erazmin's rebels overthrow King Mechagon. Mechagon reunites with Gnomeregan and joins the Alliance."]],
 fig:[],
 more:['Prince Erazmin','King Mechagon (overthrown)','Mimiron (keeper)'],
 kin:[['gnomes','The same people, reunited']],
 wiki:'Mechagnome'},

// Open to both factions
{id:'pandaren',n:'Pandaren',f:'both',tag:'Core race \u00b7 2012',home:'Pandaria and the Wandering Isle',lead:'Each faction\u2019s pandaren have their own leaders',
 s:"Peaceful, hard-living bear people. They threw off their mogu masters and built an empire, then hid their continent in mist when the world broke apart. Some sailed away on a giant turtle, Shen-zin Su, and their descendants joined both factions when the mists parted.",
 h:[['Ancient',"The pandaren rise up against their mogu masters and found their own empire."],
    ['\u221210,000',"During the Sundering, Emperor Shaohao hides Pandaria behind a veil of mist."],
    ['\u2248 \u2212800',"The explorer Liu Lang leaves on the turtle Shen-zin Su, founding the Wandering Isle."],
    ['Mists of Pandaria',"The mists part. Pandaren of the Wandering Isle choose sides: the Tushui join the Alliance, the Huojin the Horde."]],
 fig:['yshaarj','garrosh'],
 more:['Chen Stormstout (brewmaster)','Emperor Shaohao','Aysa Cloudsinger (Tushui)','Ji Firepaw (Huojin)'],
 kin:[],
 wiki:'Pandaren'},
{id:'dracthyr',n:'Dracthyr',f:'both',tag:'Core race \u00b7 2022',home:'The Forbidden Reach, Dragon Isles',lead:'Scalecommander Emberthal',
 s:"Humanoid dragonkin created by Neltharion as ideal soldiers, able to use the magic of all five dragonflights. After a war with the Primalists, they were sealed in a magical sleep. They woke millennia later and chose their own path, some joining the Alliance and some the Horde.",
 h:[['Ancient',"Neltharion creates the dracthyr in Aberrus as his elite soldiers."],
    ['Ancient',"After a terrible battle with the Primalists, Malygos seals them in a magical sleep in the Forbidden Reach at Neltharion's request."],
    ['Dragonflight',"The Primalists' return wakes them, and they join both factions as evokers."]],
 fig:['deathwing','wrathion'],
 more:['Scalecommander Azurathel (Alliance)','Scalecommander Cindrethresh (Horde)'],
 kin:[['dragons','Made from the essence of dragons']],
 wiki:'Dracthyr'},
{id:'earthen',n:'Earthen',f:'both',tag:'Allied race \u00b7 2024',home:'Khaz Algar',cap:'Dornogal',
 s:"Titan-forged beings of living stone, made by the keepers to shape Azeroth's depths. Most earthen elsewhere became dwarves under the Curse of Flesh. Those of Khaz Algar endured, and they joined both factions during the war against Xal'atath.",
 h:[['Ancient',"The titans' keepers make the earthen to shape the world's deep places."],
    ['Ancient',"The Curse of Flesh turns most earthen into dwarves. Some remain stone."],
    ['The War Within',"The earthen of Khaz Algar face Xal'atath's invasion and join both factions."]],
 fig:['magni'],
 more:['The Machine Speakers'],
 kin:[['dwarves','Descendants']],
 wiki:'Earthen'},
{id:'haranir',n:'Haranir',f:'both',tag:'Allied race \u00b7 2026',home:'Harandar, where the roots of the World Trees meet',lead:'Five elders',
 s:"A reclusive people who guard the roots of the World Trees underground. Neither elves nor trolls, they have bat-like ears, small tusks and quills, and can turn into bats. In Midnight they came to the surface and joined both factions.",
 h:[['Ancient',"The haranir live near Mount Hyjal until a call from their goddess Aln'hara, whom the wiki identifies as Azeroth's world-soul, leads them underground to Harandar."],
    ['The War Within',"Heroes first meet them in Azj-Kahet, guarding the roots of the World Trees."],
    ['Midnight',"They visit the World Trees on the surface and join both factions as an allied race."],
    ['Midnight',"Elder Hagar reveals that trolls and elves descend from haranir who stayed on the surface."]],
 fig:['azeroth'],
 more:['Orweyna','Elder Hagar'],
 kin:[['trolls','Descendants, says Elder Hagar'],['nightelves','Descendants, says Elder Hagar']],
 wiki:'Haranir'}
);
