window.CHAR_BIOS = window.CHAR_BIOS || {};

window.CHAR_BIOS['xalatath'] = [
  ["A Child of the Void", [
    "Xal'atath says she began as a mortal child on a world the Void consumed. In a vision she later showed the ethereal Nexus-King Salhadaar, she stands among the ashes of her people in priestly robes while a Void portal opens in the sky. Her old body crumbles and the Void remakes her. Only her own account supports this story. Whatever her start, she became the Harbinger of the Void, the chosen herald of the voidlord Dimensius, who devours worlds. She says her long life taught her one lesson above all others, that survival comes first.",
    "As his herald she went ahead of Dimensius to K'aresh, home of the people who became the ethereals. She wanted to be free of him, and the Reshii Ribbons, K'areshi artifacts that turn any energy into arcane power, offered a way. She struck a bargain with the Ravel, a secret circle of K'areshi scholars. Her rituals and their ribbons would turn the K'areshi into beings of pure energy, and the planet's destruction would kill Dimensius. The Ravel acted too early. K'aresh was shattered, and Dimensius was only broken into fragments. The sources do not make clear how these events line up in time with her deeds on Azeroth."
  ]],
  ["Sealed in the Blade", [
    "Her gaze turned to Azeroth, where four Old Gods were reaching down toward a sleeping world-soul. She wanted the prize for herself. After N'Zoth finished building his city of Ny'alotha, she attacked him by surprise. N'Zoth called on C'Thun, Y'Shaarj and Yogg-Saron, and together they defeated her and sealed her inside the Blade of the Black Empire, a dagger their priests used for sacrifices. Y'Shaarj mocked her that she could only watch the world grow strong. She answered that the game had only begun.",
    "For ages the dagger passed from hand to hand and whispered to whoever held it. Around sixteen thousand years before the Dark Portal, it led an outcast troll witch doctor named Zan'do to wake Kith'ix, a buried general of the Old Gods, who raised the insect-like aqir against the trolls. About 230 years before the Dark Portal, the Dark Iron sorceress Modgud used it to bring the shadows of Grim Batol to life. The blade then abandoned her in battle, she died, and the city stayed cursed. Between the First and Second Wars it taught the human bishop Natalie Seline the shadow magic that priests still use. Some say it later turned her own followers against her, and they murdered her in her sleep."
  ]],
  ["Breaking Free", [
    "In Legion, the cult leader Twilight Deacon Farthing tried to use the dagger to raise a monstrous servant of the Old Gods in the Tomb of Tyr. Xal'atath turned on him and chose the shadow priest who came to stop him instead. She fought the Burning Legion in that priest's hands and dropped hints that N'Zoth was slowly breaking free. In the end her power was drained to pull corruption out of the Sword of Sargeras, and the dagger went dormant.",
    "In Battle for Azeroth the naga had the blade. A Horde priest fed it naga blood and souls and woke her again. In Drustvar she killed the high elf Inanis and took her corpse as a body. She then guided the priest to gather three relics for the naga and brought them to the Crucible of Storms, where she offered the relics and the priest to N'Zoth in exchange for her freedom. N'Zoth cut her free and kept the dagger. Azshara later gave that same blade to Wrathion, who used it to crack N'Zoth's outer shell in Ny'alotha. With the last living Old God dead, Xal'atath took the title Harbinger of the Void. The Primal Incarnate Iridikron gave her the Dark Heart, a relic that had absorbed the essence of the ancient dragon Galakrond, and claimed she would free Azeroth from the grasp of the titans."
  ]],
  ["The War Within", [
    "Disguised as the dead archmage Drenden, she joined the Kirin Tor's ruling council and talked it into teleporting Dalaran to Khaz Algar. Over the Isle of Dorn she drained the city's magic into the Dark Heart, pulled Khadgar into the relic and destroyed Dalaran. She had already made a bargain with the nerubian Ansurek, who stabbed her own mother to take the throne of Azj-Kahet and remade her people with the Black Blood of the dead Old Gods. When heroes brought Ansurek down, Xal'atath stood over the dying queen and told her she had promised nothing, yet given everything. At Hallowfall, Alleria Windrunner shot the Dark Heart instead of the Harbinger and cracked it, and Khadgar came free.",
    "The goblin Jastor Gallywix repaired the relic for her, then handed it to the Shadowguard, void-touched ethereals who wanted Dimensius back. She abandoned Gallywix and turned to her old ally Locus-Walker. On the ruins of K'aresh she fought beside him, Alleria and the heroes, and told Alleria that the Ravel had destroyed K'aresh themselves. In Manaforge Omega they forced the revived Dimensius into the Dark Heart. She seemed to trap herself inside with him. When Locus-Walker picked up the relic, she burst out, destroyed him and left with the voidlord's power. She promised Alleria that next time she would take everything Alleria loved."
  ]],
  ["The Devouring Host", [
    "With that power she united the Void's warring factions into the Devouring Host. She consumed the high lords of the domanaar, solitary Void predators, and the rest bowed to her. She showed Salhadaar her mortal past and offered his Shadowguard survival, and he knelt. The remnants of the Twilight's Hammer cult became her Twilight's Blade. In a realm called the Voidstorm she raised a citadel, the Voidspire.",
    "In Midnight she struck the Sunwell on the Isle of Quel'Danas. Lor'themar Theron defied her, Lady Liadrin's prayer brought the Vanguard of the Light, and a flare from the Sunwell drove her army back. She had Salhadaar turn the naaru T'era to the Void, then betrayed him. When the Vanguard stormed the Voidspire, she lured Alleria away and used the Blade of the Black Empire to tear the dark naaru L'ura out of her body. With L'ura's power she corrupted the Sunwell into the Darkwell. Alleria and her husband Turalyon were lost to the Void.",
    "The elves of every nation retook the island and destroyed L'ura. Xal'atath moved to kill Arator and Vereesa Windrunner, but Sylvanas Windrunner stepped from a portal out of the Maw and loosed an arrow at her. Xal'atath and her army escaped down the Darkwell's beam, deep beneath the surface. She is still at large, carrying a voidlord's power toward the heart of the world. The coming Eclipse update is set to follow her toward the Worldcore, where Azeroth's world-soul lies. Her goal has never changed. She wants the world-soul for herself. How much of her mortal story is true remains an open question."
  ]]
];

window.CHAR_BIOS['dimensius'] = [
  ["The Devouring War", [
    "Dimensius the All-Devouring is a voidlord, one of the monstrous beings of pure shadow who rule the Void outside reality. He came for K'aresh, a desert world under twin suns and home of the K'areshi. The surviving ethereals still argue over how he found it. He opened countless gateways into the Void around the planet and blotted out its suns, and the K'areshi named the struggle the Devouring War. His herald Xal'atath went ahead of him, though she secretly wanted to be free of him. Their bond was old. At the height of the Black Empire on Azeroth, he had given her an ancient staff called Voidsong. A Void creature named Pandemonius served among his commanders on K'aresh.",
    "The K'areshi raised barriers around their cities, powered by the Reshii Ribbons, artifacts that turn any energy into arcane power. The shields held back the Void, but long exposure to their arcane energy stripped away the K'areshi's bodies and turned them into beings of energy. Their new minds and magic held Dimensius to a standstill for years. Then he grew strong enough to summon armies of Void creatures, and many K'areshi fled."
  ]],
  ["The Shattering of K'aresh", [
    "Dimensius never finished his meal. The K'areshi Locus-Walker and the agent Nari saw that their world was lost either way. With Xal'atath, they chose to destroy it to kill him before he could devour its world-soul. The Ravel, a secret circle of K'areshi scholars, set off the destruction too early. The blast shattered Dimensius and scattered his fragments across the cosmos. Most ethereals came to believe he had destroyed their home, and the truth stayed hidden for ages.",
    "Nexus-King Salhadaar, leader of the ethereal Ethereum, swore to hunt Dimensius down. In secret he served the voidlord and used the hunt as cover to gather his fragments. His followers who fell to the Void became the Shadowguard. One fragment attacked a world called Karkora until the naaru T'uure spent its own life to drive him off, though Dimensius consumed a piece of it. Another appeared atop Manaforge Ultris in Outland's Netherstorm during The Burning Crusade, where heroes and the ethereal Protectorate stopped it. A tear in the Nether kept that fragment out of reach of physical harm, so the ethereal Professor Dabiri had heroes lock onto and destroy its conduit before the Protectorate's soldiers moved in."
  ]],
  ["Manaforge Omega", [
    "In The War Within, the Shadowguard took the Dark Heart, a powerful relic, and brought it to Manaforge Omega on the ruins of K'aresh to revive their master. The broker Ve'nari founded the K'aresh Trust to stop him, and Locus-Walker brought in Alleria Windrunner, Azeroth's heroes and his old acquaintance Xal'atath. Dimensius radiated enough power to annihilate any mortal who came near. Xal'atath's rituals and the Reshii Ribbons turned the heroes into beings of energy so they could reach him.",
    "When the heroes killed Forgeweaver Araz, Dimensius returned before he reached full strength. They held him off until Xal'atath joined the fight, and together they forced him into the Dark Heart. Xal'atath then broke out of the relic, destroyed Locus-Walker and left with the voidlord's power. Dimensius is now sealed inside the Dark Heart, which she holds, and his strength drives her war on Azeroth. Whether any part of him could return on its own is unknown. His defeat also gave K'aresh a chance. Its world-soul had survived his feast in a faint form, and Soul-Scribe, leader of the ethereal Wastelanders, gave her life to heal its last fragment."
  ]]
];

window.CHAR_BIOS['cthun'] = [
  ["The God of Ahn'Qiraj", [
    "C'Thun was one of the four Old Gods that struck Azeroth in its earliest age, sent by the void lords to corrupt the sleeping world-soul. With its fellow Old Gods it built the Black Empire, served by the faceless n'raqi and the insect-like aqir, and it enslaved the elemental spirits that had ruled the world before. It is remembered as the Old God of madness and chaos. When Xal'atath attacked N'Zoth, C'Thun sent help, noting that even Old Gods work together against such open betrayal.",
    "When the titans came, their titan-forged servants imprisoned C'Thun in the southwest of the world after they had dealt with N'Zoth. The keeper Ra and his giant anubisath servants later expanded the prison into the fortress of Ahn'Qiraj. C'Thun was rooted so deep that tearing it out could have destroyed the world-soul itself."
  ]],
  ["The Qiraji and the Scarab Wall", [
    "Around sixteen thousand years before the Dark Portal, the aqir fought a long war against the trolls. One group fled southwest, overran Ahn'Qiraj and enslaved its anubisath guardians. The trolls contained them there, and over millennia C'Thun's influence turned them into the qiraji, its fanatical servants.",
    "About a thousand years before the Dark Portal, night elves entered Ahn'Qiraj and woke the dormant qiraji. C'Thun stirred and drove them and their silithid swarms into a frenzy across Silithus. This was the War of the Shifting Sands. The night elf army under Fandral Staghelm was pushed back until the bronze dragon Anachronos brought in four dragonflights. Together they sealed the city behind the Scarab Wall, a magical barrier, and C'Thun's plans failed. The war cost Fandral his son Valstann, killed by the qiraji. Anachronos made two keys that could open the wall, the Scarab Gong and the Scepter of the Shifting Sands, and gave the scepter to Fandral, who shattered it in grief."
  ]],
  ["Death in the Temple", [
    "Centuries later, the ogre Cho'gall and his Twilight's Hammer cult came to Silithus. They could not pass the wall, so they performed a ritual that reached through it into C'Thun's prison and broke its bonds. The ritual killed most of the cultists, and the qiraji grew restless again. Cho'gall abandoned the survivors and, guided by C'Thun's whispers, set out to recruit new members and loosen the bonds of the other Old Gods. C'Thun had foreseen that dragons would come for it and prepared a spell to bind them to its will. It did not expect mortals.",
    "During the original World of Warcraft, the Alliance and Horde pooled their resources, reopened the Scarab Wall and held off the swarm while champions fought into the temple. They got past the qiraji Twin Emperors, who ruled the temple in C'Thun's name, and killed the Old God in its chamber. Its eye was brought to the red dragon Caelestrasz. Even dead, C'Thun was not silent. In the comics, the Twilight's Hammer used Ahn'Qiraj as a base, and when the young mage Med'an landed on the Old God's corpse, it whispered chaos into his ears. For years nobody was sure the Old God was truly gone. After N'Zoth fell, Magni Bronzebeard declared Azeroth free of the Old Gods, and Xal'atath later confirmed that C'Thun is dead."
  ]]
];

window.CHAR_BIOS['yogg'] = [
  ["The Prisoner of Ulduar", [
    "Yogg-Saron was one of the four Old Gods of the Black Empire. When Xal'atath attacked N'Zoth, Yogg-Saron sent help, judging that she had played her hand too early. After the titans' servants broke the Black Empire, they found the Old Gods rooted too deep to kill without harming the world. They sealed Yogg-Saron beneath Ulduar, a titan city in the north, and set six keepers to guard it, among them Loken, Thorim, Tyr and Freya.",
    "The prison never held completely. Yogg-Saron's black blood ran through the land and hardened into saronite, an ore that drives those around it to madness, and its whispers spread with it."
  ]],
  ["Whispers Among the Keepers", [
    "The whispers reached Loken. Yogg-Saron clouded his mind until he killed Sif, his brother Thorim's wife, and covered up the crime by blaming the frost giant king Arngrim. To hide his guilt Loken leaned on the Old God's power. He arranged the apparent death of Mimiron, made Hodir and Freya complacent and had Odyn, leader of the keepers, imprisoned. Tyr fled Ulduar with a few loyal followers and later died in the land now called Tirisfal Glades, fighting a servant of the Old Gods. Yogg-Saron also planted the Curse of Flesh in the Forge of Wills, the machine that made the titan-forged. The curse slowly turned stone and metal servants into mortal flesh and helped give rise to dwarves, gnomes and humans.",
    "Its reach went further. The ancient dragon Galakrond drank from waters tainted by Yogg-Saron. Later the night elves grew a World Tree, Andrassil, whose roots reached the prison. The druids cut the tree down once they saw the corruption, but Yogg-Saron had already opened a door into the Emerald Dream, and through it the Old Gods planted the seed of the Emerald Nightmare. Ages later the corrupted stump of the tree drove the furbolgs who settled there mad, and they used its dark power to raise the bear god Ursoc as a twisted reflection of himself."
  ]],
  ["The Fall of the Old God", [
    "Before the war against the Lich King, Cho'gall of the Twilight's Hammer slipped into Ulduar and weakened Yogg-Saron's chains. Its grip on the keepers turned strong as iron. Loken used the Forge of Wills to build armies of iron dwarves and captured Thorim so the Old God could break him. In Wrath of the Lich King, heroes freed Thorim, fought through the city with the explorer Brann Bronzebeard and reached Yogg-Saron's prison. There it showed them visions of the Dragon Soul's creation, the murder of King Llane and the Lich King tormenting Bolvar Fordragon, and it promised that no king rules forever. The heroes killed it.",
    "Its whispers still linger in parts of Northrend and Ulduar. In Legion, saronite vapors and faceless ones attacked Brann and Khadgar in Ulduar's antechamber while a voice whispered in their minds. Xal'atath later confirmed that Yogg-Saron is dead. The Scourge built Icecrown Citadel with saronite and spoke the Old God's name with hatred, but the full link between Yogg-Saron and the Lich King was never explained. Blizzard has admitted that the connection came across poorly in the game."
  ]]
];

window.CHAR_BIOS['nzoth'] = [
  ["The Corruptor", [
    "N'Zoth was one of the four Old Gods of the Black Empire. It ruled a vast territory in the east and waged endless war on C'Thun and Yogg-Saron. It once lost a great battle to Y'Shaarj where the Broken Shore now lies. After N'Zoth finished its city of Ny'alotha, Xal'atath attacked it, and the other Old Gods came to its aid and sealed her in a dagger. As she was sealed, she whispered an offer of power to N'Zoth.",
    "After Y'Shaarj died, N'Zoth was the first Old God the titan-forged defeated and imprisoned. Old lore placed its prison in the darkest depths of the ocean. Xal'atath and Azshara both thought it the weakest of the four, yet it did more harm than any of them. Prison did not stop it. Later sources name N'Zoth as the Old God that drove the Earth-Warder Neltharion mad and made him Deathwing. When the Well of Eternity imploded, N'Zoth spoke to the drowning Queen Azshara through a small red-eyed fish and offered to save her people in exchange for service. They became the naga. Through the door Yogg-Saron had opened into the Emerald Dream, N'Zoth helped spread the Emerald Nightmare, where the satyr Xavius served it."
  ]],
  ["The Hour of Twilight", [
    "After heroes killed C'Thun and Yogg-Saron, N'Zoth saw its chance closing. It fed its own dark power into Deathwing, who was healing in the elemental plane of Deepholm, and had the Twilight's Hammer cult bolt metal plates onto his body to hold it together. It called on the Elemental Lords, its ancient servants. Neptulon and Therazane refused. Ragnaros and Al'Akir agreed in return for the promise of freedom, so N'Zoth sent Azshara's naga against Neptulon. It let Deathwing believe he would rule the world, though it meant to discard him once the Black Empire returned. When Deathwing burst out and broke the world in the Cataclysm, N'Zoth struck on every front. It hoped one attack would succeed and bring the Hour of Twilight, the end of all life. Heroes stopped each one. At Wyrmrest Temple, N'Zoth sent its faceless ones into the final battle and poured more power into Deathwing than ever, yet the Aspects destroyed him with the Dragon Soul."
  ]],
  ["Release and Death", [
    "In Battle for Azeroth, N'Zoth's whispers spread among the tidesages of Kul Tiras. At the Crucible of Storms it freed Xal'atath from her dagger in return for three relics and kept the blade. Azshara then lured both factions to Nazjatar and used the power of the Heart of Azeroth to break N'Zoth's last chains. N'Zoth carried her off, raised Ny'alotha and sent its armies against Pandaria's Vale of Eternal Blossoms and the desert of Uldum. Its forces attacked the Chamber of Heart, where Magni tended the world-soul. The keeper Ra threw himself into the portal to Ny'alotha to save the chamber, and N'Zoth fed on his old despair and corrupted him.",
    "Magni sent heroes into Ny'alotha. Azshara, tortured for betraying N'Zoth, gave them the Xal'atath dagger, and Wrathion used it to crack the Old God's shell. The heroes then destroyed N'Zoth with the titan Forge of Origination, fired through the Heart of Azeroth. Before it died, N'Zoth revealed that Sylvanas had schemed with Azshara. Xal'atath later confirmed that N'Zoth is dead. It was the last living Old God on Azeroth."
  ]]
];

window.CHAR_BIOS['azeroth'] = [
  ["The Sleeping Titan", [
    "Azeroth is a world-soul, a titan still growing in the core of the planet that bears her name. The haranir, an ancient hidden people, call her Aln'hara. The Pantheon of titans believed that if she ever woke she would be the most powerful titan ever seen, stronger than Sargeras and able to overthrow the void lords by herself. Her growth drew in much of the element called Spirit, which is why Azeroth's elementals are so violent. Some say the Emerald Dream began as her dream. She rarely speaks. Magni Bronzebeard, her chosen Speaker, hears her as feelings and song, and she often seems like a frightened child troubled by nightmares."
  ]],
  ["Wounds", [
    "Azeroth has been hurt again and again. The Old Gods sank their tendrils toward her before the titans came, though they never reached her. When the titan Aman'Thul tore Y'Shaarj off the planet, the wound bled her arcane lifeblood, and the pool became the Well of Eternity. In Harandar lies the Rift of Aln, a wound that never healed. It formed when someone took the world-soul from her original cradle. Her screams still pour out of it as formless terrors, and the sources say she is now held captive against her will. Who moved her, and when, has not been revealed.",
    "Malygos's war on magic nearly did her lasting harm. At the end of the Legion war, Sargeras drove his sword into Silithus, and she began to bleed azerite. In Shadowlands the Jailer drew her lifeblood through the Forge of Souls and tried to pull her soul into his Sepulcher. Magni said her screams nearly split his head in two. Between those wounds she found ways to fight back. In Legion she showed Magni that Sargeras was coming and that her defenders' destiny lay on Argus. After the sword struck, she gave a champion the Heart of Azeroth, an amulet that gathered azerite to heal her. That wound has never fully closed."
  ]],
  ["Who Wants Her", [
    "The void lords made the Old Gods to twist her into a dark titan. Sargeras feared that outcome so much that he decided to burn all life, and his Legion tried to destroy her. The titans want her to wake. Their earthen servants built the Worldcore around her to shield her, leaving the titans as the only influence on her. The Jailer wanted her soul for his remaking of reality. The Primal Incarnate Iridikron claimed that Xal'atath would free Azeroth from the Pantheon's grasp. Xal'atath herself wants to claim the world-soul as her own."
  ]],
  ["The Worldsoul Saga", [
    "After the Shadowlands, Magni said Azeroth had begun a new song of hope. She blessed the Dragon Aspects and restored their powers. In The War Within, people everywhere heard a Radiant Song, and her vision of a burning city drew Dalaran to Khaz Algar, where Xal'atath destroyed it. She warned Vereesa Windrunner of the coming invasion, and in Midnight she answered Lady Liadrin's prayer, told her not to be afraid and summoned the Vanguard of the Light. Xal'atath escaped through the Darkwell toward the world's heart, and the Eclipse update is set to follow her to the Worldcore. The Last Titan, due in 2027, will bring the titans back to Ulduar and reveal a conspiracy about their intentions and Azeroth's true nature. Whether she wakes, and whose she becomes, is the open question of the saga."
  ]]
];

window.CHAR_BIOS['lura'] = [
  ["The Naaru Who Stayed Behind", [
    "L'ura was a naaru, a being of living Light. About thirteen thousand years ago, when Velen and the draenei fled Argus aboard the ship Genedar, she stayed behind to hold back the Burning Legion and was wounded. On Kil'jaeden's orders the eredar locked her in the Seat of the Triumvirate. Over millennia of captivity she fell from Light to Void, a rare dark stage in a naaru's life.",
    "During the Legion war on Argus, the Shadowguard, void-touched ethereals, came to claim her power. Alleria Windrunner, Locus-Walker and Azeroth's heroes defeated them, and Alleria drew L'ura's essence into herself. She became the first void elf. The fallen naaru inside her drew the interest of Xal'atath, who had watched Alleria since her first brush with the Void on Argus. For years afterward Alleria needed strict discipline to hold the raging naaru in check."
  ]],
  ["The Darkwell", [
    "In Midnight, Alleria let L'ura out of her body in the Voidstorm to destroy T'era, another dark naaru that Xal'atath wanted to control. At the Voidspire, Xal'atath lured Alleria away from her allies and wore down her mastery of the Void. Turalyon, their son Arator and the heroes helped Alleria regain control. Then Xal'atath stabbed Alleria in the back with the Blade of the Black Empire and tore L'ura out of her. With L'ura's power she corrupted the Sunwell into the Darkwell, a font of the Void. In the March on Quel'Danas, Arator, Vereesa Windrunner and the heroes defeated L'ura in the Darkwell. The elves then cleansed the font, and it became the Dawnwell. Xal'atath had already used the Darkwell as a road for her army deep into the world."
  ]]
];

window.CHAR_BIOS['yshaarj'] = [
  ["The Seven-Headed One", [
    "Y'Shaarj was the most powerful of the four Old Gods that struck Azeroth. It was known as the beast of seven heads, and the mantid said it inhaled courage and breathed fear. The greatest temple city of the Black Empire rose around its body. When Xal'atath attacked N'Zoth, Y'Shaarj sent help, knowing N'Zoth would owe it a debt. Afterward it mocked the sealed Xal'atath, saying she could only watch the world grow strong.",
    "When the titan-forged approached its city, Y'Shaarj twisted their thoughts and drew out their darkest feelings. The titans feared their servants would lose, so Aman'Thul reached down from the sky and tore the Old God off the planet. Its body was ripped apart, mountains shattered and hundreds of titan-forged died. The tear also wounded the world-soul, and the titans decided to imprison the other Old Gods. Y'Shaarj was the only one the titans killed.",
    "The keeper Ra found its heart still intact. Hoping that studying it would teach the titan-forged about the Old Gods and the Void, he sealed it in a vault beneath the Vale of Eternal Blossoms in Pandaria, guarded by his mogu. Aqir drawn to the remains became the mantid, who worshiped Y'Shaarj for ages. Its last breath gave rise to the seven sha, spirits of anger, hatred, violence, fear, doubt, despair and pride. In Mists of Pandaria, Garrosh Hellscream dug up the heart, restored it with the Vale's waters and carried it to Orgrimmar. When the Siege of Orgrimmar brought him down, the heart failed and faded away. Nothing remains of Y'Shaarj's power. The mantid Klaxxi, who told its story to outsiders, warned that if the Old Ones ever returned the mantid would stand beside them again."
  ]]
];

window.CHAR_BIOS['ghuun'] = [
  ["The Blood God", [
    "G'huun is an Old God that the titans made by accident. At Uldir, a research facility in Zandalar, they studied the imprisoned Old Gods and tried to understand their endless need to corrupt. The experiments created a perfect embodiment of that hunger. G'huun is rot, plague and decay, a parasite that cannot stop eating its host until nothing is left. It was weaker than the other Old Gods but could still end the world. The titans sealed it inside Uldir behind three great seals in Nazmir, Vol'dun and Zuldazar.",
    "From its prison G'huun reached for the trolls. It turned the troll priest Kel'vax Deathwalker into a lich with promises of eternal life. The blood trolls of the swamp of Nazmir, descended from trolls who kept practicing blood magic after a failed attempt to summon the blood god Hakkar unleashed a plague, came to worship it as their god and call themselves its children. The ancient creature Mythrax the Unraveler broke the seal in Vol'dun long ago, G'huun's minions damaged the one in Nazmir, and its corruption began spreading over the land. In Battle for Azeroth it also fought the death loa Bwonsamdi for the souls of the dead and corrupted Hir'eek, the loa of bats.",
    "The traitor prophet Zul and his allies worked to free G'huun so it could replace the loa as the trolls' god. Brann Bronzebeard and Princess Talanji led heroes of both factions into Uldir. In its Festering Core they used a titan device to weaken G'huun and drag it into the open, then killed it before it could break free."
  ]]
];

window.CHAR_BIOS['chogall'] = [
  ["The Twilight Prophet", [
    "Cho'gall was born in Highmaul, capital of the ogre empire on Draenor. A rare two-headed ogre, he was raised in privilege and trained in sorcery, but the rulers feared his popularity and tried to kill him. He fled and became the foremost apprentice of Gul'dan in the Shadow Council, which secretly ruled the Horde. Gul'dan sent him to the Pale, exiled orcs who worshiped the Void, and Cho'gall turned them into the Twilight's Hammer clan. He later took revenge on Highmaul and burned its emperor, Mar'gok, alive.",
    "On Azeroth the clan heard the whispers of the Old Gods, and Cho'gall became their true believer. He bound the Pale's prophecies into a book made of their own skin, the Twilight Canticle. He persuaded Ragnaros's servants to let the Horde use Blackrock Spire, survived Orgrim Doomhammer's purge of the Shadow Council and followed Gul'dan to the Tomb of Sargeras, where he barely survived Doomhammer's soldiers. He then led his cult to Kalimdor. When the half-orc assassin Garona hunted his followers, he trapped her and bent her mind to his will. In Silithus his ritual broke C'Thun's bonds. His cult also drew in powerful recruits, among them Archbishop Benedictus of the Church of the Holy Light. Before the war against the Lich King he slipped into Ulduar and weakened Yogg-Saron's chains. In the comics, the young mage Med'an buried him under the ruins of Ahn'Qiraj, but he survived.",
    "In the Cataclysm, Cho'gall served Deathwing and the Old Gods. His cult conquered the Twilight Highlands and built the Bastion of Twilight. Heroes stormed the fortress and killed him there. As he died, his head Cho seemed horrified at what they had done, while Gall reveled in it. Other leaders took over the cult after him."
  ]]
];

window.CHAR_BIOS['ragnaros'] = [
  ["The Firelord", [
    "Ragnaros was the lord of fire, one of the four Elemental Lords who fought each other on primordial Azeroth. Where he went, volcanoes erupted. When the Old Gods arrived, the Elemental Lords united against them for the first time, but they lost, and Ragnaros became a lieutenant of the Black Empire. When the titans came, the keepers Tyr and Odyn fought him for weeks and finally beat him. He was banished to the Firelands, his corner of the Elemental Plane, where he ruled from Sulfuron Keep. In a later war among the elementals he defeated Thunderaan, Prince of Air, and fed on his essence.",
    "About 230 years before the Dark Portal, the losing Dark Iron dwarf leader Thaurissan tried to summon help in the War of the Three Hammers. Ragnaros burst into the world, killed Thaurissan, shattered the mountains and raised the volcano of Blackrock Mountain. He ruled the Dark Irons from the Molten Core for more than two centuries. He also warred with the black dragon Nefarian, who held the upper mountain. Heroes recruited by the Hydraxian Waterlords, a group of water elementals, banished him back to the Firelands.",
    "In the Cataclysm he joined Deathwing at N'Zoth's command and attacked Mount Hyjal to burn the World Tree Nordrassil. Its defenders drove him back, and heroes followed him into the Firelands. There Cenarius, Malfurion Stormrage and Hamuul Runetotem bound him in hardened lava, and the heroes killed him. Among his defenders was Fandral Staghelm, the former archdruid, who had joined the flames in his grief. Because he died in his own realm, his death was final. The Dark Irons were freed, and a fire lord named Smolderon took his title. A cult of Dark Irons later tried to revive him and failed."
  ]]
];

window.CHAR_BIOS['ansurek'] = [
  ["The Queen Who Chose the Void", [
    "As a child, Ansurek watched her mother, Queen Neferess, refuse to let the nerubians serve the Old Gods again. Neferess gave her people freedom, but years of hardship and hunger left Ansurek wanting greatness instead. Xal'atath approached both mother and daughter, offering to make the nerubians powerful with the Black Blood of the dead Old Gods. Neferess refused. Ansurek accepted, stabbed her mother and took the throne of Azj-Kahet. She declared Neferess dead and blamed the human Arathi of Hallowfall, but she secretly had her mother transformed into a hulking monster. She also replaced her army's general with an officer loyal to Xal'atath.",
    "In The War Within, her armies invaded Dalaran after Xal'atath brought it to Khaz Algar and carried off many of its people. Ansurek turned more and more nerubians into Ascended with Black Blood, and she went to war with the Arathi. Alleria Windrunner's attempt on Xal'atath during one of the queen's speeches made her paranoid and harsh. Nerubians who opposed her formed a secret alliance, the Severed Threads, to restore Neferess's ideals. It was led by the weaver Widow Arak'nai, the spurned general Anub'azal and Executor Nizrek. Ansurek invented a holiday, Ascendance Day, to speed up the transformations, and her agents abducted citizens to be ascended.",
    "The Severed Threads and Azeroth's heroes stormed Nerub-ar Palace and brought her down. As Ansurek lay dying, Xal'atath appeared. The queen reminded her that she had promised to make the kingdom great. Xal'atath replied that she had promised nothing and yet given everything, and told her that the true lesson of the Void is that only the strongest survive. Her loyalists kept attacking Hallowfall after her death, but the Arathi drove them off."
  ]]
];

window.CHAR_BIOS['amanthul'] = [
  ["The Highfather", [
    "According to legend, Aman'Thul was the first titan to wake. Sure that others existed, he searched the cosmos, nurtured the sleeping world-souls he found and woke them, and together they became the Pantheon of Order with him as Highfather. He called on celestial beings, the constellar, to watch the worlds they ordered, and he set the constellar Algalon to watch Azeroth. He gave part of his power to the keepers Ra and Odyn, and he armed Ra with a weapon later called the Fist of Ra-den. When the titans saw Y'Shaarj resisting their servants, Aman'Thul reached down from the sky and tore the Old God apart. He later ordered rebel earthen, changed by the world-soul's power, to be hunted down. Through the keeper Ra he gave the dragon Nozdormu power over time. His vision of the Old Gods one day bringing the Hour of Twilight was one reason the titans made the Dragon Aspects.",
    "At the world of Nihilam, Aman'Thul begged Sargeras to stop and told him about Azeroth, a young world-soul who might one day stand against the void lords. Sargeras was unmoved and destroyed the Pantheon's bodies. Aman'Thul's spirit struck Ra, who drew it out and sealed a fragment in a mountain vault near the Vale of Eternal Blossoms. Ages later the mogu warlord Lei Shen absorbed its power. The Legion later captured Aman'Thul's spirit and tortured it on Argus. Heroes freed the Pantheon, and the titans helped defeat Argus the Unmaker and imprisoned Sargeras. In that battle Aman'Thul tried to unravel Argus with a blast of collapsing time. The Last Titan is set to bring the Pantheon back to Azeroth and question what the titans truly intend."
  ]]
];

window.CHAR_BIOS['aggramar'] = [
  ["The Avenger", [
    "Aggramar was a young titan with little experience of battle when the Pantheon sent him to help Sargeras hunt demons. He learned fast, became Sargeras's trusted lieutenant and fought beside him across the cosmos. After Sargeras left the Pantheon, Aggramar took up his role as champion. On his travels he heard the dreams of a powerful world-soul and found Azeroth already infested by the Old Gods. He urged the Pantheon to save her, and Eonar backed him. Because the titans were too large to fight on the planet safely, he proposed building servants to fight for them. He gave his courage and strength to the keeper Tyr and forged the titansteel used to make the keepers. On Draenor he created Grond, a living mountain, to tame the world's wild plant life. Pieces that broke off Grond became the colossals, and Aggramar left to investigate a dying constellar, promising to return. He never did.",
    "When Sargeras founded the Burning Legion, Aggramar confronted him, and they fought until both their blades shattered. Near the world of Nihilam he approached his old teacher unarmed and reminded him of the battles they had fought together. Sargeras cut him down, and the rest of the Pantheon died soon after. Sargeras later captured and corrupted Aggramar's weakened soul and placed it in an avatar body on Argus. He attacked the Army of the Light in Krokuun and watched demons torture his siblings' souls, promising Sargeras that Eonar would not escape. He served as the Legion's guardian of Antorus, the Burning Throne. Heroes defeated him, which freed him from Sargeras's grip. He rejoined the Pantheon, helped defeat Argus the Unmaker and helped imprison Sargeras."
  ]]
];

window.CHAR_BIOS['eonar'] = [
  ["The Life-Binder", [
    "Eonar is the titan of life and nature. When Sargeras argued that the only way to stop the Void was to burn away all life, Eonar reminded him that the Pantheon had sworn to protect life. When Aggramar found Azeroth, she quickly sided with him. She convinced the other titans that this world-soul could grow strong enough to defeat the void lords, and that Azeroth was their sibling and could not be abandoned. One legend says she first tried to plant a World Tree to drive back the darkness, and Aman'Thul tore it up because it did not serve order. She wept bitter tears but joined the war on the Old Gods.",
    "Eonar gave the keeper Freya command over Azeroth's plants and beasts. After the defeat of the dragon Galakrond she channeled her power through Freya into Alexstrasza and Ysera, making them the Aspects of life and of the Emerald Dream. Alexstrasza's red dragonflight took up Eonar's duty to protect all life. Sargeras destroyed her body with the rest of the Pantheon near Nihilam. Her spirit apparently hid from the Legion for millennia in a refuge called the Elarian Sanctuary. Sargeras wanted her gifts of life and growth to make his army unstoppable. When the Legion finally found the sanctuary, she called to Magni Bronzebeard for help, and heroes held off the demons in Antorus, the Burning Throne. She then joined her family against Argus the Unmaker, bringing the fallen heroes back to life with a great tree, and helped imprison Sargeras."
  ]]
];
