// Character biographies: the Old Horde and the Horde.
// Each entry is a list of [section heading, [paragraphs]].
window.CHAR_BIOS = window.CHAR_BIOS || {};

window.CHAR_BIOS['guldan'] = [
  ["An Outcast in Gorgrond", [
    "Gul'dan was born crippled and twisted in a small village in Gorgrond, a rugged region of Draenor. His clan mocked and beat him for years. When they finally tried to beat him to death, the village shaman stopped them. The old orc told Gul'dan he saw greatness in him and sent him to the Throne of the Elements, the holiest site of orc shamanism. Gul'dan slapped his hand away, and the chieftain banished him.",
    "After months of starving in the wilds, Gul'dan dragged himself to the Throne and offered himself to anything that would end his pain. The spirits of the elements sensed the hate in him and pulled away. Into that silence came the voice of Kil'jaeden, a demon lord of the Burning Legion, who offered him power in exchange for service. Gul'dan accepted. He went home, killed the chieftain with fel fire and burned the village. He thanked the shaman who had once been kind to him, then killed him too. He wanted no one alive who knew where he came from."
  ]],
  ["The False Apprentice", [
    "Kil'jaeden needed a respected leader to turn the orcs against the draenei, and Gul'dan could never be that leader himself. He went to the Shadowmoon clan with a story that ogres had destroyed his village. Its chieftain, the elder shaman Ner'zhul, took him in as an apprentice. Ner'zhul was grieving his dead mate and cut off from the spirits, and Gul'dan fed that grief while Kil'jaeden whispered to the old shaman in disguise.",
    "When Ner'zhul learned the truth and tried to back away, Gul'dan was ready. He had gathered a circle of warlocks he called the Shadow Council, and they seized Ner'zhul and left him a powerless figurehead. Gul'dan opened schools of demon magic to replace the shamans' lost bond with the elements. He arranged for the brutal Blackhand to be chosen Warchief, because Blackhand's pride made him easy to steer. He bound the mind of Garona, a half-orc outcast, and made her his spy and assassin. Then he offered the chieftains the blood of the pit lord Mannoroth. Grom Hellscream drank first, and almost every clan followed. The blood bound the Horde to the Legion, and the slaughter of the draenei that followed was Gul'dan's proof that the orcs were ready."
  ]],
  ["The Dark Portal", [
    "With the draenei broken and Draenor dying from fel magic, a hooded stranger came to the Shadow Council. He was Medivh, the Guardian of Azeroth, secretly possessed by Sargeras, the dark titan who leads the Legion. When Gul'dan attacked him, Medivh threw the spell back and forced him to kneel in front of his followers. Gul'dan never forgave that insult. Still, Medivh promised to reveal the Tomb of Sargeras, where Gul'dan believed he could become a god, if the Horde would conquer Azeroth.",
    "Gul'dan and Blackhand had the Horde build the Dark Portal. At the ritual that opened it, Gul'dan drained the life from almost every draenei prisoner the Horde still held. Through the First War he and his ogre apprentice Cho'gall steered the Horde from the shadows. When Azeroth's heroes stormed Medivh's tower, Gul'dan dove into the Guardian's mind to steal the location of the tomb. Medivh died while Gul'dan was still inside, and the shock left the warlock in a coma.",
    "While he lay helpless, everything he had built fell apart. Orgrim Doomhammer killed Blackhand in a duel, took the Horde, tortured the Shadow Council's hiding place out of Garona and slaughtered most of its warlocks."
  ]],
  ["A Traitor's Death", [
    "Gul'dan woke to find himself almost alone. He begged Orgrim for his life and bought it with a promise of new weapons for the war against the Alliance. He sacrificed his own necrolytes to make the first death knights, the corpses of human knights animated by the spirits of slain warlocks. He founded his own Stormreaver clan and twisted loyal ogres into ogre magi. Orgrim never trusted him and planned to kill him once the war was won.",
    "Gul'dan struck first. On the eve of the Horde's attack on Lordaeron's capital, he took the Stormreaver and Cho'gall's Twilight's Hammer clans and sailed off to find the tomb. Losing nearly half his army forced Orgrim to turn back, and the Alliance used that time to recover. Gul'dan raised the tomb from the sea floor, creating the island now called the Broken Shore, and went inside. Maddened demons trapped in the tomb tore him apart, and Orgrim's warriors killed the followers he had left outside. In his last moments Gul'dan understood that Sargeras had used him."
  ]],
  ["The Skull and the Second Gul'dan", [
    "Even dead he was dangerous. His skull became a focus of fel power that still held a piece of his mind. Ner'zhul used it to open his portals, it later corrupted the forests of Felwood in Kalimdor, and Illidan Stormrage absorbed its power and became half demon.",
    "In Warlords of Draenor a second Gul'dan appeared. He came from an alternate Draenor that Garrosh Hellscream reached by traveling into the past, where Grommash refused the demon blood and Gul'dan was taken prisoner. This Gul'dan escaped and later took over the Iron Horde by giving the blood to the chieftain Kilrogg Deadeye. He summoned Archimonde to Hellfire Citadel, and when heroes destroyed the demon, Archimonde's dying blast hurled Gul'dan into the Twisting Nether. Kil'jaeden sent him on to Azeroth with orders to open the Tomb of Sargeras. Inside, Gul'dan seized the power meant for the Legion's portal. Kil'jaeden told him that the Legion had let the first Gul'dan die because his betrayal split the Horde when it might have won. Khadgar and the warden Maiev kept attacking him though they could not win, and Gul'dan saw he would face that stubbornness forever on his own. He let the power go, and the Legion's third invasion of Azeroth began.",
    "This Gul'dan led the demon army at the Broken Shore, where he killed King Varian Wrynn of Stormwind. He stole Illidan's body from the Vault of the Wardens and tried to make it a vessel for Sargeras in the Nighthold, the palace of Suramar. Heroes defeated him there. Stripped of his borrowed power, he knelt alone, as he once had at the Throne of the Elements, until the freed Illidan seized him and burned him away. Illidan crushed the skull that was left. Both versions of Gul'dan made the same choice. Each sold his people for power, and each was thrown away by the masters he served."
  ]]
];

window.CHAR_BIOS['thrall'] = [
  ["A Slave Named Thrall", [
    "Thrall was born Go'el, son of Durotan and Draka, in Year 1. His parents' Frostwolf clan had been exiled by Gul'dan to the Alterac Mountains. Soon after his birth, his parents were murdered on the way home from a secret meeting with Orgrim Doomhammer, and the baby was left in the cold. A human officer, Aedelas Blackmoore, found him the next day. Blackmoore took him to his fortress, Durnholde Keep, and named him Thrall, a word for slave.",
    "Blackmoore wanted an orc with a warrior's strength and a human's education. Thrall learned to read, to study tactics and to fight, and became the star of Durnholde's gladiator ring. He was beaten often. His only friend was Taretha Foxton, the daughter of the woman who nursed him. She smuggled him letters hidden in books, and when he finally decided to escape, she created the distraction that let him slip out of the keep."
  ]],
  ["Freeing the Orcs", [
    "Outside, Thrall was caught and thrown into one of the internment camps where the orcs had been held since the Second War. Most of the prisoners were listless and broken. An old prisoner told him that Grom Hellscream of the Warsong clan was the one chieftain still fighting. Thrall escaped again and found Grom, who taught him the orc language and recognized the Frostwolf mark on his old swaddling cloth.",
    "Thrall went north into the mountains. The Frostwolves took him in, and their blind elder shaman, Drek'Thar, taught him the old ways. The elements accepted him. He became the first new orc shaman since Gul'dan's corruption, a sign that the spirits were ready to forgive his people. One night a gruff stranger at the Frostwolf fire mocked his plans until Thrall challenged him and won. The stranger was Orgrim Doomhammer, the old Warchief, who had come to test Durotan's son.",
    "Together they raided the camps. Thrall slipped inside as a prisoner and woke the inmates with his shaman powers. At the fifth camp a knight's lance killed Orgrim, who used his last breath to name Thrall Warchief and give him his black armor and the Doomhammer. Thrall then marched on Durnholde and offered Blackmoore a chance to surrender. Blackmoore answered by throwing down Taretha's severed head, because she had helped Thrall. Thrall wept for the first time in his life. He killed Blackmoore in the battle, let the surviving humans go, sent Taretha's necklace to her family and brought the keep down."
  ]],
  ["A Home in Kalimdor", [
    "Thrall spent the next years gathering the freed orcs. Then a mysterious prophet, later revealed as Medivh, came to him in visions and urged him to sail west to Kalimdor. The new Horde stole Alliance ships. Storm-wrecked on an island along the way, Thrall fought beside the Darkspear trolls, and their dying chieftain Sen'jin foresaw that Thrall would lead his tribe to greatness. The Darkspear joined the Horde. In Kalimdor, Thrall saved Cairne Bloodhoof's tauren from centaurs and escorted them to Mulgore, and the tauren became lifelong allies.",
    "The Prophet brought Thrall face to face with Jaina Proudmoore, a human sorceress, and told them to work together. Thrall agreed because Grom had drunk demon blood again. With Cairne and Jaina's help he captured Grom and had the taint purged, and Grom then killed the pit lord Mannoroth at the cost of his life, freeing every orc from the blood curse. At Mount Hyjal, Thrall stood with humans and night elves until the demon lord Archimonde was destroyed.",
    "Afterward Thrall founded Durotar, named for his father, with its capital Orgrimmar, named for Orgrim. He kept an uneasy peace with Jaina's city of Theramore, even after her father, Admiral Daelin Proudmoore, attacked the orcs and died in the fighting. When one of his own warriors turned out to serve a demon cult, Thrall killed him with the Doomhammer. On Cairne's advice he accepted Sylvanas Windrunner's Forsaken into the Horde, and later the blood elves, despite his doubts."
  ]],
  ["The Shaman Steps Down", [
    "After the Lich King fell, the elements began to rage, and Thrall could not be both warchief and shaman. Over Cairne's objections, he named Garrosh Hellscream, Grom's son, as acting warchief and went to Nagrand in Outland to understand the elements. There he met Aggra, a blunt Mag'har shaman who told him he had straddled two roles for too long. She became his mate. Thrall joined the Earthen Ring at the Maelstrom, the wound in the sea left by Deathwing's return, and was nearly lost when Fandral Staghelm scattered his spirit across the elemental planes. Aggra brought him back. The Dragon Aspects then chose Thrall to wield the Dragon Soul, and with it he destroyed Deathwing.",
    "Meanwhile Thrall's choice of successor went badly wrong. Garrosh killed Cairne in a duel in which a tauren rival had secretly poisoned his axe, destroyed Theramore with a mana bomb and tried to have Vol'jin murdered. Jaina blamed Thrall, and Thrall blamed himself. He joined the Darkspear rebellion, fought Garrosh beneath Orgrimmar and lost, and was stopped from executing him after the champions of both factions brought Garrosh down. Thrall then knelt and pledged his loyalty to Vol'jin as the new warchief. When Garrosh escaped his trial to an alternate Draenor, Thrall followed. He met that world's living Durotan and Draka, then killed Garrosh in a duel in Nagrand."
  ]],
  ["Back to the Horde", [
    "The years of war wore him down. During the Legion invasion he gave the Doomhammer and the leadership of the Earthen Ring to a younger shaman champion. He retired with Aggra and their children to a farm in Nagrand, where he forged an axe, Dra'gora, and hid it under his anvil. During the Fourth War, Varok Saurfang came and asked him to fight against Sylvanas, who had burned Teldrassil. Forsaken assassins attacked them both, and Thrall dug out the axe. He helped free Baine Bloodhoof from Sylvanas's prison and stood at Orgrimmar's gates when Saurfang died in his duel with her. When the Horde's leaders offered him the title of warchief again, he refused and proposed a council instead. He has spoken for the orcs on that council since.",
    "The Jailer's servants later dragged Thrall into the Maw, the prison of the Shadowlands. After his rescue he met the soul of his mother, Draka, now a leader of the necrolords of Maldraxxus. She knew him at once and told him to honor his past without being trapped by it. He helped defeat the Jailer and watched Sylvanas begin her sentence in the Maw.",
    "Since then he has helped bring back the orcish festival of Kosh'harg, worried over his son Durak's rite of passage and grown close to Geya'rah, the Mag'har leader and daughter of the alternate Durotan and Draka. When the void-touched Xal'atath destroyed Dalaran, Thrall and Jaina rallied Horde and Alliance forces together against her. Thrall is a healer who keeps being pulled back into war, and he owns his mistakes, above all choosing Garrosh."
  ]]
];

window.CHAR_BIOS['sylvanas'] = [
  ["Ranger-General of Silvermoon", [
    "Sylvanas Windrunner was the middle of three Windrunner sisters, between Alleria and Vereesa, and grew up at Windrunner Spire in the forests of Quel'Thalas. She followed her mother into the rangers and rose to Ranger-General of Silvermoon, commander of all high elven forces. She never wanted the post and gave everything to it anyway. She championed Nathanos Marris, a human ranger, against fierce objections from her fellow elves and even Prince Kael'thas, and made him the only human ranger lord. In the Second War she fought trolls and orcs in her homeland, and she quarreled bitterly with Alleria when her sister left to fight for the Alliance."
  ]],
  ["The Banshee", [
    "In the Third War, the death knight Arthas Menethil led the undead Scourge into Quel'Thalas. Sylvanas fought him at every gate and bridge on the road to Silvermoon, and she lost. As she lay dying from his runeblade Frostmourne, she asked for a clean death. Arthas refused. He tore her soul back into the world as a banshee, a wailing spirit bound to his will, and made her watch as he destroyed her people and the Sunwell, the source of their magic.",
    "When Arthas's hold on his servants weakened, Sylvanas broke free. She reclaimed her body, gathered other undead who had regained their minds, and ambushed Arthas with a paralyzing arrow, though he escaped. She named her followers the Forsaken, made the Undercity beneath Lordaeron's ruined capital their home and ruled them as the Banshee Queen. When she overheard her old comrades in Quel'Thalas mourning her, she left without showing herself."
  ]],
  ["Queen of the Forsaken", [
    "Needing allies, Sylvanas sent envoys to both factions. Her envoys to the Alliance never came back. The tauren persuaded Thrall to accept the Forsaken into the Horde, and she later helped bring the blood elves in as well. Her apothecaries spent years on a plague meant to destroy the Scourge. At the Wrathgate in Northrend, the apothecary Putress unleashed it on Alliance and Horde soldiers alike while the demon Varimathras seized the Undercity. Sylvanas retook her city beside Thrall and Vol'jin, but many never trusted her again.",
    "After Arthas died, she climbed Icecrown Citadel and threw herself from the top. Her soul fell into a dark void of terror and cold. Nine Val'kyr, winged spirits who had served the Lich King, brought her back and bound her life to theirs. Much later it came out that she had also met the Jailer, ruler of the Maw, and made a pact with him. Back in the world she used the Val'kyr to raise fallen enemies as new Forsaken. In the war for Gilneas, her poisoned arrow killed Prince Liam Greymane when he took a shot meant for his father."
  ]],
  ["Warchief", [
    "After the disaster at the Broken Shore, where she sounded the Horde's retreat, the dying Vol'jin named Sylvanas warchief. He believed the spirits had told him to, but the voice belonged to Mueh'zala, a servant of the Jailer. In the Fourth War she invaded the night elf lands of Kalimdor and ordered Teldrassil, the night elves' World Tree, burned with the city of Darnassus on its branches. At Lordaeron she released the Blight on a battlefield where her own soldiers still fought, then abandoned the city to the Alliance.",
    "She raised Jaina Proudmoore's dead brother Derek as a weapon and jailed Baine Bloodhoof for freeing him. Varok Saurfang turned against her and challenged her to a duel at Orgrimmar's gates. When he cut her and told her she could not kill hope, she killed him with a burst of strange power, declared the Horde nothing and left it, taking Nathanos with her. It later emerged that she had started the war to send as many souls as possible to the Maw, where they fed the Jailer's strength."
  ]],
  ["The Jailer's Ally", [
    "At Icecrown, Sylvanas took the Helm of Domination from the new Lich King, Bolvar Fordragon, and tore it in two. That broke open the way to the Shadowlands, the realm of the dead. Her forces dragged Thrall, Jaina, Baine and King Anduin Wrynn into the Maw. She bent Anduin into the Jailer's champion and led the Jailer's armies against Ardenweald, where Tyrande Whisperwind, empowered as the Night Warrior, nearly killed her.",
    "Sylvanas had believed the Jailer would break a system of death that gave no one a choice. When she saw that he meant to remake reality so that everyone would serve him, she turned on him. In answer he restored the piece of her soul that Frostmourne had torn away, and the shock left her unconscious, reliving her crimes. Uther the Lightbringer, whose soul had also been split by Frostmourne, helped her accept that the ranger she had been and the queen she became were the same person. She then helped the heroes free Anduin and defeat the Jailer. Afterward she submitted to Tyrande's judgment and was sentenced to search the Maw for every lost soul and send each one on to the afterlife."
  ]],
  ["Atonement in the Maw", [
    "Sylvanas has kept to that sentence. She sent word to her loyalists that her days of leadership were over and that the Desolate Council should lead the Forsaken. The soul of Nathanos, killed by Tyrande, also went to the Maw and can be found near her there. When her nephew Arator, son of Alleria, came to ask her back to Quel'Thalas, she refused. She told him her duty was in the Maw, and that she had grown suspicious of the Shadowlands and wanted to learn the truth about them.",
    "In Midnight, after Xal'atath corrupted the Sunwell, Sylvanas stepped out of the Maw through a portal to rescue Vereesa and Arator from her. She warned her family that leaving the Maw carried a toll, then went back to finish her sentence. All her life Sylvanas trusted her own judgment over anyone else's. That made her a fierce defender of her homeland, and later the author of some of Azeroth's worst atrocities."
  ]]
];

window.CHAR_BIOS['nerzhul'] = [
  ["The Deceived Shaman", [
    "Ner'zhul was chieftain and elder shaman of the Shadowmoon clan and the most respected spiritual leader on Draenor. When his mate Rulkan died and the spirits fell silent, he lost both of his comforts at once. The demon lord Kil'jaeden used that grief. He came to Ner'zhul in dreams wearing Rulkan's face and blamed the draenei for the orcs' troubles. Ner'zhul believed him and told the clans at their great Kosh'harg gathering that the draenei were their enemies.",
    "As the clans grew more savage, Ner'zhul began to doubt. He went secretly to the sacred mountain of Oshu'gun, where the true spirit of Rulkan told him he had been deceived. By then his apprentice Gul'dan was Kil'jaeden's servant. Gul'dan's Shadow Council seized Ner'zhul on his way home and left him a figurehead with no real power. In one quiet act of defiance, Ner'zhul slipped an unsigned warning into the council's own letters, telling Durotan of the Frostwolves about the coming demon blood. Durotan refused to drink because of it."
  ]],
  ["The Shattering of Draenor", [
    "Ner'zhul stayed on Draenor through the First and Second Wars, consumed by guilt. When the Alliance destroyed the Dark Portal after the Second War, he was badly hurt in the blast. The death knight Teron Gorefiend came to him with a plan to open new portals and lead the remaining orcs to fresh worlds. Ner'zhul, now haunted by visions of death and wearing a skull painted on his face, agreed. He reopened the Dark Portal with the Skull of Gul'dan, sent raiders to steal artifacts from Azeroth and handed the skull to Deathwing in exchange for black dragons. The skull's whispers made him care more and more about his own power.",
    "At the Black Temple, Ner'zhul opened his rifts and fled through one with his closest followers, leaving the rest of the Horde behind. The magic tore Draenor apart, and what remained became Outland."
  ]],
  ["The First Lich King", [
    "Kil'jaeden was waiting in the Twisting Nether. His dreadlords tortured Ner'zhul until his mind cracked and he agreed to serve. His body was destroyed, and his spirit was bound into a suit of armor and the runeblade Frostmourne and sealed in ice in Northrend. As the Lich King, he was ordered to spread a plague of undeath and soften Azeroth for the Legion. He obeyed while he had to and plotted revenge. He lured Prince Arthas Menethil to Frostmourne and made him his champion, and after the Legion's defeat at Mount Hyjal the Scourge broke free of Kil'jaeden.",
    "When Arthas put on the Helm of Domination, the two merged. Over the years Arthas's will crushed Ner'zhul's, using the old orc's guilt to drive him into despair until little of him remained. The last remnant of his soul ended up in the Maw, encased in spiked armor in the Jailer's Sanctum of Domination, where heroes destroyed it. Its final words called out to Rulkan. Ner'zhul meant to protect his people and became the tool that doomed them, and in the end he abandoned them to save himself. A separate, alternate Ner'zhul appears in Warlords of Draenor as one of the Iron Horde's warlords."
  ]]
];

window.CHAR_BIOS['orgrim'] = [
  ["Durotan's Friend", [
    "Orgrim of the Blackrock clan met Durotan of the Frostwolves as boys at the Kosh'harg festival. They sneaked out of the sleeping tents and spent the night competing, and the rivalry grew into a lifelong friendship, rare between orcs of different clans. Orgrim inherited the Doomhammer, his family's ancient warhammer, along with a prophecy that its last bearer would bring doom to his people. He rose to become Warchief Blackhand's second-in-command.",
    "Orgrim followed Blackhand into the war on the draenei, but he watched fel magic wither Draenor and grew suspicious of Gul'dan. When the chieftains drank Mannoroth's blood, he avoided it by claiming he was unworthy to drink from Blackhand's cup. In Year 1, Durotan met him in secret near Loch Modan and told him about Gul'dan's pact with demons. Orgrim sent guards to see the Frostwolves home. The guards were secretly loyal to the Shadow Council and murdered Durotan and Draka. Orgrim regretted that choice until he died."
  ]],
  ["Warchief of the Horde", [
    "Near the end of the First War, with Gul'dan in a coma, Orgrim challenged Blackhand to a duel to the death, calling him a traitor who had sold the orcs to dark powers. He crushed Blackhand's skull with the Doomhammer, banned fel magic and took Stormwind. He had Garona tortured to find the Shadow Council's hideout and slaughtered most of its warlocks. He spared Garona afterward and made the warrior Eitrigg her handler. He spared Gul'dan only because the warlock offered him death knights, and he planned to kill him once the war was won.",
    "In the Second War Orgrim proved a gifted general. He overran the dwarven lands of Khaz Modan but called off the bloody siege of Ironforge, judging the city not worth the lives. He let the Dragonmaw clan enslave the dragon queen Alexstrasza so the Horde could ride her children into battle. He paid the goblins as equals, won the Amani trolls by promising to help them against the elves, and kept his word to the human traitor Lord Perenolde of Alterac. Gul'dan's desertion at the gates of Lordaeron's capital cost him the war. At Blackrock Spire, Orgrim killed Anduin Lothar, the Alliance commander, but Lothar's lieutenant Turalyon rallied the army, broke the Horde and captured Orgrim."
  ]],
  ["The Last Campaign", [
    "Orgrim was kept as a curiosity in Lordaeron's capital until he escaped on his own. He saw the broken orcs in the camps and nearly fell into the same despair, then lived as a hermit in the wilds. When Drek'Thar sent word that Durotan's son was alive, Orgrim came to the Frostwolves in disguise and insulted Thrall until the young orc fought him and won. Then he revealed himself and made Thrall his second-in-command.",
    "Together they freed four camps. At the fifth, now the Horde town of Hammerfall in the Arathi Highlands, a knight's lance pierced him from behind. Dying, he named Thrall Warchief and gave him his black armor and the Doomhammer. Thrall named Orgrimmar after him. Orgrim was ruthless when he judged it necessary, but he wanted his people to have their honor back. His spirit appeared at the first Kosh'harg held on Azeroth, proud of how far the orcs had come."
  ]]
];

window.CHAR_BIOS['grom'] = [
  ["The Warsong Chieftain", [
    "Grommash Hellscream became chieftain of the Warsong clan young, and some whispered about how the old chieftain had died. After an ogre counterattack nearly wiped out his clan, his mate Golka lay dying and begged him to end her pain. Grom could not bring himself to do it, called her weak and walked away, and the moment haunted him for years. Captured and tied to a tree by an ogre warlord, he refused to break and finally bit the ogre to death. His son Garrosh caught red pox and was sent away to Nagrand, and Grom never saw him again.",
    "When Ner'zhul called for war on the draenei, Grom answered first. When Gul'dan offered Mannoroth's blood, Grom drank first, and nearly every clan followed. He helped sack the draenei city of Shattrath. Gul'dan kept the Warsong on Draenor during the First and Second Wars, so Grom never faced the Alliance in those wars."
  ]],
  ["Years in Hiding", [
    "After the Second War, Grom fought for Ner'zhul and held the Dark Portal on the Azeroth side. When it was destroyed, he and the Warsong were stranded in Lordaeron, where they hid in the forests for nearly fifteen years. The demon blood left most orcs listless, but Grom fought that weakness with sheer will. When the runaway Thrall found him, Grom was impressed by his courage and mercy. He taught Thrall the orc language, gave him his own necklace as a sign of trust and pointed him toward the Frostwolves. The Warsong then joined Thrall and Orgrim in freeing the camps."
  ]],
  ["Fall and Redemption", [
    "At the start of the Third War, humans captured Grom, and Thrall rescued him. It was Grom who suggested stealing Alliance ships to sail west. He reached Kalimdor apart from the rest of Thrall's Horde. He kept attacking Jaina Proudmoore's humans against Thrall's orders, so Thrall sent the Warsong to cut timber in Ashenvale. The night elves and their demigod Cenarius struck back. Desperate, Grom found a fountain of Mannoroth's blood and drank, and his warriors drank with him. They killed Cenarius, and Mannoroth took control of them.",
    "Thrall, Cairne and Jaina captured Grom and had the taint purged. Grom confessed that the chieftains had chosen the blood knowing it would enslave them. Freed, he went with Thrall to hunt Mannoroth. When the pit lord knocked Thrall aside, Grom drove his axe Gorehowl into Mannoroth's chest. The demon's death blast killed him, and the blood curse lifted from every orc. Thrall called him brother and raised a monument at Demon Fall Canyon, and Grommash Hold in Orgrimmar bears his name. His spirit later appeared at the first Kosh'harg on Azeroth, regretting only that he had not lived to guide Garrosh."
  ]],
  ["Another Grommash", [
    "Warlords of Draenor shows a different Grommash on an alternate Draenor. Warned by Garrosh, who had traveled there from the future, he refused the blood, killed Mannoroth and survived. He founded the Iron Horde and tried to conquer Draenor and Azeroth. After Gul'dan seized his army, he fought beside the heroes against Archimonde and helped rebuild his world. Years later, as warchief of the Mag'har, he died holding off the zealous Lightbound draenei so his people could escape to Azeroth."
  ]]
];

window.CHAR_BIOS['garrosh'] = [
  ["Son of Hellscream", [
    "Garrosh, son of Grom and Golka, caught red pox as a child on Draenor and was sent to Garadar in Nagrand. That kept him away from the demon blood. He grew up among the uncorrupted Mag'har, ashamed of his father and afraid he would repeat Grom's mistakes. When Thrall came to Nagrand and showed him how Grom had died killing Mannoroth, Garrosh's shame turned to pride. Thrall saw promise in him and brought him to Azeroth as an adviser.",
    "Garrosh scorned Thrall's peace with the Alliance and once challenged him to a duel in Orgrimmar. In Dalaran he came to blows with King Varian Wrynn of Stormwind. In Northrend he led the Horde's Warsong Offensive, and his aggressive tactics worked but alarmed veterans like Varok Saurfang. When Thrall stepped down to study the elements, he made Garrosh warchief."
  ]],
  ["Warchief Hellscream", [
    "Garrosh rebuilt Orgrimmar as a fortress, moved most non-orcs out of its center and pushed hard into Ashenvale for timber. Cairne Bloodhoof challenged him to a duel for leadership of the Horde, and Garrosh won only because Magatha Grimtotem had secretly poisoned his axe. He had not known about the poison, and he refused to back Magatha when she seized Thunder Bluff. Still, he drifted away from the Horde's other leaders and let a Blackrock enforcer, Malkorok, silence dissent.",
    "He set out to drive the Alliance from Kalimdor. His forces took Northwatch Hold, and then a mana bomb dropped on his orders destroyed Jaina Proudmoore's city of Theramore and killed the archmage Rhonin. In Pandaria he admired the cruel mogu and used a relic called the Divine Bell to fill his elite Kor'kron guards with the dark power of the sha, until Anduin Wrynn destroyed it. He sent an assassin after Vol'jin when the troll would not stop criticizing him. Vol'jin survived and started a rebellion, and Garrosh answered by putting the Darkspear lands under martial law."
  ]],
  ["The Siege of Orgrimmar", [
    "Garrosh then found the heart of the Old God Y'Shaarj beneath the Vale of Eternal Blossoms, the sacred heart of Pandaria. He woke it, ruining the valley, and moved it under Orgrimmar to build what he called a True Horde. Rebels and Alliance forces stormed the city together. Garrosh beat Thrall in single combat, but the champions of both factions brought him down. At his trial in Pandaria he mocked the court, spoke openly only to Anduin and showed no regret. The bronze dragon Kairoz broke him out and took him to an alternate Draenor in the past."
  ]],
  ["The Iron Horde and His Death", [
    "There Garrosh persuaded his father's younger self not to drink the demon blood and helped him kill Mannoroth. With knowledge of future technology he helped build the Iron Horde, which invaded Azeroth through a new Dark Portal. Thrall tracked him to Nagrand and killed him in a duel. Garrosh blamed Thrall for making him warchief and then abandoning him, and Thrall answered that Garrosh had chosen his own path.",
    "In the Shadowlands his soul was sent to Revendreth to atone, and was later dragged into the Maw, where a soulrender drained its strength in the Sanctum of Domination. Garrosh refused to break, swearing he would make every choice again and submit to no one. What became of his soul after that has not been told. Garrosh was brave and proud of his people, and he could never accept being wrong."
  ]]
];

window.CHAR_BIOS['cairne'] = [
  ["Chieftain of the Bloodhoof", [
    "Cairne Bloodhoof led the Bloodhoof tribe of tauren in the Barrens, where he grew up beside his lifelong friend, the druid Hamuul Runetotem. He was a great warrior grown old, and his wife Tamaala had died before the Third War, leaving him with their son, Baine. Centaur raids had driven off the game and threatened to wipe out his people. When Thrall's newly arrived orcs defended a tauren village from centaurs, Cairne saw something noble in them.",
    "Thrall escorted Cairne's people across the Barrens to the grasslands of Mulgore, and in return Cairne told him of the Oracle on Stonetalon Peak. Then he followed Thrall to the mountain to repay the debt, helped free the wyverns from the harpies and stood with Thrall and Jaina Proudmoore when the Oracle revealed itself. Cairne helped capture Grom Hellscream so the demon taint could be purged and pledged the tauren to the Horde for the battle against the Legion at Mount Hyjal."
  ]],
  ["High Chieftain", [
    "After the war Cairne united the tauren tribes and built their first city, Thunder Bluff, atop the mesas of Mulgore. When centaurs kidnapped Baine, Cairne sank into a grief so deep he could not lead. The beastmaster Rexxar rescued Baine, and a joyful Cairne marched to help Thrall against Admiral Daelin Proudmoore. He later urged Thrall to give the Forsaken a place in the Horde. The scattered tribes came to agree that he was the wisest of them. The exception was Magatha Grimtotem, an ambitious elder who believed she should lead the tauren. Cairne let her live in Thunder Bluff anyway, reasoning that it was wise to keep enemies close."
  ]],
  ["The Last Duel", [
    "Cairne visited Garrosh Hellscream in Northrend and came away impressed by his skill as a commander. But when Thrall named Garrosh acting warchief, Cairne objected, and the two old friends parted in anger. Soon after, Cairne heard that Garrosh had sanctioned the killing of innocent druids. He challenged Garrosh to a mak'gora, a ritual duel for leadership of the Horde, and agreed when Garrosh insisted it be fought to the death. Each fighter could carry one weapon and no armor. Cairne took the sacred Bloodhoof Runespear, and Garrosh took his father's axe, Gorehowl. Magatha blessed the axe before the fight and secretly poisoned it. Cairne was winning until a glancing cut left him too weak to raise his broken spear. His last thought was that he had lived with honor and would die betrayed.",
    "Magatha used his death to seize Thunder Bluff, but Baine took it back. Thrall came back from Outland to mourn him, regretting that they had parted on bad terms. He called the tauren the heart of the Horde and kept a shard of Cairne's spear, marked with the rune for healing. Cairne was a gentle soul who would have preferred the open plains to the duties of a chief. His spirit has appeared to Baine since, once to counsel him before Garrosh's trial and again during the Fourth War, to remind him that the tauren way is harmony and that his parents watch over him."
  ]]
];

window.CHAR_BIOS['voljin'] = [
  ["Son of Sen'jin", [
    "Vol'jin was the son of Sen'jin, chieftain of the Darkspear trolls, who lived in exile on islands in the Great Sea. He grew up with his best friend, Zalazane. As young trolls he and Zalazane were tested by the loa, the troll gods, and both became shadow hunters. In their visions they saw that one day they would fight each other to the death. While he was away, humans and murlocs nearly wiped out his tribe. Thrall's passing Horde saved the survivors, but Sen'jin died, after foreseeing that Thrall would lead the Darkspear to greatness.",
    "A year later Vol'jin led his people to Durotar and settled them on the Echo Isles. When Admiral Daelin Proudmoore's fleet attacked, he used his voodoo to turn the beastmaster Rexxar and his companions into spirit wyverns to strike the ships. He became one of Thrall's closest advisers and helped retake the Undercity from the demon Varimathras. He later freed the Echo Isles from Zalazane, who had gone mad with power and enslaved the trolls there."
  ]],
  ["Against Garrosh", [
    "Vol'jin distrusted Garrosh from the start. He openly threatened the new warchief and moved most of his people out of Orgrimmar. When the Zandalari called on every troll tribe to build a new empire, Vol'jin refused, saying the Horde was his people, and helped stop them. In Pandaria, Garrosh sent an assassin to kill him. Poisoned and near death, Vol'jin was found by the pandaren brewmaster Chen Stormstout and healed at the Shado-Pan Monastery, where he trained with the monks and formed an unlikely friendship with a human hunter, Tyrathan Khort.",
    "He came home to lead the Darkspear Rebellion, won over Baine and the blood elf regent Lor'themar Theron, accepted help from the Alliance and led the siege that brought Garrosh down."
  ]],
  ["Warchief", [
    "In the ruins of Garrosh's sanctum, Thrall knelt to him, and Vol'jin became the first warchief who was not an orc. He did not feel worthy but swore to give everything. King Varian Wrynn accepted him and offered peace, warning that it would last only as long as the Horde kept its honor. He led the Horde through the war on the alternate Draenor and into the Legion invasion. At the Broken Shore a felguard's spear struck him. He broke the spear and killed the demon, but its fel poison was fatal. Back in Orgrimmar, dying, he told the Horde's leaders that he had never trusted Sylvanas, then named her warchief anyway because he believed the loa had told him to."
  ]],
  ["Beyond Death", [
    "Vol'jin's spirit never reached Bwonsamdi, the loa of death. Some other power had taken it and made it stronger. During the Fourth War his spirit guided Princess Talanji against the Blood God G'huun and helped Baine look for the truth about Sylvanas's appointment. In the Shadowlands he learned that the voice had belonged to Mueh'zala, a former loa of death allied with the Jailer. Vol'jin entered the Maw to rescue lost spirits and took in the essence of the dying loa Rezan. The Winter Queen of Ardenweald then placed him in a seed to be reborn. Whether that rebirth has finished has not yet been revealed. Vol'jin put his people's safety ahead of his own wishes, and he never stopped valuing freedom."
  ]]
];

window.CHAR_BIOS['saurfang'] = [
  ["A Blackrock Veteran", [
    "Varok Saurfang was born on Draenor into the Blackrock clan, the younger brother of the warrior Broxigar. He chose to drink Mannoroth's blood and helped sack the draenei city of Shattrath, where the Horde killed children along with everyone else. Those screams haunted him for the rest of his life, and he refused to eat pork because the squeal of slaughtered pigs brought them back. He hid his young son Dranosh in Garadar in Nagrand, keeping a promise to his mate Remda that the boy would never cross the Dark Portal. Orgrim Doomhammer made him his second-in-command, and Saurfang fought through both wars until the Horde's defeat.",
    "After Mannoroth's death freed the orcs, Saurfang helped other veterans live with what they had done. He became one of Thrall's most trusted warriors and commanded the joint Horde and Alliance army against the qiraji of Ahn'Qiraj. His brother Broxigar, sent by Thrall to investigate a strange anomaly, was pulled ten thousand years into the past and died a hero in the War of the Ancients."
  ]],
  ["Grief and Duty", [
    "Dranosh, now grown, joined his father on Azeroth and led the Horde vanguard at the Wrathgate in Northrend, where the Lich King killed him and raised him as a death knight. Saurfang faced his son's risen body inside Icecrown Citadel, then carried it home to Nagrand to burn it beside his family. In Northrend he also kept watch on Garrosh Hellscream's recklessness and swore to kill him if he led the orcs down a dark road. Years later he joined Thrall in the Siege of Orgrimmar. After Vol'jin's death he led the orcs from Grommash Hold."
  ]],
  ["Against Sylvanas", [
    "Sylvanas made him her war leader. When she asked him to plan the conquest of Stormwind, he told her it could not be done, and she steered him toward Kalimdor instead. He planned to take Teldrassil and hold it as a hostage, and was horrified when she burned it instead. At Lordaeron he walked out alone to meet the Alliance army and die, until the young troll Zekhan talked him back. In the battle he knocked down King Anduin Wrynn and spared him. Captured, he told Anduin he wanted his Horde back, and Anduin left his cell door open.",
    "Saurfang escaped, survived Sylvanas's assassins and went to Nagrand to pull Thrall out of retirement. Together they freed Baine, rallied Horde rebels and joined forces with Anduin to remove Sylvanas."
  ]],
  ["The Last Duel", [
    "At Orgrimmar's gates, unwilling to see more Horde blood spilled, Saurfang challenged Sylvanas to a mak'gora. He fought with Thrall's axe and Anduin's sword. He cut her across the eye and told her she could not kill hope. In a rage she killed him with a burst of strange magic, declared the Horde nothing and abandoned it. His death ended her rule without a battle, and the Horde reunited. Thrall and Anduin spoke at his funeral, and he was buried in Nagrand. What happened to his soul has not been told directly. The death loa Bwonsamdi showed Zekhan a vision of Saurfang at peace with his family, but that vision was a lie."
  ]]
];

window.CHAR_BIOS['blackhand'] = [
  ["Gul'dan's Warchief", [
    "Blackhand was chieftain of the Blackrock clan on Draenor, a brilliant tactician who ruled his warriors through fear. He was also vain and hungry for power, which made him easy for Gul'dan to steer. Gul'dan arranged for the clans to choose him as the first Warchief of the Horde and let him believe he was an equal on the Shadow Council. He was a puppet. Blackhand eagerly turned his clan's shamans into warlocks and had his own children magically aged so they could fight sooner. With his own hands he forged Anguish and Sorrow, the cursed daggers Gul'dan gave to his assassin Garona.",
    "Blackhand led the war on the draenei and, after the Dark Portal opened, the First War against Stormwind. His raiders burned villages across the kingdom. When the human commander Anduin Lothar nearly killed him in an ambush in the Redridge Mountains, he blamed the two warlocks who had saved him and executed them. Near the end of the war Gul'dan fell into a coma, and Blackhand lost his protector. His second-in-command, Orgrim Doomhammer, challenged him to a mak'gora and called him a traitor who had sold the orcs to dark powers. After hours of fighting, Orgrim crushed his skull with the Doomhammer.",
    "His sons Rend and Maim later led a Dark Horde of Blackrock orcs who rejected Thrall's Horde, and years later Varok Saurfang called Sylvanas the true heir to Blackhand's bloody legacy. An alternate Blackhand with a hand of stone appears in Warlords of Draenor as the Iron Horde's master of Blackrock Foundry, where heroes killed him. Older stories gave the original Blackhand that stone hand too, but World of Warcraft: Chronicle replaced it with a black tattoo."
  ]]
];

window.CHAR_BIOS['durotan'] = [
  ["The Frostwolf Chieftain", [
    "Durotan was the son of Garad, chieftain of the Frostwolf clan in the cold north of Draenor. As a boy at the Kosh'harg festival he met Orgrim of the Blackrock clan, and they became lifelong friends. He became chieftain when his father died of red pox, and he took as his mate Draka, a once-sickly girl who had made herself a strong warrior.",
    "When Ner'zhul called the orcs to war against the draenei, Durotan obeyed but doubted. He let the draenei prophet Velen go free, saying there was no honor in taking a willing prisoner. Yet he also opened the way into the hidden draenei town of Telmor, which he remembered from a boyhood visit, and his clan helped destroy it. A secret letter from Ner'zhul warned him about the demon blood, and he refused to drink it. He kept questioning Gul'dan openly, so Gul'dan banished the Frostwolves after the Horde reached Azeroth. They settled in the Alterac Mountains, where Draka gave birth to their son, Go'el."
  ]],
  ["Murder in the North", [
    "The baby's green skin, a mark of the fel magic spreading among the orcs, convinced Durotan he could not stay silent. In Year 1 he met Orgrim near Loch Modan and told him everything he knew about Gul'dan. Orgrim sent guards to see the family home, but they were loyal to the Shadow Council. Several days later they attacked. Durotan and Draka killed one before they were cut down, and the baby was left in the cold. A human officer found the child and named him Thrall.",
    "Durotan is buried under the Rock of Durotan in Alterac Valley, and Thrall named his nation, Durotar, after him. His soul's place in the Shadowlands has not been shown, but at the first Kosh'harg held on Azeroth his spirit appeared beside Draka's, honored to see the land that bears his name."
  ]]
];

window.CHAR_BIOS['draka'] = [
  ["A Frostwolf Warrior", [
    "Draka was born weak and sickly into the Frostwolf clan, and her family was pushed to the edge of the village. Blackhand said that in his clan she would have been drowned. As a teenager she set out alone on a dangerous hunt that the clan's elder had given her, and she came home strong. She learned the hunt itself had been the cure. Durotan noticed her at the Kosh'harg festival, and after a hunt together they became mates.",
    "Draka stood by Durotan through the war on the draenei and the Frostwolves' exile to the Alterac Mountains. In Year 1 she gave birth to Go'el, the son later called Thrall. She went with Durotan to warn Orgrim Doomhammer about Gul'dan, and on the way home guards loyal to the Shadow Council murdered them both."
  ]],
  ["A Leader in Maldraxxus", [
    "Her soul went to Maldraxxus, the Shadowlands realm where the necrolords train armies for the afterlife. She became a spy and a baroness of the House of Eyes, then joined the House of the Chosen when civil war tore the realm apart. She held the loyal forces together, and the Primus, the realm's ruler, named her Margrave of the Chosen. She led Maldraxxus against the Jailer.",
    "Draka met Thrall in the Maw and knew him at once by his father's eyes, but she waited until their mission was done to call him Go'el. She told him to remember his past and take pride in who he was now. When he blamed himself for Garrosh, she told him Garrosh had chosen his own path. She has since been reunited with Durotan, and their spirits appeared together at the first Kosh'harg on Azeroth."
  ]]
];

window.CHAR_BIOS['garona'] = [
  ["Gul'dan's Blade", [
    "Garona Halforcen was born on Draenor to an orc warrior of the Bladewind clan and Leran, a draenei captive. Half-breeds were despised, and she survived by fighting and by learning languages. Gul'dan took her in, bound her mind to his will, magically aged her and trained her as his spy and assassin. He told her she was half human, a lie that made her more useful among humans.",
    "On Azeroth she became Gul'dan's envoy to Medivh, who befriended her, and she grew close to his apprentice Khadgar. She helped expose Medivh as the one who had opened the Dark Portal and joined the attack on his tower. There she saw a vision of herself killing King Llane Wrynn, one of the few people who had treated her kindly. Gul'dan's buried commands made it happen. Weeping, she cut out Llane's heart while his son Varian watched. She was carrying Medivh's child at the time."
  ]],
  ["Breaking Free", [
    "Orgrim captured and tortured her, then spared her. After the war she left her son, Med'an, with the mage Meryl Winterstorm, hid her daggers and spent years, with Khadgar's help, breaking Gul'dan's hold on her mind. Cho'gall, the last who knew the controlling spell, later forced her to try to kill Varian at a peace summit. She failed, learned her true heritage from her draenei uncle Maraad and helped Med'an defeat Cho'gall. She has since worked with the Horde and the Uncrowned, a secret order of rogues, and was pressed into Sylvanas's service in the Fourth War while privately faking loyalty. She came out of seclusion for the orcs' first Kosh'harg on Azeroth and, for the first time, considered joining a clan."
  ]]
];

window.CHAR_BIOS['aggra'] = [
  ["The Mag'har Shaman", [
    "Aggra is a Mag'har shaman from Garadar in Nagrand, raised among the orcs of Outland who never drank demon blood. When Thrall came to Nagrand before the Cataclysm to understand the troubled elements, his grandmother Geyah sent him to her. Aggra told him bluntly that he had tried for too long to be both warchief and shaman. She guided his vision quest, and despite their rough start they fell in love.",
    "Aggra came to Azeroth with Thrall. When Alliance agents captured him at sea on the way to the Maelstrom, she led the shipwrecked crew and their new goblin allies to free him. Then she joined the Earthen Ring at the Maelstrom. When Fandral Staghelm scattered Thrall's spirit across the elemental planes, the Dragon Aspects feared he was lost for good. Aggra refused to give up and sent heroes to recover every piece of him. After his rescue they married, and at Deathwing's defeat Alexstrasza revealed that Aggra was pregnant. Their son is Durak, and they later had a daughter, Amarehz."
  ]],
  ["Farseer", [
    "Aggra cared for their children while Thrall fought on the alternate Draenor, joined him there for a time, and later shared the family's quiet years on a farm in Nagrand. When the Jailer's servants seized Thrall, she stayed to protect the children and urged the Horde's champions to bring him home. During the revival of the Kosh'harg festival she created the om'gora, a new orcish rite of honor, and Drek'Thar named her a Farseer. When tensions flared between the Mag'har and the humans of Stromgarde, she went to calm Overlord Geya'rah. Aggra is frank and fierce, and she keeps Thrall honest."
  ]]
];

window.CHAR_BIOS['baine'] = [
  ["Son of Cairne", [
    "Baine is the son of Cairne Bloodhoof and Tamaala. As a young tauren he was kidnapped by centaurs in Mulgore, which sent his father into despair until the beastmaster Rexxar rescued him. He grew into a capable leader and often ruled Thunder Bluff when Cairne was away.",
    "When Garrosh killed Cairne in a duel rigged with Magatha Grimtotem's poison, her tribe seized Thunder Bluff and tried to kill Baine. He escaped, retook the city with allies including the goblin Gazlowe, and exiled Magatha instead of executing her. For the sake of Horde unity he chose not to seek revenge on Garrosh. Later he joined Vol'jin's rebellion, and at Vol'jin's request he defended Garrosh at his trial."
  ]],
  ["A Voice for Moderation", [
    "Baine became a close friend of Anduin Wrynn and a steady voice for peace. When Sylvanas ordered him to cut off contact with Anduin, he wrote one last letter and sent along a piece of his horn as a keepsake. In the Fourth War he was appalled when Sylvanas raised Jaina Proudmoore's brother Derek as one of the Forsaken. He freed Derek and brought him to Jaina, saying no life was worth living if he could not be true to his nature. Sylvanas jailed him and planned his execution, but Thrall, Saurfang, Jaina and Mathias Shaw broke him out, and he backed Saurfang's revolt. After the war he joined the Horde Council. The Jailer's servants dragged him into the Maw, where the Jailer judged his soul unworthy and wounded it before Thrall and others rescued him. He still leads the tauren and is often seen with Mayla Highmountain of the Highmountain tauren."
  ]]
];

window.CHAR_BIOS['nathanos'] = [
  ["The Human Ranger Lord", [
    "Nathanos Marris was a human ranger from Lordaeron. He saved Sylvanas Windrunner and Lor'themar Theron from a troll ambush, and Sylvanas brought him into the elven Farstriders over the objections of many elves, including Prince Kael'thas. He became the first and only human ranger lord. The Farstriders whispered that the two were in love, and neither denied it.",
    "The Scourge killed Nathanos at his home, the Marris Stead, during the Third War and raised him as a mindless servant. Sylvanas searched the Plaguelands to reclaim him. As Nathanos Blightcaller he became her champion, cold and sardonic, scornful of nearly everyone but her. A Val'kyr ritual that sacrificed his own cousin restored his body, and he felt nothing but duty."
  ]],
  ["The Queen's Champion", [
    "After years training Forsaken rangers in the Undercity, Nathanos became Sylvanas's right hand when she was named warchief. Even he was shocked when she had Forsaken executed for meeting their living families at a peace gathering. In the Fourth War he carried out her order to saturate the ruins of Lordaeron with the Blight, raised fallen night elves in Darkshore, led the fleet that lured both factions to Nazjatar and left the Horde with Sylvanas when she abandoned it. On her orders he tried to kill the troll death loa Bwonsamdi and failed. He then returned to the Marris Stead and sat in plain sight. Tyrande Whisperwind, empowered as the Night Warrior, killed him in mid-taunt. He expected death to send him to Sylvanas. His soul went to the Maw like everyone else's, and he can now be found there near her."
  ]]
];

window.CHAR_BIOS['talanji'] = [
  ["Princess of Zandalar", [
    "Talanji is the daughter of King Rastakhan of the Zandalari Empire, the oldest troll nation, and was raised as a priestess of the loa Rezan. She admired Vol'jin from afar. Believing her father's council was failing to protect the empire from blood trolls, she slipped away to seek help from the Horde. The Alliance captured her on the way, and a Horde strike team freed her from Stormwind's prison.",
    "She brought the Horde home and led an expedition into the swamps of Nazmir against the blood trolls and their Blood God, G'huun. She grieved deeply when the traitor prophet Zul destroyed Rezan. When the Alliance attacked the capital, Dazar'alor, her father was killed, and his last act was to pass her the power of Bwonsamdi, the loa of death, to whom he had bound his bloodline."
  ]],
  ["Queen of the Zandalari", [
    "Talanji took the throne, passed the trials of the loa and brought Zandalar into the Horde as an equal. She did not follow Sylvanas blindly and objected when Baine was jailed without a hearing. After the war an assassination attempt and a rebellion by the Widow's Bite, Zandalari who feared a queen tied to the death loa, tested her rule. With help from the Horde's envoy Zekhan she put it down and joined the Horde Council. She has blamed Jaina Proudmoore for her father's death. In Midnight she led the Zandalari delegation to Harandar, home of the haranir, where she learned that trolls, elves and haranir share a common ancestor, and she volunteered to tell the other troll tribes."
  ]]
];
