window.CHAR_BIOS = window.CHAR_BIOS || {};

window.CHAR_BIOS['sargeras'] = [
  ["The Defender", [
    "Sargeras was a titan, a world-soul that woke and joined the Pantheon of Order, the family of titans who searched the Great Dark Beyond for sleeping world-souls and shaped their worlds. He was the strongest warrior among them and was called the Defender. Like the rest of his kind he was just and generous, and at first he could not even imagine true evil.",
    "When demons from the Twisting Nether began attacking mortal worlds, the Pantheon sent Sargeras to stop them. He beat them with ease. The trouble was that a slain demon simply grew a new body in the Nether and came back. So Sargeras built a prison world called Mardum and locked away every demon he defeated. The Pantheon sent him a young titan, Aggramar, as a helper, and Aggramar became his student and his trusted lieutenant. Together they made demon attacks rare for a long age."
  ]],
  ["The Fall", [
    "The two titans split up to guard more of the cosmos. On one world, overrun by the Void creatures called Old Gods, Sargeras questioned a group of dreadlords and learned what the void lords were doing. They planted Old Gods on worlds that held sleeping titans, hoping to twist each unborn titan into a dark titan that nothing could stop. In his rage Sargeras split that planet in two and killed the titan inside it.",
    "The Pantheon scolded him, believing the world-soul might have been saved. Sargeras answered that any world could already be tainted, and that a lifeless universe was better than one ruled by the Void. When they would not agree, he left and never returned. Alone, he sank into despair and decided that all life had to burn. He shattered Mardum. The blast of fel energy freed its demons and warped him into a giant of fire and black armor. He gave the demons a choice to serve him or die, and the Burning Legion was born.",
    "Aggramar fought his old master to a standstill. Later, at the world Nihilam, the Pantheon faced him in force. Aman'Thul, their leader, begged him to stop and spoke of Azeroth, a young world-soul who might one day stand against the void lords. To Sargeras that only made Azeroth the greatest danger of all. When Aggramar came to him unarmed, Sargeras cut him down, then destroyed the bodies of the whole Pantheon. He never learned that Norgannon's last spell had saved their souls."
  ]],
  ["Lord of the Legion", [
    "His demons were strong but had no generals. About 13,000 years before the Dark Portal, Sargeras appeared in a radiant, kindly form to the three rulers of the eredar on Argus. Kil'jaeden and Archimonde accepted his offer and became his commanders. Velen refused and fled with his followers, who became the draenei. The rest of the eredar were twisted into demons.",
    "About 10,000 years before the Dark Portal, the magic of the Well of Eternity led him to Azeroth. Queen Azshara of the night elves and her Highborne court worshipped him and worked to open a portal big enough for him to cross. While he waited, he turned her advisor Xavius into the first satyr and gave Illidan Stormrage demonic sight by burning out his eyes. The night elf resistance destroyed the portal before he could step through, and the Well imploded in the Great Sundering. It was his first defeat. He then had the eredar forge the Jeweled Scepter of Sargeras, a tool that could tear open brief rifts between worlds, so that next time he could send part of his soul through with little warning."
  ]],
  ["The Guardian's Son", [
    "About 800 years before the Dark Portal, he sent an avatar to fight Aegwynn, the Guardian of Tirisfal, a mage chosen to protect Azeroth from demons. He let her destroy it. As the avatar died, his spirit slipped inside her and waited. She sealed the corpse in a tomb under the sea off the Broken Isles, later called the Tomb of Sargeras. When she bore a son, Medivh, Sargeras wove himself into the child.",
    "Medivh grew up to inherit the Guardian's power, and Sargeras slowly bent his mind. Through him he contacted the orc warlock Gul'dan and opened the Dark Portal, bringing the orcish Horde to Azeroth. Aegwynn came to confront her son in Karazhan and lost. Medivh's friend Anduin Lothar and his apprentice Khadgar finally killed him, and Sargeras's spirit was cast back into the Nether. Years later Gul'dan broke into the tomb looking for its power. He found only maddened demons and died there."
  ]],
  ["The Last Crusade", [
    "In Legion, the demons gathered at his tomb for a third invasion of Azeroth. Gul'dan planned to use Illidan's empty body as a vessel for him, and a piece of Sargeras's soul did fill it for a time at the Nighthold before Illidan broke free. On Argus, Sargeras revived Aggramar as a brainwashed servant and had the souls of the captive Pantheon tortured, hoping to remake them as a Dark Pantheon to claim Azeroth.",
    "Azeroth's heroes freed the Pantheon at Antorus, the Burning Throne, and the titans imprisoned Sargeras in the Seat of the Pantheon. In his last act before he was bound, he drove his colossal sword into Silithus. It barely missed the heart of the world-soul, and Azeroth began to bleed the golden substance called azerite. Illidan chose to stay behind as his jailer."
  ]],
  ["What Remains", [
    "Sargeras is a fallen protector. He saw a real danger, and his answer was to destroy everything he had once sworn to guard. Shadowlands added a twist. The dreadlords who served him were secretly spies of the Jailer, and they talked him into filling Argus's world-soul with death magic so that its death would cripple the Arbiter of the afterlife. Blizzard has not said whether the dreadlords who first told him about the void lords were already working that plan.",
    "As of Midnight he remains a prisoner of the Pantheon. The Void he feared is still Azeroth's enemy."
  ]]
];

window.CHAR_BIOS['arthas'] = [
  ["The Crown Prince", [
    "Arthas Menethil was born to King Terenas Menethil II and Queen Lianne of Lordaeron, four years before the First War. His older sister was Calia. As a boy he sparred with Prince Varian Wrynn of Stormwind, learned the sword from the dwarf Muradin Bronzebeard, and studied the Light under Uther the Lightbringer, the first paladin. At nineteen he was made a knight of Uther's Order of the Silver Hand.",
    "He was brave, charming and sure of himself, and he loved his people. He was also proud and quick to anger, and he hated to lose. Uther worried that he pushed too hard even in training. Arthas courted Jaina Proudmoore, a gifted young mage of Dalaran. He broke it off, and later they drew close again. When his horse Invincible was mortally hurt in a riding accident he caused, he had to kill it himself, and the memory haunted him."
  ]],
  ["Stratholme", [
    "In Year 20 a plague began killing the farm towns of Lordaeron. Arthas and Jaina traced it to the necromancer Kel'Thuzad, and Arthas killed him at Andorhal. Kel'Thuzad named his master, the dreadlord Mal'Ganis. At Hearthglen, Arthas saw the plague's real purpose when the dead rose as undead. A mysterious prophet urged him to sail west to Kalimdor. He refused to abandon his people.",
    "At Stratholme the tainted grain had already been handed out. Arthas ordered the whole city killed before its people could turn. Uther refused, and Arthas stripped him of his command. Jaina walked away too. Arthas and his loyal soldiers carried out the purge while Mal'Ganis taunted him, then the dreadlord dared him to follow to Northrend."
  ]],
  ["Frostmourne", [
    "In Northrend, Arthas found Muradin, who was searching for a legendary runeblade called Frostmourne. When orders came from home to return, Arthas had his own ships burned and blamed hired mercenaries, who were killed for it. In the sword's cavern Muradin read a warning that the blade was cursed. Arthas swore he would pay any price to save his people and took it. A shard of ice struck Muradin down, and Arthas left him for dead.",
    "With Frostmourne he cut through the undead and killed Mal'Ganis, or believed he did. The sword had taken his own soul first. Its voice belonged to the Lich King, the spirit that ruled the dead from the Frozen Throne in Icecrown. Arthas became the Lich King's first death knight and raised his own murdered soldiers to serve him."
  ]],
  ["The Death Knight", [
    "He came home to a hero's welcome, knelt before his father's throne and stabbed Terenas through the heart. He then led the undead Scourge across Lordaeron. He killed Uther in a duel and scattered his father's ashes. He carried Kel'Thuzad's remains to the elven kingdom of Quel'Thalas, killed the ranger-general Sylvanas Windrunner and raised her as a banshee to torment her, killed King Anasterian, and used the Sunwell to bring Kel'Thuzad back as a lich. At Dalaran he killed Archmage Antonidas so that Kel'Thuzad could summon the demon lord Archimonde.",
    "In Kalimdor the Lich King had him quietly undermine the demons, and he steered Illidan Stormrage toward the Skull of Gul'dan so that Illidan would kill the dreadlord Tichondrius. After the Legion fell at Mount Hyjal in Year 21, Arthas returned to Lordaeron. As the Lich King's power weakened, Sylvanas broke free and ambushed him, and only Kel'Thuzad saved him. The Lich King called him north. The Frozen Throne was cracked, and Illidan was coming to destroy it."
  ]],
  ["The Frozen Throne", [
    "The crypt lord Anub'arak led him through the ruins of Azjol-Nerub, and he raised the blue dragon Sapphiron as a frost wyrm on the way. At the foot of Icecrown he defeated Illidan in single combat. He climbed the glacier, shattered the ice around the throne and put on the Helm of Domination. He and Ner'zhul, the orc whose spirit was the Lich King, merged into one being. Over the years on the throne he consumed Ner'zhul completely and became the Lich King alone. He also cut out his own heart and cast it into the depths beneath Icecrown, the last of his humanity thrown away.",
    "In Wrath of the Lich King he woke and attacked the living world. He drew Azeroth's champions to Northrend, planning to kill them and raise them as his new servants. At the Wrathgate he faced the Alliance and Horde in person, and he took the badly burned Bolvar Fordragon to his citadel to torture. When Jaina came to him in the Halls of Reflection hoping to reach the man she had loved, he was unmoved. Tirion and the Argent Crusade later found his frozen heart and struck it with the Ashbringer, wounding him badly. Tirion Fordring and the heroes finally reached him atop Icecrown Citadel. Tirion shattered Frostmourne with the Ashbringer, freeing the souls inside, and the heroes struck him down. He died in the arms of his father's spirit, seeing only darkness ahead."
  ]],
  ["The Last of His Soul", [
    "As he died, Uther and a rebel kyrian named Devos cast his soul into the Maw, the prison of the damned, though the law of the afterlife said every soul must be judged. Shadowlands revealed the larger plan behind his fall. The Jailer, the Maw's ruler, had forced an enslaved Eternal One to design Frostmourne and the Helm, and dreadlords had delivered them. The Lich King was meant to herald the Jailer's coming. Arthas chased his own power instead, and the Jailer called him a failure. His sister Calia said that Arthas made his own choices, but that his fate was shaped in part by the Jailer.",
    "The Jailer set what was left of Arthas's soul inside Kingsmourne, a cursed sword used to control King Anduin Wrynn. When Anduin broke free and split the blade, only a faint flicker of Arthas remained, too little to be judged. Sylvanas, Jaina and Uther watched it fade away for good. Jaina said she was one of the few who still remembered the prince he had been."
  ]]
];

window.CHAR_BIOS['jailer'] = [
  ["The First Arbiter", [
    "Zovaal was an Eternal One, one of the rulers of the Shadowlands, the realms of the dead. Like his siblings he was made by the First Ones, the mysterious creators of the cosmos, in their realm of Zereth Mortis. He was the strongest of the Eternal Ones and was given the role of Arbiter, the judge who sends each soul to the afterlife it has earned.",
    "Watching countless mortal lives made him afraid. He came to believe that some unseen power would one day threaten all of creation, and that the divided realms of Death could never stand against it. His siblings dismissed the fear. Zovaal decided to remake reality himself. The First Ones' secrets were sealed in the Sepulcher of the First Ones, and only the Eternal Ones' sigils, the symbols of their power, could open it. When his siblings refused him, he tried to take their sigils by force."
  ]],
  ["The Banished One", [
    "It took all the other Eternal Ones together to defeat him, led by the Primus, ruler of Maldraxxus. They put him on trial in Oribos. Kyrestia the Archon found him guilty of betraying his duty, and the Winter Queen said he had threatened the cycle of life and death. Sire Denathrius only remarked that he could have chosen another way. Zovaal answered that they were preserving a doomed cosmos. The Primus hoped long imprisonment would bring his brother to repent.",
    "They stripped him of his sigil and his anima, the energy of souls, leaving a hole in his chest. From what they took they built a new Arbiter to replace him. The Primus invented a new magic, Domination, and carved Zovaal's sentence into his flesh with it, and the Winter Queen used the Heart of the Forest to seal the Maw, the realm of the damned. Zovaal became its Jailer. Over the ages most of the Shadowlands forgot he had ever been the Arbiter."
  ]],
  ["Master of the Maw", [
    "Imprisonment only hardened him. Over countless ages he broke his chains, learned to wield Domination, and built an army of tortured souls called the Mawsworn. Allies joined him from outside. Denathrius of Revendreth secretly gave him his own sigil and lent him his dreadlords, spies who posed as demons of the Burning Legion. The loa Mueh'zala brought him an eye taken from the titan-forged Odyn, which he made into the Eye of the Jailer, and the val'kyr Helya came to his side.",
    "When the Primus came to investigate, the Jailer defeated him, broke his mind and set him to work as the Runecarver, a prisoner who forged whatever the Maw required. From the Runecarver's memory the Jailer took designs for Frostmourne and the Helm of Domination. He also had his dreadlords persuade Sargeras to fill the world-soul of Argus with death magic, so that if Argus ever died its soul would crash into the Arbiter and break her."
  ]],
  ["The Lich Kings", [
    "The dreadlords carried the helm and sword across to the living world and used them to bind the orc Ner'zhul as the Lich King. The Burning Legion thought the Lich King was its own weapon. The Jailer meant him as a herald who would open Azeroth to him, because he believed the power of Azeroth's world-soul was the key to his plan. All three Lich Kings failed him. He judged Ner'zhul weak and tortured his soul in the Maw. Arthas chased his own glory, and the Jailer took his soul when he died. Bolvar Fordragon felt a dark presence pressing on his mind and resisted it."
  ]],
  ["Sylvanas and the Sigils", [
    "When Sylvanas Windrunner killed herself after Arthas's fall, her soul fell into the Maw. The Jailer told her he wanted to free all souls from an unjust system, released her, and gave her five signs to watch for. A fiery darkness would return, she would step out of the shadows and lead, and a blade would pierce the heart of the world. Each came true. In Legion she accepted his pact. When heroes killed Argus, his soul broke the Arbiter as planned, and every soul that died began falling into the Maw. Each death in Sylvanas's Fourth War made him stronger. In the starving afterlives his agents went to work. Kel'Thuzad turned the houses of Maldraxxus against each other, the rebel kyrian Devos led the Forsworn in Bastion, and Denathrius hoarded Revendreth's anima for him.",
    "In Shadowlands, Sylvanas shattered the Helm of Domination, tore open the sky over Icecrown and brought him four captive leaders of Azeroth. He chose King Anduin Wrynn as his tool and bound him with Kingsmourne, a blade holding the last of Arthas's soul. Through Anduin he stole the sigils of the Archon, the Winter Queen and the Primus, and he let Denathrius fall once he had served his purpose. Then he seized Oribos, absorbed the Arbiter and became whole again. He told Sylvanas his true goal, a new reality where everyone would serve him. She defied him. He handed back the piece of her soul Frostmourne had cut away, left her to her enemies, and departed for Zereth Mortis with Anduin."
  ]],
  ["The End of Zovaal", [
    "He forced his way into the Sepulcher of the First Ones and set its great machine to drain the soul of Azeroth through the Forge of Souls beneath Icecrown Citadel. Azeroth's heroes freed Anduin, then reforged the broken helm into the Crown of Wills, which let them resist Domination. With help from Azeroth herself they defeated him at the heart of the Sepulcher. As his body dissolved, he repeated the warning he had given his siblings ages before, that a divided cosmos could not survive what was coming. Blizzard has never said what threat he meant.",
    "The kyrian Pelagos became the new Arbiter, and the flow of souls into the Maw stopped. Zovaal was patient, certain and cold. He used Sylvanas, Denathrius and the Lich Kings as tools and threw each away when done. Bolvar said that even in defeat, the doubt the Jailer had planted in his enemies lived on."
  ]]
];

window.CHAR_BIOS['kiljaeden'] = [
  ["Brother of Velen", [
    "Kil'jaeden was one of the rulers of the eredar on their world of Argus, a genius among a race of geniuses. He governed beside his closest friend Velen, and the two loved each other like brothers. Later the ambitious young sorcerer Archimonde joined them.",
    "When the titan Sargeras came to the three rulers with his offer, Kil'jaeden accepted and Velen refused. Velen fled Argus with his followers and the naaru, and Kil'jaeden took it as a betrayal. As his reward Sargeras sharpened Kil'jaeden's cunning and made him the Legion's recruiter, charged with corrupting other races. Kil'jaeden also hunted the fleeing draenei across the stars for thousands of years. He took Velen's son, renamed him Rakeesh, which means butcher, and had him raised as a Legion general while Velen believed him dead."
  ]],
  ["The Deceiver", [
    "His scouts finally found the draenei on a world they called Draenor, shared with the orc clans. Kil'jaeden posed as the orcs' ancestors and told the shaman Ner'zhul that the draenei were plotting against them. When Ner'zhul discovered the truth and balked, Kil'jaeden stripped his power and relied on Gul'dan, an outcast he had secretly trained in fel magic and placed as Ner'zhul's apprentice. Gul'dan had the clan chiefs drink the blood of the pit lord Mannoroth. The maddened Horde slaughtered the draenei at Shattrath. Then, on Sargeras's orders, he cut the orcs off so that desperation would drive them to invade Azeroth. He called the orcs his masterpiece.",
    "When the Horde failed, he decided the lesson was disloyalty. He tortured Ner'zhul's spirit until nothing else remained, made it the Lich King, and sealed it in the Frozen Throne in Year 8, with dreadlords set as its jailers. Shadowlands later revealed that the helm and sword used for this came from the Jailer, and that the dreadlords served him in secret. The Lich King broke free of Kil'jaeden's control during the Third War. Kil'jaeden sent Illidan Stormrage to destroy the Frozen Throne, and Illidan failed. Arthas took the throne instead."
  ]],
  ["The Sunwell and the End", [
    "In The Burning Crusade he made the blood elf prince Kael'thas his servant and tried to come through the Sunwell itself. He was halfway into the world when Anveena, the Sunwell's living spirit, sacrificed herself to weaken him, and heroes drove him back into the Nether.",
    "In Legion he guided the Gul'dan of an alternate Draenor into the Tomb of Sargeras. When Gul'dan accused him of planning to discard him, Kil'jaeden answered that every creature serves a master, even the Deceiver, and that he had never once lied to him. He led the Legion's last invasion of Azeroth from his command ship over Argus, though he privately questioned Sargeras after so many failures. After the battle in the Tomb of Sargeras, Velen and Azeroth's champions followed him into the Twisting Nether and fought him aboard that ship. He mocked Velen about the son he had left behind. Dying, he admitted he had always envied Velen's faith and vision, and wondered aloud if Velen might yet prove Sargeras could be stopped. Velen laid a hand on his brow before leaving. Kil'jaeden died as the ship exploded. Because he died in the Nether, the home of demons, his death is final."
  ]]
];

window.CHAR_BIOS['archimonde'] = [
  ["The Apprentice", [
    "Archimonde began as an apprentice to Thal'kiel, an eredar sorcerer on Argus who secretly built an army of summoned demons to make himself dictator. The night before the coup, Archimonde betrayed his master to the rulers Kil'jaeden and Velen, led the attack on Thal'kiel's hidden camp and beheaded him himself. He was hailed as a hero, rose to rule beside the other two, and quietly kept his master's skull, gilded to channel magic.",
    "He was brilliant, ruthless and hungry for power. Visions of a dark god leading a conquering army came to him in his sleep, apparently through that skull. When Sargeras arrived he was the first to accept. Most eredar joined out of thirst for knowledge. Archimonde joined for power."
  ]],
  ["The Defiler", [
    "Sargeras made him supreme commander of the Burning Legion's armies, and he burned world after world. He drove his demons to ever greater savagery, and he armed the pit lords and made them his siege engines. He cared little for Kil'jaeden's hunt for Velen and the draenei, though he did nothing to stop it. About 10,000 years before the Dark Portal he led the invasion of Kalimdor in the War of the Ancients with the pit lord Mannoroth. He killed the demigod Malorne by snapping his neck. When the portal collapsed and the Well of Eternity imploded, he was thrown back into the Twisting Nether.",
    "In the Third War the lich Kel'Thuzad used the Book of Medivh to summon him to Azeroth. He told the Scourge's leaders that the Lich King was no longer needed and put the dreadlord Tichondrius in command of the undead. His first act was to destroy Dalaran with a single spell as a warning. When the orcs fled west, he followed them. His pit lord Mannoroth corrupted Grom Hellscream's clan into killing the demigod Cenarius, and Tichondrius used the Skull of Gul'dan to poison the forests of Ashenvale. Archimonde shrugged off setbacks, such as Illidan killing Tichondrius, and pressed on to the night elves' World Tree, Nordrassil, hoping to drain the Well of Eternity beneath it and become a rival to Sargeras himself. Humans, orcs and night elves stood against him together on Mount Hyjal. In Year 21 he smashed their bases one by one and began climbing the tree, ignoring the tiny wisps gathering around him. Malfurion Stormrage sounded the Horn of Cenarius, and thousands of wisps exploded at once and tore him apart. Only his bones were left."
  ]],
  ["The Final Death", [
    "A demon slain outside the Twisting Nether can return, and Archimonde did. In Warlords of Draenor, when Kil'jaeden's plan to corrupt the orcs failed on an alternate version of Draenor, Archimonde took over the Legion's invasion there and attacked openly. He had no interest in Kil'jaeden's grudge against the draenei. To him, that Draenor was simply a chance.",
    "He made his stand in Hellfire Citadel. Draenei, orcs and Azeroth's heroes, led by Khadgar, Yrel and Durotan, fought him, and he dragged them into the Twisting Nether itself. They beat him there, and a demon killed in the Nether does not come back. With his last breath he hurled the warlock Gul'dan through a portal to carry on the Legion's work. Archimonde's whole life was a reach for godlike power, and he betrayed his teacher, his people and his world to get it."
  ]]
];

window.CHAR_BIOS['bolvar'] = [
  ["Regent of Stormwind", [
    "Bolvar Fordragon was a paladin of the Alliance, known since boyhood for his determination and noble spirit. When the Scourge struck Lordaeron in the Third War, he sent his young daughter Taelia, whom he called his shining star, to be raised in safety in Kul Tiras.",
    "When King Varian Wrynn vanished, Bolvar ruled Stormwind as Highlord and regent for the boy king Anduin. He did so with the black dragon Onyxia, disguised as the noblewoman Katrana Prestor, at his side, and an amulet she gave him clouded his mind until her plot was exposed. He still acted decisively when it counted. He agreed with Warchief Thrall to send Alliance and Horde armies together against the Old God C'Thun in Ahn'Qiraj, and he sent heroes against Kel'Thuzad's floating fortress of Naxxramas."
  ]],
  ["The Wrathgate", [
    "When Varian returned and war came with the Lich King, Bolvar led the Alliance army to Northrend. There he formed a grudging respect, even a kind of friendship, with Dranosh Saurfang, the Horde commander. The two armies met before Angrathar the Wrathgate and faced the Lich King himself. Then the Forsaken Grand Apothecary Putress betrayed everyone and drenched the field in plague. Bolvar fell. The red dragon queen Alexstrasza burned the plague away with her fire, and his body vanished.",
    "Everyone thought he was dead. In fact the dragonfire had left him charred but alive, and the Scourge carried him to Icecrown Citadel, where Arthas tortured him and failed to break him."
  ]],
  ["Jailer of the Damned", [
    "When Arthas died, the spirit of King Terenas warned that the dead without a master would overrun the world. There must always be a Lich King. Tirion Fordring was about to take the Helm of Domination himself when Bolvar asked for it instead, since he could never live among the living again. He made Tirion promise to tell the world that Bolvar died with the Lich King. Then he sealed himself in ice on the Frozen Throne.",
    "The Light left him the moment he put on the helm, and holding back the Scourge took nearly all his strength. In Legion he worked with the death knights of the Ebon Blade against the demons, though his methods were grim, including an attempt to raise Tirion's body as one of his Four Horsemen. Before Sylvanas Windrunner came for the helm, he tried a gamble. He made the Horsemen believe he had fallen to darkness, so they would arrive after the fight and kill whoever won. Sylvanas beat him and split the helm in two, and the sky over Icecrown tore open into the Shadowlands."
  ]],
  ["A Second Chance", [
    "Freed but still undead, Bolvar became Highlord of the Knights of the Ebon Blade. He used shards of the broken helm to look into Torghast, the Jailer's tower, and guided the rescue of Jaina Proudmoore, Thrall and Baine Bloodhoof, even when the Jailer began staring back and tried to seize his mind. He helped reforge the helm's remains into the Crown of Wills, which let the heroes resist the Jailer's Domination magic, and he fought beside them to the end.",
    "Taelia, now grown, learned the truth and was angry no one had told her. She said his sacrifice had been paid by everyone who loved him. He hoped she could forgive him, and they began to rebuild their bond. In The War Within, Taelia said her father was still brooding and apologetic as he worked out what it meant for there to be no Lich King, but was better than before."
  ]]
];

window.CHAR_BIOS['kelthuzad'] = [
  ["The Archmage", [
    "Kel'Thuzad sat on the Council of Six, the ruling council of the mages of Dalaran, and was counted among the finest mages of his day. He thought his peers timid and unimaginative. After seeing orc death knights raid Dalaran, he grew fascinated with necromancy, the magic of raising the dead. He began with dead rats and moved on to people he lured from the sewers. When Archmage Antonidas found out, he confiscated Kel'Thuzad's dark materials and warned him to give it up or be exiled. Kel'Thuzad left Dalaran forever.",
    "A voice in his mind had been calling him north. He sold his estates and traveled to Northrend, where the crypt lord Anub'arak showed him the ruins of Azjol-Nerub. At Icecrown he offered his soul to the Lich King, who promised him immortality and sent him home to found a religion."
  ]],
  ["Herald of the Plague", [
    "Back in Lordaeron he spent three years building the Cult of the Damned, promising poor and weary people equality and eternal life. He brought along friends such as Baron Rivendare. When the Lich King sent plague cauldrons, his cultists hid them in their villages, and the dead began to rise. Kel'Thuzad named the growing undead army the Scourge.",
    "Prince Arthas chased him to Andorhal and killed him in Year 20, as the Lich King intended. After Arthas took Frostmourne, he carried Kel'Thuzad's remains to the Sunwell in Quel'Thalas and raised him as a lich. After Arthas stormed Dalaran and seized the Book of Medivh, Kel'Thuzad used it to summon the demon lord Archimonde, who promptly destroyed the city. When Arthas left for Northrend, he called Kel'Thuzad a loyal friend and left him to rule the Plaguelands from the flying fortress Naxxramas."
  ]],
  ["Lord of Naxxramas", [
    "From Naxxramas he ruled the Plaguelands for years. He raised the fallen paladin Alexandros Mograine to lead his elite Four Horsemen, death knights who served as his guard, and kept the undead frost wyrm Sapphiron in his chambers. When Alexandros's son Darion gave his life at Light's Hope Chapel to free his father's soul, Kel'Thuzad raised Darion too, calling him a fitting prize. Heroes stormed the fortress and destroyed his body, but a traitor in the Argent Dawn stole his phylactery, the vessel that held his soul, and he rose again. In Wrath of the Lich King, Naxxramas floated over Northrend, and heroes defeated him a second time. His phylactery was destroyed at some point after, and the story is unclear exactly when."
  ]],
  ["Servant of the Jailer", [
    "In the Shadowlands his soul went to Maldraxxus, the realm of war. Sire Denathrius had recruited him to the Jailer's cause, and secret shipments of anima from Revendreth helped him rise fast in the House of Rituals. He set the great houses of Maldraxxus against each other, destroying two of them, and plotted to sacrifice a captive kyrian to breach the walls of the Maw. Denathrius gave him the Medallion of Dominion, a relic that could command the venthyr of Revendreth. When he was exposed he fled to the Jailer and fought for him in the Sanctum of Domination. The heroes destroyed his phylactery there and then struck him down. He died unable to believe that death did not answer to him.",
    "He served the Lich King faithfully, and he later claimed he had been working toward Azeroth's end all along. Whatever the truth, he was a proud and patient man who traded everything for forbidden knowledge."
  ]]
];

window.CHAR_BIOS['velen'] = [
  ["The Prophet of Argus", [
    "Velen ruled the eredar of Argus beside his friend Kil'jaeden, and later Archimonde, and loved them as parts of his own soul. He was known for wisdom and compassion. When a memory-stealing curse spread, he walked among the sick and cured them with T'uure, a crystal that had fallen from the sky. When the sorcerer Thal'kiel showed off his new demon-summoning, Velen forbade it. At his son's birth he had a vision of himself weeping over a dying, fel-twisted eredar, and did not understand it.",
    "When Sargeras made his offer, the naaru K'ure showed Velen what the Legion really was. He gathered his followers and fled aboard the naaru ship Genedar. He had sent a friend, Talgath, to bring his wife and son, but Talgath secretly gave them to Kil'jaeden. The exiles, now called draenei, were chased across the stars for thousands of years."
  ]],
  ["Exile and Survival", [
    "About 200 years before the Dark Portal, the Genedar crashed on a world the draenei named Draenor. Just before the crash Velen threw out the naaru K'ara, which had fallen to the Void, and the struggle left his visions unreliable. On Draenor he kept a refuge at the Temple of Karabor. When Kil'jaeden turned the orcs against his people, Velen survived the slaughter by hiding in the marshes by the Zangar Sea. He welcomed the Broken shaman Nobundo when other draenei shunned him.",
    "Decades later he led a raid to seize the Exodar, a naaru ship, and fled the shattered world, now called Outland. Sabotage threw the ship to Azeroth, where it crashed on Azuremyst Isle. Velen pledged the draenei to the Alliance. After Kil'jaeden was driven back at the Sunwell, he used the heart of the fallen naaru M'uru to restore the Sunwell with holy Light, saving the same blood elves who had wronged his people. In the years after he taught a young Anduin Wrynn in the ways of the Light."
  ]],
  ["The Son and the Brother", [
    "In Legion the demon general Rakeesh attacked the Exodar. As heroes beat him, Velen suddenly understood his old vision and tried to stop them. Rakeesh was his son. He held him as he died, renounced the title of Prophet and said the draenei were going home. He followed Kil'jaeden into the Twisting Nether. When his old friend lay dying and confessed his envy, Velen laid a hand on his brow, letting go of his hatred for his own sake and his son's memory.",
    "On Argus he faced Illidan's charge that his faith had cost his people dearly, killed the traitor Talgath, and rebuilt the Crown of the Triumvirate to power the ship Vindicaar for the final assault. After Sargeras was imprisoned, he said victory had come, though not salvation."
  ]],
  ["Healer of Old Wounds", [
    "Velen became one of Anduin's closest advisors through the Fourth War. In Dragonflight he accepted Arzaal, a repentant man'ari eredar, into draenei society and invited his estranged old friend Hatuun to his council, hoping to reunite the scattered eredar. In Midnight he joined the Light-wielders defending the Sunwell from Xal'atath and her Void armies, pouring Light into it without rest. He has led his people for thousands of years and, as of Midnight, he is alive."
  ]]
];

window.CHAR_BIOS['mannoroth'] = [
  ["The Destructor", [
    "Mannoroth is the king of the pit lords, huge demons the Legion uses as living siege engines. Kil'jaeden recruited him, and Archimonde made him his second-in-command. He loves slaughter, but he is also a powerful sorcerer. In the War of the Ancients, about 10,000 years before the Dark Portal, he came through Queen Azshara's portal and showed her Highborne how to shield the Well of Eternity for their own use, burning one frightened elf to ash on arrival. He fought the demigod Cenarius, and when the night elves' spell swept the portal's casters away, he was hurled out over the Well, roaring.",
    "Thousands of years later Kil'jaeden sent him to Draenor. Gul'dan offered Mannoroth's blood to the orc chieftains, and drinking it filled the orcs with a demonic bloodlust that bound them to the Legion. After the Horde lost its wars on Azeroth, Mannoroth wanted revenge. In the Third War, Kel'Thuzad summoned him back to Azeroth, and he followed the orcs to Kalimdor. He spilled his blood into a fountain, and Grom Hellscream and his Warsong clan drank it to kill Cenarius. Mannoroth then claimed Grom as his slave again.",
    "Thrall freed Grom and fought Mannoroth in Ashenvale. Mannoroth knocked Thrall aside and told Grom the curse could never be broken. Grom killed him with one blow to the chest, freeing the orcs from the blood curse and dying himself. Mannoroth's skull and armor were raised as a monument in Orgrimmar, and his broken spear still marks the spot in Demon Fall Canyon. On the alternate Draenor of Warlords of Draenor, Grom refused the blood and killed him at the Throne of Kil'jaeden. Gul'dan raised him again in Hellfire Citadel, where heroes slew him once more."
  ]]
];

window.CHAR_BIOS['malganis'] = [
  ["The Dreadlord", [
    "Mal'Ganis is a dreadlord, one of the bat-winged nathrezim. Sire Denathrius made the dreadlords in Revendreth, a realm of the Shadowlands, to spy and spread Death's influence. They posed as servants of the Burning Legion while secretly working for the Jailer. Mal'Ganis was among the dreadlords who tortured the orc Ner'zhul until he agreed to become the Lich King, and then stayed on as his jailers.",
    "In the Third War he commanded the Scourge in Lordaeron, with Kel'Thuzad under him. The Lich King wanted Prince Arthas as his champion, and Mal'Ganis became the bait. He taunted Arthas during the purge of Stratholme and dared him to follow to Northrend, where the dreadlords had planted clues to lead the dwarves to Frostmourne. When Arthas took the sword, the Lich King ordered him to kill Mal'Ganis. The dreadlord died stunned at the betrayal. The nathrezim had protected themselves from Frostmourne, so his soul went to the Twisting Nether and he took a new body.",
    "In Wrath of the Lich King he whispered to the Scarlet Crusade as the voice of the Light, then posed as Grand Admiral Westwind to lead its splinter group, the Scarlet Onslaught, against Arthas. Exposed, he escaped. After Legion he visited Sylvanas Windrunner and told her the Jailer's plan. In Shadowlands he infiltrated the court of Prince Renathal as a distraction while other dreadlords freed Denathrius. In Zereth Mortis he disguised himself as one of Azeroth's own heroes to delay the covenant armies. Heroes defeated him and the dreadlord Kin'tessa in the Sepulcher of the First Ones. It is not known whether that death is permanent."
  ]]
];

window.CHAR_BIOS['anubarak'] = [
  ["The Traitor King", [
    "Anub'arak was the last king of Azjol-Nerub, the underground empire of the spider-like nerubians in Northrend. Proud and strong, he fought the Lich King when the Scourge came, and he crushed every attempt to spread the plague in his kingdom. As the war turned against him, he begged the southern nerubian kingdom of Azj-Kahet for help three times. Its queen, Neferess, refused.",
    "He fell in battle, and the Lich King raised him as an undead crypt lord. He chafed at his chains but could not break them. He was forced to lead the Scourge against his own people and turn their ziggurats, Naxxramas among them, into strongholds for his master. The surviving nerubians named him the Traitor King. He also guided the newly arrived Kel'Thuzad through the ruins.",
    "In Year 21, when the Lich King's power was failing, he met Arthas on the coast of Northrend and saved him from Kael'thas's blood elves. He led him through the broken tunnels of Azjol-Nerub, helped kill and raise the dragon Sapphiron, and dug Arthas out of a collapse. He guarded Arthas as the prince climbed to the Frozen Throne.",
    "In Wrath of the Lich King he still ruled the ruins of his kingdom for his master. Heroes killed him there, and his last words were relief at being free of the Lich King. Arthas raised him again with new frost powers and set him beneath the Argent Crusade's tournament grounds. Heroes destroyed him for good at the end of the Trial of the Crusader."
  ]]
];

window.CHAR_BIOS['sindragosa'] = [
  ["Queen of the Frostbrood", [
    "Sindragosa was one of the original blue dragons and the beloved consort of Malygos, Aspect of the blue dragonflight. She fought for over a century against the Primalists in the War of the Scaleborn. During the War of the Ancients she sensed something wrong with Neltharion, the black Aspect who later became Deathwing, but kept her doubts to herself. When he turned the Dragon Soul against the other dragons, its blast nearly destroyed the blue flight and threw her far into the frozen north.",
    "Blind and dying, she tried to reach the Dragonblight, where dragons go to die, and fell short in the peaks of Icecrown. She called to Malygos and no answer came. She died filled with hatred for the Legion, for Neltharion, for Malygos, and most of all for the mortal world.",
    "Ages later the Lich King Arthas raised her bones as a frost wyrm and made her queen of the Frostbrood, his undead dragons. As a last cruelty he raised the spirits of her lost whelps before her. In Wrath of the Lich King she slaughtered the freed slaves escaping the Pit of Saron and defended her lair in the Frostwing Halls of Icecrown Citadel. Heroes destroyed her and carried her essence to the blue dragon Kalecgos, who laid it to rest.",
    "In Dragonflight, Kalecgos, now the blue Aspect, found an arcane copy of her mind preserved on the Dragon Isles. They worked together to free the trapped souls of Malygos and Sindragosa. Once free, the two departed into the afterlife side by side, finally at peace."
  ]]
];

window.CHAR_BIOS['darion'] = [
  ["The Ashbringer's Son", [
    "Darion Mograine was born still and lifeless until his father, the paladin Alexandros Mograine, plunged him into an icy stream and he came to life. His mother died from the birth. After the Third War he joined the Silver Hand. When his brother Renault murdered their father with the holy sword Ashbringer, the blade became corrupted, and Kel'Thuzad raised Alexandros as a death knight. Darion joined the Argent Dawn, fought his way into Naxxramas, defeated his undead father and took the corrupted sword.",
    "The sword held his father's trapped soul. Tirion Fordring told him only an act of love greater than the act of evil could free it. When Kel'Thuzad attacked Light's Hope Chapel, Darion drove the Ashbringer through his own heart. The blast of Light freed his father and swept away the Scourge. Kel'Thuzad raised Darion as a death knight anyway.",
    "As Highlord of Acherus, the Lich King's death knight fortress, he led the assault on Light's Hope. When the Lich King appeared to claim the Ashbringer's spirit, Darion broke free and threw the corrupted blade to Tirion, who purified it and drove Arthas off. Darion founded the Knights of the Ebon Blade, fought beside Tirion in the Ashen Verdict, and helped forge the runeblade Shadowmourne.",
    "In Legion he served Bolvar against the demons, and the Light itself killed him at Light's Hope while the Ebon Blade tried to raise Tirion as a Horseman. The new Deathlord raised Darion as leader of the Four Horsemen. In Shadowlands he handed the title of Highlord to Bolvar, fought in the Maw and was reunited with his father's soul. In Midnight he and the Horsemen helped defend Light's Hope from Scourge remnants."
  ]]
];

window.CHAR_BIOS['denathrius'] = [
  ["The Master of Revendreth", [
    "Sire Denathrius, called the Master, is an Eternal One, ancient, calculating and methodical, made by the First Ones to rule Revendreth, the realm of the Shadowlands where proud souls atone for their sins. He created the venthyr who run its castles, Prince Renathal first among them. He also created the nathrezim, or dreadlords, as spies to spread Death's influence through the cosmos. When their spying provoked an attack from the Light, he publicly exiled them, but he secretly kept them working.",
    "He sat at the trial of Zovaal and told him only that he could have chosen another way. At some point he gave Zovaal his own sigil and joined the Jailer's cause. His dreadlords posed as Legion demons and spread the Jailer's plans across the living worlds. He also recruited Kel'Thuzad after the lich's final defeat, fed him anima, and later handed him the Medallion of Dominion. The venthyr were meant to cleanse sin, and their creator had been corrupted by the very sins his realm was built to punish.",
    "When the anima drought struck, Revendreth hoarded the anima the other realms needed. Denathrius asked the newly arrived Maw Walkers to help crush Renathal's rebellion, using them while he poured his stockpile into the Maw. Renathal and the heroes defeated him in Castle Nathria. His sentient sword Remornia absorbed his essence, and both were held at Dawnkeep under the watch of the naaru Z'rali, meant to stay until he repented. The Jailer, asked about rescuing him, said Denathrius had served his purpose.",
    "His dreadlords stole Remornia and freed him anyway. Since the Jailer's defeat, his location and fate are unknown."
  ]]
];

window.CHAR_BIOS['arbiter'] = [
  ["The Judge of Souls", [
    "The Arbiter was the Eternal One who judged every soul that entered the Shadowlands and sent it to its proper afterlife. She lived in the Crucible at the heart of the city of Oribos. She was not the first Arbiter. The other Eternal Ones built her from the anima and sigil they tore from Zovaal when they banished him to the Maw. They made her dispassionate, so she could not be swayed the way he had been. Zovaal claimed they made her without a will so she could never defy the design. She never spoke. Her attendants served her, and Tal-Inara spoke on her behalf. Most of the Shadowlands did not know where she came from.",
    "The Jailer prepared her downfall long in advance. His dreadlords convinced Sargeras to fill the world-soul of Argus with death magic. At the end of Legion, heroes killed Argus, and his broken soul flew to Oribos and struck her. She fell dormant. Every soul that died after that went straight into the Maw. The realms of the dead starved for anima while the Jailer grew stronger.",
    "In Shadowlands the Jailer seized Oribos, broke through her defenses and merged with her, taking back her essence and sigil, and her body dissolved. Her attendants still carried her voice and used it to help recreate her sigil. Since the Jailer's invasion had disrupted the normal way of making a new Arbiter, the kyrian Pelagos volunteered to be transformed and took her place in the Crucible, and the flow of souls was set right again."
  ]]
];

window.CHAR_BIOS['winterqueen'] = [
  ["Queen of Ardenweald", [
    "The Winter Queen is the Eternal One who rules Ardenweald, the forest realm of the Shadowlands. She tends the cycle of rebirth, restoring fallen nature spirits such as Wild Gods and loa and sending them back to the living world. She and her land are one. The moon goddess Elune is her sister, and together they stand for the cycle of death and life. When the Eternal Ones banished Zovaal, she used the Heart of the Forest to make the Maw inescapable.",
    "The anima drought hit Ardenweald hardest. For the first time she had to choose which groves and souls would be fed and which would fade. Her Wild Hunt even came for the soul of the Wild God Ursoc. When its keeper protested, she showed him the whole forest dying and, in tears, left the choice to him, and he drained it. She grew bitter at Elune, believing her sister had ignored her pleas. In fact Elune had sent her the souls of night elves killed in the War of the Thorns, but those souls had fallen into the Maw.",
    "When the soul of Ysera, the green dragon Aspect, arrived nearly gone, she spared some of her scarce anima to revive it. In Shadowlands she fought off the drust, then hid her sigil in the Heart of the Forest during the Jailer's assault. The dominated Anduin Wrynn stole it anyway. When Elune appeared through Tyrande Whisperwind, the sisters learned the truth and made peace, and the Sisters' Tear restored the Heart.",
    "In Dragonflight she let Ysera return to the living world in exchange for Malfurion Stormrage, who stayed bound to Ardenweald in her place. She still rules her realm."
  ]]
];

window.CHAR_BIOS['xera'] = [
  ["The Light Mother", [
    "Xe'ra was a naaru, a being of living Light, and one of the first naaru forged in the ordering of the cosmos. She was called the prime naaru and the Light Mother. She said she had been among those who failed to stop the Burning Legion's rise. After the draenei fled Argus, their finest warriors followed her aboard the ship Xenedar as the Army of the Light, an endless crusade against the demons. Over time survivors of many ruined worlds joined it.",
    "She filled the human hero Turalyon with Light, making him Lightforged and unaging, and he became the Army's leader. When his wife Alleria Windrunner began studying the Void, Xe'ra had her imprisoned until she would return to the Light, and was talked out of executing her only by Turalyon. She kept from her soldiers the fact that a naaru could fall to the Void.",
    "She became convinced that Illidan Stormrage was the Child of Light and Shadow, prophesied to end the age of demons. In the novel Illidan, a powerful naaru matching her met Illidan on Argus shortly before his death at the Black Temple, showed him a vision of himself as a champion of the Light, and branded a holy rune on his forehead. In Legion, with her Army near defeat, she sent her core, Light's Heart, to Azeroth and guided a champion through Illidan's memories to help restore his soul.",
    "On Argus the Xenedar was shot down, and she was restored aboard the Vindicaar. She tried to bind Illidan in chains of Light and force his destiny on him. He broke free and destroyed her. Velen gathered her shards. Turalyon later agreed that she had been wrong to force the Light on anyone. Whether a naaru slain outside the Light can re-form is unknown."
  ]]
];

window.CHAR_BIOS['muru'] = [
  ["The Captive Naaru", [
    "M'uru was a naaru, a being of living Light. When Khadgar and Velen asked the naaru for help against the dark forces in Outland, the Army of the Light could spare no soldiers. M'uru, A'dal and O'ros came instead, bringing the fortress Tempest Keep to the region called Netherstorm.",
    "Prince Kael'thas Sunstrider's blood elves seized Tempest Keep, and Kael'thas sent M'uru home to Silvermoon as a gift for his people. There the magisters chained it beneath the Hall of Blood. In captivity its voice, normally a soft chime, sounded like breaking glass. The blood elves had lost their faith after the Scourge destroyed their homeland, and through M'uru they learned to take the Light by force. This founded the Blood Knights under Lady Liadrin. Many blood elves, the Farstriders among them, thought the abuse shameful.",
    "Later, Kael'thas turned to the Legion, stole M'uru back and took it to the Sunwell. He drained it until it fell into darkness and set it to guard the Sunwell's final gate. When heroes attacked, it became the void god Entropius. After Kil'jaeden was driven out, Liadrin mourned the harm her knights had done. Velen used M'uru's heart, still untouched by the darkness, to restore the Sunwell, which now holds both arcane and holy power. The Blood Knights now draw their strength from the Sunwell instead of from a prisoner.",
    "Before that, when Liadrin came to Shattrath to beg forgiveness for M'uru's imprisonment, the naaru A'dal told her that Velen had foreseen M'uru's captivity, and that M'uru had willingly accepted its role, knowing it would lead the blood elves to redemption. Liadrin renounced Kael'thas and her knights joined the fight against him."
  ]]
];

window.CHAR_BIOS['yrel'] = [
  ["High Exarch of the Lightbound", [
    "Yrel lives on an alternate Draenor, a version of the orc world that Garrosh Hellscream reached by traveling back in time. Raised by her older sister Samaara, she was a quiet acolyte at the Temple of Karabor and a promising healer. The Prophet Velen of that world took her as his pupil.",
    "When the orc clans united as the Iron Horde, she was captured and enslaved. Azeroth's expedition freed her in Tanaan Jungle. The war hardened her fast. Samaara died at the hands of the Shadowmoon clan, and Velen sacrificed himself to stop Ner'zhul's Dark Star, passing his mark to her. Yrel led the defense of Karabor, helped Durotan drive his axe into the warlord Blackhand, joined the attack on Garrosh in Nagrand and won a seat on the Council of Exarchs. She fought Archimonde beside Khadgar at Hellfire Citadel.",
    "Afterward orcs and draenei lived together in peace for years. More naaru arrived, and with no demons left to fight, the draenei grew fixated on the Light. When Draenor began to wither, Yrel's Lightbound blamed the orcs. Guided by visions from a Light Mother, she set out to bring every orc into the Light, and many were converted by force. Grommash Hellscream's Mag'har resisted until a stalemate in Gorgrond. Yrel faced Grom and called him an old friend. He held off her forces so that his people, led by Overlord Geya'rah, could escape to Azeroth, and he died fighting. Yrel began as a gentle healer and became a crusader who forced her faith on others. As far as is known, she still leads the Lightbound on her Draenor."
  ]]
];
