window.EVENT_STORIES = window.EVENT_STORIES || {};

window.EVENT_STORIES['wars-6'] = [
  "The plague began far from Lordaeron. In Northrend, the Lich King needed a way to weaken the living kingdoms before the Burning Legion returned. He was the spirit of the orc shaman Ner'zhul, sealed in ice by the demon Kil'jaeden. He found a willing servant in Kel'Thuzad, a member of the Kirin Tor's ruling council in Dalaran who had secretly studied necromancy. When Archmage Antonidas threatened him with exile, Kel'Thuzad left the city, crossed the sea to Icecrown and offered his soul to the Lich King.",
  "Kel'Thuzad came home to build the Cult of the Damned. Over about three years he won over the poor and overworked laborers of northern Lordaeron, promising them equality and eternal life. His cultists hid plague cauldrons in their villages and tainted the grain stored at Andorhal, the region's main grain hub. People who ate the grain usually died within three days and rose as mindless undead under the Lich King's command. Kel'Thuzad named this growing army the Scourge. Above him stood the dreadlord Mal'Ganis, one of the demons the Legion had sent to watch over the Lich King.",
  "King Terenas Menethil II had other worries. Thrall's orcs had broken out of the internment camps, and a mysterious prophet urged the king to lead his people west across the sea. Terenas refused. He sent his son, Prince Arthas, and Uther the Lightbringer, leader of the paladins of the Silver Hand, to look into the sickness in the north. Dalaran sent Jaina Proudmoore, Antonidas's gifted apprentice and Arthas's former love, to help. Arthas and Jaina tracked Kel'Thuzad from the village of Brill to Andorhal. Before Arthas killed him, the necromancer named Mal'Ganis as his master and warned that his death would change little.",
  "At Hearthglen, Arthas learned what the plague truly did. Its victims rose again as undead, and his small force barely held the town against an army of the dead until Uther arrived with reinforcements. On the road north, the prophet appeared to Arthas as well and told him to go west. Arthas answered that his place was with his people. Jaina thought the stranger might be right, but Arthas would not listen.",
  "At Stratholme they found the grain already handed out to the townsfolk. Arthas knew the citizens would soon turn, so he ordered the city purged. Uther refused, saying he would not obey such an order even if Arthas were already king. Arthas called this treason, relieved Uther of command and suspended the paladins from service. Uther left, and Jaina followed him. Arthas and the soldiers who stayed loyal, among them Captain Falric, went into the city and killed its people, racing Mal'Ganis, who was gathering the dead for the Scourge. When Arthas demanded a final battle, the dreadlord slipped away and dared the prince to follow him to Northrend.",
  "Stratholme burned, and the Scourge later made the ruined city a stronghold. Some former paladins, later called Deathlords, carried out similar purges in other towns of Lordaeron. When Jaina and Uther returned to bury the dead, the prophet found Jaina and told her she must lead survivors west, and she later did. Arthas gathered his troops at Lordaeron's harbor and sailed for Northrend, set on killing Mal'Ganis whatever it cost. He had broken with the two people closest to him, and he left his kingdom just as it needed him most."
];

window.EVENT_STORIES['wars-7'] = [
  "Arthas reached Northrend about a month after leaving Stratholme. On the coast his men ran into an old friend, Muradin Bronzebeard, brother of the dwarf king Magni and once Arthas's sword teacher. Muradin's expedition had come looking for a legendary runeblade called Frostmourne and had been cut off by the undead. The dreadlords had secretly planted the clues that led the dwarves there. The Lich King had sent Frostmourne out from the Frozen Throne to wait for a champion, and Arthas was the one he wanted.",
  "When orders came from Terenas and Uther calling the expedition home, Arthas refused to leave. He had local mercenaries burn his own ships, then blamed them for it, and his men killed them. With no way home, his soldiers had to follow him. Arthas and Muradin found Frostmourne sealed in ice in a cavern watched over by a mysterious guardian. Muradin read the inscription and warned that the blade was cursed. Arthas swore he would pay any price to save his people. The ice shattered, a shard struck Muradin down, and Arthas left him for dead. The dwarf survived but lost his memory for years.",
  "Frostmourne took Arthas's own soul first. With the blade he crushed Mal'Ganis's army. The dreadlord told him the new voice in his head belonged to the Lich King, and Arthas replied that the voice wanted Mal'Ganis dead. He killed the demon on the spot. The Lich King had used the prince to rid himself of one of his demon jailers. Mal'Ganis's spirit actually escaped and he returned years later, but Arthas believed him gone. Arthas then wandered into the frozen wastes, killed nearly all his own soldiers and raised them as undead. He returned as the Lich King's first death knight.",
  "Months later, Lordaeron's capital celebrated the prince's return. Arthas knelt before his father's throne, told Terenas he no longer needed to bear the weight of his crown, and drove Frostmourne through his heart. Then he opened the city to the Scourge and the Cult of the Damned. On the Lich King's orders he recovered Kel'Thuzad's remains at Andorhal. He needed an urn guarded by the Silver Hand to carry them, and Uther defended it. Uther nearly won their duel, but the Lich King lent Arthas new strength and he killed his old teacher. The urn held Terenas's ashes. Arthas threw them out and put Kel'Thuzad's remains inside.",
  "Only the Sunwell, the fount of magic in the high elf kingdom of Quel'Thalas, had the power to raise Kel'Thuzad. Ranger-General Sylvanas Windrunner fought Arthas from the first elfgate almost to the walls of Silvermoon, and a traitor mage, Dar'Khan Drathir, helped the Scourge break through. Arthas struck Sylvanas down and refused her the peace of death, turning her into a banshee bound to his will. He sacked Silvermoon, killed King Anasterian Sunstrider in single combat and placed Kel'Thuzad's remains in the Sunwell. The necromancer rose as a lich, and the Sunwell was corrupted. Roughly nine in ten high elves died.",
  "Kel'Thuzad then explained the full plan. The Scourge marched on Dalaran, killed Archmage Antonidas and seized the spellbook of Medivh. With it, Kel'Thuzad summoned the demon lord Archimonde, who destroyed Dalaran and took command of the invasion. Archimonde declared that the Lich King was of no further use, yet Kel'Thuzad told Arthas that all was going as their master foresaw. Lordaeron, the greatest human kingdom, was gone, and its dead filled the Scourge's ranks."
];

window.EVENT_STORIES['wars-8'] = [
  "While the plague spread, Thrall was gathering the freed orcs of Lordaeron into a new Horde. In a vision, a mysterious prophet told him that the orcs' only hope lay across the sea in Kalimdor. Thrall rescued his friend Grommash Hellscream, chieftain of the Warsong clan, from human captors, and Grom suggested they steal Alliance ships for the voyage. The Horde seized a fleet and sailed west.",
  "A storm near the Maelstrom, a great whirlpool, scattered the fleet. Thrall's ships took shelter at an island home to the Darkspear trolls, whose people were under attack from a human outpost. The orcs helped the trolls destroy it, then faced murlocs who served a sea witch. The murlocs sacrificed the Darkspear leader Sen'jin before Thrall could save him. Dying, Sen'jin shared a vision that Thrall would lead the Darkspear to greatness, and Thrall offered the trolls a place in the Horde. They escaped together as a volcano erupted and the island sank.",
  "The ships reached Kalimdor far apart. Thrall gathered what orcs and trolls he could find and came upon tauren under attack by centaurs. Cairne Bloodhoof, chieftain of the Bloodhoof tribe, welcomed the help. Thrall's warriors defended Cairne's village and escorted his people to the grasslands of Mulgore. In return Cairne told Thrall of an oracle on Stonetalon Peak who might guide him. Meanwhile Grom's Warsong clan had landed separately and kept attacking Jaina Proudmoore's human refugees, even against Thrall's orders. Thrall sent him into the forests of Ashenvale to cut timber for a settlement, hoping hard work would cool his bloodlust.",
  "The logging angered the night elves, who had guarded those forests for thousands of years. Their Sentinels attacked, and then Cenarius came in person. He was a demigod of the forest, and he saw the orcs as demon-spawn who deserved only death. A troll witch doctor sensed power in a nearby fountain. The pit lord Mannoroth had filled it with his own blood, the same blood that had bound the orcs to the Legion long before. Grom drank, and his warriors drank with him. Strengthened and maddened, the Warsong killed Cenarius. Then Mannoroth appeared and claimed them as his slaves once more.",
  "At Stonetalon Peak, Thrall and Jaina came face to face. The oracle revealed himself as the prophet who had sent them both west and told them they must fight together or be destroyed. Jaina prepared a soul gem. Thrall, with Cairne's tauren and Jaina's forces, fought through the corrupted Warsong while infernals fell burning from the sky. Grom taunted Thrall that the old chieftains had chosen to drink the demon's blood, knowing it would enslave them. Thrall caught Grom's spirit in the gem and carried it to a ritual circle, where orc shamans and human mages purged the demonic taint together.",
  "Free again, Grom went with Thrall to hunt Mannoroth in a canyon in Ashenvale. The pit lord knocked Thrall aside, but Grom drove his axe Gorehowl through Mannoroth's armor and into his chest. The dying demon exploded in fire, and Grom took the full blast. As he lay dying, the red glow faded from his eyes. Thrall told him he had freed every orc, because the blood curse lifted from all who had drunk it. The place is now called Demon Fall Canyon. The deaths of Cenarius and Mannoroth opened the way for Archimonde to march into Kalimdor, and the grieving night elves now counted the orcs among their enemies."
];

window.EVENT_STORIES['wars-9'] = [
  "With Cenarius and Mannoroth dead, Archimonde led the Legion and its undead Scourge into Kalimdor from the coast of Azshara. His target was Mount Hyjal, where the World Tree Nordrassil grew over the second Well of Eternity, a lake of raw magic. With that power he hoped to finish the conquest of Azeroth and bring forth the Legion's master, Sargeras. The night elves had fought this enemy ten thousand years before. Their leader, High Priestess Tyrande Whisperwind, blamed the human and orc newcomers for bringing the demons back.",
  "Tyrande woke her old love, the archdruid Malfurion Stormrage, from his ages-long sleep, and he roused the druids who had slept beside him. Tyrande also freed Malfurion's twin brother Illidan from his ten-thousand-year imprisonment, hoping his power would help. In Felwood, Arthas tempted Illidan to take the Skull of Gul'dan, a demonic artifact. Arthas was secretly working against the Legion for the Lich King. Illidan absorbed the skull's power and used it to kill the dreadlord Tichondrius, but it turned him half-demon, and Malfurion banished him.",
  "The prophet then called Thrall, Jaina, Tyrande and Malfurion to a grove at the foot of the mountain. He revealed that he was Medivh, the last Guardian, whose corruption had once helped open the Dark Portal. He had come back to set right his crimes, and he told the four leaders that only together could they survive. The night elves agreed despite their distrust. Malfurion proposed a plan. The dragon Aspects had placed powerful enchantments in Nordrassil long ago, and he would ignite them all at once when Archimonde reached the tree. The armies had to buy him time.",
  "Three bases blocked the path up the mountain. Jaina's camp of Lordaeron refugees, dwarves and high elves met the Legion first and fell after a stubborn defense. Jaina faced Archimonde himself and teleported away. Thrall's base came next, held by orcs, tauren and Darkspear trolls. Thrall wounded Archimonde with a bolt of lightning before Jaina pulled him to safety. In the fighting, an orc named Broxigar was the only survivor of a band ordered to hold a vital pass. Each fallen base let the undead army grow. At last the night elves near the summit gave way as well.",
  "As Archimonde climbed the World Tree, a vast host of wisps, glowing night elf spirits, gathered in its branches. Malfurion blew the Horn of Cenarius. The wisps poured their energy into Nordrassil as one, its enchantments ignited, and the blast destroyed Archimonde along with much of his army and the forest around the tree. The allies fell on the demons and undead who were left. Arthas, who had stayed in Kalimdor, barely escaped with what Scourge he could rally. Medivh watched the celebrations from afar. Satisfied that the world no longer needed a Guardian, he vanished.",
  "The victory ended the Third War and dealt the Legion its worst defeat since the War of the Ancients. The cost fell hardest on the night elves. Nordrassil survived but was badly weakened, and with its blessing spent, they lost their immortality. For years afterward, the memory of humans, orcs and night elves fighting side by side shaped how the mortal races dealt with one another. The Lich King, meanwhile, was free of his demon masters."
];

window.EVENT_STORIES['wars-10'] = [
  "After Hyjal, the survivors had to build new lives far from home. Thrall led his orcs to a dry, rocky land on Kalimdor's eastern coast, drove off the Razormane quilboar who lived there, and named the country Durotar after his father. Its capital became Orgrimmar, named for Orgrim Doomhammer. Cairne's tauren settled in Mulgore, and the Darkspear trolls made their home on the Echo Isles off Durotar's coast.",
  "Jaina gathered the humans, dwarves and high elves of her expedition on the coast of Dustwallow Marsh, to the south, and built the island citadel of Theramore to shelter them. She and Thrall stayed in touch. Their uneasy wartime truce grew into a promise that each would respect the other's land and avoid acts of aggression. For a time the two peoples lived as wary neighbors.",
  "The peace did not last long. Rexxar, a half-ogre beastmaster of the Mok'Nathal clan who had left the old Horde in disgust, came to Orgrimmar carrying a dying scout's message and stayed to earn his keep. With the troll shadow hunter Rokhan and the wandering pandaren brewmaster Chen Stormstout, he found human soldiers gathering on Durotar's coast. They razed an orc outpost and attacked the Darkspear on the Echo Isles. Thrall was invited to a peace summit with Jaina. Rexxar went in his place, suspecting a trap, and found an ambush waiting.",
  "Jaina knew nothing of these attacks. Her father, Lord Admiral Daelin Proudmoore of Kul Tiras, had sailed to Kalimdor with much of his fleet to find her and crush the Horde before it could take root. Daelin had lost his eldest son, Derek, to the Horde in the Second War, and he believed orcs could never change. He seized the fort of Northwatch Hold, built new bases and then took control of Theramore itself, where he ordered Rexxar arrested on sight. Rexxar escaped and went looking for allies. He rescued Cairne's son Baine from centaurs, which brought the grieving chieftain and his tauren back to Thrall's side, and he won command of the Stonemaul ogres by defeating their warlord.",
  "Thrall named Rexxar Champion of the Horde, and the gathered army razed Daelin's mainland stronghold. Daelin fell back to Theramore behind a naval blockade. Jaina then teleported into Thrall's camp. She understood that her father would never stop, and she told Thrall where to find goblin ships that could break the blockade. She asked only that he spare as many of her people as he could. The Horde stormed the island. Thrall tried to tell Daelin that this Horde was different from the one he had fought. Daelin refused to believe it, and Rexxar and his companions killed him in battle.",
  "Jaina knelt over her father's body, and Rexxar told her to remember him as a proud warrior. The Horde then withdrew and left Theramore in peace. Kul Tiras held Daelin's death against Jaina for many years. Its people blamed her for betraying her family and cut themselves off from the Alliance, and Daelin's widow Katherine became Lord Admiral. The other Alliance leaders, busy with the plague in Lordaeron, would not take up his cause. Durotar and Theramore kept their fragile peace, and the friendship between Thrall and Jaina became the main bridge between Horde and Alliance in the years before World of Warcraft."
];

window.EVENT_STORIES['wars-11'] = [
  "After Hyjal, the demon lord Kil'jaeden found Illidan Stormrage and offered him one last chance. The Lich King had grown too strong to control, and Kil'jaeden wanted the Frozen Throne destroyed, promising Illidan great power in return. Illidan called on the naga, serpent-like descendants of the ancient Highborne elves, and Lady Vashj pledged her people to him. Maiev Shadowsong, the Warden who had been his jailer for ten thousand years, chased him across the sea.",
  "On the Broken Isles, Illidan took the Eye of Sargeras from the Tomb of Sargeras and brought the tomb down on Maiev's Watchers. He carried the artifact to Lordaeron and, near the ruins of Dalaran, began a spell that tore at the ice of Northrend. Malfurion and Maiev stopped him. Maiev had told Malfurion that Tyrande was dead, but Prince Kael'thas Sunstrider revealed that she had been swept away by a river. Illidan helped his brother rescue her, and Malfurion let him go. Illidan fled through a rift to Outland, the shattered remains of the orc homeworld Draenor. His spell had failed, yet the Lich King's power began to fade after the attack.",
  "Kael'thas led the surviving blood elves in Lordaeron under the human Grand Marshal Garithos, who despised other races. When Kael accepted help from Vashj's naga, Garithos jailed the elves for treason. Vashj freed them and led them through the portal Archimonde had used, to Outland. There they rescued Illidan from Maiev, and Kael pledged his people to Illidan, who promised to feed their hunger for magic. With Akama, a leader of the broken draenei, they took the Black Temple from the pit lord Magtheridon. Kil'jaeden appeared and gave Illidan one more chance to destroy the Lich King.",
  "In Lordaeron, the Lich King's weakness let many undead wake from his control, and Sylvanas Windrunner was among them. After an ambush on Arthas failed, she gathered the free-willed undead, defeated the dreadlord Varimathras and made him her servant, then destroyed his brothers Detheroc and Balnazzar. She used Garithos and his soldiers in the fight, then had them killed. She named her people the Forsaken and claimed the ruins of the capital.",
  "Arthas, summoned home by the Lich King, sailed for Northrend. Kael'thas's blood elves ambushed him when he landed, and Anub'arak, the undead former king of the spider kingdom Azjol-Nerub, came to his aid. Anub'arak led Arthas through the ruined tunnels beneath the land, a shortcut to Icecrown. At the glacier, Arthas battled Illidan's naga and blood elves for control of four obelisks, drove off Kael'thas and opened the way to the Frozen Throne. Illidan met him there in single combat, and Arthas cut him down with Frostmourne. Arthas left him in the snow, and Vashj and Kael carried Illidan back to Outland.",
  "Arthas climbed the glacier alone while the remembered voices of Muradin, Uther and Jaina called after him. At the top, Ner'zhul asked him to return the blade and set him free. Arthas shattered the ice that held the Lich King's armor and put on the Helm of Domination, and the two spirits merged into a single Lich King. Over the next years, Arthas's will slowly overpowered Ner'zhul's. The new Lich King sat silent on the Frozen Throne, gathering his strength, until his war with the living resumed in Wrath of the Lich King."
];
