window.EVENT_STORIES = window.EVENT_STORIES || {};

window.EVENT_STORIES['wars-0'] = [
  "The Dark Portal was built by two very different minds. Medivh was the Guardian of Tirisfal, the mage meant to shield Azeroth from the Burning Legion, and a hero in Stormwind since he had helped his boyhood friends Llane Wrynn and Anduin Lothar break the Gurubashi trolls. But the spirit of Sargeras, the Legion's dark titan master, had hidden inside him since before his birth. Under that influence Medivh became sure that Azeroth needed an army, and he found one on Draenor. He struck a deal with the orc warlock Gul'dan. If Gul'dan brought the Horde to Azeroth, Medivh would reveal the location of the Tomb of Sargeras, a prize Gul'dan wanted badly.",
  "Following Medivh's instructions, Gul'dan and Warchief Blackhand had the Horde raise a huge stone gate on a meeting of ley lines in Hellfire Peninsula. When it was done, warlocks murdered the stonemasons who had built it to prime its final seal. At the ritual, Gul'dan drained the life from almost every draenei prisoner the Horde still held, and that burst of power bridged the gap between worlds. On the other side, Medivh used his Guardian's strength to rip open the rift in the Black Morass, a swamp on Stormwind's southern edge. His mother Aegwynn, the Guardian before him, felt the fel magic in it and confronted him at his tower of Karazhan, but he drove her away. Blackhand sent scouts of the Bleeding Hollow and Black Tooth Grin clans through to make camp and frame the Azeroth side in stone.",
  "At first Stormwind heard only rumors of monsters in the swamp. Some said they were vengeful spirits, others trolls with a new kind of power. King Llane sent Lothar with a small band of knights to find out. Lothar won several bloody skirmishes, but every orc he killed seemed to be replaced by two more, and he had to pull back without ever finding the portal. He warned the king that the invaders were being reinforced from somewhere. Llane named him King's Champion, the highest military rank in the kingdom, and Stormwind prepared for war.",
  "Blackhand sent raiding parties deep into the kingdom to spread panic. Villages in Brightwood, Westfall and the southern Redridge Mountains burned, and by the time patrols arrived the raiders were gone. Lothar studied where they struck and set ambushes on their routes home, and small groups of knights sometimes destroyed whole raiding parties. In the jungles of Stranglethorn Vale, the Gurubashi trolls lured Kilrogg Deadeye's Bleeding Hollow clan deeper and cut them down until Blackhand called them back. Gul'dan also banished the Frostwolf clan, whose chieftain Durotan had openly questioned him, and the Frostwolves slipped away north toward the Alterac Mountains.",
  "Llane begged the other human kingdoms for help, but few believed his tales of green-skinned invaders. In Lordaeron, the black dragon Deathwing, disguised as a Stormwind noble, mocked the reports as a peasant revolt, and no help came. Meanwhile Medivh played the reluctant hero. Khadgar, a young mage sent by Dalaran's Kirin Tor, had become his apprentice. When Lothar met them in the Black Morass and urged his old friend to fight, Medivh claimed he feared his own power, buying the Horde more time. Lothar quietly asked Khadgar to look after his master. Gul'dan sent Garona, a half-orc who served as his spy and interpreter, to watch the Guardian, and at Karazhan she and Khadgar became wary friends. Together they would uncover Medivh's secret."
];

window.EVENT_STORIES['wars-1'] = [
  "About a year into the war, far from the fighting, Durotan's mate Draka gave birth to a son in the Alterac Mountains. The baby's skin was green, like that of orcs who had used fel magic, and the sight pushed Durotan to act. Through the shaman Drek'Thar he arranged a secret meeting with his old friend Orgrim Doomhammer, Blackhand's second-in-command, at the edge of Loch Modan. Durotan told Orgrim what he suspected about Gul'dan and his hidden Shadow Council of warlocks. Orgrim sent guards to see the family home, but they were loyal to the Shadow Council. They killed Durotan and Draka and left the baby in the cold, where the human officer Aedelas Blackmoore found him. When Orgrim learned the truth, he kept quiet and waited for a chance at revenge.",
  "Three years after the portal opened, the raids had wrecked Stormwind's farms and trade, and the capital was running short of food. Blackhand marched north. Near Lakeshire in the Redridge Mountains, Lothar's knights ambushed his raiders and nearly killed him, until two Shadow Council warlocks drove Lothar off with fel fire. Blackhand executed them anyway for missing the ambush. Then the Horde surrounded Stormwind City, and Kilrogg Deadeye and the two-headed ogre Cho'gall led the assault. Just as the walls were about to fall, Lothar's knights, who had slipped around the Horde by sea, charged its rear while the city's defenders poured out of the gates. The Horde fled. Lothar had been warned of the attack by Khadgar, who had learned the plans from Garona.",
  "Khadgar and Garona then cast a spell to see the past and watched a figure calling himself the Guardian give orders to Gul'dan. It was Medivh. King Llane refused to believe it, but Lothar did. Before dawn he flew with Khadgar, Garona and a few soldiers to Karazhan on gryphons. In the depths of the tower, Garona saw a vision of herself killing Llane. Medivh admitted that Sargeras lived within him, and his magic turned Khadgar into an old man. As Lothar held the Guardian's attention, Khadgar drove a sword into Medivh's heart, and Lothar cut off his head. At that moment Gul'dan was inside Medivh's mind, hunting for the location of the tomb, and the death threw him into a coma. The blast of Medivh's death scorched the land around Karazhan into Deadwind Pass and darkened Brightwood into Duskwood.",
  "With Gul'dan helpless, Orgrim challenged Blackhand to a mak'gora, a duel to the death, calling him a traitor who had sold the orcs to dark powers. After hours of fighting, Orgrim crushed Blackhand's skull with his family's hammer, the Doomhammer. As the new Warchief he banned fel magic and led the Horde back to Stormwind. During the second siege, the old commands Gul'dan had planted in Garona's mind took hold of her. Weeping, she killed King Llane in his own keep, and his young son Varian saw it happen. Stormwind City burned.",
  "Lothar declared the war lost. With the remains of the army, Prince Varian, Khadgar and as many civilians as he could gather, he sailed north to Lordaeron, burning the ships he left behind so the orcs could not follow. Orgrim captured Garona and had her tortured until she revealed the Shadow Council's hideout in Blackrock Spire. His warriors slaughtered most of the warlocks there, though Cho'gall talked his way into Orgrim's service. The 2016 Warcraft film tells this story quite differently. This account follows the games and Blizzard's Warcraft Chronicle."
];

window.EVENT_STORIES['wars-2'] = [
  "In Lordaeron, King Terenas Menethil II heard Lothar's warning and called the human rulers to the Council of Seven Nations. Genn Greymane of Gilneas and Aiden Perenolde of Alterac resisted until Turalyon, a young priest, stood beside the orphaned Prince Varian and begged the kings not to let pride doom them as Stormwind had been doomed. The council voted to form the Alliance of Lordaeron. Lothar became Supreme Commander, partly because he came from no northern kingdom and partly because he was the last heir of Thoradin, the ancient founder of human Arathor. Archbishop Alonsus Faol founded the Knights of the Silver Hand, warrior-priests called paladins, and Lothar made Turalyon and Uther his lieutenants. Lothar also called on an old oath the high elves had sworn to Thoradin's line. King Anasterian Sunstrider sent only a token force, but the ranger Alleria Windrunner came south with her own band.",
  "The Horde was rearming too. Gul'dan woke from his coma and bought his life by offering Orgrim new warriors. He put the spirits of slain Shadow Council warlocks into the corpses of human knights, creating death knights. The first was Teron Gorefiend. The Horde overran the dwarven lands of Khaz Modan, though it could not take Ironforge or Gnomeregan. Guided in secret by Deathwing, the Dragonmaw clan used an ancient artifact called the Demon Soul to capture Alexstrasza, Aspect of the red dragonflight. They chained her deep in the old dwarf fortress of Grim Batol and forced her children to serve as war mounts. The forest trolls of Zul'jin's Amani tribe joined after the Horde freed him from a human prison.",
  "Red dragons drove off the Kul Tiras fleet so the Horde could land in Hillsbrad, where paladins first faced death knights. Orgrim then swung east through the Hinterlands, where the gryphon-riding Wildhammer dwarves joined the Alliance, and into Quel'Thalas. Dragon fire burned much of Eversong Forest. Anasterian committed his full army, and his mages raised a shield from the Sunwell around Silvermoon that the Horde could not break. Orgrim turned toward Lordaeron's Capital City. Perenolde betrayed the Alliance and let the Horde through Alterac's passes, and Terenas took his place on the battlements as siege engines pounded the walls.",
  "Then Gul'dan deserted, taking his Stormreaver clan and Cho'gall's Twilight's Hammer to raise the Tomb of Sargeras from the sea. Short of troops, with Turalyon's army arriving, Orgrim had to retreat. Demons inside the tomb tore Gul'dan apart, and the Black Tooth Grin clan, sent by Orgrim, cut down most of his followers. The Alliance freed Khaz Modan, and the dwarves and gnomes joined it. At Blackrock Spire, Orgrim cut his way to Lothar, shattered his sword and killed him. Turalyon blazed with holy light, knocked Orgrim senseless with Lothar's broken sword and rallied the army to break the Horde. Survivors fled through the Dark Portal, and Khadgar and his fellow mages destroyed it behind them.",
  "Victory left hard questions. Gilneas and Stromgarde wanted the captured orcs executed, but Terenas argued for mercy, and the orcs were locked in internment camps that Lordaeron paid for with a new tax. Anasterian later left the Alliance, saying it had abandoned Quel'Thalas and that his debt to Thoradin's line was paid. The Dragonmaw stayed hidden in Grim Batol with their captive queen until a band led by the mage Rhonin freed her years later. A rift still lingered where the portal had stood, and Khadgar built Nethergarde Keep to watch it."
];

window.EVENT_STORIES['wars-3'] = [
  "On Draenor, the old shaman Ner'zhul had spent the wars as a powerless figurehead. Gul'dan's Shadow Council had taken over his clan and left him behind, and the blast that destroyed the Dark Portal wounded him badly. As his dying world sank into clan feuds, the death knight Teron Gorefiend came to him with a plan. The orcs would open new portals and escape to fresh worlds to conquer. Ner'zhul, now haunted by visions of death and wearing a painted skull on his face, agreed to lead the Horde again. His spell would need three artifacts from Azeroth: the Book of Medivh, the Jeweled Scepter of Sargeras and the Eye of Dalaran.",
  "Using the Skull of Gul'dan, the remains of his old apprentice, Ner'zhul and the death knights reopened the portal. Grom Hellscream's Warsong clan held the gate while Gorefiend's raiders hunted the artifacts. Deathwing helped them find the artifacts in exchange for carrying his eggs to Draenor. At Nethergarde, Khadgar and Turalyon held the line until a captured death knight confessed that Ner'zhul had no interest in Azeroth at all. He wanted doors to other worlds. Turalyon decided to end the Horde on its home soil. Calling his army the Sons of Lothar, he led them through the portal with Khadgar, Alleria Windrunner, the Stromgarde warrior Danath Trollbane and Kurdran Wildhammer of the gryphon riders. Turalyon and Alleria, by now lovers, left their infant son Arator in the care of her sister Vereesa.",
  "The expedition built a fort called Honor Hold in Hellfire Peninsula and stormed Hellfire Citadel, but Ner'zhul had already marched south. Turalyon split his army. He, Khadgar and Alleria went north after the Skull of Gul'dan, which Deathwing had taken. They made a pact with Gruul, a gronn giant at war with the black dragons, smashed Deathwing's eggs and wounded the dragon until he dropped the skull. Danath and Kurdran chased Ner'zhul south through the tombs of Auchindoun to the Black Temple.",
  "The two halves reunited outside the temple too late. Turalyon fought his way through and struck Gorefiend down, but the death knight's spirit escaped. Ner'zhul opened a series of rifts in the sky, abandoned the Horde he had promised to save and fled through the largest one. The energy of his spell tore Draenor's ley lines apart, and the planet began to break up in quakes and eruptions. Turalyon and Khadgar saw that the backlash could pour through the Dark Portal into Azeroth, so the portal had to be destroyed from the Draenor side. As desperate orcs fought to escape through it, Khadgar and his mages used the Skull of Gul'dan to blow its stone frame apart. Some orcs got through first, among them Grom and his Warsong, who went into hiding in the forests of Lordaeron.",
  "With nowhere else to go, the Sons of Lothar ran into an open rift. Khadgar, Danath, Kurdran and many soldiers came out on the broken remains of Draenor, now called Outland, a shattered land drifting in the Twisting Nether. They held on at Honor Hold for many years. Turalyon and Alleria were swept elsewhere, into the Twisting Nether, where the Army of the Light found them. They spent centuries of their own time fighting the Legion and did not reappear until the Legion campaign on Argus. On Azeroth, the expedition was presumed dead, and statues of its leaders were raised at the gates of Stormwind."
];

window.EVENT_STORIES['wars-4'] = [
  "Ner'zhul stepped through his rift expecting a new world. Instead, Kil'jaeden was waiting for him in the Twisting Nether. The demon lord had a score to settle. Years before, Ner'zhul had discovered that the spirit guiding the orcs to war was a demon in disguise and had tried to undo his part in it. Now Kil'jaeden destroyed Ner'zhul's body piece by piece while keeping his spirit awake and aware. When Ner'zhul begged for death, the demon offered him a choice. He could suffer forever, or he could rule an army of the dead for the Legion. Ner'zhul chose to serve.",
  "Kil'jaeden did not trust him, so he gave him no body. He sealed Ner'zhul's spirit inside a block of diamond-hard ice from the far reaches of the Nether. Warped by the demon's power, Ner'zhul's mind expanded until he became a spectral being of enormous psychic strength. This was the Lich King. Dreadlords bound his spirit to a suit of armor crowned by the Helm of Domination and to a runeblade called Frostmourne. Much later, the Shadowlands expansion revealed that both had been crafted by the Runecarver for the Jailer, a power of the realms of death, before they came into the Legion's hands. The warlocks and death knights who followed Ner'zhul through the rift were remade as the first liches, undead sorcerers bound to his will. Kil'jaeden promised him freedom and a new body if he succeeded.",
  "The Lich King's task was to succeed where the quarrelsome orcs had failed. He would spread a plague of undeath, raise the fallen as an army without fear or feuds, and leave Azeroth too weak to resist the Legion's next invasion. Kil'jaeden hurled the icy prison across the sky. It struck the frozen continent of Northrend and buried itself in the Icecrown Glacier, and the crystal, scarred by its fall, took the shape of a throne. The Frozen Throne became Ner'zhul's prison and seat. Dreadlords led by Tichondrius stayed to guard him and began the fortifications that grew into Icecrown Citadel.",
  "Ner'zhul learned his powers quickly. His plague and his mind control took the ice trolls, the wendigo, the vrykul and the humans of Northrend, and every soul he claimed made him stronger. The nerubians, spider-like people of the underground empire of Azjol-Nerub, were immune to both. Their king Anub'arak fought him for years in what became known as the War of the Spider. The Lich King finally ground them down, since their bodies could still be raised by necromancy even if the plague could not touch them. He raised Anub'arak as an undead crypt lord to lead the attack on his own people. Impressed by their resistance, Ner'zhul adopted nerubian architecture for his own buildings.",
  "With Northrend under his control, he reached out across the sea for clever, ambitious servants. Kel'Thuzad, a member of the Kirin Tor of Dalaran, answered, travelled to Icecrown and founded the Cult of the Damned to worship the Lich King and prepare the plague for Lordaeron. Ner'zhul never forgot what Kil'jaeden had done to him. He secretly looked for a way out of his prison. He talked his dreadlord jailers into letting him cast Frostmourne out of the Frozen Throne, and the sword waited in the ice for a living champion who could carry his will into the world. That champion would be Prince Arthas Menethil."
];

window.EVENT_STORIES['wars-5'] = [
  "After the Second War, thousands of captured orcs filled internment camps across southern Lordaeron. The command passed to Aedelas Blackmoore, a hard-drinking veteran who ran the system from his fortress of Durnholde Keep in the Hillsbrad Foothills. Over the years the prisoners sank into a strange lethargy. Fights and escapes stopped, and guards grew lazy. Archmage Antonidas of Dalaran suspected the orcs were suffering withdrawal from the demonic magic that had once fueled their rage, and that only a spiritual cure would help them. A few orcs stayed free. Grom Hellscream's Warsong clan hid in the forests and raided for food, and Orgrim Doomhammer, who had escaped from captivity in Lordaeron's capital, lived as a hermit in the wilds.",
  "Blackmoore had raised Durotan's orphaned son as his property and named him Thrall, a word for slave. He trained him as a gladiator and also had him taught to read and to think like a strategist. He secretly meant to make Thrall a general who would lead an army of camp orcs against the Alliance and hand Blackmoore the spoils. Blackmoore beat him often. The one kindness in Thrall's life was Taretha Foxton, daughter of Blackmoore's secretary, whose mother had nursed him as a baby. She passed him letters hidden in books.",
  "When Thrall was a young man, Taretha set a diversion that let him slip out of Durnholde. He found the camps full of listless orcs who barely cared they were prisoners. An old prisoner told him of Grom, the one chieftain still fighting, and Thrall sought him out. Grom taught him the orc tongue and recognized the Frostwolf mark on his old swaddling cloth. Thrall travelled to the Alterac Mountains, where the exiled Frostwolves took him in. Their elder shaman, Drek'Thar, told him who his father was and guided him through his initiation. The elemental spirits accepted Thrall, making him the first new shaman of his generation and a sign that the spirits had forgiven the orcs.",
  "A cloaked stranger came to the Frostwolf camp and mocked the idea of fighting the humans. Thrall challenged him and won. The stranger was Orgrim Doomhammer, who had come to test Durotan's son. Orgrim made Thrall his second-in-command. Thrall slipped into the camps as a prisoner and used his shamanism to wake the orcs from their stupor, and the camps fell one after another. At the fifth camp, knights from Durnholde lay in wait. A charging knight's lance pierced Orgrim's back. With his last breath he named Thrall Warchief and gave him his black armor and the Doomhammer. Thrall later had the pierced back plate restored but never replaced, and the Frostwolf symbol was added to the hammer. That camp is now the Horde outpost of Hammerfall in the Arathi Highlands.",
  "Thrall marched on Durnholde to end the camps for good. Taretha refused to flee, and when Thrall offered Blackmoore a peaceful surrender, the drunken lord threw her severed head into the courtyard. The Horde stormed the keep, and Thrall killed Blackmoore. He let the surviving humans walk away with a message for the Alliance. Free the orcs and give them land, and they would live in peace. Then he called on the spirit of earth to bring Durnholde down. The cost of the camps, and now their failure, strained the Alliance further, and Gilneas and Stromgarde left it around this time. Thrall now led a new Horde, free of the old warlocks."
];
