window.EVENT_STORIES = window.EVENT_STORIES || {};

window.EVENT_STORIES['wow-0'] = [
  "World of Warcraft opens about four years after the Battle of Mount Hyjal, where orcs, humans and night elves stood together against the Burning Legion. That shared purpose has faded. Thrall's Horde has settled Durotar and taken in the tauren, the Darkspear trolls and the undead Forsaken. The Alliance gathers around Stormwind with the dwarves, gnomes and night elves. Neither side wants open war, yet clashes break out in places like Ashenvale, and old enemies rise while the two factions quarrel.",
  "Stormwind is rotting from within. King Varian Wrynn vanished on his way to peace talks at Theramore, seized by the Defias Brotherhood, a gang of unpaid stonemasons turned bandits. His young son Anduin was crowned, with Highlord Bolvar Fordragon ruling as regent. At Bolvar's side stands the noblewoman Lady Katrana Prestor, who is really the black dragon Onyxia, daughter of Deathwing. She clouds the minds of Stormwind's leaders and keeps its soldiers at home while orcs of the Blackrock clan raid the borderlands. Marshal Reginald Windsor uncovered her secret and exposed her in Stormwind Keep, and she killed him. Onyxia fled to her lair in Dustwallow Marsh, where she was finally slain, and her head was hung at Stormwind's gates. The comics tell the fuller tale. Onyxia's spell had split Varian into two men. The two halves found each other, merged again during the fight in her lair, and Varian killed the dragon himself.",
  "Blackrock Mountain holds two more great threats. Deep in its Molten Core lies Ragnaros the Firelord, an elemental lord the Dark Iron dwarves summoned centuries earlier while trying to win a war. He has enslaved them ever since. Above him, Onyxia's brother Nefarian, posing as the nobleman Lord Victor Nefarius, rules Blackrock Spire. He commands a new Dark Horde of orcs under Rend Blackhand, plots to crush Ragnaros, and breeds chromatic dragons from the blood of every dragonflight. With help from the water spirits of the Hydraxian Waterlords, heroes banished Ragnaros back to his realm, the Firelands. A Horde force stormed Blackwing Lair, killed Nefarian and carried his head to Orgrimmar.",
  "In the desert of Silithus, the Old God C'Thun has stirred beneath the city of Ahn'Qiraj. A thousand years earlier, night elves and dragons had walled its insect armies, the qiraji and the silithid, behind the Scarab Wall. Now the Twilight's Hammer cult serves C'Thun and the swarms grow restless again. The Alliance and Horde pooled supplies for a shared war effort. Heroes rebuilt the Scepter of the Shifting Sands, the key to the wall, with help from the bronze dragon Anachronos, and the gates were opened. Armies held off the swarm outside while champions fought through the temple, past the qiraji Twin Emperors, and killed C'Thun.",
  "The last threat came from the north. Kel'Thuzad, the necromancer Arthas had raised as a lich, commands Naxxramas for the Lich King. In a wave of attacks, lesser necropolises appeared over many lands, and the Scourge struck at Stormwind and the Undercity. The Argent Dawn, an order sworn to fight the undead, found a way past the citadel's wards. Heroes broke in and defeated Kel'Thuzad in his own hall. His defeat did not last. The Lich King would raise him again and bring his citadel to Northrend, while the next chapter opened in the south when demons poured through the Dark Portal."
];

window.EVENT_STORIES['wow-1'] = [
  "The Burning Crusade begins when the Burning Legion forces the Dark Portal open again. Doom Lord Kazzak in the Blasted Lands and Highlord Kruul on the far side worked a ritual on both ends of the gate, and demons flooded into Azeroth. With help from Nethergarde Keep and the Argent Dawn, the Alliance and Horde drove them back and then followed them through. On the other side lay Outland, the shattered remains of the orc homeworld Draenor.",
  "Outland belonged to Illidan Stormrage, who had fled there after losing to Arthas at Icecrown. From the Black Temple, once the draenei Temple of Karabor, he ruled with fel orcs bred from the blood of the captive pit lord Magtheridon, with Lady Vashj's naga, and with Kael'thas Sunstrider's blood elves. Illidan had not stopped fighting the Legion. He was training an army of demon hunters, the Illidari, and planning to strike the eredar homeworld Argus. The Legion knew it, and part of Kil'jaeden's plan was to lure Azeroth's armies into Outland so they and Illidan would wear each other down.",
  "The newcomers found allies in Shattrath City, where the naaru A'dal and the Sha'tar sheltered refugees and where Archmage Khadgar still served. Back home, Velen's draenei, whose ship the Exodar had crashed on Azeroth, joined the Alliance, and the blood elves of Quel'Thalas joined the Horde. Kael'thas himself had grown desperate to cure his people's hunger for magic, and Kil'jaeden won him over with promises of power. Kael seized the naaru fortress Tempest Keep in Netherstorm and sent the captured naaru M'uru to Silvermoon, where the Blood Knights forced the Light out of it. When former followers, the Scryers, revealed his pact with the Legion, the Horde declared war on its own prince. Heroes beat him in Tempest Keep, but he escaped.",
  "Illidan's own lieutenant turned on him. Akama, leader of the Ashtongue tribe of Broken draenei, freed Maiev Shadowsong, the Warden who had hunted Illidan for ten thousand years, and opened a way into the Black Temple. While the Aldor and Scryers attacked outside, champions fought their way to Illidan, and Maiev joined the final battle. Illidan died whispering Tyrande's name. Maiev took his body to the Vault of the Wardens, and Akama claimed the temple for his people.",
  "Kael'thas had survived. He returned to Quel'Thalas with felblood elves, took M'uru back from Silvermoon and fortified the Isle of Quel'Danas. His goal was to turn the Sunwell into a gateway for Kil'jaeden. Lady Liadrin, leader of the Blood Knights, saw the attack, renounced House Sunstrider and joined the Shattered Sun Offensive, a new union of Aldor and Scryers. Heroes killed Kael'thas in Magisters' Terrace, but Kil'jaeden had already begun to rise from the Sunwell. They fought him on the plateau, and Anveena Teague, the mortal avatar of the Sunwell's power, gave her life to weaken him. Kil'jaeden was driven back and the gateway closed.",
  "The Sunwell was left tainted. Velen came to pay respects to the fallen M'uru, sensed a spark of power left in its heart, and used it to cleanse the well. It now holds both arcane magic and the Holy Light. Kael'thas was the last of the Sunstrider line, so Regent Lord Lor'themar Theron was left to lead the blood elves. With the Legion's foothold broken, the Alliance and Horde turned north, where the Lich King was waking."
];

window.EVENT_STORIES['wow-2'] = [
  "After years of silence, the Lich King struck. Arthas sent his new death knights against Light's Hope Chapel in the Eastern Plaguelands, ready to sacrifice them all to draw out the paladin Tirion Fordring. The Light overwhelmed the undead. When Arthas came in person, Darion Mograine, son of the Ashbringer's first wielder, defied him long enough to hand Tirion the corrupted sword. Tirion cleansed it and drove Arthas off. Darion founded the Knights of the Ebon Blade, and Tirion joined the Argent Dawn and the Silver Hand as the Argent Crusade. The Alliance's Valiance Expedition under Bolvar Fordragon and the Horde's Warsong Offensive under Garrosh Hellscream sailed for Northrend.",
  "Both armies pushed inland and met before Angrathar the Wrathgate, the southern gate of Icecrown. Bolvar and the Horde commander Dranosh Saurfang fought side by side until Arthas came out to face them. He killed Saurfang and took his soul into Frostmourne. Then Grand Apothecary Putress of the Forsaken rained a new plague on the field, killing living and undead alike. Thousands died, Arthas barely escaped, and red dragons burned the plague away. Bolvar was believed dead, but the Scourge carried his burned body into Icecrown. Alexstrasza and her consort Korialstrasz knew his fate and kept silent.",
  "Putress had acted for the dreadlord Varimathras, who seized the Undercity in the same hour. Thrall, Sylvanas and Vol'jin retook the city, while Varian Wrynn, back on his throne, led the Alliance through the sewers after Putress. Both traitors died. Disgusted by the Forsaken's experiments on human bodies, Varian declared war on the Horde in the throne room. Only Jaina Proudmoore's magic, freezing both sides and teleporting the Alliance away, prevented a slaughter. From then on the factions skirmished across Northrend, and the Argent Crusade and the Ebon Blade led the push on Icecrown.",
  "Northrend held other dangers. Malygos, the blue Aspect of Magic, had gone mad and declared war on every mortal spellcaster. Alexstrasza's Wyrmrest Accord and the Kirin Tor, whose city of Dalaran now floated over Northrend, backed the heroes who killed him in his realm, the Eye of Eternity. In the Storm Peaks, the titan city of Ulduar proved to be the prison of the Old God Yogg-Saron, whose whispers had corrupted its keepers. With Brann Bronzebeard's help, heroes fought through the city and defeated it.",
  "Tirion believed only a small strike force could reach Arthas, so he held the Argent Tournament to choose his champions. Arthas answered by breaking the coliseum floor and dropping them into the tunnels of Anub'arak, the undead nerubian king, who was slain there. Tirion and Darion then led the Ashen Verdict into Icecrown Citadel. Champions fought past Saurfang's risen corpse and the frost wyrm Sindragosa to the Frozen Throne. Arthas froze Tirion in ice and killed the champions in a single blow, meaning to raise them as his own. Tirion broke free and shattered Frostmourne with the Ashbringer. The souls it released, among them King Terenas, restored the fallen heroes, and Arthas died with his father's spirit beside him.",
  "Terenas warned that the Scourge without a master would overrun the world. Tirion lifted the Helm of Domination to take the burden himself, but Bolvar, alive on the Frozen Throne and scarred beyond healing by dragonfire, asked for it instead. Crowned the new Lich King, he sealed himself in ice and told Tirion to say Bolvar had died with Arthas. The Scourge was held in check, but the bitterness between Varian and the Horde remained."
];

window.EVENT_STORIES['wow-3'] = [
  "Before Deathwing appeared, the world was already shaking. Elemental unrest struck across Azeroth, and Thrall decided he could do more good as a shaman than as warchief. He named Garrosh Hellscream, hero of the Northrend war, to lead the Horde in his absence and left to study the elements, later joining the Earthen Ring at the Maelstrom. In Ironforge, King Magni Bronzebeard tried an ancient earthen ritual to learn why the earth was in pain. It turned him into diamond, fused to the heart of the city.",
  "Garrosh ruled hard. Cairne Bloodhoof, the tauren high chieftain, challenged him to a mak'gora, a ritual duel. Without Garrosh's knowledge, the Grimtotem elder Magatha had poisoned his axe, and Cairne died. When Magatha tried to seize Thunder Bluff, Garrosh refused to back her, and Cairne's son Baine drove her out. The Darkspear trolls left Orgrimmar after Vol'jin openly threatened Garrosh. The worgen of Gilneas joined the Alliance, the goblins of Kezan joined the Horde, and the two factions fought openly from Ashenvale to Gilneas.",
  "Then Deathwing burst out of Deepholm, the elemental plane of earth, where he had healed for years while the Twilight's Hammer cult bolted plates of elementium onto his body. His return shattered the world. The Barrens split in two, Thousand Needles flooded, and Stormwind's gates were torn apart when he landed on them. He loosed his elemental allies on the world. Ragnaros attacked the World Tree Nordrassil on Mount Hyjal, Al'Akir's air elementals and the tol'vir of the Neferset tribe served him in Uldum, and the naga rose against the sea lord Neptulon.",
  "Heroes fought back on every front. In the Twilight Highlands they broke the cult's fortress, the Bastion of Twilight, and killed its two-headed ogre leader Cho'gall. Beneath Blackrock they again defeated Nefarian, whom the cult had raised from death. Malfurion Stormrage and the druids saved Hyjal, and heroes followed Ragnaros into the Firelands, where the Firelord died for good. Among his servants they found Fandral Staghelm, the former archdruid, who had turned to the flames in his madness and grief.",
  "Deathwing could not be beaten by force, because the Old Gods' power let him heal from any wound. Korialstrasz died early in the struggle, destroying a clutch of twisted twilight dragon eggs that the cult had corrupted beneath Wyrmrest Temple. The blue dragon Kalecgos became the new Aspect of Magic. The surviving Aspects needed the Dragon Soul, the artifact Deathwing had forged long ago and that had since been destroyed. The bronze Aspect Nozdormu sent heroes ten thousand years into the past to fetch it. Because no dragon could wield it, Thrall would use it for them.",
  "At Wyrmrest Temple, heroes held off Deathwing's forces while Thrall and the Aspects charged the Dragon Soul. Thrall struck Deathwing, who fled toward the Maelstrom. The Aspects and heroes chased him on the gunship Skyfire and tore the armor plates from his back. He fell into the sea and rose in a monstrous new form, and the Aspects poured their power through the Dragon Soul to destroy him. The effort spent the gifts the titans had given them. Alexstrasza declared the start of the Age of Mortals, when the younger races would guard Azeroth themselves."
];

window.EVENT_STORIES['wow-4'] = [
  "Mists of Pandaria starts with Garrosh's war at its worst. He wanted all of Kalimdor for the Horde. After taking the Alliance fort of Northwatch, his armies laid siege to Theramore, Jaina Proudmoore's city. Then a mana bomb, strengthened with the Focusing Iris stolen from the blue dragons, fell on the town from the air. Rhonin, leader of the Kirin Tor, drew the blast into Jaina's tower and pushed her through a portal to save her. He died with most of the city's defenders. Jaina, warped by grief and the bomb's energies, took his place at the head of the Kirin Tor and swore to destroy Garrosh.",
  "Soon after, the mists that had hidden Pandaria for ten thousand years faded, and the warring fleets of both factions found the continent. Their fighting woke the sha, dark spirits born from the last breath of Y'Shaarj, an Old God the titans had torn apart long ago. Both sides then fought Pandaria's own enemies, among them the insectoid mantid swarm, the Zandalari trolls and Lei Shen, the Thunder King, an ancient mogu tyrant the Zandalari raised from death. Heroes killed him in his Throne of Thunder. Meanwhile Wrathion, Deathwing's son, cleansed of corruption before he hatched, tested champions from both sides. He believed one faction had to crush the other so a united world could face the Legion's return.",
  "Garrosh kept looking for more power. Helped by Sunreaver blood elves in Dalaran, his agents seized the Divine Bell, a mogu relic. Jaina answered by purging the blood elves from Dalaran. Garrosh used the bell to fill his elite Kor'kron guards with the power of the sha until Anduin Wrynn, Varian's son, destroyed it. Garrosh also tried to have Vol'jin murdered. Vol'jin survived and raised the Darkspear Rebellion, and Baine, Lor'themar Theron and Sylvanas turned against Garrosh too.",
  "Then Garrosh's goblin diggers found the heart of Y'Shaarj buried beneath the Vale of Eternal Blossoms, the sacred heart of Pandaria. Garrosh woke it with the Vale's waters, ruining the valley, and carried it to Orgrimmar. The siege came from every side. Vol'jin's rebels marched through Durotar, Varian's fleet landed at Bladefist Bay, and Thrall and Varok Saurfang slipped into the city. Tyrande's Sentinels brought down the gates, and the attackers fought down to Garrosh's sanctum beneath the city. Garrosh defeated Thrall, but the champions of both factions brought him down despite the heart's power.",
  "Thrall wanted to execute Garrosh on the spot. Varian and the Shado-Pan leader Taran Zhu insisted he stand trial in Pandaria for his crimes. Jaina urged Varian to end the Horde while all its leaders stood in one room. Varian instead accepted Vol'jin as the new warchief and offered peace as long as the Horde kept its honor. The trial never reached a verdict. Wrathion helped the bronze dragon Kairoz, who served the Infinite dragonflight, free Garrosh and send him back in time to another Draenor, which set up Warlords of Draenor."
];

window.EVENT_STORIES['wow-5'] = [
  "Kairoz brought Garrosh to an alternate Draenor in the past, at the moment the orc clans gathered to drink Mannoroth's blood. In this timeline Garrosh had never been born, but his father Grommash Hellscream was alive. Garrosh showed Grommash what the demon blood would do to their people. When Gul'dan offered the cup, Grommash poured it on the ground, and the Warsong ambushed Mannoroth with weapons built from Garrosh's knowledge of the future. Grommash killed the pit lord and Gul'dan was taken prisoner. Seven clans united as the Iron Horde, free of demons but bent on conquest.",
  "The Iron Horde built its own Dark Portal in Tanaan Jungle, powered by souls that Gul'dan and his captive warlocks were forced to channel, and invaded the Blasted Lands. Archmage Khadgar led a strike back through the portal with Thrall, the draenei Vindicator Maraad and champions of both factions. They freed Gul'dan's warlocks to break the spell and destroyed the portal from the Draenor side, cutting off the invasion. Stranded on a hostile world, the Alliance and Horde built fortified garrisons and carried the war to the Iron Horde.",
  "They found allies among peoples the old Horde had never ruined. The Frostwolf clan, led by this world's Durotan, Thrall's father in the original timeline, still lived free in Frostfire Ridge. The draenei of Shadowmoon Valley followed this world's Prophet Velen. When the Shadowmoon chieftain Ner'zhul called down the Dark Star, a fallen naaru turned to the Void, Velen gave his life to restore it as the naaru K'ara. His young student Yrel rose to lead the draenei in his place.",
  "Thrall found Garrosh in Nagrand and challenged him to a mak'gora. As they fought, Garrosh raged that Thrall had made him warchief and then abandoned him. Thrall answered that Garrosh had chosen his own path, and ended the fight with a bolt of lightning. Heroes then brought down the Iron Horde's warlords one by one, among them Blackhand in his Blackrock Foundry. With the Iron Horde crumbling, the escaped Gul'dan came back. He offered the demon blood once more. Grommash refused again, but Kilrogg Deadeye of the Bleeding Hollow clan drank it. Gul'dan took command, imprisoned Grommash, and flooded the Iron Horde's new fortress in Tanaan with fel energy, turning it into Hellfire Citadel.",
  "Heroes stormed the citadel and freed Grommash from his demon torturer. At its peak they found Archimonde, the Legion's great general, whom Gul'dan had summoned through a portal called the Black Gate. Khadgar, Yrel and Grommash fought beside the champions, and Archimonde was destroyed. With his last breath he blasted Gul'dan into the Black Gate. Khadgar warned Yrel that Gul'dan's masters would not be banished so easily and that this was only the beginning.",
  "Draenor was free. Grommash, Durotan and Yrel promised to rebuild their world together, and the Alliance and Horde went home. Khadgar was right about Gul'dan. The Legion sent him to the original Azeroth with orders to open the Tomb of Sargeras, which began the Legion's third invasion."
];

window.EVENT_STORIES['wow-6'] = [
  "Gul'dan reached the Broken Isles, the remains of ancient night elf lands, and broke into the Tomb of Sargeras. Khadgar and Maiev Shadowsong tried to stop him and failed. Gul'dan seized the tomb's power and, after weighing a betrayal, gave it to the Legion, tearing open the way for its greatest invasion. He also broke into the Vault of the Wardens and stole Illidan Stormrage's body, which Maiev had kept prisoner since the Black Temple.",
  "Varian Wrynn sent SI:7 to scout the Broken Shore. The dreadlord Detheroc killed the scouts and, wearing the face of spymaster Mathias Shaw, told the king an attack could work. The Alliance and Horde fleets landed together, straight into a trap. The Argent Crusade was nearly wiped out, and Gul'dan dropped the captured Tirion Fordring into lava. Tirion survived long enough to be rescued, then died of his wounds. On the high ridge, demons hit the Horde from behind. Vol'jin was mortally wounded, and Sylvanas sounded the retreat to save what was left of the Horde. Left exposed, Varian got many of his soldiers away on a gunship, then stayed behind and fought his way to Gul'dan, who killed him with fel magic. Before he died, Vol'jin named Sylvanas warchief, saying the spirits had told him to.",
  "Anduin took his father's throne. Khadgar moved Dalaran to the Broken Isles, and heroes searched for the five Pillars of Creation, titan relics that could help seal the tomb. Each search pulled them into a local war. In Val'sharah, the satyr Xavius corrupted the Aspect Ysera with the Emerald Nightmare, and Tyrande and the druids had to put her to rest. In Suramar, Grand Magistrix Elisande had let the Legion into her city. First Arcanist Thalyssra's Nightfallen rebels, backed by both factions, stormed her palace, the Nighthold, and Elisande fell.",
  "In the Nighthold, Gul'dan was trying to place a piece of Sargeras's soul inside Illidan's body. Khadgar used the Pillars and the naaru Light's Heart to return Illidan's own soul, and Illidan killed Gul'dan. His demon hunters, the Illidari, had already been freed to fight the Legion. Azeroth's forces, now united as the Armies of Legionfall, retook the Broken Shore and broke into the Tomb of Sargeras. Velen followed Kil'jaeden into the Twisting Nether, where the demon lord died, envying the faith of his old friend. Illidan then pulled Argus, the eredar homeworld, into Azeroth's sky.",
  "The draenei warship Vindicaar carried Azeroth's forces to Argus. There they joined the Army of the Light, led by the naaru Xe'ra and the paladin Turalyon, and found Alleria Windrunner, who had fought beside him against the Legion for centuries. Xe'ra tried to force Illidan into the destiny she had marked him for as an infant. He refused and destroyed her. Alleria, cut off from the Light, took the power of the Void into herself.",
  "At Antorus, the Burning Throne, heroes freed the imprisoned souls of the Pantheon titans and defeated Argus the Unmaker, the tortured world-soul of the planet. The Pantheon pulled Sargeras from the sky over Azeroth and bound him in their seat, where Illidan stayed behind to guard him. As he was dragged away, Sargeras drove an enormous sword deep into Silithus. That wound would bring a new substance, azerite, to the surface and fuel the faction war of Battle for Azeroth."
];
