window.EVENT_STORIES = window.EVENT_STORIES || {};

window.EVENT_STORIES['wow-7'] = [
  "The war began with a wound. In the last act of the Legion war, Sargeras drove his sword into Silithus, and Azeroth started bleeding azerite, a golden substance of enormous power. Magni Bronzebeard, who now speaks for the world-soul, begged the faction leaders to help heal her. Warchief Sylvanas Windrunner saw a weapon instead. She sent the Horde to seize the night elf lands of northern Kalimdor. Varok Saurfang, her war leader, had planned to capture Teldrassil and hold it. Sylvanas ordered the tree burned with its people still inside.",
  "King Anduin Wrynn answered by marching on Lordaeron. Sylvanas flooded the Undercity with plague rather than give it up, and the Forsaken capital became a ruin. Both sides went looking for allies. Jaina Proudmoore came home to Kul Tiras, the island kingdom that had branded her a traitor, won back her people and brought its navy into the Alliance. The Horde sailed to Zandalar, where Princess Talanji helped them defeat Zul, a traitor prophet who served the blood god G'huun. Heroes destroyed G'huun in the titan facility of Uldir. When the Alliance stormed the Zandalari capital, King Rastakhan was killed, and Talanji took the throne.",
  "The war cost Sylvanas her own people's trust. Tyrande Whisperwind took on the power of the Night Warrior, an avatar of Elune's vengeance, and drove the Horde out of Darkshore. Saurfang, captured at Lordaeron and quietly released by Anduin, turned against his warchief. Baine Bloodhoof freed Jaina's brother Derek, whom Sylvanas had raised as an undead servant, and returned him to his family. Sylvanas jailed Baine for it, and Saurfang, Thrall, Jaina and Mathias Shaw broke him out together.",
  "Older enemies stirred under the war. Queen Azshara of the naga lured both fleets to her undersea realm of Nazjatar. Her ritual used the heroes' own power to break the chains of N'Zoth, the last living Old God, and N'Zoth carried her away as she fell. At the gates of Orgrimmar, Saurfang challenged Sylvanas to a mak'gora, a duel of honor. She killed him, but in her fury she declared the Horde nothing and abandoned it, leaving with her champion Nathanos Blightcaller.",
  "N'Zoth raised his sunken city of Ny'alotha and sent his armies against the Vale of Eternal Blossoms in Pandaria and the desert of Uldum. Magni guided the fight back. The heroes carried the Heart of Azeroth, an amulet the world-soul filled with azerite, and the black dragon Wrathion received Xal'atath, a whispering Old God dagger, from Azshara. Inside Ny'alotha, Wrathion broke N'Zoth's outer shell with the blade, and the heroes destroyed the Old God with the power of the Forge of Origination, an ancient titan device.",
  "Before he died, N'Zoth revealed that Sylvanas had schemed with Azshara and meant to unleash a darkness on the world. The Alliance offered an armistice, and the Horde chose to be led by a council of its leaders instead of a warchief. Sylvanas's next move would come at Icecrown."
];

window.EVENT_STORIES['wow-8'] = [
  "Sylvanas reappeared at Icecrown Citadel. She defeated Bolvar Fordragon, the Lich King, and shattered the Helm of Domination. The blow tore open the veil between the living world and the Shadowlands, the realms of the dead. Her Val'kyr seized Anduin Wrynn, Jaina Proudmoore, Thrall and Baine Bloodhoof and dragged them into the Maw, a prison realm for the worst souls. Tyrande fought off the attempt to take her. Bolvar and his death knights led the heroes through the rift to rescue the captives.",
  "The Shadowlands were already failing. The Arbiter, who judges every soul, had fallen dormant after the dead titan Argus's soul struck her, a plot by the dreadlords on behalf of the Jailer. Every soul now fell into the Maw and fed its master. The other realms starved of anima, the energy of souls. The heroes escaped the Maw to the city of Oribos and worked with the four covenants of Bastion, Maldraxxus, Ardenweald and Revendreth. In Bastion, the soul of Uther the Lightbringer was drawn into a rebellion. In Maldraxxus, Thrall's mother Draka rose to lead the realm's armies. In Ardenweald, the realm of the Winter Queen, the green dragon Ysera was reborn.",
  "The Jailer, named Zovaal, had once been the Arbiter himself. The other Eternal Ones cast him into the Maw ages ago for trying to remake reality. To try again he needed their sigils, which could open the way to the Sepulcher of the First Ones in the forbidden realm of Zereth Mortis. He had secret allies. Sire Denathrius of Revendreth hoarded anima for him until the heroes defeated him in Castle Nathria. Sylvanas dominated Anduin and made him the Jailer's weapon, and Anduin took the sigils of Bastion's ruler Kyrestia and of the Winter Queen.",
  "In the Sanctum of Domination, the Jailer's tower, the heroes destroyed the lich Kel'Thuzad and fought Sylvanas while the Jailer merged with the Arbiter and claimed her sigil. Sylvanas saw that she had been used and told him she would never serve. He gave back the piece of her soul that Frostmourne had torn away and left her senseless. Then he fled to Zereth Mortis with Anduin. Uther helped Sylvanas wake, and she joined the heroes.",
  "In the Sepulcher, the heroes broke the Jailer's grip on Anduin, and the last fragment of Arthas's soul faded away. From the remains of the Helm, they forged the Crown of Wills to resist Domination. With a boon from Azeroth herself, they stopped the Jailer from drawing the world-soul into the Sepulcher and killed him. In his last moments he insisted the cosmos could not survive a threat he had foreseen. The rift over Icecrown closed, and the kyrian Pelagos became the new Arbiter.",
  "Sylvanas gave herself up to Tyrande's judgment. Tyrande sentenced her to free every soul trapped in the Maw, until only Sylvanas remained. Anduin returned to the living world shaken by what he had been forced to do."
];

window.EVENT_STORIES['wow-9'] = [
  "After the war in the Shadowlands, Azeroth's elemental power grew stronger. A titan watcher named Koranos relit the Beacon of Tyrhold, and the Dragon Isles, the ancient home of the dragons, came out of hiding. The flights returned and formed the Valdrakken Accord under Alexstrasza. Their Aspects were weak, having given up their titan-granted powers to kill Deathwing. At the same time, Primalists led by Kurog Grimtotem freed Raszageth the Storm-Eater. She was one of the Primal Incarnates, proto-dragons who had rejected the titans' gifts and embraced the raw elements. The Aspects had imprisoned them about twenty thousand years earlier.",
  "Raszageth raged across the isles. She struck the Ruby Life Pools and tried to destroy the ley lines of the Azure Span, which Kalecgos and his blue dragons defended. She died in the Vault of the Incarnates, but she freed her siblings Iridikron, Fyrakk and Vyranoth. The Incarnates then broke into Zaralek Cavern, Neltharion's secret underground realm deep under the isles. Wrathion and Sabellian, rival claimants to lead the black dragons, followed them down. There Fyrakk bathed in shadowflame and grew far more dangerous.",
  "Iridikron had a longer plan. With help from the infinite dragonflight, which serves Murozond, a corrupted future version of Nozdormu, he traveled back in time. He used the Dark Heart, a relic made for Neltharion, to absorb the essence of Galakrond, the ancient father of dragons. Chromie and the heroes chased the infinite dragons through the timeways, but Iridikron escaped with his prize.",
  "Fyrakk made a pact with the Druids of the Flame, led by Tindral Sageswift, who wanted immortality. Together they burned their way into the Emerald Dream, where a new World Tree, Amirdrassil, was growing. Fyrakk meant to fill its heart with shadow and flame. Vyranoth was sickened by his cruelty. She warned Alexstrasza and turned against him. Alexstrasza, Merithra of the green flight, Tyrande and the heroes fought him across the Dream, and he died inside Amirdrassil itself.",
  "With Fyrakk dead, Amirdrassil bloomed into the waking world on the Dragon Isles. Azeroth herself blessed the Aspects and restored their powers. She blessed Vyranoth too, and Vyranoth became the Aspect of Storms. The night elves built a new city, Bel'ameth, in the tree. When Malfurion came home, he and Tyrande stepped down and named Shandris Feathermoon leader of the night elves.",
  "Iridikron stayed free. He met Vyranoth one last time and told her that the Dark Heart was now in the hands of the Harbinger. He vowed she would not see him again until the titans faced their reckoning. Soon people across Azeroth began hearing a strange song, and Khadgar sent Alleria Windrunner to learn who the Harbinger was. With the ethereal Locus-Walker, she found Xal'atath."
];

window.EVENT_STORIES['wow-10'] = [
  "The Radiant Song grew louder. People across Azeroth heard it in visions, and Magni Bronzebeard believed it came from the world-soul. Locus-Walker warned that his people had heard something similar before the voidlord Dimensius devoured their world, K'aresh. The song led to Khaz Algar, a continent long hidden from the outside world. Xal'atath, disguised as an archmage of the Kirin Tor, persuaded the council to teleport the floating city of Dalaran there. Above the Isle of Dorn she revealed herself. She drained Dalaran's magic into the Dark Heart, pulled Khadgar into it and destroyed the city.",
  "Survivors crashed onto the Isle of Dorn, home of the earthen, people of living stone. Xal'atath had corrupted their Awakening Machine, and Magni used the world-soul's power to cleanse it. The heroes then went into the depths. In Hallowfall, under a giant crystal of Light called Beledar, they found the Arathi, humans descended from a lost expedition. Anduin Wrynn, who had struggled to reach the Light since the Shadowlands, found his faith again fighting beside a young soldier named Faerin Lothar.",
  "Below lay Azj-Kahet, the nerubian kingdom. Queen Ansurek had stabbed her own mother to take the throne and accepted Xal'atath's offer to remake her people with Black Blood, the blood of the dead Old Gods. Heroes and a secret resistance called the Severed Threads stormed Nerub-ar Palace and killed Ansurek. Xal'atath watched her die and offered no help. Xal'atath also tried to drain Beledar into the Dark Heart. Alleria shot the relic instead of the Harbinger and cracked it, and a wounded Khadgar came free.",
  "Xal'atath needed the relic repaired. She turned to Jastor Gallywix, who had seized power over the goblin city of Undermine, and he forced his engineers to fix it with Black Blood. Monte Gazlowe led the goblins in revolt, and Gallywix died in his last stand. By then he had handed the Dark Heart to the Shadowguard, void-touched ethereals who wanted to bring Dimensius back. They did not answer to Xal'atath, so she went to Locus-Walker with a warning.",
  "On the shattered world of K'aresh, Alleria reluctantly fought beside Locus-Walker and Xal'atath. The heroes could not stop the Shadowguard from reviving Dimensius in Manaforge Omega, but together they forced him into the Dark Heart. Xal'atath seemed to trap herself inside with him. When Locus-Walker picked up the relic, she burst out, destroyed him and left with the voidlord's power. She promised Alleria that next time she would take everything Alleria loved.",
  "Xal'atath then united the Void's warring factions into an army, the Devouring Host. The domanaar, powerful Void predators, and Nexus-King Salhadaar's Shadowguard bowed to her, and the remnants of the Twilight's Hammer cult joined as the Twilight's Blade. In a realm called the Voidstorm she raised a dark citadel, the Voidspire. Vereesa Windrunner had a vision of Xal'atath in Silvermoon City, and the Windrunner family prepared for what was coming."
];

window.EVENT_STORIES['wow-11'] = [
  "Xal'atath's Devouring Host struck the Isle of Quel'Danas, home of the Sunwell, the font of arcane magic and Light at the heart of the blood elf kingdom. Lor'themar Theron and Lady Liadrin held the ramparts while Liadrin prayed for help. Priests and paladins from across the world arrived through the Sunwell as the Vanguard of the Light, led by Turalyon, Alleria's longtime love. Their combined Light drove the Host from the island, and a beam from the Sunwell held the Voidstorm back. Silvermoon then opened part of the city to the Vanguard and the Alliance, and the welcome was uneasy.",
  "The Light brought its own trouble. Light-fed plants called Lightbloom spread wildly through Eversong Woods. Turalyon's zeal clashed with Lor'themar's caution. When the Amani trolls of Zul'Aman marched into Eversong, Turalyon tried to strike down their warrior Zul'jan, and his son Arator took the blow. Liadrin later allied with the new Amani chieftain Zul'jarra against the Twilight's Blade, and the heroes won the trust of the haranir, an ancient hidden people of Harandar, where the roots of the World Trees meet.",
  "In the Voidstorm, Alleria kept hunting. With Arator and the dreadlord paladin Lothraxion, she forced a domanaar named Decimus to help them, and learned that Xal'atath had once been mortal. When Salhadaar turned the naaru T'era to the Void, Alleria released her own dark naaru, L'ura, to destroy her. Lothraxion, blinded by the Light, tried to destroy a Nexus-Point that could have devastated Silvermoon, and Alleria and Arator had to kill him. Decimus then shut the Nexus-Points down, and the Vanguard crossed into the storm.",
  "The assault on the Voidspire went wrong. Some of Turalyon's officers, blinded by the Light, turned on Alleria and Arator, and Turalyon chose his family over them. Xal'atath lured Alleria away and tore L'ura out of her body with the Blade of the Black Empire. With the naaru's power, she corrupted the Sunwell into the Darkwell, a font of Void. Alleria and Turalyon were lost to the Void, and their fate is unknown. Magister Umbric, leader of the void elves, pulled Arator back to Silvermoon.",
  "Arator called on every elven people. Blood elves, night elves under Shandris Feathermoon, Thalyssra's nightborne, void elves and Vereesa's high elves marched together, joined by the Amani and the haranir. In the Darkwell, Arator, Vereesa and the heroes destroyed L'ura. Xal'atath moved to kill them, but Sylvanas Windrunner stepped out of a portal from the Maw and loosed an arrow at her. Xal'atath and her army escaped down the Darkwell's beam, deep beneath Azeroth's surface, and Sylvanas went back to her penance.",
  "The Sunwell was nearly extinguished. Each people gave a gift to cleanse it, and Liadrin then filled it with Light. It became the Dawnwell, gentler and weaker than before. Rommath and Umbric concluded that Xal'atath had already gotten what she wanted, a path into the depths of the world. Later patches turned to the Amani. Patch 12.1 followed Zul'jan to the Coiled Isle and the serpent Ula'tek, and patch 12.1.5 set Liadrin and the trolls against Kith'ix, an ancient Old God general the Amani had locked away long ago."
];

window.EVENT_STORIES['wow-12'] = [
  "The Last Titan is the third and final chapter of the Worldsoul Saga, and it has not been released. Blizzard showed a teaser at BlizzCon in September 2026 and set its release for 2027. It returns players to Northrend, the frozen continent of the Lich King's war, rebuilt for the expansion. Blizzard calls it the culmination of more than twenty years of Warcraft storytelling and says it will also lay groundwork for what comes after.",
  "The announced story centers on Ulduar, the titan city in Northrend's Storm Peaks. There, players will witness the titans' return to Azeroth. They will also uncover a conspiracy that runs through the world's history and challenges what was believed about the titans' intentions and the true nature of Azeroth. Blizzard has framed the whole saga around the fate of Azeroth's world-soul and the long-term plans of the Pantheon, the titans who once shaped the world.",
  "Midnight left the road there open. Xal'atath escaped down the Darkwell's beam with Dimensius's power and much of her army. Patch 12.2, Eclipse, planned for early 2027 as Midnight's last major update, will send heroes after her into a titan vault beneath the surface and toward the worldcore, where she nears her goal of seizing the world-soul. Alleria and Turalyon remain lost to the Void. Iridikron, the last Primal Incarnate, has vowed to return when the titans face their reckoning.",
  "Blizzard has not said how these threads connect, or what the titans' return will mean for Azeroth. It plans to share more about the expansion in early 2027."
];
