window.EVENT_STORIES = window.EVENT_STORIES || {};

window.EVENT_STORIES['cosmos-0'] = [
  "Everything in the Warcraft universe traces back to the First Ones, also called the Progenitors, and almost nothing about them is certain. Lore revealed in Shadowlands says they designed reality around six forces. The Eternal Ones tell it as a story of six First Ones who fought until their struggle settled into balance, each then giving part of itself to a shared pattern. Some believe in a seventh of unclear nature. Nobody in the story knows whether the First Ones still exist.",
  "Their best-known work is the realm of Death. In Zereth Mortis, a hidden workshop realm full of geometric machines and servant constructs called automa, they shaped the Shadowlands and forged its rulers, the Eternal Ones, who form the Pantheon of Death. Each received a sigil and a realm. Kyrestia the Archon rules Bastion, the Primus commands the soldiers of Maldraxxus, the Winter Queen tends Ardenweald, where fallen nature spirits are reborn, and Sire Denathrius rules Revendreth, where proud souls atone. The First Ones also built Oribos, the city where every soul arrives, and then forbade the Eternal Ones from returning to Zereth Mortis.",
  "In Oribos sits the Arbiter, the judge who weighs each soul and sends it to an afterlife. The first Arbiter was Zovaal, the strongest of the Eternal Ones. Judging countless lives taught him much about mortals, and it frightened him. He foresaw an unseen power that would one day threaten all creation and believed the divided realms of Death could never stand against it. His siblings answered that the First Ones would have prepared for any such threat. Zovaal resolved to remake the Shadowlands with forbidden knowledge sealed in the Sepulcher of the First Ones, and to open it he tried to seize his siblings' sigils by force.",
  "It took the whole Pantheon of Death, led by the Primus, to stop him. At his trial in Oribos, Kyrestia found him guilty of betraying his duty, and the Winter Queen said he had threatened the cycle of Life and Death. Denathrius only remarked that Zovaal could have chosen another way. The Eternal Ones stripped him of his anima, his sigil and part of his essence, and from those pieces they built a new, impartial Arbiter. The Primus invented a new magic, Domination, to carve their sentence into his flesh, and the Winter Queen used Ardenweald's Heart of the Forest to make the Maw inescapable. Zovaal became its Jailer.",
  "Prison did not end him. Over countless ages he learned to wield Domination himself, and his goal grew from remaking Death to remaking all of reality under his will. Denathrius secretly joined him and made the nathrezim, the dreadlords, as spies. Their schemes reached Azeroth through the Lich King, and through the world-soul of Argus, whose death knocked the Arbiter dormant and sent every new soul into the Maw. Heroes finally destroyed Zovaal in the Sepulcher during Shadowlands, and the kyrian Pelagos became the new Arbiter.",
  "Much is left open. With his last breath Zovaal repeated that the cosmos would not survive the threat he had foreseen, and Blizzard has never said what it is. The link between the First Ones and the titans is also hazy. The First Ones gave the titans gifts in a realm called Zereth Ordus, a fact the keeper Odyn kept from mortals, and the scholar Firim feared Zovaal's attack had weakened the balance of the six forces."
];

window.EVENT_STORIES['cosmos-1'] = [
  "A world-soul is a young titan that forms inside one of a small number of planets and sleeps in its fiery core for ages. Generations of life rise and fall on the surface while it grows. When one finally wakes, it becomes a titan, a being the size of a world made of arcane magic and the raw matter of creation. Titans embody Order, and they are described as so pure that they cannot even imagine true evil.",
  "Legend says the first titan to wake was Aman'Thul, though nobody knows when or why. Sure that others like him existed, he searched the Great Dark Beyond, the physical universe, and roused the sleeping world-souls he found. Together they became the Pantheon of Order, with Aman'Thul as Highfather. Eonar was the patron of life and nature, Golganneth ruled skies and seas, Khaz'goroth shaped and forged worlds, and Norgannon kept magic and lore. Sargeras, the mightiest warrior among them, served as their champion and was called the Defender.",
  "The Pantheon worked by a set method. On each world it calmed the raging elemental spirits, reshaped land and sea, and seeded life, hoping to coax out a hidden world-soul. Most worlds proved empty, yet the titans had sworn to protect them all. They left servant races behind, along with great machines that could watch a world and wipe away its life if it fell into disorder. Celestial beings called the constellar, called on by Aman'Thul, kept watch and could trigger such a purge. Over time the titans found fewer and fewer world-souls, but they believed they had searched only a small corner of the universe.",
  "Not every threat was visible to them. Demons, chaotic creatures of the Twisting Nether, began attacking mortal worlds, and the Pantheon sent Sargeras to fight them. Later the young titan Aggramar joined him and became his student and lieutenant. Slain demons simply returned to the Nether in new bodies, so Sargeras built a prison world, Mardum, to hold the ones he defeated, and attacks grew rare. He also noticed that some demons wielded Void energy and suspected darker powers behind them. The Pantheon knew the Void existed but nothing of the void lords, who envied the titans and had already failed to corrupt any that were awake.",
  "Two discoveries shaped everything after. Sargeras found out what the void lords were doing to world-souls that had not yet woken, and the quarrel that followed split the family. Later Aggramar found Azeroth, the most powerful world-soul the titans had ever seen, already besieged by the Void. Azeroth is still a titan growing inside her planet, which is why so many powers want her.",
  "Some of this has been reframed. Chronicle, Blizzard's illustrated history, presents the titans as the great bringers of order, and their keepers' records credit them with creation itself. Shadowlands revealed that the First Ones designed the cosmic forces and gave the titans gifts in a realm called Zereth Ordus, and that the keeper Odyn forbade sharing this with mortals. Shadowlands scholars accuse the titans of taking credit for a cosmos they only inherited. How beings born from world-souls fit the First Ones' design has not been explained."
];

window.EVENT_STORIES['cosmos-2'] = [
  "Sargeras's fall began on a single world. While he and Aggramar split up to guard more of the cosmos, Sargeras found a planet almost entirely overrun by Old Gods, its sleeping world-soul's dreams twisted into nightmares. He interrogated the nathrezim, demons who lived among the Old Gods there, and learned the void lords' plan. Their Old Gods were meant to warp a world-soul into a dark titan, a Void creature able to devour all creation that even the Pantheon could not stop. In his rage Sargeras cleaved the planet in two, killing the world-soul inside.",
  "The Pantheon was horrified. They told him they might have purged the corruption and saved their unborn sibling. Sargeras answered that any world might already hide the same danger, and that a universe empty of life was safer than one ruled by the Void. If life had begun once, he said, it could begin again. Eonar replied that the Pantheon had sworn to protect life. Seeing they would never agree, Sargeras left and never came back. Alone, he brooded until fear and despair convinced him that the whole flawed cosmos had to burn.",
  "For that he needed an army. Sargeras returned to Mardum, the prison world where he had locked away the demons he defeated, and shattered it. The blast of fel energy freed the demons and warped Sargeras into a burning being of hatred. He offered the demons a choice to serve or die. Those who rallied behind the dreadlord Ulthalesh were reaped with a scythe forged from Mardum's fires, which took the rebel's name. The rest became the Burning Legion, and its first world soon burned. When Aggramar came to demand answers, the two dueled until both blades shattered, and Aggramar fled to warn the others.",
  "The Pantheon met the Legion near a world called Nihilam. By then the titans had already found and ordered Azeroth. Aman'Thul begged Sargeras to stop and told him of this young world-soul, who might one day be strong enough to face the void lords. Sargeras was unmoved, because to him a corrupted Azeroth was the greatest danger of all. Aggramar approached him unarmed, recalling the battles they had fought together, and Sargeras cut him down. The other titans attacked, but their combined might failed against his fel power, and all their bodies were destroyed. With his last act Norgannon shielded their spirits and flung them across the cosmos.",
  "The spirits struck the keepers, the titans' servants on Azeroth, who felt only a flash of confused memories. Only the keeper Ra understood that his makers were gone, and he sank into despair. Sargeras proclaimed victory and turned to the eredar of Argus for commanders. Ages later the Legion captured most of the titan spirits and tortured them on Argus, twisting Aggramar into its guardian. In Legion, Azeroth's heroes freed them, and the restored Pantheon sealed Sargeras away.",
  "Some threads remain loose. Shadowlands revealed that the nathrezim were really spies created by Sire Denathrius, a lord of the Shadowlands, but Blizzard has not said whether the demons who told Sargeras about the void lords were already following that plan. How the Legion found the scattered titan spirits is also unexplained. The danger Sargeras feared is real in canon, and the Void still hunts Azeroth's world-soul."
];

window.EVENT_STORIES['cosmos-3'] = [
  "The Old Gods were made for a single purpose. The void lords, the rulers of the Void beyond reality, could not corrupt titans once they were awake, so they targeted titans still asleep as world-souls. They pooled their power into parasitic horrors and hurled them across the cosmos. Because they did not know which planets held world-souls, they simply hoped some of their creations would strike one.",
  "Four struck Azeroth: Y'Shaarj, C'Thun, Yogg-Saron and N'Zoth. When this happened is unknown. They embedded themselves in the surface and sent tendrils down toward the defenseless world-soul at the planet's core. From matter seeping out of their bodies came two servant races, the cunning n'raqi, or faceless ones, and the insect-like aqir, who built temple cities around their masters' immense forms. The greatest surrounded Y'Shaarj, the strongest of the four, near the center of the world's largest continent.",
  "Before the Old Gods came, Azeroth belonged to its elemental spirits. The four Elemental Lords, Ragnaros of fire, Therazane of earth, Al'Akir of air and Neptulon of water, had always been rivals, but now they united for the first time. They still could not stand against the endless swarms of n'raqi and aqir, and the Old Gods enslaved them. The Black Empire spread over much of the world, and a permanent twilight fell. The Old Gods also warred among themselves. N'Zoth's armies fought those of C'Thun and Yogg-Saron, and N'Zoth once lost a great battle to Y'Shaarj where the Broken Shore now lies.",
  "Xal'atath's place in this story has changed. Older lore described her as a dagger of the Black Empire, a weapon its dark priests used for sacrifices. The War Within and later patches revealed that she is a Void being, once the herald of the void lord Dimensius, who came to Azeroth to claim its world-soul for herself. After N'Zoth finished building his city of Ny'alotha, she attacked him by surprise. The other Old Gods sent help, defeated her and sealed her inside that sacrificial dagger, the Blade of the Black Empire. Y'Shaarj mocked her that she could only watch this world grow strong. She replied that the game had only begun.",
  "Even so, the Old Gods never reached the world-soul. When the titan Aggramar found Azeroth, the surface was shrouded in Void energy, but the titan sleeping inside was still untouched. The Pantheon judged her the most powerful world-soul it had ever found and came to save her. By then the Old Gods had dug in so early and so deep that they were bound to the planet itself. Their influence shaped Azeroth for ages after their empire fell, through the aqir's descendants, the corruption of Deathwing and the Emerald Nightmare, until N'Zoth, the last of them, was killed in Battle for Azeroth.",
  "Blizzard leaves several questions open. Nobody knows how many Old Gods the void lords made or how many other worlds they struck, though infested planets appear elsewhere in the lore. A Chronicle painting of Azeroth's Old Gods even shows an unexplained fifth creature. Xal'atath claims she began as a mortal child on a world the Void consumed, but that remains her own account."
];

window.EVENT_STORIES['cosmos-4'] = [
  "Once the Pantheon agreed to save Azeroth, it faced a problem. The titans were so vast that fighting on the planet might kill the very world-soul they meant to protect. Aggramar proposed making servants to fight for them. Guided by the forger Khaz'goroth, the titans shaped the titan-forged, warriors of stone and metal. Each titan gave part of its power and likeness to the mightiest of them, the keepers. Aggramar gave courage and strength to Tyr, and Eonar gave Freya command of plants and beasts. Odyn led them and was named Prime Designate.",
  "The titan-forged first defeated the elementals and sealed the Elemental Lords in a newly made Elemental Plane, which calmed the world's raging nature. They destroyed most of the aqir. As they neared Y'Shaarj's temple city, the titans feared their servants could not win, so Aman'Thul reached down through the sky and tore Y'Shaarj off the planet. The Old God was ripped apart, mountains shattered and hundreds of titan-forged died. Its last breath later spawned the sha of Pandaria. The tearing also opened a wound in the world, and the world-soul's arcane lifeblood poured out. The keepers stabilized it, and it became the Well of Eternity.",
  "The titans now saw that the remaining Old Gods were rooted too deep to remove without killing Azeroth, so they ordered them imprisoned. After long campaigns the titan-forged sealed C'Thun at Ahn'Qiraj and Yogg-Saron beneath the fortress of Ulduar in Northrend, and bound N'Zoth in a prison whose location is unclear. The Pantheon also studied the Old Gods at a facility called Uldir. Trying to understand their endless hunger to corrupt, they accidentally created a new one, G'huun, a god of rot and blood, and sealed it inside.",
  "Then the ordering itself began. The keepers made Ulduar their base and built the Forge of Wills to create more titan-forged, including the stone earthen. They raised mountains, dredged seas and shaped one great continent around the Well, which the titans named Kalimdor. In the place later called Khaz Algar, earthen began building the Worldcore to shield the young world-soul. Satisfied that Azeroth was in good hands, the Pantheon left to continue its search among the stars. Its bodies never returned.",
  "The Dragon Aspects came much later, more than twenty thousand years before the Dark Portal, and the idea came from the keepers. Tyr and five proto-dragons, Alexstrasza, Ysera, Malygos, Neltharion and Nozdormu, defeated the monstrous Galakrond. Tyr then urged the keepers to empower the five. Odyn refused, but the others reached out to the Pantheon anyway. Through the keepers, Aman'Thul gave Nozdormu power over time, Eonar blessed Alexstrasza with life and Ysera with the Emerald Dream, Norgannon gave Malygos magic, and Khaz'goroth gave Neltharion the earth. That last gift felt to Neltharion like the weight of the world, and the Old Gods later turned him into Deathwing.",
  "The ordering left dangerous loose ends. The imprisoned Old Gods kept whispering, and Yogg-Saron's Curse of Flesh slowly turned many titan-forged into mortal races of flesh. The titans also never told the Aspects that a titan slept inside Azeroth. The order of events is only partly fixed in canon. The Pantheon died at Nihilam after the ordering, but the keepers' wars and Galakrond's fall have only rough dates."
];

window.EVENT_STORIES['cosmos-5'] = [
  "After destroying the Pantheon at Nihilam, Sargeras had a vast demon army but almost nobody to lead it. Most demons were bloodthirsty and poor at strategy, and many had died needlessly in the battle. On the world of Argus he found what he wanted. The eredar were brilliant, ancient and gifted in every kind of magic, and three leaders ruled them together: Velen, Kil'jaeden and Archimonde. Velen and Kil'jaeden had ruled together long before Archimonde joined them, and they loved each other like brothers.",
  "Sargeras came to the three in a radiant, kindly form. He offered limitless knowledge and power, along with a chance to help him fix what he called the one true flaw at the heart of the universe. The eredar prized knowledge above all. Kil'jaeden and Archimonde accepted gladly, and so did about two-thirds of their people. Velen held back. The naaru K'ure, a being of living Light, sent him a vision. At first he saw himself leading a shining eredar host to bless other worlds, as Sargeras promised. Then he saw his people as twisted demons, burning worlds to bare rock.",
  "K'ure told Velen to gather his followers on the highest mountain of Argus on the longest day of the year. Velen's friend Talgath, secretly loyal to Kil'jaeden, handed Velen's wife and son to the Deceiver, and the warrior Hatuun stayed behind to hold off the pursuers. The naaru carried the refugees away aboard the dimensional ship Genedar, and they became the draenei, the exiled ones. Kil'jaeden took their flight as betrayal and swore to hunt them down. He raised Velen's son as the demon Rakeesh.",
  "The eredar who stayed received Sargeras's gift. Fel energy flooded their bodies, and his whispers drowned out their reason. They became the man'ari, and as the first people to pledge themselves to Sargeras they became the Legion's commanders. Kil'jaeden sought out and corrupted other races, Archimonde led the armies, the eredar tongue Eredun became the Legion's common language, and Argus became its fortress. Argus also held a sleeping world-soul. Dreadlords persuaded Sargeras to let them fill it with death magic, making it an engine that brought slain demons back. Shadowlands revealed their real master was the Jailer, who wanted the soul of Argus to break the Arbiter once Argus was killed.",
  "The naaru also split the Genedar in two. Its finest warriors followed the prime naaru Xe'ra aboard a second ship, the Xenedar, to wage open war on the Legion as the Army of the Light, later known as the Lightforged. The rest fled with Velen from world to world for thousands of years. K'ure told Velen that the naaru could not stop the corruption because of free will. They could only save those who chose to leave. That split between the man'ari and the exiles drove events until Legion, when Azeroth's heroes reached Argus and Kil'jaeden fell.",
  "The date has moved between sources. The Warcraft Wiki follows the later short story Bringer of the Light in placing Sargeras's offer about 13,000 years before the Dark Portal, while the eredar themselves arose about 25,000 years ago. Older material claimed the draenei had been fleeing for 25,000 years. How long Argus thrived before Sargeras arrived is not recorded."
];
