window.RACE_STORIES = window.RACE_STORIES || {};

window.RACE_STORIES['humans'] = [
  ["Children of the Vrykul", [
    "Humans descend from the vrykul, the giant warriors of Northrend. The vrykul began as beings of living iron made by the Keepers, the titans' servants on Azeroth, but a corruption called the Curse of Flesh slowly turned them to flesh and blood. About 15,000 years before the Dark Portal opened, mothers of the Dragonflayer clan began giving birth to small, frail children.",
    "King Ymiron of the Dragonflayers called these infants aberrations and ordered them killed. Some parents could not bear it. They carried their children south to the land now called Tirisfal Glades and left them with vrykul who guarded the grave of the keeper Tyr. These outcasts became the first humans.",
    "For thousands of years humans lived as warring tribes in the forests and hills of the Eastern Kingdoms. They forgot where they came from, keeping only tales of giants who once watched over them. Humanity learned the truth only when the war against the Lich King brought them face to face with the vrykul in Northrend."
  ]],
  ["Thoradin and the Empire of Arathor", [
    "About 2,800 years before the Dark Portal, the Amani forest trolls grew more aggressive. Thoradin, warlord of the Arathi tribe, saw that scattered tribes could not survive a true war with the trolls. Over six years he united them through marriages, promises and conquest, offering each defeated rival peace and an honored place. He named the kingdom Arathor and built its capital, the fortress-city of Strom, in what are now the Arathi Highlands.",
    "Meanwhile the high elves of Quel'Thalas were losing their own war against the Amani. Their king, Anasterian Sunstrider, sent envoys to Strom, and the elves agreed to teach one hundred humans arcane magic in exchange for soldiers. The joint army drew the trolls into a trap near the Alterac Mountains, where human and elven magi burned the Amani host in a great firestorm. This victory ended the Troll Wars. It also began some two thousand years of friendship between humans and high elves.",
    "After the war, human priests began to receive visions from the naaru, beings of living Light from beyond Azeroth. From those visions grew the faith of the Holy Light, which became the main religion of humankind."
  ]],
  ["The Seven Kingdoms", [
    "After Thoradin, Arathor spread across the north. New city-states rose: Dalaran, a haven for mages; the harbors of Gilneas; the island colony of Kul Tiras; and Alterac in the mountains. As these cities grew rich, they listened less to Strom. Around 1,200 years before the Dark Portal, the empire came apart. Strom's nobles moved north to fertile Lordaeron, and the last of Thoradin's bloodline sailed south to found Stormwind. The few families who stayed behind renamed their city Stromgarde.",
    "The result was the Seven Kingdoms: Stormwind, Lordaeron, Gilneas, Kul Tiras, Alterac, Stromgarde and Dalaran. They traded with dwarves, gnomes and high elves, but they also spied on one another and fought border wars. Lordaeron, ruled by the Menethil kings, often acted as a leader among them. At some unknown point, other Arathi sailed away with high elf companions and founded a separate Arathi Empire across the sea."
  ]],
  ["The Orcs and the Alliance", [
    "In Year 0 the orcish Horde came through the Dark Portal into the swamps south of Stormwind. The First War ended in disaster. King Llane Wrynn was assassinated by the half-orc Garona, and Stormwind was left in ruins. Llane's champion, Anduin Lothar, the last heir of Thoradin's line in the Eastern Kingdoms, led the survivors across the sea to Lordaeron with the young Prince Varian.",
    "Lothar persuaded King Terenas Menethil II of Lordaeron to call together the rulers of the seven kingdoms. They formed the Alliance of Lordaeron, later joined by the dwarves, gnomes and high elves. In the Second War the Horde swept north, and Lothar was killed at Blackrock Spire. His lieutenant Turalyon took command, broke the Horde and destroyed the Dark Portal. The captured orcs were held in internment camps.",
    "Peace strained the Alliance. Stormwind was rebuilt, but the cost of the camps angered several kings, and Gilneas, Stromgarde and Quel'Thalas all left."
  ]],
  ["Plague and the Fall of Lordaeron", [
    "In Year 20 a plague spread through the grain of northern Lordaeron. Those who died of it rose as the Scourge, the undead army of the Lich King. Prince Arthas Menethil hunted the source of the plague, purged the infected city of Stratholme and followed the trail to Northrend. There he took up the cursed runeblade Frostmourne, came home as a death knight, murdered his father Terenas, and led the Scourge through Lordaeron, Quel'Thalas and Dalaran.",
    "Lordaeron, the greatest human kingdom, was destroyed. Before the end, a mysterious prophet urged the young sorceress Jaina Proudmoore to lead refugees west across the sea to Kalimdor. There humans fought beside orcs and night elves to defeat the Burning Legion at Mount Hyjal. In Lordaeron, many of the dead later broke free as the Forsaken, while the zealots of the Scarlet Crusade fought to purge every undead."
  ]],
  ["Stormwind at the Heart of the Alliance", [
    "With Lordaeron gone, Stormwind became the center of humanity and the leader of the Alliance. In the early years of World of Warcraft, King Varian Wrynn vanished while the black dragon Onyxia, disguised as a noblewoman, manipulated his court. Varian returned once she was exposed. He led the Alliance against the Lich King in Northrend and, during Mists of Pandaria, became High King of the whole Alliance.",
    "Varian died on the Broken Shore at the start of the Legion invasion, holding the line so his soldiers could escape. His son Anduin, a priest who prized peace, took the crown, yet his reign brought the Fourth War after the Horde burned the night elf city of Teldrassil. Later the Jailer's servants captured Anduin and bent him to their will for a time. Turalyon, the Second War hero who had spent a thousand years fighting the Legion beyond Azeroth, became regent.",
    "In The War Within, the Void herald Xal'atath destroyed the floating city of Dalaran, and the human kingdoms sent troops to the continent of Khaz Algar. Anduin returned home after that war but chose not to reclaim his throne. As the Midnight era opens, Turalyon still governs Stormwind as regent. At the end of the Midnight campaign he was lost to the Void with Alleria, and his fate is unknown. Other human realms have recovered. Stromgarde was restored under King Danath Trollbane, Gilneas was reclaimed, and Kul Tiras rejoined the Alliance."
  ]],
  ["Light, Ambition and Short Lives", [
    "Humans live short lives compared with most of Azeroth's peoples, and they are known for pride, ambition and quick recovery from disaster. They build fast and in stone. Many of history's greatest magi have been human, from the Kirin Tor of Dalaran to the Guardians of Tirisfal.",
    "The Church of the Holy Light shapes most human societies. Its holy warriors, the paladins of the Order of the Silver Hand, were founded during the Second War. Their name recalls a vrykul legend about Tyr, who lost a hand fighting a great evil and replaced it with one of silver. Some humans follow other paths, such as the sea goddess of Kul Tiras or the harvest witches of Gilneas. Stormwind, rebuilt from the ashes of the First War, has become the symbol of a people who keep rising after every fall."
  ]]
];

window.RACE_STORIES['kultirans'] = [
  ["Sailors from Gilneas", [
    "Kul Tiras began as a colony of the Empire of Arathor, the first great human kingdom. After the Troll Wars, about 2,700 years before the Dark Portal opened, Arathi settlers built harbors along the coast of Gilneas. The boldest of their sailors found a large island in the Great Sea, rich in metal ore and other resources. The first tidesages, sailors who heard the voice of a sea goddess they called the Tidemother, guided others there. They founded a maritime outpost named Kul Tiras, centered on the town of Boralus.",
    "The island already had people. The Drust, a tall race descended from vrykul who had sailed there long before, did not welcome the newcomers and raided them for generations. The settlers founded the Order of Embers to fight back. Finally Colonel Arom Waycrest led an assault on the Drust city of Gol Osigr and killed their king, Gorak Tul. The Drust were all but wiped out, and Arom became the founder of House Waycrest. A few Drust who kept to their druidic ways joined Kul Tiran society, and their teachings survive among the druids called Thornspeakers."
  ]],
  ["Masters of the Great Sea", [
    "When Arathor split into the Seven Kingdoms around 1,200 years before the Dark Portal, Kul Tiras became an independent nation. It had the largest navy of any human state. Its merchant fleets sailed the coasts of the Eastern Kingdoms and came home with exotic goods and tales of distant lands. Until the First War, Kul Tiras was the richest nation in the known world. Gilneas, unable to compete at sea, turned to its armies instead.",
    "Four noble houses grew to rule the islands. House Proudmoore of Tiragarde Sound commanded the fleet and the guard, and its head, the Lord Admiral, led the nation. House Waycrest of Drustvar supplied ore and soldiers. House Stormsong of Stormsong Valley worked with the tidesages to build and bless the ships. House Ashvane controlled much of the nation's wealth. Each had a seat on the ruling council, and rivalry between them was constant."
  ]],
  ["Daelin Proudmoore's Wars", [
    "When the orcish Horde destroyed Stormwind in the First War, Lord Admiral Daelin Proudmoore backed the founding of the Alliance of Lordaeron. He became Grand Admiral of the Alliance fleet. In the Second War his ships smashed the crude Horde fleet near the island of Zul'Dare, though dragons forced him back. Later, near the island of Crestfall, his fleet and Wildhammer gryphon riders destroyed most of the Horde navy. That victory cost him dearly, because his eldest son Derek was lost with the Third Fleet.",
    "Daelin's daughter Jaina studied magic in Dalaran. During the Third War she took part of the Kul Tiran fleet west to Kalimdor with refugees from Lordaeron, apparently without telling her father. There she made peace with the orc leader Thrall and founded Theramore Isle. A few months after the war, Daelin arrived with a great fleet and attacked the orcs' new nation of Durotar. He seized Theramore and refused to hear his daughter. Jaina chose peace and helped the Horde stop him, and Daelin died in the battle for Theramore."
  ]],
  ["Years of Silence", [
    "The people of Kul Tiras demanded vengeance, but the rest of the Alliance had little pity for an admiral who had started a war on his own authority. In fury, Kul Tiras withdrew from the Alliance and closed itself off. Its anger fell mostly on Jaina, whom many saw as the daughter who betrayed her family. Daelin's widow, Katherine Proudmoore, became Lord Admiral.",
    "For years the outside world knew little of the islands. Without Daelin's leadership the four houses drifted apart. Piracy and corruption grew, the fleet went missing, and the guard was stretched thin. In Stormsong Valley, Lord Stormsong and many tidesages fell under the whispers of the Old Gods and secretly served the naga queen Azshara. In Drustvar, witches of the Heartsbane Coven, servants of the dead Drust, spread their influence as far as House Waycrest itself. Lady Ashvane began plotting to take the throne for herself."
  ]],
  ["Jaina's Homecoming", [
    "During the Fourth War, the Alliance needed a fleet to match the Horde and its new troll allies. Jaina volunteered to win back her homeland, but her return led to her imprisonment. With her help, Alliance champions worked across the islands to earn the houses' trust. They broke the Heartsbane Coven in Drustvar, defeated the corrupted tidesages at the Shrine of the Storm, and freed the trapped fleet from a magical storm.",
    "Jaina then faced her own past, reconciled with her mother and brought the fleet home. When House Ashvane attempted a coup during the Siege of Boralus, the Alliance stopped it. Katherine stepped aside, and Jaina was named Lord Admiral. Kul Tiras rejoined the Alliance and sent its fleet against the Zandalari capital of Dazar'alor. Jaina's brother Derek, whom Sylvanas Windrunner had raised as an undead and stripped of free will, later escaped to the Alliance with the help of a Forsaken sympathizer."
  ]],
  ["The Admiralty Today", [
    "Kul Tiras has stayed in the Alliance since. During the war against the Jailer, his servants captured Jaina in Boralus and took her to the Maw, the realm of damned souls, but she returned. Pirates remained a problem for years after. When Xal'atath destroyed Dalaran in The War Within, Jaina and Thrall called the leaders of both factions to a joint meeting in Boralus to plan the campaign in Khaz Algar. As of the Midnight era, Jaina remains Lord Admiral."
  ]],
  ["Sea, Storm and Steel", [
    "Kul Tirans tend to be broader and more rugged than their mainland cousins, and their clothing is made for harsh weather. Most worship the Tidemother and look to the sea for guidance the way others look to the Light. Tidesages bless every ship. The dead are usually sent to the sea, where the tidesages ring a bell called the Dead Ringer to release their souls. Drustvar is different. Many of its people follow the Holy Light, and the region buries its dead.",
    "The sea runs through every part of Kul Tiran life. Ships are built with storm silver, a light metal that resists rust and is blessed and sunk underwater for a year before use. Horses are trained not to fear the surf. Piracy is one of the worst crimes under Kul Tiran law and is punished by death. The national color is green, and a startled Kul Tiran is likely to exclaim, \"For tides' sake!\""
  ]]
];

window.RACE_STORIES['worgen'] = [
  ["The Druids of the Pack", [
    "The worgen curse began with the night elves, about 9,300 years before the Dark Portal opened. During the War of the Satyr, a group of night elf druids called the Druids of the Pack learned to take a wolf form that carried the fury of Goldrinn, the great wolf among the Wild Gods. They could not control its rage. The druid Ralaar Fangfire and the moon priestess Belysra Starbreeze tried to tame it by binding one of Goldrinn's fangs to a staff blessed by the moon goddess Elune. The result was the Scythe of Elune.",
    "The scythe made things worse. It turned Ralaar and his followers into worgen, upright wolf-beasts ruled by their instincts. They tore through the satyrs and their own allies alike, and every night elf they wounded became a worgen too. To stop the spread, the archdruid Malfurion Stormrage and a regretful Belysra sealed the worgen in an endless sleep inside the Emerald Dream, the spirit world of nature. Ralaar, now called Alpha Prime, would wait there for thousands of years."
  ]],
  ["Gilneas Behind Its Wall", [
    "Gilneas began as a string of harbors built by settlers from the human empire of Arathor. It became one of the Seven Kingdoms, known for its strong army. Under King Archibald Greymane it also became the most industrial of the human nations, full of factories and firearms. His son, King Genn Greymane, was proud, stubborn and suspicious of outsiders.",
    "Genn joined the Alliance of Lordaeron during the Second War but held his armies back until the orcs reached his own borders. Afterward he resented paying Gilnean taxes for the camps that held the captured orcs. When Thrall freed the orcs from those camps, Genn withdrew Gilneas from the Alliance. He built the Greymane Wall across the land route into his kingdom, and it was finished before the Third War. When the Scourge destroyed Lordaeron, he would not open the gates even to human refugees."
  ]],
  ["Arugal's Mistake", [
    "The Scourge soon gathered outside the Greymane Wall. As his soldiers died, Genn allowed the Dalaran archmage Arugal to summon the sleeping worgen from the Emerald Dream. The beasts tore the undead apart. Then they turned on the Gilnean soldiers. Arugal went mad, swore himself to Alpha Prime, and turned the castle of Baron Silverlaine in Silverpine Forest into the haunted Shadowfang Keep. He also cursed the nearby village of Pyrewood to become worgen every night.",
    "Some bitten Gilnean soldiers had already returned behind the wall. When they changed, they were hunted, but the curse could not be stamped out. At the same time, the nobleman Darius Crowley led the Northgate Rebellion against Genn, angry that the king had left Crowley's lands outside the wall. Through the Wolf Cult, Alpha Prime's followers spread the curse inside Gilneas for years. Genn and his nobles secretly hunted feral worgen in the forests during the full moon, hoping to avoid panic. Other worgen packs appeared elsewhere, including the Nightbane of Duskwood."
  ]],
  ["The Fall of Gilneas", [
    "The Cataclysm cracked the Greymane Wall and sank part of the Gilnean coast. The Forsaken, ordered by the Horde's new warchief Garrosh Hellscream to take Gilneas and its ports, poured in. In the same days, the worgen of the Wolf Cult overran Gilneas City, and many of its defenders, including Crowley, were bitten. The royal chemist Krennan Aranas made a potion that brought some victims back to their senses for a while.",
    "Belysra Starbreeze, the night elf priestess who had helped make the scythe long ago, led the cursed Gilneans to the hidden grove of Tal'doren. There they performed the Ritual of Balance, a night elf rite that brings the human and wolf sides of the mind into balance. Genn revealed that he too was a worgen, and loyalists and rebels united against the Forsaken. They retook their capital, but Sylvanas Windrunner killed Genn's son, Prince Liam. The night elves carried the survivors to Darnassus, and Gilneas formally rejoined the Alliance. Crowley stayed behind to keep fighting the Forsaken in the Gilneas Liberation Front."
  ]],
  ["A Long Exile and a Return", [
    "For over a decade the Gilneans lived as refugees, first in Darnassus and later in Stormwind. Genn's hatred of Sylvanas drove much of what he did. During the Legion invasion his worgen formed a large part of the Alliance assault on the Broken Shore, and in Stormheim he wrecked Sylvanas's attempt to bind the Val'kyr Eyir. In the Fourth War, Sylvanas burned Teldrassil, the night elves' world tree, where many Gilneans had made new homes. Gilnean forces under Princess Tess Greymane and Lorna Crowley later fought for the night elves in Darkshore.",
    "In the Dragonflight era, Genn finally led his people home. The Scarlet Crusade had seized Gilneas City after the Forsaken withdrew. Tess asked the Forsaken of the Desolate Council for help, and together they drove the zealots out. With Gilneas secure, Genn abdicated, and Tess, who is not afflicted by the curse, became Queen of Gilneas. Genn himself later governed Stormwind on the regent's behalf during the war in Khaz Algar."
  ]],
  ["Living With the Curse", [
    "The curse spreads through a worgen's bite or by drinking its blood. A worgen is larger, faster and stronger than a human, with keen senses and the ability to run on all fours. Rage and guilt draw out the beast, and a worgen consumed by them can lose its mind for good. Disciplined worgen like Genn and Crowley keep their minds through the Ritual of Balance and constant self-control, and they can shift back to human form at will. The curse cannot be cured, but sanity can be restored to those who are not too far gone.",
    "Gilnean worgen still see themselves as Gilneans first. Tess concluded that being Gilnean in spite of the curse is what defines her people. Many still follow the Holy Light, while others now revere Goldrinn, whose fang began it all. The old harvest witches of Gilneas found their nature magic strengthened by the curse, and some trained as druids with the night elves. Because the curse resists undeath, the Forsaken's Val'kyr could not raise worgen as Forsaken. Feral packs such as the Bloodfang still live wild in the forests of Lordaeron."
  ]]
];

window.RACE_STORIES['forsaken'] = [
  ["Death Comes to Lordaeron", [
    "The Forsaken began as the people of Lordaeron, the richest human kingdom of the north. In Year 20 a plague spread through its grain. Those who died rose as the Scourge, mindless undead soldiers of the Lich King, a spirit imprisoned in the ice of Northrend. Prince Arthas Menethil, now a death knight bound to the Lich King, murdered his father and led the Scourge across the land. Lordaeron's people died by the thousands and joined the army that killed them.",
    "Arthas then marched on Quel'Thalas, the high elf kingdom. Its ranger-general, Sylvanas Windrunner, fought him every step of the way. When he finally defeated her, he tore her soul from her body and made her a banshee, a spirit forced to serve him. She would become the founder and queen of the Forsaken."
  ]],
  ["Breaking Free", [
    "In Year 21, after the night elf Illidan Stormrage attacked the Frozen Throne, the Lich King's power began to fade. Many undead in Lordaeron woke from his control with their minds and memories restored. Sylvanas was among them. When Arthas left for Northrend, she gathered the free-willed undead and seized power in the Plaguelands. The dreadlord Varimathras swore loyalty to her, and she used the remaining human forces of Lordaeron, then betrayed and killed them once the ruins of the capital were hers.",
    "Sylvanas named her people the Forsaken. They took over the catacombs beneath the ruined capital, which the Scourge had begun to build, and finished them as the Undercity. Freedom came with a terrible cost. The Forsaken remembered what they had done as Scourge, and every living nation saw them as monsters to destroy."
  ]],
  ["An Alliance of Need", [
    "Sylvanas sent envoys to find allies. Those sent to the Alliance never returned. In Kalimdor, the tauren archdruid Hamuul Runetotem saw a chance for redemption in the Forsaken and persuaded the orc warchief Thrall to accept them. The undead claimed they hoped for a cure for their condition. In return they promised to support the Horde in the Eastern Kingdoms, and the Horde gained a foothold there.",
    "In the early years of World of Warcraft, the Forsaken fought the Scarlet Crusade, human zealots who sought to destroy all undead. They battled the Alliance over Hillsbrad and Arathi. In secret, the Royal Apothecary Society worked on a new plague meant for the Scourge, and possibly for the living as well. The Forsaken also helped the blood elves of Quel'Thalas reclaim their lands and supported their entry into the Horde."
  ]],
  ["Vengeance and Betrayal", [
    "When the Horde invaded Northrend, Sylvanas led her own forces to the Howling Fjord. At the Wrathgate, where Alliance and Horde armies faced the Lich King together, Grand Apothecary Putress poured a new plague over the battlefield and killed soldiers of both sides. At the same moment Varimathras seized the Undercity. Sylvanas, Thrall and the troll leader Vol'jin retook the city, but the Horde never fully trusted the Forsaken again. Arthas was finally slain, and Sylvanas was left without the purpose that had driven her.",
    "Then came a new way to grow. Sylvanas made a pact with the Val'kyr, winged spirits who had served the Lich King, and they could raise the dead as new Forsaken. On Garrosh Hellscream's orders, the Forsaken invaded Gilneas and raised many of its fallen. Not every new Forsaken welcomed the gift. Some, like Lilian Voss, were horrified by what they had become. When Garrosh's rule turned brutal, Sylvanas joined the rebellion against him."
  ]],
  ["Abandoned by Their Queen", [
    "During the Legion invasion the dying Vol'jin named Sylvanas warchief of the Horde. While she ruled from Orgrimmar, a group of Forsaken formed the Desolate Council to govern the Undercity. Some of them wanted the right to remember their old lives and see their living families. At the Gathering, a meeting between Forsaken and their living relatives, Arthas's sister Calia Menethil appeared and urged them to join the Alliance. Sylvanas had them all slain. Calia was then brought back under the guidance of the naaru Saa'ra as an undead infused with the Holy Light.",
    "In the Fourth War, Sylvanas burned the night elf city of Teldrassil. When the Alliance struck back at Lordaeron, she flooded the Undercity with plague rather than lose it, and its people fled to Orgrimmar as refugees. She raised fallen night elves to swell her armies and even took away the free will of the undead Derek Proudmoore. Finally, at the gates of Orgrimmar, she abandoned the Horde and called her own people nothing. Lilian Voss stepped forward to speak for the Forsaken on the new Horde Council."
  ]],
  ["The Desolate Council", [
    "After the war against the Jailer, the Forsaken returned to Tirisfal Glades to reclaim their homeland. With help from the realm of Maldraxxus they cleansed the surface ruins of Lordaeron of plague, though the Undercity itself remains sealed. Lilian Voss argued that her people held many views and should be led by a council. A new Desolate Council was formed: Voss, Calia Menethil, Deathstalker Commander Belmont, Dark Ranger Velonara and Master Apothecary Faranell.",
    "The council has led the Forsaken since. It beat back the Scarlet Crusade in Silverpine Forest and withdrew Forsaken troops from Gilneas. It then sent the Forsaken army to help the Gilneans retake their kingdom from the Crusade, a rare act of trust between old enemies. Sylvanas, from her penance in the Maw, sent word to her loyalists that the council was their rightful leadership. Forsaken soldiers have since fought with the Horde in Khaz Algar. In the Midnight era, Calia stood among the Light-wielders who defended the Sunwell of Quel'Thalas against Xal'atath."
  ]],
  ["The Nature of the Forsaken", [
    "Most Forsaken were humans of Lordaeron, though high elves, night elves and others are among them. Their bodies decay, they feel little pain or taste, and they repair themselves by grafting on new flesh. They do not need to eat, breathe or sleep. Without the Val'kyr they can no longer add to their numbers on a large scale, so every loss matters.",
    "Free will is the cornerstone of Forsaken identity, since it is the line between them and the Scourge. Many take new names to mark their rebirth. They speak a language of their own called Gutterspeak. Some still serve the Holy Light despite the pain it causes them, while others follow the Cult of Forgotten Shadow, which teaches balance between Light and darkness. The harshest punishment in their law is true death, and a Forsaken who chooses to die willingly is said to accept the Last Death."
  ]]
];

window.RACE_STORIES['vrykul'] = [
  ["Forged for Odyn", [
    "The vrykul were among the titan-forged, the servants made to shape and guard Azeroth. The Keepers, powerful beings empowered by the titans, created them of living iron at the Forge of Wills in Northrend. The keeper Odyn wanted his own army of heroes and chose the vrykul. He raised part of the titan city of Ulduar into the sky as the Halls of Valor and promised that vrykul who died with honor would be reborn there as his immortal Valarjar warriors.",
    "Someone had to carry the souls of the fallen to those halls. When no vrykul would volunteer, Odyn turned his adopted daughter Helya into the first Val'kyr, a winged spirit of death. Helya resented him for thousands of years. In time she sealed Odyn inside his own halls and began claiming vrykul souls for her realm of Helheim, where her undead sea raiders, the kvaldir, still serve her."
  ]],
  ["The Curse of Flesh", [
    "The Old God Yogg-Saron, imprisoned beneath Ulduar, planted a corruption called the Curse of Flesh in the Forge of Wills. Slowly it turned the titan-forged from metal and stone into flesh and blood, making them mortal. The fierce Winterskorn clan felt it first. While they waged war across the Storm Peaks, their iron skin grew brittle and weak, and the dragons Ysera and Nozdormu finally put them into a timeless sleep.",
    "Other vrykul fled south with the keeper Tyr, who was trying to save the titan-forged from the corrupted keeper Loken. In the land later called Tirisfal Glades, Tyr died fighting a monstrous servant of the Old Gods so the others could escape. The vrykul who were with him settled at his grave and swore to guard it forever. Meanwhile the Dragonflayer clan of Northrend tamed proto-dragons to make up for their fading strength and drove their enemies south under King Ymiron."
  ]],
  ["Ymiron's Decree", [
    "About 15,000 years before the Dark Portal opened, Dragonflayer mothers began bearing children who were small and frail. Vrykul society split over what to do. King Ymiron decided that the titans themselves had cursed his people. He outlawed titan worship and ordered every such infant killed, and parents who refused were to be executed.",
    "Some parents hid their children and carried them to Tirisfal, where Tyr's vrykul guardians still lived. They raised the children in secret, taught them vrykul stories, smithing and warfare, and left them with the guardians before returning home. These outcasts became the first humans. A warrior named Skadi hunted down many of the parents who defied the king and earned the name Skadi the Ruthless. Later, hoping to escape the curse, the Dragonflayers sealed themselves in great vaults and slept for thousands of years."
  ]],
  ["Wanderers of the North", [
    "Not every vrykul slept. Some crossed the sea to Stormheim, on the Broken Isles, beneath the Halls of Valor. There King Magnar Icebreaker drove out the night elf Highborne, and Stormheim became sacred ground where vrykul worshiped Odyn and hoped to join his Valarjar. Other vrykul took to the sea after the Great Sundering. One group settled the islands of Kul Tiras and became the Drust, who later fought the human colonists there and were nearly wiped out."
  ]],
  ["Servants of the Lich King", [
    "When the Lich King stirred in Northrend, the sleeping vrykul woke. Many saw him as a god of death and pledged themselves to him. King Ymiron led them again from Utgarde Keep, and the Dragonflayers under Ingvar the Plunderer attacked the Alliance port of Valgarde in the Howling Fjord. In the pits of Jotunheim, vrykul warriors fought for the right to be raised as undead. Winners became the elite Ymirjar, losers became the lesser undead called vargul, and some vrykul women became Val'kyr in the Lich King's service.",
    "Not all followed him. The Hyldnir women of the Storm Peaks stayed loyal to the keeper Thorim. Ymiron fell before he could unite the vrykul under the Lich King, and most of the Scourge vrykul died in Icecrown. After the Lich King's defeat, some of his Val'kyr joined Sylvanas Windrunner and the Forsaken. In these same years Alliance explorers learned from visions of the past that the vrykul were the ancestors of humanity."
  ]],
  ["Stormheim and the Legion", [
    "During the Legion invasion, Stormheim became a battlefield. Its vrykul king had been murdered by his son Skovald, who killed his brothers and declared himself God-King of the Tideskorn clan. He allied with the Burning Legion and tried to seize the Aegis of Aggramar, one of the titans' relics, from the Halls of Valor. He failed and died before Odyn's throne. Other vrykul, the Valarjar of Valdisdall, stayed loyal to Odyn and fought the demons. Champions also descended into Helheim and defeated Helya.",
    "Skovald's daughter Sigryn had been foretold by the Val'kyr Eyir to unite the Tideskorn against the Legion. She defeated rival leaders and overcame the fel taint in her own blood, and Eyir made her God-Queen of the Tideskorn."
  ]],
  ["The Vrykul Today", [
    "With no death god left to serve, the vrykul of Northrend have gone back to their old ways. The Dragonflayers still raid the human port of Valgarde, the Winterskorn have rebuilt their village of Skorn, and slumbering vrykul are still being woken in the fortress of Gjalerhorn. At sea, the Bloodwake clan under its raider-king Jorun hunts treasure across the oceans, and in The War Within it fought for crystal on the Siren Isle. In the Midnight era, vrykul are among the peoples taken by the Domanaar to fight in their Voidscar Arena.",
    "Vrykul are giants, larger than tauren, and live as warriors, seafarers and proto-dragon riders. They prize glory, honor and a worthy death in battle. Women of the household keep its keys as a sign of status, and Bonespeakers, vrykul mystics, bury kings and thanes. Their magic is carved in runes and tattoos. Many vrykul legends passed down to humanity, including the tale of Tyr's silver hand that gave the paladins of the Silver Hand their name."
  ]]
];
