window.RACE_STORIES = window.RACE_STORIES || {};

window.RACE_STORIES['nightelves'] = [
  ["Trolls by the Well", [
    "The night elves began as a tribe of dark trolls. Long before any human kingdom existed, this quiet, nocturnal tribe settled on the shores of the Well of Eternity, a vast lake of raw magic at the heart of the ancient continent of Kalimdor. Over many generations the Well's power changed them. They grew taller and stronger, their skin turned shades of violet, and they stopped aging.",
    "The new people began to worship Elune, a moon goddess they believed slept in the Well's depths by day. They named themselves kaldorei, which means \u201cchildren of the stars.\u201d Cenarius, a demigod of the forests, befriended them and taught them about the natural world. For thousands of years the night elves denied that they came from trolls. Proof of their troll ancestry came only in recent times, from Cenarius and from ancient titan records."
  ]],
  ["Azshara's Empire", [
    "In time many night elves turned from the forests to the arcane. Their sorcerers learned to draw on the Well, and their society grew into the Kaldorei Empire, which spread across most of Kalimdor. Its armies broke the great troll empires of the Gurubashi and the Amani, a defeat the trolls never forgave. The empire's ruler was Queen Azshara, a sorceress so adored that her people renamed their capital Zin-Azshari, \u201cthe Glory of Azshara.\u201d",
    "Azshara's favored nobles were called the Highborne. They thought themselves better than other elves, and they pushed their experiments with the Well further and further. Their magic caught the attention of Sargeras, a fallen titan who leads the Burning Legion, an endless army of demons. Posing as a god, Sargeras persuaded Azshara and her advisor Xavius to open a gateway so that he could enter the world."
  ]],
  ["The War of the Ancients", [
    "About ten thousand years before the Dark Portal opened, demons poured out of the queen's palace. A small band of night elves led the resistance. Malfurion Stormrage was a student of Cenarius and the first druid. Tyrande Whisperwind was a priestess of Elune. Malfurion's twin brother Illidan was a gifted sorcerer, and Jarod Shadowsong became a reluctant commander. Dragons, demigods, and many other races joined them.",
    "Malfurion disrupted the portal before Sargeras could come through. The strain was too much for the Well of Eternity, and it collapsed in a disaster called the Great Sundering. Most of Kalimdor sank or broke apart, and a permanent storm, the Maelstrom, formed where the Well had been. Azshara and her court were dragged into the sea and later became the naga. The Highborne of the city of Suramar survived under a magical shield and became the nightborne."
  ]],
  ["The Long Vigil", [
    "The survivors settled on Mount Hyjal and gave up arcane magic, which they now saw as the cause of their ruin. Illidan secretly made a new Well by pouring stolen water from the old one into a lake. He was imprisoned for it, guarded by the warden Maiev Shadowsong. Three great dragons then planted the World Tree Nordrassil over the new Well to hide its power. Nozdormu blessed the tree so that night elves would never age while it stood, and Ysera bound the druids to the Emerald Dream, a spirit realm where they slept for centuries at a time.",
    "Tyrande led the people as high priestess, and the Sisters of Elune commanded the Sentinels, an army made up mostly of women. Some Highborne could not live without magic. Around 7,300 years before the Dark Portal, their leader Dath'Remar unleashed a magical storm on Ashenvale in protest, and the night elves exiled them. They sailed east and became the high elves. The night elves hid their lands behind mist and fought alone through later wars against the satyrs and the insect armies of Ahn'Qiraj."
  ]],
  ["Hyjal and the Alliance", [
    "The Third War ended the night elves' isolation. Orcs arrived in Ashenvale and killed Cenarius, and then the Legion and its undead Scourge marched on Hyjal. Tyrande woke Malfurion and his druids, and the night elves fought beside humans and orcs at the Battle of Mount Hyjal. Malfurion destroyed the demon lord Archimonde with the power of Nordrassil itself. The cost was high, because the tree's blessing was spent and the night elves became mortal again.",
    "Archdruid Fandral Staghelm planted a second World Tree, Teldrassil, off Kalimdor's northern coast without the dragons' blessing, and the night elves built their capital, Darnassus, in its branches. They joined the Alliance. Fandral, now leader of the druids, was later exposed as a secret ally of Xavius and the Emerald Nightmare, a corruption of the Dream. Malfurion and Tyrande married and shared the rule. After the Cataclysm they lifted the ban on arcane magic and welcomed Highborne back into society, and they sheltered the worgen of Gilneas. During the Legion's third invasion, night elves fought beside high elves, blood elves, and nightborne to free Suramar, the first time all the elves worked together."
  ]],
  ["Fire and Renewal", [
    "During the Fourth War, Horde forces under Sylvanas Windrunner burned Teldrassil, killing a great many of the people who lived there. In her grief Tyrande performed a ritual to become the Night Warrior, an avatar of Elune's wrath, and drove the Horde out of Darkshore. In the Shadowlands, the realms of the dead, she later chose renewal over vengeance. Sylvanas was sentenced to free the souls trapped in the Maw, among them many night elves lost in the fire.",
    "During the events of Dragonflight, a new World Tree, Amirdrassil, grew in the Emerald Dream and then bloomed into the waking world on the Dragon Isles. The night elves defended it from Fyrakk, a primal dragon of fire, and from the Druids of the Flame. They built a new home, Bel'ameth, \u201cArms of the Goddess,\u201d beneath its roots. Tyrande and Malfurion then stepped down and named Shandris Feathermoon, general of the Sentinels and their adopted daughter, as leader of the night elves.",
    "In Midnight, the leaders of the blood elves, nightborne, and void elves came to Bel'ameth to ask for help retaking the Sunwell from Xal'atath and her forces of the Void. Over Maiev's objections, Shandris lent them her army, woke the ancients, and led the charge on the Isle of Quel'Danas. She offered water from a Moonwell to help purify the well, and she warned the blood elves to think hard before restoring its power. Afterward the haranir, a hidden underground people, told the gathered elves and trolls that both races descend from haranir who stayed on the surface long ago."
  ]],
  ["Moon, Grove, and Sentinel", [
    "Night elf faith centers on Elune, though they speak of the gods in the plural. Moonwells, pools blessed by the goddess, heal wounds and bless food. Night elves also honor their ancestors and believe that the valiant dead ride across the sky as stars. Druids of the Cenarion Circle, which Malfurion founded, guard the balance of nature and stay neutral between the factions.",
    "For ten thousand years their society was divided by gender. Most men became druids, and most women became priestesses or Sentinels. These lines have eased since the Third War, but they still shape night elf life. Many night elves alive today are thousands of years old, so they change slowly, feel deeply, and remember everything. They are strongest at night, call the animals of the forest their kin, and speak Darnassian among themselves."
  ]]
];

window.RACE_STORIES['bloodelves'] = [
  ["Exiles from Kalimdor", [
    "The blood elves descend from the Highborne, the magic-loving nobles of the ancient night elf empire. After the Great Sundering, the night elves banned arcane magic, but many Highborne suffered painful withdrawal without it. Around 7,300 years before the Dark Portal opened, their leader Dath'Remar Sunstrider and his followers unleashed a magical storm on Ashenvale to defy the ban. The night elves would not execute so many of their own, so they exiled them.",
    "The Highborne built a fleet and sailed east, taking with them a stolen vial of water from the Well of Eternity. They landed on the continent now called the Eastern Kingdoms. Cut off from the Well, they lost their immortality. Over time they grew shorter, their skin paled, and they began to age and fall sick. They settled for a while in Tirisfal Glades, but dark energies there drove some of them mad, and Dath'Remar led them north."
  ]],
  ["The Kingdom of the Sun", [
    "Around 6,800 years before the Dark Portal, the exiles reached a place in the far north where powerful ley lines met. Dath'Remar poured the vial into a lake on the Isle of Quel'Danas, and a fountain of energy rose into the sky. They called it the Sunwell. They crowned Dath'Remar their first king, named their land Quel'Thalas, \u201cHigh Home,\u201d and became known as the high elves. They turned away from Elune and the moon and took their strength from the sun.",
    "Quel'Thalas was built on land the Amani trolls held sacred, and the trolls fought hard to drive the elves out. The elves raised a ring of Runestones called Ban'dinoriel to hide their magic and keep the trolls at bay. Inside it they built Silvermoon City and the forests of Eversong, a land of endless spring. A council called the Convocation of Silvermoon governed alongside the Sunstrider kings."
  ]],
  ["Old Allies of Humanity", [
    "About 2,800 years before the Dark Portal, the Amani and their Zandalari allies attacked in such numbers that the elves faced destruction. King Anasterian Sunstrider asked the human Empire of Arathor for help. In exchange, elven mages taught one hundred humans to use magic. Together they burned the troll army and won the Troll Wars, and the elves swore an oath of friendship to the bloodline of the human king Thoradin.",
    "That oath brought the elves into the Second War against the orcs, though Anasterian sent only a small force. The Horde and the Amani burned the forests of Eversong. Rangers such as Alleria Windrunner fought far beyond Quel'Thalas. After the war Anasterian blamed the humans for failing to protect his land, and he took his kingdom out of the Alliance."
  ]],
  ["The Fall of Quel'Thalas", [
    "In Year 20 the death knight Arthas Menethil led the Scourge into Quel'Thalas. Ranger-General Sylvanas Windrunner fought a long retreat, but the traitor Dar'Khan Drathir broke the kingdom's magical defenses. Arthas killed Sylvanas and turned her into a banshee, killed King Anasterian, and used the Sunwell to raise the necromancer Kel'Thuzad as a lich. Roughly ninety percent of the high elves died.",
    "Prince Kael'thas Sunstrider returned from Dalaran to find his kingdom in ruins. The Sunwell's corrupted energy was poisoning his people, so he destroyed it. The survivors took a new name, sin'dorei, \u201cchildren of the blood,\u201d in memory of their dead. Without the Sunwell they suffered a crippling hunger for magic. Kael'thas went to Outland, where Illidan Stormrage taught him to feed on other sources of magic, including demons. He left Lor'themar Theron, a former ranger, to rule as regent."
  ]],
  ["Rebirth in the Horde", [
    "Back home, Grand Magister Rommath taught the elves to drain magic from crystals and creatures. Those who lost control became the wretched, mindless addicts. Pressed by the Scourge and the Amani, Lor'themar accepted an offer from Sylvanas, now ruler of the Forsaken, to join the Horde. Then the truth about Kael'thas came out. He had sworn himself to the demon lord Kil'jaeden and tried to bring him into the world through the Sunwell. Heroes stopped him, and in Year 26 the draenei prophet Velen relit the Sunwell with the heart of the naaru M'uru. It now held both arcane magic and the Holy Light.",
    "Lor'themar refused to take the crown and kept the title of regent lord. Later he nearly left the Horde when Warchief Garrosh Hellscream endangered his people. When Jaina Proudmoore purged the blood elves from Dalaran, he chose to stay, and he backed the rebellion that overthrew Garrosh. During the Legion invasion, blood elves helped the nightborne free Suramar. During the Fourth War, Lor'themar sided with the rebels against Sylvanas, joined the new Horde Council, and later married Thalyssra, leader of the nightborne."
  ]],
  ["Midnight and the Dawnwell", [
    "In Midnight, Xal'atath, a herald of the Void, and her Devouring Host attacked the Sunwell. As Lady Liadrin prayed for help, Azeroth herself answered and sent the Vanguard of the Light, drawing most of the world's priests and paladins to the Sunwell. Silvermoon then let the Vanguard and its Alliance members into part of the city, which led to many tense moments. Meanwhile the blood elves made peace with the Amani trolls and won the help of the haranir.",
    "After a battle at the Voidspire, Xal'atath tore the dark naaru L'ura from Alleria Windrunner and used it to corrupt the Sunwell into the Darkwell. The blood elves called on every elven people. Night elves, nightborne, void elves, and high elves marched with them to retake Quel'Danas. Each people gave a gift to cleanse the well, and Liadrin then filled it with the Light. It became the Dawnwell. It is gentler and weaker than the old Sunwell, and the nightborne's arcan'dor fruit is expected to ease the elves' old hunger for magic. Afterward the high elves of the Silver Covenant and the blood elves of the Sunreavers ended their feud and formed the Silversun Compact."
  ]],
  ["Phoenix and Sun", [
    "The blood elves chose the phoenix as their symbol, a bird reborn from its own ashes, and they favor red and gold. They speak Thalassian, a language descended from ancient Darnassian, and they greet each other with words about the sun. Three great orders protect the kingdom. The Farstriders are its rangers, the Magisters are its mages, and the Blood Knights are its paladins, who draw the Light through the Sunwell.",
    "Blood elves are proud, practical, and fiercely loyal to their homeland. Many never leave Silvermoon, and noble politics there can be as dangerous as any battlefield. They have learned the cost of chasing power, so dark magic is restricted, which is the same kind of rule that once drove their ancestors out of Kalimdor. Each year a champion carries a lantern lit by the Sunwell to remember those who fell to the Scourge."
  ]]
];

window.RACE_STORIES['voidelves'] = [
  ["Alleria and the Shadow", [
    "The story of the void elves begins with Alleria Windrunner, a high elf ranger who fought the orcs in the Second War. After the war she followed the Alliance through the Dark Portal and vanished into the Twisting Nether with her beloved, the paladin Turalyon. They spent what felt to them like a thousand years fighting demons with the Army of the Light.",
    "During that long war, Alleria was touched by the Void, the dark force of shadow that opposes the Light. She learned to control it from Locus-Walker, an ethereal, a being made of energy, who had mastered the Void. On the demon world of Argus she absorbed the essence of L'ura, a naaru fallen into darkness, and gained a shadowy form. Alleria said she was still herself. She became the first void elf."
  ]],
  ["Exiles of Silvermoon", [
    "After the Sunwell was restored in Year 26, it held the Holy Light as well as arcane magic, and the Magisters of Silvermoon banned rituals of the Void. Magister Umbric and his followers believed the kingdom needed every source of power it could find, and they kept studying the Void against the orders of Grand Magister Rommath. After the war on Argus, Rommath had them banished, believing they endangered the Sunwell. Their homes and property were taken, and some left family behind.",
    "Umbric's group continued in the haunted Ghostlands of southern Quel'Thalas. They found notes left by Dar'Khan Drathir, the traitor who had helped the Scourge destroy Quel'Thalas, and used them to open a path to Telogrus Rift. This broken world floats in the Void beyond Azeroth. There they found an ancient cube that was said to grant control over shadows. At about the same time, Alleria visited Silvermoon to ask the blood elves to rejoin the Alliance. Something used the Void inside her to attack the Sunwell, and Lor'themar sent her away."
  ]],
  ["Born in Telogrus", [
    "Alleria followed Umbric's trail to Telogrus and arrived just as his followers opened the cube. Out came Nether-Prince Durzaan, a void ethereal who had stalked Alleria, and he began a spell to strip the elves of their flesh and turn them into creatures of the Void. Alleria and her companions killed him before the ritual finished. The elves kept their minds and souls, but their bodies were changed for good.",
    "Umbric apologized for his arrogance and accepted Alleria's offer to teach his people control. Since Silvermoon had cast them out, they swore loyalty to Alleria and to the Alliance. They took the name ren'dorei, \u201cchildren of the Void,\u201d and made Telogrus Rift their base. Locus-Walker helped train them. Other blood elves and high elves curious about the Void later came to Telogrus, and some chose to undergo the same change."
  ]],
  ["Proving Their Loyalty", [
    "During the Fourth War, Alleria and the void elves saved King Anduin Wrynn at the Battle for Lordaeron. Lor'themar called them traitors. Umbric led void elves on raids in Zandalar, and void elf mages helped the Alliance win the Battle of Dazar'alor. Their power carried a real risk. When the Old God N'Zoth rose, some void elves fell under his control.",
    "When Xal'atath returned during Dragonflight, the Shadowguard, an army of void ethereals, attacked Telogrus. Alleria decided to keep her distance from her people for their safety, and Umbric promised them she would return. In The War Within, the ren'dorei fought in Khaz Algar and on K'aresh against the void lord Dimensius. There Xal'atath killed Locus-Walker, and Alleria swore to hunt her down."
  ]],
  ["Return to Quel'Thalas", [
    "In Midnight, Xal'atath's Devouring Host struck Quel'Thalas, and the void elves came home to fight. Rommath still distrusted them and barred them from Silvermoon, so they worked from Tranquillien and Windrunner Village. Lor'themar was more open, and he sent Arator Windrunner, Alleria's son, to help them. When the paladin Turalyon finally approved using their skills, Umbric took an artifact called the Cynosure of Twilight from the Magisters' Terrace and led a ren'dorei strike team into the Voidstorm, the dark realm where Xal'atath had built her stronghold.",
    "At the Voidspire, Xal'atath tore L'ura out of Alleria and used the dark naaru to corrupt the Sunwell. Alleria and Turalyon were lost to the Void, and their fate is still unknown. Umbric pulled Arator back to Silvermoon. The void elves then cut a path for the elven armies that marched on Quel'Danas. Umbric placed a Void crystal in the corrupted well to balance its dark energy, one of the gifts that helped turn it into the Dawnwell. In return, Silvermoon granted the void elves an embassy in the city and let their magisters study at the Magisters' Terrace again. Void elves also began training as demon hunters with the Illidari, sharing their secrets of the Void."
  ]],
  ["Living with the Whispers", [
    "Most void elves have pale or blue-violet skin, glowing blue eyes, and hair in shades of purple and blue. Their blood is purple, and their voices carry a dark echo. They can open short rifts to step through space and can wrap themselves in shadow in battle. Some have kept more of their old looks.",
    "Every void elf hears whispers from the Void, mixing lies, half-truths, and promises. Resisting them takes constant discipline. A void elf's grief or loneliness can even take shape as a shade, a dark double that attacks them. They speak Thalassian and Common and stand with the Alliance by belief. Their bond with the blood elves is still raw, with families split and old grudges unhealed. The new embassy in Silvermoon is the first real step toward peace between them."
  ]]
];

window.RACE_STORIES['nightborne'] = [
  ["Jewel of the Empire", [
    "Ten thousand years ago, Suramar was one of the greatest cities of the Kaldorei Empire. It was the empire's center of magical learning, home to a famous academy where elves and even blue dragons studied the arcane. It was also a center of worship for Elune. Malfurion Stormrage, Illidan Stormrage, and Tyrande Whisperwind all grew up there.",
    "When Queen Azshara and her Highborne nobles invited the Burning Legion into the world, Suramar became a heart of the resistance. Many of its people marched to war against the demons. One group of Highborne stayed behind. Led by Grand Magistrix Elisande, they served the queen in Suramar and collected powerful artifacts in the city's vaults."
  ]],
  ["Elisande's Choice", [
    "As the War of the Ancients went on, Elisande came to distrust the Legion. Then she learned that demons planned to open a second portal inside Suramar's Cathedral of Eternal Night. She feared it would destroy the city. Her Highborne turned on the demons and used the Pillars of Creation, ancient titan artifacts, to seal the portal.",
    "Elisande did not join the march on the capital. She chose to defend Suramar. Using one of the Pillars, the Eye of Aman'Thul, her sorcerers created the Nightwell, a vast fountain of arcane power. They raised a shield over the city. When the Well of Eternity collapsed in the Great Sundering, part of Suramar fell into the sea, but most of it survived under the dome."
  ]],
  ["Ten Thousand Years Under Glass", [
    "Inside the shield, the people of Suramar believed the rest of the world had been destroyed. They lived under an artificial night sky, ruled by Elisande. When their food ran out, they began to live on the Nightwell's energy, drinking it as arcwine. The Nightwell kept them alive, but it made them deeply dependent on it, and over the ages it changed them into a new race. They called themselves shal'dorei, the nightborne.",
    "Their worst punishment was exile. An exile cut off from the Nightwell wasted away into a starving state called nightfallen. If that hunger went on too long, the elf became one of the withered, a feral creature with no mind left, and that change could not be undone. Meanwhile Suramar kept the magic, art, and manners of the old empire almost unchanged, and its arcanists kept improving their craft. Elisande herself mastered time magic."
  ]],
  ["The Nightfallen Rebellion", [
    "When the Legion invaded again in Year 32, the warlock Gul'dan gave Elisande a choice. She could lower the shield and give the demons the Nightwell, or Suramar would be destroyed. Elisande looked into possible futures and decided that resisting would doom her people, so she accepted. First Arcanist Thalyssra tried to stop her and was stabbed and left for dead.",
    "Thalyssra survived as a starving exile and built a rebellion from a hidden refuge called Shal'Aran. Her allies grew an arcan'dor, a magical tree whose fruit freed nightborne from their need for the Nightwell. Night elves under Tyrande, blood elves under Liadrin, and high elves under Vereesa Windrunner joined the fight. The rebels stormed Elisande's palace, the Nighthold, where Elisande and Gul'dan were killed. As the new ruler, Thalyssra let the dying Nightwell fade, so her people would never again depend on a single source of power."
  ]],
  ["A Place in the Horde", [
    "The Alliance seemed closed to the nightborne, and Tyrande distrusted Highborne who had hidden while Kalimdor burned. The blood elves, who had faced their own addiction and their own betrayal by a leader, had been more sympathetic. Liadrin invited Thalyssra to Silvermoon. Seeing that the Horde let the blood elves keep their old ways, Thalyssra pledged Suramar to the Horde.",
    "During the Fourth War, nightborne fought for the Horde and joined blood elf scholars on digs in Zandalar. When the Horde split, Thalyssra sided with the rebels against Sylvanas and took a seat on the Horde Council. She later married Lor'themar Theron, the regent of the blood elves, in Suramar. By the time of The War Within, every nightborne had been given the chance to eat the arcan'dor's fruit, and none still starved for magic."
  ]],
  ["Midnight", [
    "When Xal'atath's forces corrupted the Sunwell, Thalyssra joined the envoy that asked the night elves for help and gathered her own army. Her troops failed to arrive, and she found that agents of the Twilight's Blade, a doomsday cult, had killed her steward, taken his place, and drained Suramar's mana. A few nightborne mages had even helped the cult. Once the sabotage was stopped, the nightborne marched with the other elves to retake Quel'Danas and supported the attack from the sea.",
    "To help cleanse the corrupted well, Thalyssra gave a fruit of the arcan'dor, the same gift that had freed her own people. She dedicated it to the blood elves who had once come to Suramar's aid. Later she attended the haranir gathering in Harandar, where she was surprised to hear that elves and trolls share common ancestors."
  ]],
  ["Children of the Nightwell", [
    "The nightborne are tall elves with skin in shades of blue and violet. Magic runs through every part of their society. Constructs guard the streets and do chores, and children learn spellcraft very young. Their language, Shalassian, grew from ancient Darnassian, just as Thalassian did.",
    "Their culture is the closest living link to the Kaldorei Empire, with its nobles, artisans, vintners, and honor duels called Tal'ashar. Worship of Elune faded during the long isolation. Years under Legion occupation left them with a deep hatred of fel magic. They feel close to the blood elves and remain wary of the night elves, who see them as Highborne who never changed their ways."
  ]]
];

window.RACE_STORIES['haranir'] = [
  ["Hidden on Hyjal", [
    "The haranir are one of the oldest peoples of Azeroth, though almost no one knew they existed until very recently. They once lived in the forests of Mount Hyjal in northern Kalimdor, so well hidden that even Freya, a titan-made keeper who lived on the mountain, never found them. They were fierce hunters of the wolverines, quill-bears, and bats of those woods.",
    "At some point after about 16,000 years before the Dark Portal, by Blizzard's dating, the haranir grew restless and looked for a new purpose. Some of them looked up to the moon and stars. Others, including the group later called the Hara'ti, heard a song calling them from deep inside the world. They believed it came from their goddess, Aln'hara. Aln'hara is the haranir name for Azeroth's world-soul, the young titan growing at the planet's core."
  ]],
  ["The Echo in Harandar", [
    "The singers followed the song on a long journey underground to Harandar, a glowing jungle in a vast cavern where the roots of the World Trees meet. When they arrived, Aln'hara was gone. They heard only an echo of her song. She had been torn from her cradle in Harandar, and the violence of it left a wound called the Rift of Aln. Her cries of pain still pour out of the rift and give birth to monsters. Who took her, and how, has not been revealed.",
    "Harandar was in chaos, with fungal creatures and other beings at war. Tired and disheartened, the haranir joined the fighting and even fought one another. When peace finally came, they were too afraid to go back to the surface. Their elders forbade it. The Hara'ti still watch over the empty cradle, hoping their goddess will one day return."
  ]],
  ["Oaths of Silence", [
    "For ages the haranir guarded the great roots and kept themselves secret. Their oaths forbid them to reveal themselves to other races or even speak with them. They are meant to stay unseen, move through the brush, and hide in their animal forms. Anyone who sees them must be dealt with, and they sweep away traces of their nature magic with special scythes.",
    "Five elders lead the haranir: Hagar, Ter'kova, Gnarla, Ran'hune, and Nye'rangi. Hagar once served as a rootwarden of Teldrassil, tending the night elves' World Tree from below. The haranir can read the history of an ancient tree in the rings of its roots."
  ]],
  ["Orweyna's Visions", [
    "Heroes first met the haranir during The War Within, in Azj-Kahet, the underground kingdom of the nerubians, a spider-like people. A haranir named Orweyna had led a small band there to protect the roots from Black Blood, a corrupting substance. Most haranir did not think it was a threat. Orweyna heard Azeroth's song clearly and trusted her visions, so she broke her oaths and accepted help from outsiders.",
    "Her companions eventually tired of breaking tradition and went home to face the elders. Orweyna asked them to put the blame on her. She followed her visions on her own, uncovered a scheme by the goblin Jastor Gallywix to mine Black Blood, and revealed herself to Alliance and Horde leaders. The dwarf Magni Bronzebeard, who also speaks with Azeroth, urged her to find others to walk that path with her."
  ]],
  ["Coming Into the Light", [
    "In Midnight, outsiders traveled to Harandar and slowly earned the haranir's trust. Some haranir went up to the surface to commune with the World Trees, among them Nordrassil, Amirdrassil, and Teldrassil. Seeds from the Rift of Aln, brought to Quel'Thalas by the blood elf ranger Halduron Brightwing, helped stop a wild growth of Light-fed plants in Eversong. Haranir warriors carrying Alndust, a substance from Harandar, helped the elves retake their forests. They marched with the elves and the Amani trolls against Xal'atath on Quel'Danas.",
    "After the Sunwell was purified, the haranir invited the elves and trolls of Azeroth to a gathering. There Elder Hagar revealed that trolls and elves all descend from haranir who stayed on the surface. The elves and trolls present were stunned. The haranir offered visions of the past as proof, and the game later confirmed that they are the ancestors of all trolls, and through them of the elves. Blizzard's writers have said that the exact path, including where the dark trolls fit, is still open. After the gathering, individual haranir answered their goddess's call and joined both the Alliance and the Horde."
  ]],
  ["Keepers of the Roots", [
    "The haranir are often described as neither elves nor trolls. They have tapered, bat-like ears, small tusks, gray-purple skin partly covered in dark fur and quills, and clawed feet. They wear clothing made of leaves and thorns and can turn into bats. Their druids take the shapes of the predators their ancestors hunted on Hyjal.",
    "They are a deeply spiritual people whose traditions are private and sacred. The Shul'ka are honored warriors who cut their own bond with the goddess so they can enter the Rift of Aln without going mad and fight the horrors inside. The Zur'ashar are historians and artists who paint the past on Harandar's walls, and Alndust can bring those paintings to life as visions. The haranir dance in their rituals and to travel along the roots, and they steam their meals wrapped in saptor fronds."
  ]]
];

window.RACE_STORIES['naga'] = [
  ["The Queen's Court", [
    "The naga were once Highborne, the noble night elves who served Queen Azshara in the days of the Kaldorei Empire. They lived in splendor in her capital, Zin-Azshari, on the shore of the Well of Eternity. They studied its magic without restraint, and their experiments drew the attention of Sargeras and his Burning Legion. At Sargeras's command they opened a portal in the Well, starting the War of the Ancients.",
    "Among Azshara's closest servants was her handmaiden, Lady Vashj. When the night elf resistance closed the portal, the Well of Eternity collapsed. Azshara and her loyal Highborne were gathered in her palace when the sea rushed in."
  ]],
  ["The Pact in the Deep", [
    "As the ocean dragged them down into the Maelstrom, Azshara made a bargain with N'Zoth, an Old God, one of the ancient evil beings imprisoned deep beneath the world. She swore herself and her people to his service in exchange for their survival. At once she became the first naga, a scaled, serpent-bodied creature able to breathe water. Her followers changed with her.",
    "On the sea floor beneath the Maelstrom, the naga built a new capital, Nazjatar, and a hidden empire under the waves. Azshara grew into a huge and terrible figure. The naga resented being banished to the sea and planned to return to the surface one day. For more than ten thousand years they stayed out of sight."
  ]],
  ["Rising from the Sea", [
    "The naga came back into the world around the Third War. Illidan Stormrage, Malfurion's exiled brother, cast a spell that reached the ocean floor, and Lady Vashj answered with her followers. They did not come out of loyalty. The Old Gods wanted Illidan's war against the Lich King to succeed. Vashj helped Illidan reach the Tomb of Sargeras and also helped the blood elf prince Kael'thas escape an Alliance prison. The naga followed Illidan to Outland, where Vashj tried to seize the waters of Zangarmarsh until adventurers killed her.",
    "Naga raided coasts across Azeroth. In Northrend one tribe tried to melt the polar ice to flood the world. During the Cataclysm, N'Zoth sent Azshara's armies against Neptulon, the elemental lord of water, and they took control of the undersea region of Vashj'ir."
  ]],
  ["Azshara's Last Gambit", [
    "During the Legion invasion, Azshara sent naga to seize the Tidestone of Golganneth, a titan artifact with power over water. In the Fourth War she corrupted the tidesages of Kul Tiras and sent naga against the coasts of both Kul Tiras and Zandalar. Then she used the Tidestone to part the sea and draw the Alliance and Horde down to Nazjatar. There she revealed that she had manipulated both sides all along. As they fought her, she drew power from the Heart of Azeroth, an artifact the heroes carried, and broke the last chains holding N'Zoth.",
    "N'Zoth carried Azshara away to his city of Ny'alotha and had her tortured. Heroes freed her, and she gave them Xal'atath, a dagger that could hurt the Old God. She said she was tired of serving others and would claim the true throne of power for herself. Then she stepped through a Void portal and vanished. N'Zoth was destroyed soon after. Azshara has not been seen since."
  ]],
  ["A Kingdom Without Its Queen", [
    "Without their queen, the naga have splintered. In Dragonflight, the Farscale naga claimed that Azshara had called to them from beyond the Umbral Veil, the boundary of the known cosmos. By the time of The War Within, the naga of Nazjatar were fighting among themselves in ever more factions. Darktide naga invaded the Siren Isle and had clashed with the Arathi Empire across the sea.",
    "In Midnight, Daggerspine naga landed on the western coast of Eversong Woods. With the help of a crooked blood elf shipping company, they gathered arcane energy and shipped it far out into the Great Sea. Their leader, Princess Naz'jena, promised with her dying breath that the naga would rise again. The Deeplurk naga soon joined them and began draining energy from Void creatures as well. They spoke of being called to a Concord of Tides. What that gathering is, and whether Azshara is behind it, has not yet been revealed."
  ]],
  ["Life Beneath the Waves", [
    "Naga society is matriarchal. Female naga kept their old memories and personalities better than males after the change, and they are powerful sorceresses of water and ice. Many have four or more arms, and some are said to be immortal. Males are larger and more beastly, with dragon-like heads, and they serve as warriors. Naga hatch from eggs, and their spawning grounds are among the most heavily guarded places they hold. They can breathe both air and water.",
    "Their long exposure to the Well of Eternity left them addicted to magic. Their leaders still carry the titles prince and princess from the old empire, and they speak Nazja, a cousin of the night elves' Darnassian. They worship Azshara as a demigod and look down on land-dwellers, calling them landwalkers and softskins. Oddly, they fear turtles, which they see as bad luck."
  ]]
];
