window.RACE_STORIES = window.RACE_STORIES || {};

window.RACE_STORIES['pandaren'] = [
  ["Slaves of the Mogu", [
    "The pandaren are a people of large, bear-like humanoids from Pandaria, a wide land of forests and mountains in the southern seas. No one knows exactly where they came from. By their own account they settled around the Vale of Eternal Blossoms in the distant past, long before humans had kingdoms. There they came to revere four great Wild Gods they called the August Celestials: Chi-Ji the Red Crane, Niuzao the Black Ox, Xuen the White Tiger and Yu'lon the Jade Serpent.",
    "That peace ended with the mogu, huge stone-skinned warriors who had once served the titans. After a long age of mogu warlords fighting each other, one of them, Lei Shen, the Thunder King, crushed his rivals and enslaved every other people in Pandaria. He wrote the first written laws on Azeroth, and the first law punished rebellion with public execution. Fearing the pandaren's potential, he banned them from reading and writing, killed their philosophers and burned their books and art.",
    "The slaves were not allowed weapons. The mogu did allow one caste of slaves to brew teas and remedies so that workers stayed on their feet. Over time these brewers became healers and community leaders. In secret they learned to fight with bare hands, farm tools and bamboo staves, drawing on their inner energy, called chi. They were the first monks."
  ]],
  ["Revolution and Empire", [
    "Lei Shen died far from home, during a campaign in the desert of Uldum, but mogu rule went on without him. In time a pandaren named Kang, the Fist of First Dawn, inspired the slaves to rise. The monks led the fighting, and the pandaren won over the hozen (a monkey-like people), the jinyu (a fish-like people) and the small grummles. The mogu empire fell in a bloody revolution.",
    "About a century later the mogu's old allies, the Zandalari trolls, invaded to restore their friends. Troll bat riders ruled the skies until a girl named Jiang tamed a cloud serpent and fought them in the air. Her riders became the Order of the Cloud Serpent and helped turn the war. The pandaren empire that followed lasted for thousands of years."
  ]],
  ["The Last Emperor and the Mists", [
    "In those years the pandaren were friendly with the night elves of Kalimdor. When the elven Highborne grew obsessed with arcane magic, the pandaren cut ties. As a parting gift they left an empty chest, a hint that the elves needed no more arcane magic at all. Soon after, a young pandaren named Shaohao was crowned emperor. A jinyu seer warned him that sorcerers would call demons into the world and that the continents would shatter.",
    "Guided by the August Celestials and his friend the Monkey King, Shaohao set out to purge himself of doubt, despair, fear, anger, hatred and violence. Each emotion took shape as a sha, a living shadow, and he buried them beneath Pandaria's temples. He founded the Shado-Pan to guard them. Then, in the Vale of Eternal Blossoms, he became one with the land. When the world broke apart in the Great Sundering, about ten thousand years before the Dark Portal opened, Pandaria drifted free and vanished behind a wall of mist.",
    "Shaohao had kept one flaw, his pride. The Sha of Pride used it to wrap the land in mist, because the emperor believed his people were better off solving their own problems apart from the world. Pandaria was saved, but it was cut off for ten thousand years. With no outside threat, no new emperor took his place, and power passed to local communities. To this day, strong negative feelings in Pandaria can take physical form as sha, so pandaren work hard to stay calm."
  ]],
  ["The Wandering Isle", [
    "Most pandaren believed the rest of the world had died in the Sundering. About eight centuries before the First War, a scholar named Liu Lang doubted this. He befriended a young sea turtle, named him Shen-zin Su, and rode beyond the mists. Liu Lang came back every five years with stories of trolls, tauren and strange lands, and slowly others joined him. The turtle kept growing until whole villages and forests sat on his shell.",
    "Liu Lang died on his last voyage at the age of 122. His followers' descendants lived on as the people of the Wandering Isle. A few left to see the world, such as the brewmaster Chen Stormstout, who helped Thrall and Rexxar found the orc homeland of Durotar after the Third War."
  ]],
  ["The Mists Part", [
    "After the Cataclysm, the mists around Pandaria suddenly faded, and Alliance and Horde fleets found a continent where their maps showed open sea. At about the same time, an Alliance gunship crashed into the side of Shen-zin Su and wounded him. Two young monks, Ji Firepaw and Aysa Cloudsinger, saved the turtle but disagreed on how, and their followers split. Aysa's Tushui, who prize patience and discipline, joined the Alliance. Ji's Huojin, who hold that doing nothing is the greatest injustice, joined the Horde.",
    "On the mainland, the war between outsiders woke the sha. The pandaren also faced a mantid swarm, rebel mogu, the Zandalari and a revived Thunder King, and the Alliance and Horde won their trust by fighting these enemies at their side. Then the Horde's warchief, Garrosh Hellscream, dug the Heart of Y'Shaarj, the remains of an Old God, out of the Vale of Eternal Blossoms and poisoned the sacred valley. After his defeat at the Siege of Orgrimmar, he was tried under pandaren law, with the Shado-Pan leader Taran Zhu as judge and the Celestials as jury, but he escaped. Shaohao's spirit planted a new tree in the Vale, and the land slowly healed."
  ]],
  ["After Pandaria", [
    "When the Burning Legion invaded, demons destroyed the monastery at the Peak of Serenity. Its surviving monks moved to the Wandering Isle and formed the Order of the Broken Temple. In the Fourth War, Ji Firepaw's Huojin backed Varok Saurfang against Sylvanas Windrunner, and Aysa's Tushui stood with them at the end. Pandaria itself was attacked again when the Old God N'Zoth sent his forces against the Vale.",
    "In the war against Xal'atath in Khaz Algar, Ji and Aysa trained the earthen there as monks. Around the same time, during the Spirit Festival, Shen-zin Su returned to the waters of Pandaria for the first time in centuries, reuniting the island and mainland peoples. The story of Midnight centers on Quel'Thalas, and the pandaren have not played a major part in it so far."
  ]],
  ["Living in the Moment", [
    "Pandaren try to live fully in the present. Every meal, nap and friendship deserves their whole attention. They are slow to anger and prefer measured answers to problems, but a pandaren roused to fight hits with the weight of a bear. Brewing is close to an art form, and brewmasters roam far in search of rare ingredients.",
    "Pandaria has no central government. Farmers of the Tillers' Union, the Lorewalkers who keep their history, and the Shado-Pan who guard against the sha each look after their own part of life. Pandaren respect the rule of law as the way to restore balance. They face death believing that new life blossoms from every passing."
  ]]
];

window.RACE_STORIES['dracthyr'] = [
  ["Neltharion's Soldiers", [
    "The dracthyr are humanoid dragonkin who can use the magic of all five major dragonflights and shift between a draconic form and a mortal-looking visage. They were made by Neltharion, the black Dragon Aspect who guarded the earth, long before he became the monster known as Deathwing. More than twenty thousand years ago, Neltharion saw a split growing between the Aspects and the Primal Incarnates. These were proto-dragons who rejected the titans' gifts and wanted dragonkind to stay wild and elemental. The Dragon Queen Alexstrasza hoped words would settle the quarrel. Neltharion expected war.",
    "The existing dragonkin did not satisfy him. Drakonid were slow, and dragonspawn were fragile. Neltharion wanted soldiers with the strength of every flight and the cleverness and adaptability he saw in the young mortal races. In his secret laboratory of Aberrus he ran countless experiments, many of them on drakonid and many with horrific results, before anything like a dracthyr emerged. He shaped the Forbidden Reach, an island off the Dragon Isles, into their training ground. He also used a titan relic called the Oathbinder to bind them to his will."
  ]],
  ["The Long Sleep", [
    "Neltharion never had time to finish. Raszageth the Storm-Eater, one of the Primal Incarnates, struck the Forbidden Reach first, and in that battle the Oathbinder was destroyed. To defeat her, Neltharion listened for the first time to the whispers of the Old Gods, and with that new power he sealed Raszageth away. The attack began the War of the Scaleborn, more than two hundred years of fighting between the dragonflights and the Incarnates.",
    "Without the Oathbinder, Neltharion could no longer control his soldiers. He had built them to kill dragons, and he feared they might turn on the Aspects. He asked his friend Malygos, the blue Aspect of magic, to seal them in magical stasis inside creches beneath the Reach, with blue dragons standing watch. A black dragon named Adamanthia tried several ways to restore his control, and argued that the dracthyr would serve him freely without it. Neltharion had her sealed away as well. The dracthyr slept for nearly twenty thousand years and missed their creator's fall, the Sundering of the world and the departure of the dragons from the Dragon Isles."
  ]],
  ["Waking to a Storm", [
    "A few years after the war against the Jailer, the Primalists, followers of the Incarnates, broke into the Forbidden Reach and freed Raszageth. The magical surge woke the dracthyr, but their long stasis had left their memories blurred. Raszageth's storm then forced them to abandon the only home they knew. At a gathering of the weyrns, their fighting units, each leader chose a different road.",
    "Scalecommander Emberthal of the Adamant Vigil, the only survivor of her weyrn, stayed behind to look for survivors and answers. Scalecommander Sarkareth renounced dragonkind and renamed his Ebon Scales the Sundered Flame. Viridia's Healing Wings stayed on the Dragon Isles. Azurathel led the Obsidian Warders to Stormwind with the black dragon Wrathion to warn the Alliance, and Cindrethresh took the Dark Talons to Orgrimmar with the black dragon Ebyssian to warn the Horde. From these two dragons they learned to take mortal visage forms, which made it easier to live among other races."
  ]],
  ["Breaking the Oathbinder", [
    "After Raszageth died in the Vault of the Incarnates, the storm faded and the dracthyr returned to the Reach. They set up camp at Morqut Village and searched for the secrets Neltharion had left behind. Sarkareth wanted those secrets for himself. In Zaralek Cavern, deep under the Dragon Isles, he found and partly repaired the Oathbinder, hoping to rule the dracthyr as Neltharion once had. Emberthal destroyed it.",
    "Sarkareth fled into Aberrus. There he threw away his followers' lives chasing Neltharion's legacy and fell to the Void before he was killed. From a fragment of the Oathbinder he dropped, Nozdormu, the bronze Aspect of time, and a dracthyr champion forged Nasz'uro, the Unbound Legacy. It freed the dracthyr so that no one could ever control them through the Oathbinder again. Emberthal and Ebyssian also freed Adamanthia, and the black dragon essence Neltharion had drained from the dracthyr returned to them. Surviving members of the Sundered Flame rejoined their people as the Ebon Scales under Emberthal."
  ]],
  ["Choosing Their Own Path", [
    "By the time the Primalist war ended, the Obsidian Warders had formally joined the Alliance and the Dark Talons the Horde. Others found their own callings. Young dracthyr studied at Algeth'ar Academy and pledged themselves to individual dragonflights, and some joined the time-traveling Timewalkers or went to work for the Black Market Auction House.",
    "During the war in Khaz Algar, Emberthal returned to the Forbidden Reach and woke still more dracthyr from the creches. She told them what had happened while they slept and sent them out to decide their own futures. As of Midnight, the dracthyr remain a young people with feet in both factions and among the dragons, still learning what to do with a freedom they were never meant to have."
  ]],
  ["Weyrns, Signets and Scalecommanders", [
    "The dracthyr were built as an army, and their culture still shows it. Every dracthyr belonged to a weyrn suited to their skills, and weyrn members are as close as clutch-mates. Each weyrn was led by a Scalecommander, chosen and trained by Neltharion himself. The rare dracthyr who could master the skills of every weyrn earned the title of evoker.",
    "Dracthyr wear signets on their horns, inscribed with their names like soldiers' tags, so that the dead can be named and remembered. A dracthyr who dishonors their creche is expected to fall honorably in battle. They think of Neltharion as both their general and their father. Made only for war, many find crafts, art and the idea of a day off strange at first. What they lack in experience they make up for with a deep hunger to learn."
  ]]
];

window.RACE_STORIES['dragons'] = [
  ["Galakrond and the First Aspects", [
    "Long before any mortal kingdom, Azeroth's skies belonged to proto-dragons, wild ancestors of today's dragons. One of them, Galakrond, drank from waters on the Dragon Isles tainted by the Old God Yogg-Saron. He grew to monstrous size and began eating other proto-dragons, and those he devoured rose again as undead slaves. Five proto-dragons stood against him with the help of Tyr, a titan-forged keeper: Alexstrasza, Ysera, Malygos, Neltharion and Nozdormu. In the end Malygos lodged a boulder in Galakrond's throat and Neltharion drove it deeper, and the giant choked to death. His bones still lie in Northrend, in the land called the Dragonblight.",
    "Tyr asked the other keepers to empower the five, and they did so against the wishes of their leader, Odyn. More than twenty thousand years before the Dark Portal opened, the titans of the Pantheon blessed them through the keepers. Alexstrasza became the guardian of life, Ysera of the Emerald Dream and nature, Malygos of magic, Neltharion of the earth and Nozdormu of time. These were the Dragon Aspects. To stop any dragon from following Galakrond's path, they encouraged a rumor that the titans had made them from Galakrond, and they kept the truth about his cannibalism hidden."
  ]],
  ["The Age of Dragons", [
    "The keepers then filled hundreds more proto-dragons with titan order magic, creating the five dragonflights: red, green, blue, black and bronze. Dragonkind built a kingdom on the Dragon Isles, which they called the Broodlands, ruled from the city of Valdrakken with Alexstrasza as Dragon Queen. The Aspects lifted the reptilian tarasek into the first drakonid, who served as their guards, builders and caretakers.",
    "Not every proto-dragon wanted the titans' gift. The Primal Incarnates, led by dragons such as Raszageth, Fyrakk, Iridikron and Vyranoth, demanded that Tyr be driven out. Their rebellion grew into the War of the Scaleborn, which lasted more than two hundred years. The dragonflights won, but Alexstrasza could not bring herself to kill her old clutch-mates and imprisoned them in the Vault of the Incarnates."
  ]],
  ["Deathwing's Betrayal", [
    "Neltharion felt the weight of the whole earth pressing on him, and in time the Old Gods' whispers took hold. During the War of the Ancients, about ten thousand years before the Dark Portal, he convinced the other Aspects to pour part of their power into a weapon called the Dragon Soul. His own flight secretly gave nothing. On the battlefield he used it against the demons of the Burning Legion, then turned it on his allies. He killed almost every blue dragon, and from then on he was called Deathwing.",
    "The other flights went to war against the black dragons and nearly destroyed them. When the world broke apart in the Great Sundering, much of the Dragon Isles' magic drained away, and the dragons left their homeland. Alexstrasza had its titan-forged watchers hide the isles until elemental power returned. The surviving Aspects gave the night elves a new World Tree, Nordrassil, and in later centuries the bronze, red, green and blue dragons helped seal the insect armies of Ahn'Qiraj behind the Scarab Wall."
  ]],
  ["Chains, War and the Age of Mortals", [
    "Deathwing kept scheming. During the Second War, he let the orcs of the Dragonmaw clan take the Dragon Soul, now called the Demon Soul, and they used it to enslave Alexstrasza and her flight as war beasts. At Grim Batol the human mage Rhonin destroyed the artifact, and the Aspects regained the power they had lost ten thousand years before. Deathwing's children, Onyxia and Nefarian, later plotted against the mortal kingdoms and were slain.",
    "Malygos, maddened by grief for his flight, declared war on all mortal spellcasters and was killed in his own realm. Alexstrasza formed the Wyrmrest Accord to unite the other flights. Then Deathwing burst from the earth and caused the Cataclysm. The remaining Aspects, with the orc shaman Thrall, recharged the Dragon Soul and destroyed him. The effort spent their titan-given powers. Alexstrasza declared the start of the Age of Mortals, when Azeroth's younger races would have to guard the world themselves."
  ]],
  ["Return to the Dragon Isles", [
    "Hard years followed. Ysera was corrupted by the Emerald Nightmare during the Legion invasion and was put to rest. Then, as Azeroth's elemental energy grew stronger again, a watcher named Koranos lit the Beacon of Tyrhold, and the Dragon Isles reappeared. The flights came home and founded the Valdrakken Accord. At the same moment the Primalists freed their old leaders, and the weakened Aspects had to fight the Incarnates again.",
    "The black dragons, nearly all once corrupted, found a new leader in Ebyssian, a black dragon freed from corruption as an egg. Ysera returned from the land of the dead, and her daughter Merithra took up the role of green Aspect. When Fyrakk attacked the new World Tree, Amirdrassil, he was killed, and Azeroth herself restored the Aspects' power. Vyranoth, a former Incarnate, became a sixth Aspect, of storms.",
    "Iridikron escaped. With help from the infinite dragonflight, which tries to twist time and is led by Murozond, a future version of Nozdormu, he stole the essence of Galakrond and gave it to Xal'atath. As far as the lore shows, he is still free."
  ]],
  ["Dragons Today", [
    "During the war against Xal'atath in Khaz Algar, the Void lord Dimensius's servants abducted blue dragons from the Azure Vault and corrupted them on the broken world of K'aresh, and blue dragons fought to stop them. As of Midnight, six Aspects lead dragonkind from Valdrakken: Alexstrasza, Ebyssian, Kalecgos of the blue flight, Merithra, Nozdormu and Vyranoth. The dragons have not been at the center of the fighting in Quel'Thalas so far."
  ]],
  ["Visages, Flights and Duties", [
    "Dragons are long-lived and highly intelligent, and most can take a mortal visage, often an elf or human, to walk among the younger races. Each flight carries its Aspect's charge, and Aspects choose consorts to help lead their flights. Other kinds of dragon exist too, such as the nether dragons of Outland, grown from Deathwing's eggs, and the chromatic dragons Nefarian made by mixing the flights. For all their power, dragons see their oldest duty as protecting Azeroth itself."
  ]]
];

window.RACE_STORIES['aqir'] = [
  ["Spawn of the Old Gods", [
    "The aqir are an ancient race of insect-like creatures. They arose from matter seeping out of the Old Gods, the evil beings that ruled primordial Azeroth as the Black Empire. Strong and tireless, the aqir worked as laborers for the faceless ones, the Old Gods' cunning priests, building temple cities around their masters. When the titans' servants, the titan-forged, came to break the Black Empire, they collapsed the aqir's burrows and killed most of them. A few pockets survived deep underground.",
    "Nerubian legend adds another tale. A queen named Anub'izek, born during the Black Empire to lead its legions, defied the Old Gods who made her and led her followers deep into the earth to be free. Nerubians remember her as the first queen of their people."
  ]],
  ["Azj'Aqir and the Troll Wars", [
    "Thousands of years later, about sixteen thousand years before the Dark Portal opened, trolls ruled much of Kalimdor. A rebel troll named Zan'do, guided by a whispering dagger that was really Xal'atath, woke a buried Old God general called Kith'ix. Kith'ix reached out to the hidden aqir and rallied them to build an underground empire, Azj'Aqir. Then it led them to the surface to wipe out the trolls.",
    "The troll tribes united as the Empire of Zul and, with the help of their animal gods, the loa, wounded Kith'ix. The Amani tribe hunted it down and killed it at the cost of almost their whole tribe, and later built Zul'Aman on that spot. The Drakkari trolls pursued the aqir north, and the Gurubashi pinned another group inside the titan prison of Ahn'Qiraj. After centuries of war, the trolls shattered Azj'Aqir."
  ]],
  ["Three Kingdoms", [
    "Three groups survived. In the far north, aqir settled near the prison of the Old God Yogg-Saron and slowly became the spider-like nerubians, with a vast underground kingdom called Azjol-Nerub. In the southwest, aqir took over Ahn'Qiraj, where the Old God C'Thun lay imprisoned, and its power turned them into the qiraji, who served it. A third group fled southeast toward the remains of the dead Old God Y'Shaarj. They became the mantid of Pandaria.",
    "Each people took its own path. The qiraji stayed loyal to their god. The mantid built a culture around strength and amber. The nerubians, by their own account, turned away from the Old Gods, although for a time they too served Yogg-Saron."
  ]],
  ["The Shifting Sands and Ahn'Qiraj", [
    "About a thousand years before the Dark Portal, the qiraji and their silithid swarms poured out of Silithus and drove the night elves back for months. In the War of the Shifting Sands, the bronze dragons and three other flights joined the elves. Even together they could not destroy the swarm, so they sealed the qiraji inside Ahn'Qiraj behind the Scarab Wall.",
    "The seal held for a thousand years. After the Second War, the Twilight's Hammer cult woke C'Thun, and the qiraji stirred again. The Alliance and Horde opened the gates together, fought off the swarm in Silithus, and killed C'Thun in its temple. Some qiraji remained afterward, but they have rarely been seen since."
  ]],
  ["The Fall of Azjol-Nerub", [
    "Shortly before the Third War, the Lich King arrived in Northrend to build his Scourge. The nerubians could not be turned by his plague or controlled by his mind, so they fought back. King Anub'arak sent for help from a distant southern kingdom, Azj-Kahet, but its queen, Neferess, refused. The War of the Spider ended with Azjol-Nerub overrun. While fleeing deeper, some nerubians dug into Yogg-Saron's reach and were attacked by faceless ones. The Lich King raised Anub'arak and many of his people as undead and used their architecture for his own fortresses.",
    "During the war against the Lich King, living nerubians helped the Alliance and Horde reclaim parts of Azjol-Nerub. Anub'arak was killed, and the survivors began to rebuild with hidden stores of eggs."
  ]],
  ["The Mantid Swarm", [
    "In Pandaria, the mogu built a great wall, the Serpent's Spine, to hold the mantid back. The mantid turned it into a test. About once a century, a new generation swarms the wall, and only the strong return. Their elders, the Klaxxi, guard mantid tradition and oversee the passing of power from one empress to the next.",
    "When the mists parted, Grand Empress Shek'zeer, corrupted by the Sha of Fear, launched a swarm years too early. The Klaxxi worked with outsiders to depose her. Later the Klaxxi sided with Garrosh Hellscream to protect the Heart of Y'Shaarj, and under a new empress, Shek'zara, the mantid pledged themselves to the Old God N'Zoth. During that war, original aqir also re-emerged in N'Zoth's service."
  ]],
  ["Azj-Kahet and the Return of Kith'ix", [
    "Deep beneath Khaz Algar, the nerubians of Azj-Kahet kept their old ways in isolation. With the Old Gods dead, Xal'atath offered them greatness. Queen Neferess refused, so her daughter Ansurek stabbed her, took the throne and secretly had her mother transformed. Using the Black Blood of the Old Gods, Ansurek created new forms of nerubian soldiers, helped Xal'atath destroy the mage city of Dalaran and waged war on the human Arathi of Hallowfall. A secret alliance called the Severed Threads rose against her, and Ansurek was killed in her palace. Her loyalists kept attacking Hallowfall after her death.",
    "In Midnight, the oldest story returned. Kith'ix had been held dead beneath Zul'Aman by the power of Ula'tek, the monstrous serpent the Amani summoned to kill it. When Ula'tek died, that hold broke. Aqir burst from the ground in Eversong Woods and Zul'Aman, and Kith'ix began to stir. How that threat will end is still unfolding."
  ]]
];

window.RACE_STORIES['ethereals'] = [
  ["The People of K'aresh", [
    "The ethereals are beings of living energy who wrap themselves in cloth bands to hold their shape. They were once flesh-and-blood people called the K'areshi, from K'aresh, a desert world under twin suns. Their society was made of city-states such as Tazavesh and Ma'nussa, with nomad tribes traveling between them. They held oaths sacred, and breaking one was close to blasphemy. Oracles led by the High Priest Salhadaar communed with the soul of their world. All of this happened many thousands of years ago, possibly a hundred thousand or more."
  ]],
  ["The Devouring War", [
    "Then a Void lord named Dimensius the All-Devouring came for K'aresh. Void lords are monstrous beings of pure shadow, and Dimensius wanted to consume the planet's soul. He opened gateways to the Void all around the world and eventually swallowed its suns. A technomancer later known as Locus-Walker had seen the danger coming. He joined the Ravel, a secret circle of the sharpest K'areshi minds, and his plan was adopted. Using ancient artifacts called the Reshii Ribbons, which could turn any energy into arcane power, the K'areshi raised magical barriers over their cities.",
    "The barriers kept the Void out, but their constant arcane energy slowly ate away the people inside. The K'areshi called it the Wasting and wrapped their failing bodies in layers of bandages. Locus-Walker discovered that the sick were turning into beings of pure energy and proposed finishing the change so that his people could leave K'aresh behind. Salhadaar seized the ribbons, named himself king and accused Locus-Walker of causing the Wasting."
  ]],
  ["A World Destroyed", [
    "Locus-Walker and the agent Nari escaped with the ribbons and found an unlikely ally in Xal'atath, Dimensius's own herald, who wanted to be free of him. With her help they turned their people fully into energy. Then, seeing that K'aresh was lost either way, the Ravel used the ribbons to blow the planet apart and kill Dimensius before he could devour its soul. The blast only shattered him, scattering fragments across the cosmos.",
    "The survivors fled. Those who became ethereals roamed the Twisting Nether, the chaotic space between worlds. Others reached the realm of the dead and became the brokers. A few stayed on the broken remains as Wastelanders. Nearly all of them believed Dimensius had destroyed their world.",
    "Locus-Walker, branded a traitor by Salhadaar, wandered the Great Dark Beyond as an outcast for thousands of years. The truth about K'aresh stayed hidden until recent years."
  ]],
  ["Princes and Companies", [
    "Ethereal society came to be organized into trading companies led by Nexus-Princes. The ruling council, the Ethereum, swore to hunt down Dimensius. Their leader, Nexus-King Salhadaar, secretly served the Void lord and used the hunt to gather his fragments. Ethereum members he corrupted became the Shadowguard. Other princes broke away. The Protectorate formed to stop the Ethereum, and the Consortium, a company of traders and smugglers, helped them.",
    "Azeroth's adventurers first met these factions in Outland after the Dark Portal reopened. There the Protectorate and its allies killed Salhadaar and destroyed a fragment of Dimensius in the Netherstorm. After the Cataclysm, ethereal merchants set up shop in Azeroth's capitals. On Argus during the Legion war, and later at the void elves' home of Telogrus Rift, the Shadowguard reappeared as enemies. Locus-Walker, meanwhile, became the teacher of the void-touched ranger Alleria Windrunner and a mentor to the void elves."
  ]],
  ["Ghosts of K'aresh", [
    "During the war against Xal'atath in Khaz Algar, ethereals moved in the shadows. Nexus-Princess Ky'veza advised the nerubian queen Ansurek, and a Shadowguard agent named Azir stole the Dark Heart, a Void artifact, from the goblin city of Undermine. He took it to Manaforge Omega on K'aresh to bring Dimensius back. In response, the broker Ve'nari founded the K'aresh Trust, uniting ethereals and brokers for the first time in millennia to restore their homeworld.",
    "Locus-Walker allied with the Trust, Azeroth's champions and even Xal'atath to stop the revival. Along the way Alleria learned the secret that the Ravel itself had destroyed K'aresh. Salhadaar returned, remade by Dimensius in the Void, and was killed again.",
    "The champions forced Dimensius into the Dark Heart. Xal'atath then took the relic, destroyed Locus-Walker and left with the Void lord's power. Afterward Soul-Scribe, leader of the Wastelanders, gave her life to heal the last fragment of K'aresh's world-soul. Through the Trust's eco-domes, the planet has begun to live again."
  ]],
  ["Ethereals in Midnight", [
    "Salhadaar did not stay gone. Xal'atath had taken his soul at Manaforge Omega, and when she gathered the Void's factions into a new army, the Devouring Host, he and his Shadowguard were among the last to hold out. She offered them survival, and he bowed to her. In Midnight, that army struck at the Sunwell in Quel'Thalas.",
    "Salhadaar captured the naaru T'era and turned her to the Void. Xal'atath then betrayed him, filled him with Void energy and left him to be experimented on by the ethereals he once commanded. Many ethereals still follow the Shadowguard by choice, while the K'aresh Trust works to rebuild their world."
  ]],
  ["Wrappings and Oaths", [
    "An ethereal's wrappings are its body in all practical sense, since without them its energy would scatter. Ethereals live by trade and are famous collectors of magical items and artifacts, willing to deal with anyone who serves their profit. Some are honest merchants, and others are liars and thieves. They use a blend of magic and technology called technomancy, and their companies often act much like goblin trading cartels. Above all, the old K'areshi respect for oaths endures, and that loyalty can bind them for good or for ill."
  ]]
];
