window.RACE_STORIES = window.RACE_STORIES || {};

window.RACE_STORIES['orcs'] = [
  ["Children of Stone", [
    "Orcs come from Draenor, the world that was later torn apart and became Outland. Blizzard's Warcraft Chronicle traces their line back to Grond, a huge stone giant made by the titan Aggramar to fight the wild plant life of ancient Draenor. Over thousands of years, Grond's stony descendants were softened into flesh by lingering spores. The giants called gronn came first, then the brutish ogron, then the ogres. The orcs came last of all.",
    "They were the smallest and weakest of that family, so they survived by being clever and sticking together. For generations they hid in caves under Gorgrond, out of reach of the ogron. When the ogres overthrew the ogron, the orcs moved to the surface, and about 800 years before the Dark Portal crowding split them into the famous clans. The Blackrock stayed in Gorgrond, the Frostwolves went to icy Frostfire Ridge, the Warsong roamed Nagrand and the Shadowmoon settled in Shadowmoon Valley. The clans kept apart and met in peace at a festival called the Kosh'harg."
  ]],
  ["Shamans and the Fall of Goria", [
    "Shadowmoon mystics found the spirits of earth, fire, air and water at Grond's resting place in Nagrand, which they named the Throne of the Elements. Shamanism spread to nearly every clan, and shamans became respected advisers whose bond crossed clan lines.",
    "About 400 years before the Dark Portal, the ogres of the Gorian Empire seized the Throne to study its power. Their meddling blew the temple apart and threw the elements into chaos. The clans united under the Shadowmoon elder Nelgarm and besieged the ogre capital of Goria. The ogres struck back with the red pox, a magical plague that killed many orcs, so the shamans begged the elements for help. The spirits wiped Goria from the map. Frightened by that fury, the clans went home, and over the next two centuries they became the strongest people on Draenor.",
    "About 200 years before the Dark Portal, the draenei, refugees from another world, crashed their ship in Nagrand. The orcs came to revere the wreck as Oshu'gun, the Mountain of Spirits. The two peoples traded goods but kept a polite distance."
  ]],
  ["Kil'jaeden's Bargain", [
    "The peace was broken by Kil'jaeden, a demon lord of the Burning Legion who had hunted the draenei across the stars for thousands of years. He decided to use the orcs as his weapon. He appeared to Ner'zhul, elder shaman of the Shadowmoon, in the form of his dead wife Rulkan and convinced him that the draenei planned to destroy the orcs. Ner'zhul rallied the clans for war.",
    "As the killing began, the elements went silent. Ner'zhul learned the truth and refused to go on, but his apprentice Gul'dan had served Kil'jaeden for years. Gul'dan replaced the shamans with warlocks, built a secret Shadow Council to rule from behind the scenes, and made Blackhand of the Blackrock clan Warchief of a united Horde. Fel magic slowly turned the orcs' brown skin green and drained the life from their land. Then Gul'dan offered the chieftains the blood of the pit lord Mannoroth. Most drank, including Grom Hellscream of the Warsong, while Durotan of the Frostwolves refused. The blood filled the orcs with endless rage and bound them to the Legion.",
    "The Horde took the draenei's holy temple of Karabor, stormed their capital, Shattrath, and believed it had wiped them out. With no enemy left, the clans turned on each other while Draenor withered. Then the possessed human sorcerer Medivh reached out to Gul'dan, and the Horde built the Dark Portal to a new world, Azeroth."
  ]],
  ["Invaders, Prisoners and a New Horde", [
    "The portal opened in Year 0. In the First War the Horde destroyed the human kingdom of Stormwind. Gul'dan had Durotan murdered, and Durotan's infant son was found by the human lord Aedelas Blackmoore, who raised him as a slave and gladiator named Thrall. Orgrim Doomhammer killed Blackhand, took over the Horde and broke the Shadow Council. In the Second War the Horde fought the Alliance of Lordaeron, but Gul'dan abandoned the campaign to hunt for the Tomb of Sargeras, and the divided Horde was crushed. Most survivors were locked in internment camps, where, cut off from fel magic, they sank into a deep lethargy. On Draenor, Ner'zhul's reckless portals tore the world apart, leaving Outland.",
    "Thrall escaped, learned shamanism from Drek'Thar of the exiled Frostwolves, and freed the camps with Grom and Doomhammer, who fell in the last attack. Guided by a prophet who was Medivh reborn, Thrall sailed to Kalimdor with the Darkspear trolls and befriended the tauren. In Ashenvale, Grom drank demon blood again, but Thrall helped him break free, and Grom killed Mannoroth at the cost of his own life. That act lifted the blood curse. After the Legion's defeat at Mount Hyjal, Thrall founded the nation of Durotar, named for his father, and the city of Orgrimmar, named for Doomhammer."
  ]],
  ["Warchiefs Rise and Fall", [
    "In The Burning Crusade the orcs returned to Outland, fought the demon-blooded Fel Horde and met the Mag'har, uncorrupted orcs of Nagrand. Among them was Grom's son Garrosh, who led the Horde's war in Northrend and became Warchief when Thrall stepped down in Cataclysm to help heal the elements. Garrosh grew into a tyrant. He used the heart of an Old God as a weapon and tried to purge the Horde of non-orcs, and in Mists of Pandaria the Horde and Alliance deposed him in the Siege of Orgrimmar.",
    "Garrosh escaped to an alternate Draenor and raised the Iron Horde there, until Thrall killed him in a duel in Nagrand. In Legion, the troll Warchief Vol'jin died and Sylvanas Windrunner took his place. Her war in Battle for Azeroth burned the night elves' great tree Teldrassil, and the veteran orc Varok Saurfang led a revolt against her. Saurfang died in ritual combat with Sylvanas, and she abandoned the Horde. Thrall refused the title of Warchief. A council of leaders now guides the Horde, and Thrall speaks for the orcs on it.",
    "In Dragonflight, Eitrigg and Thrall revived the Kosh'harg festival in Durotar. In The War Within, orc warriors followed Thrall to Khaz Algar to fight the Void herald Xal'atath. In Midnight, the Twilight's Blade cult tried to recruit in Orgrimmar's shadowy Cleft of Shadow, and the Horde stood with the Alliance to defend the Sunwell of the blood elves."
  ]],
  ["Honor, Clan and Spirit", [
    "Orcs prize honor above almost everything, first for their clan and the Horde, then for themselves. Strength, courage and self-reliance are admired in everyone, and exile is the worst shame an orc can suffer. Hospitality is sacred, which is one reason the orcs and the tauren became such firm allies. Since Thrall's time, women and men have stood as equals.",
    "Shamans speak with the elements for their people, and in dry Durotar they bargain with the spirits for rain. Blood seals oaths, and the mak'gora, a duel to the death, can settle leadership. The green skin the Horde took on under Gul'dan has never faded, and no green orc has returned to the old brown. Most orcs now live in Durotar, with others across Kalimdor and Outland."
  ]]
];

window.RACE_STORIES['maghar'] = [
  ["The Uncorrupted", [
    "Mag'har means \"uncorrupted\" in Orcish. The name belongs to orcs who never drank demon blood and so kept their natural brown or gray skin. There are two quite separate groups of Mag'har. The first lived on the original Draenor and survived its breaking into Outland. The second comes from an alternate Draenor, a parallel timeline that the exiled Warchief Garrosh Hellscream changed in Warlords of Draenor. The Mag'har who joined the Horde as a people in Battle for Azeroth belong to that second group."
  ]],
  ["Quarantine at Garadar", [
    "Years before Gul'dan offered the clans the blood of Mannoroth, a plague called the red pox swept through the orcs of Draenor. Geyah, the mother of the Frostwolf chieftain Durotan and grandmother of Thrall, set up a quarantine village in Nagrand. She named it Garadar after her mate, Garad. The sick orcs there were cut off from the rest of their race, so they never took part in the blood pact. Their parents and kin turned green and joined the Horde, while they stayed brown.",
    "Nagrand stayed green as well, and Geyah called the land itself mag'har. One of the children who grew up at Garadar was Garrosh, son of the famous Grom Hellscream. Long ashamed of his father's fall to demon blood, Garrosh became the war leader of the Mag'har as Geyah grew old and ill."
  ]],
  ["Kin of the New Horde", [
    "In The Burning Crusade, Thrall's Horde crossed the Dark Portal into Outland and found the Mag'har of Nagrand. Thrall met his grandmother Geyah and learned that his father's people had a living link to the old ways. The Mag'har joined the Horde and taught their green-skinned kin about their past. Their life in Outland was hard. Near Sunspring Post, the Murkblood, a tribe of mutated draenei, killed about a thousand Mag'har and threw their bodies in a lake.",
    "Thrall convinced Garrosh to come to Azeroth. Other Mag'har followed, including Dranosh Saurfang, who died at the Wrathgate in Northrend. Garrosh became Warchief, and many Mag'har stayed loyal to him to the end, serving in his elite Kor'kron guard during the Siege of Orgrimmar. Others remained in Nagrand. In Dragonflight, many travelled from Outland to the revived Kosh'harg festival in Durotar, and Jorin Deadeye, son of the Bleeding Hollow chieftain Kilrogg, hoped to reunite his clan's two branches on Azeroth."
  ]],
  ["The Draenor That Refused", [
    "After his defeat, Garrosh escaped to an alternate Draenor in the past, a timeline where he had never been born. He found the younger Grom Hellscream and showed him what the demon blood had done in the main timeline. Grom refused Gul'dan's cup and killed Mannoroth. Garrosh armed the clans with modern weapons and machines, and Grom united seven of them as the Iron Horde, free of demons but bent on conquest. They built their own Dark Portal and invaded Azeroth.",
    "Heroes of the Alliance and Horde drove them back and carried the war to Draenor. Durotan's Frostwolves, the Laughing Skull and the draenei fought beside them. Thrall killed Garrosh in a duel in Nagrand. When most of the Iron Horde's warlords had fallen, Kilrogg Deadeye drank the demon blood after all, and Gul'dan seized the Iron Horde and imprisoned Grom. Gul'dan then summoned the demon lord Archimonde, who was destroyed at Hellfire Citadel. Afterward, Grom, Durotan and the draenei leader Yrel vowed to rebuild their world together. The surviving clans united under Grom and took the old name Mag'har."
  ]],
  ["War with the Lightbound", [
    "For a time, orcs and draenei worked together to drive the last demons from alternate Draenor. Then more naaru, beings of living Light, arrived. With no demons left to fight, the draenei became obsessed with the Light. The land began to decay for reasons no source has explained, and each side blamed the other. Yrel, now High Exarch, gathered a fanatical army called the Lightbound and set out to convert the orcs, by force if needed. Some orcs converted freely, some were forced, and the rest fought back.",
    "During the Fourth War, the old orc Eitrigg used a shard of a time-travelling artifact, the Vision of Time, to reach this Draenor and ask the Mag'har to repay their debt to the Horde. Grom's second-in-command, Overlord Geya'rah, daughter of this world's Durotan and Draka, first refused. She had a war of her own. Then Yrel's whole army arrived at the stronghold of Beastwatch and offered the Mag'har one last chance to accept the Light. Grom and his blademaster Lantresor stayed behind to hold the line while Geya'rah led the Mag'har to Azeroth. What happened to Grom after that is unknown."
  ]],
  ["A New Home in the Horde", [
    "Geya'rah pledged her people to Warchief Sylvanas Windrunner, and the Mag'har settled in Orgrimmar's Valley of Honor. When Varok Saurfang rose against Sylvanas, Geya'rah stayed loyal to her. After Sylvanas abandoned the Horde, Geya'rah admitted her mistake and bent the knee. At Saurfang's funeral she said a true warchief needs both strength and honor. She took a seat on the new Horde Council, and after the armistice the Mag'har were given Hammerfall in the Arathi Highlands as a home of their own. Thrall and Geya'rah call each other brother and sister.",
    "In The War Within, Hammerfall's tensions with the nearby human stronghold of Stromgarde nearly boiled over, and Mag'har healers saved Thrall after he was poisoned there. Geya'rah's warriors then joined the Horde's fight in Khaz Algar. As of Midnight, the Mag'har remain part of the Horde under her leadership.",
    "The Mag'har keep many customs the other orcs lost. They govern themselves through ritual combat and personal honor, revere shamans, and still build in the old Draenor style. Their priests follow the Lok'osh, a path of healing taught by the Mag'har Lok'osh Nakha, who speaks of the elements within as shamans speak of the elements without."
  ]]
];

window.RACE_STORIES['ogres'] = [
  ["Born of Stone", [
    "Ogres are big, strong humanoids native to Draenor, which they call Dawgar, the Known Earth. Like the orcs, they descend from Grond, a stone giant made by the titan Aggramar. Spores from Draenor's ancient plant life slowly turned Grond's rocky descendants into flesh. Some became the gronn, huge half-stone giants. A few gronn degenerated into the ogron, and over thousands of years some ogron became ogres. The orcs, in turn, came from the ogres.",
    "The ogres themselves tell a grander story. They say the creators of Draenor shaped them from the same smoking clay as the world, which makes them its rightful rulers. The truth was harsher. For a long time the ogres were slaves of the ogron. They were thrown into battle as expendable soldiers, and their sick and old were offered as sacrifices to the gronn, whom both peoples feared as gods."
  ]],
  ["The Gorian Empire", [
    "About a thousand years before the Dark Portal, a band of bird-like arakkoa wanted to search some ruins held by the ogron. They secretly taught the ogron's ogre slaves to use arcane magic, hoping to start a revolt. Because of their descent from Grond, ogres took to magic with ease. One of the first to master it was Gog. Instead of fighting the ogron, he killed the gronn themselves, one after another. By his fifth kill, every captive ogre knew the gods could die. The ogres rose up and destroyed nearly every ogron tribe.",
    "Gog named himself Gorgog, King Gog, and called his city Goria, Throne of the King. When the arakkoa tried to claim the ruins, he drove them off. His Gorian Empire spread across much of Draenor, with strongholds such as Highmaul and Bladespire Hold linked by trade routes over land and sea. Its rulers were sorcerer-kings called imperators. Rare two-headed ogres were born with great magical talent, and Gorian sorcerers learned spells to give ordinary ogres a second head. The empire also took slaves, many of them orcs, and made them fight in arenas such as the coliseum at Highmaul."
  ]],
  ["Decline on Draenor", [
    "About 400 years before the Dark Portal, Imperator Molok seized the orcs' sacred Throne of the Elements. His sorcerers' experiments blew up the temple and threw the elements into chaos. The orc clans united and besieged Goria. Molok answered with the red pox, a plague created with magic, but the orc shamans called on the elements, which destroyed Goria and swallowed Molok whole. The empire never recovered. Its remaining fortresses became separate city-states, with Highmaul as the new seat of power, and the orcs slowly took ogre lands.",
    "About two centuries later, the draenei built Shattrath on Goria's ruins. Imperator Hok'lon of Highmaul marched to reclaim the site, but draenei warriors killed him and his generals, and the ogres never attacked Shattrath head-on again. In the years before the Horde formed, orc clans broke ogre power across Draenor. The gladiator slave Kargath led a bloody revolt in Highmaul and founded the Shattered Hand clan. In Frostfire Ridge, the Frostwolves helped the mok'nathal, half-ogre half-orc slaves bred by the Bladespire, overthrow their masters. When the Horde rose, Warchief Blackhand let most ogres join. The two-headed ogre Cho'gall and Grom Hellscream sacked Highmaul, where Cho'gall burned Imperator Mar'gok alive, and the Thunderlord clan hunted the gronn nearly to extinction. One gronn, Gruul, survived in Gorgrond."
  ]],
  ["Ogres in the Horde's Wars", [
    "A few ogres crossed into Azeroth during the First War. In the Second War, Gul'dan brought many more to keep order among the clans. Orgrim Doomhammer came to respect them and kept a bodyguard of loyal ogre warriors. Unlike the orcs, ogres knew the sea, and they helped build the Horde's armored warships, the juggernaughts. Two-headed ogre magi had existed in the Gorian Empire, but few living ogres remembered how to make them. Cho'gall did. At the Altars of Storms, carved from an elven runestone, he and Gul'dan created many new ogre magi, who secretly swore loyalty to Gul'dan.",
    "After the Horde's defeat, the ogres scattered. Some went back to Draenor. Others settled in the Eastern Kingdoms or crossed the sea to Kalimdor, where clans such as the Gordunni and the Gordok of Dire Maul in Feralas, and the Stonemaul of Dustwallow Marsh, made new homes. After the Third War, the half-ogre hero Rexxar had to kill the Stonemaul chieftain to win the clan's help against the human fleet of Admiral Daelin Proudmoore."
  ]],
  ["From Outland to Midnight", [
    "In Outland, most ogre clans fell under the rule of Gruul, whom they worshipped as a god, and his servant High King Maulgar, until adventurers killed them both. In the Blade's Edge Mountains, the Ogri'la, ogres given new wisdom by arakkoan Apexis crystals, freed themselves from the gronn and sought a peaceful life. After the Cataclysm, Cho'gall returned as leader of the Twilight's Hammer cult and drew many ogres into its ranks, while other clans resisted it.",
    "On the alternate Draenor of Warlords of Draenor, the Gorian Empire still stood under Imperator Mar'gok. It was forced to aid the Iron Horde until Azeroth's heroes stormed Highmaul and killed him. The united Mag'har later subdued that world's remaining ogre clans, and some of its ogres came to Azeroth beside the Mag'har in Battle for Azeroth. In Dragonflight, a Twilight's Hammer ogre named Cygenoth disguised himself to start a Deathwing-worshipping cult on the Dragon Isles. In Midnight, the ogre Mor'duun led the Twilight's Blade, a revived Twilight cult with many ogres in its ranks, into the Twilight Highlands, Quel'Thalas and Zul'Aman."
  ]],
  ["Strength, Clan and Mound", [
    "Ogres have no single nation or leader today. Each clan rules itself, and a chieftain holds power only as long as no challenger beats him, since besting a rival is the usual way to rise. Among the Gordunni, anyone who claims the throne and crushes all who disagree becomes King Gordok. Ogres live in caves and rough stone huts called mounds, often near steam vents, and many work as mercenaries, especially for goblin trading cartels.",
    "Size is the mark of status, and a big belly means wealth. Ogres have a natural gift for earth magic, and the rare ogre born with one eye is seen as destined for greatness. Female ogres exist but have rarely been seen in the stories. Though often mocked as brutes, ogres once built Draenor's first great empire, and two-headed magi still hold high rank in many clans."
  ]]
];

window.RACE_STORIES['draenei'] = [
  ["Exiles from Argus", [
    "The draenei began as eredar, a brilliant, magic-loving people of the world Argus. Kil'jaeden, Archimonde and Velen led them together. Then Sargeras, a fallen titan building a demonic army called the Burning Legion, offered the eredar vast power. Kil'jaeden and Archimonde accepted. Velen had a vision of his people turned into demons and refused.",
    "A naaru named K'ure reached out to Velen. The naaru are beings of living Light who oppose the Legion. On the chosen day only a few hundred loyal eredar reached the meeting place, because Velen's old friend Talgath betrayed them. With demons on their heels, they escaped aboard a naaru ship called the Genedar. They named themselves draenei, which means exiled ones. When this happened is uncertain. Older sources say the draenei had been fleeing for 25,000 years, while the more recent short story Bringer of the Light places Sargeras's offer about 13,000 years ago."
  ]],
  ["A Flight Across the Stars", [
    "Kil'jaeden swore to hunt Velen to the ends of creation. The draenei settled world after world, and each time the Legion found them and they had to flee again. On one world, Shar'gel, the priestess Askara and seventy others gave their lives so the rest could escape. On another, some draenei could not reach the ship in time and were left behind, and their descendants, the Nethersent, still live among the stars.",
    "During the long flight the naaru taught the draenei the Holy Light and gave them the Gift of the Naaru, a blessing of healing that every draenei carries. The naaru promised that one day they would forge the races that opposed the Legion into a single Army of the Light. Some time after leaving Argus, the draenei's finest warriors split off aboard a second ship, the Xenedar, to wage that war directly. They became the Lightforged."
  ]],
  ["Refuge on Draenor", [
    "About 200 years before the Dark Portal opened, the Genedar crashed on a quiet world. The draenei named it Draenor, Exiles' Refuge. The wreck became the mountain Oshu'gun in Nagrand, holding the weakened naaru K'ure. Velen kept his people's magic hidden and set up a Council of Exarchs to share leadership. The draenei built the city of Shattrath on the ruins of the ogre capital Goria and the great Temple of Karabor in Shadowmoon Valley. When ogres from Highmaul marched on Shattrath, draenei warriors killed their imperator, and the ogres never attacked it head-on again.",
    "The draenei traded with the orc clans, who revered Oshu'gun as a home of ancestral spirits, but kept a polite distance. For two centuries they lived in peace."
  ]],
  ["The Slaughter", [
    "About twelve years before the Dark Portal, Talgath found the draenei for Kil'jaeden. This time the demon lord chose not to attack directly, since the draenei had always escaped that way. He used the orcs. Through Gul'dan, the orcs were corrupted, united as the Horde and turned against their neighbors. The war lasted nearly eight years. Karabor was struck by the Dark Star, a Void power summoned by orc warlocks, and became the Black Temple. Shattrath was overrun. The orcs killed more than eighty percent of the draenei.",
    "Velen fled with a small band of survivors to the marshes of Zangarmarsh. Many who had fought the Horde were twisted by the fel magic around them and lost their bond to the Light. They became the Broken and the Lost Ones. Among them were the former exarch Akama and the vindicator Nobundo, who later learned to speak with the elements and brought the shaman's path to his people. After Draenor was torn apart and became Outland, the survivors hid in small, scattered enclaves so that no single discovery could doom them all."
  ]],
  ["The Exodar and the Alliance", [
    "When naaru came to Outland aboard their fortress Tempest Keep, Velen's people seized one of its ships, the Exodar, to look for allies. Kil'jaeden secretly let them go, hoping they would draw Azeroth into a war. Blood elf saboteurs on board wrecked the ship, and it crashed on the Azuremyst Isles off Kalimdor. The draenei joined the Alliance and helped lead its return to Outland in The Burning Crusade. After Kil'jaeden was driven back at the Sunwell, Velen used the heart of the fallen naaru M'uru to purify that fount of power. Velen later had a vision of a coming war between Light and shadow, so most draenei stayed on Azeroth to prepare its peoples.",
    "In Warlords of Draenor, Azeroth's heroes met the draenei of the alternate Draenor. There, the alternate Velen gave his life to turn the Dark Star back into the naaru K'ara, and the young vindicator Yrel rose to lead. In Legion, demons attacked the Exodar and killed the naaru O'ros. Velen learned that their commander, Rakeesh, was his own son, taken during the flight from Argus and made into a demon. The draenei built the warship Vindicaar, sailed to Argus, and met their lost kin, the Lightforged and the krokul who had stayed behind. Velen followed Kil'jaeden into the Nether and saw him destroyed. Before he died, Kil'jaeden admitted he envied Velen's faith, and Velen forgave him."
  ]],
  ["A People Reunited", [
    "The war on Argus left the draenei badly weakened. In Battle for Azeroth they welcomed the Lightforged into the Alliance, while on the alternate Draenor, Yrel's Lightbound crusade drove that world's orcs into exile. In Dragonflight, Velen accepted the Penitents, a band of demonic eredar seeking redemption, after their leader returned a shard of the eredar's sacred crystal. He then revived the Tishamaat, an old eredar rite of letting go of painful memories, and gathered draenei, Lightforged, Broken, Lost Ones, krokul and Penitents in the Exodar. There he declared that the exiles would build a new city and finally be home.",
    "Draenei went with the Alliance to Khaz Algar in The War Within. In Midnight, draenei paladins and priests answered the Light's call to defend the Sunwell from Xal'atath and the Void. Heroes also helped the Nethersent draenei of the world Nashabor escape captivity in the Voidstorm, and explorers found ruins on the world Naigtal left by the Genedar's passengers long ago."
  ]],
  ["Light, Crystal and Memory", [
    "Draenei life rests on the Light and on arcane magic. Many become vindicators, who are holy warriors, or anchorites, who are priests, and orders such as the Hand of Argus guard the Exodar. Their artificers shape purple arkonite crystals to power homes and tools, though this is a shadow of the eredar's old craft, and their great ships were built by the naaru. Draenei live very long lives and have few children.",
    "They honor their dead and built Auchindoun on Draenor to shield souls from demons who hunger for them. Their eyes glow blue or violet, and every draenei carries the naaru's gift of healing. They have long seen themselves as preparing to atone for their fallen kin, and there was once no worse insult than calling them kin to the Legion's eredar. The Penitents have begun to soften that wound."
  ]]
];

window.RACE_STORIES['lightforged'] = [
  ["The Xenedar Departs", [
    "The Lightforged draenei began among the exiles who fled the world Argus with Prophet Velen. Some time after that escape, the survivors split between two naaru ships. Most stayed with the Genedar and searched for a safe home. The finest warriors followed the Prime Naaru Xe'ra, called the Light Mother, aboard the Xenedar. Instead of hiding from the Burning Legion, they chose to fight it.",
    "Xe'ra led what became the Army of the Light, a crusade of Light-wielding races against the demons. Its most devoted soldiers underwent a ritual that filled their bodies with the essence of the Holy Light. They became the Lightforged, with pale skin, white hair, glowing golden eyes and golden markings."
  ]],
  ["A War Without End", [
    "For untold ages the Army struck at the Legion across the Twisting Nether and the worlds beyond. They raided Argus itself, the Legion's home and fortress, in quick strikes, always outnumbered. Other survivors of the Legion's crusade joined them over time. Their high commander was Lothraxion, a dreadlord, one of the Legion's own scheming demons, who had turned to the Light.",
    "After Draenor was torn apart, Lothraxion recruited two heroes of Azeroth's Second War who were stranded there, the human paladin Turalyon and the high elf ranger Alleria Windrunner. Time passes differently in the Nether. The decades that went by on Azeroth stretched to about a thousand years of war for them. Xe'ra filled Turalyon with the Light, and he rose to become High Exarch of the Army. Alleria, however, turned to the Void to save them both from the Legion, and left the Army.",
    "Before Azeroth's forces invaded Outland, Velen and the archmage Khadgar each begged the naaru for help. The Army could spare no soldiers, so three naaru, A'dal, M'uru and O'ros, came instead with their fortress Tempest Keep. As the war turned against the Lightforged, Turalyon recorded a plea for help inside a naaru relic, the Light's Heart, and cast it out into the cosmos, hoping it would reach Azeroth."
  ]],
  ["Victory on Argus", [
    "By the time of Legion, the Army was losing. The demons had shielded Argus against its raids, and the Light's Heart reached Velen as a last hope. She also sought Illidan Stormrage, whom she believed was a prophesied champion. When Azeroth's forces arrived above Argus aboard the draenei warship Vindicaar, the Xenedar was shot down. Captain Fareeya rallied the survivors on the planet's blasted surface, and the native krokul saved Turalyon's life.",
    "Xe'ra was restored and tried to bind Illidan to her vision of his destiny. Illidan broke free and destroyed her. The Lightforged had followed her for millennia, and Velen told them the Light had not died with her. They held the line at Antorus, the Legion's fortress, while Azeroth's heroes freed the imprisoned titans, who sealed Sargeras away. The crusade of the Lightforged was finally won."
  ]],
  ["Sworn to the Alliance", [
    "Turalyon believed the Alliance's ideals were worth defending and urged the Army to join it. With King Anduin Wrynn's blessing, the Lightforged pledged themselves to the Alliance in Battle for Azeroth. Aboard the Vindicaar, draenei from the Exodar could undergo trials in the Forge of Aeons to become Lightforged themselves, which reunited the two branches of the people.",
    "Lightforged soldiers fought in the Fourth War against the Horde. Blademaster Telaamon gave his life at the Battle of Dazar'alor, arguing that Sylvanas's Horde would doom Azeroth as the Legion had doomed Argus. The Army describes its Lightforged as immortal, yet many have died in battle, and their souls still pass into the Shadowlands. Some were even raised as death knights. Their children are born as ordinary draenei."
  ]],
  ["A Changing Crusade", [
    "In Dragonflight, part of the Army stayed on Argus to fight what remained of the Legion there, aided by repentant demonic eredar called the Penitents. At Velen's Tishamaat festival in the Exodar, Captain Fareeya said the Lightforged had lost far more than they had gained, but many hoped to reconnect with their non-Lightforged kin. Not all Lightforged agree on how to fight. One veteran, Ph'el Oman, lost faith after endless losses and became the first known Lightforged warlock, using fel magic alongside the Light.",
    "In The War Within, Army forces followed Turalyon to Khaz Algar to fight Xal'atath, a herald of the Void. Vindicator Jaelaana helped arm the earthen, the stone-made people of the Isle of Dorn, and Lightforged war machines defended the human Arathi of Hallowfall."
  ]],
  ["The Voidspire and After", [
    "In Midnight, the Light called many defenders to the Sunwell of Quel'Thalas when Xal'atath's Devouring Host attacked it. Turalyon led them as the Vanguard of the Light, and the Lightforged made up a large part of it. Turalyon's zeal caused friction with the blood elves, and in battle he accidentally struck his son Arator. When the Vanguard stormed the Voidspire, Xal'atath tore the dark naaru L'ura out of Alleria and corrupted the Sunwell. Turalyon and Alleria were lost to the Void, and their fate is unknown.",
    "Many Lightforged died or were badly wounded in that failed siege. Captain Fareeya took command of the Army. Her forces, though weakened, joined Riftblade Maella's campaign against the Hal'hadar, a secretive group of ethereal artificers and assassins, on the former Legion worlds of Val and Naigtal.",
    "As of Midnight, the Lightforged remain a smaller, battered army serving the Alliance from the Vindicaar and from Azeroth. They are disciplined, devout and shaped by a war longer than most mortal histories. Midnight also showed the danger of zeal, when some of Turalyon's own Vanguard officers, blinded by the Light, turned against his wife and son."
  ]]
];

window.RACE_STORIES['eredar'] = [
  ["The Wonder of Argus", [
    "The eredar arose on the world Argus. They were one of the oldest known races and gifted in every kind of magic. On Argus, art, science, magic and technology worked as one. Crystals of argunite powered their cities, and a mysterious triangular artifact, the Ata'mal crystal, helped their civilization grow. Their most sacred city was Eredath. Each year they held the Tishamaat, a rite in which they wrote painful memories on stones and let them go, and they bound the souls of great warriors into armored guardians called vigilants. Tall, horned and hoofed, with glowing eyes, they looked just as the draenei look today.",
    "Three leaders, Kil'jaeden, Archimonde and Velen, guided them as a triumvirate, and only these three could use the Ata'mal crystal. Even then, darker paths tempted some eredar. An order of sorcerers called the Wakeners, led by Thal'kiel, studied the Void and summoned demons in secret to seize power. Thal'kiel's own apprentice, Archimonde, betrayed and beheaded him."
  ]],
  ["Sargeras's Offer", [
    "The fallen titan Sargeras wanted to build an army to burn away all creation, and the eredar's genius drew his eye. He came in a radiant, beautiful form and promised the triumvirate knowledge without limit and worlds to rule. In return, the eredar would help him fix what he called a flaw at the heart of existence. Kil'jaeden and Archimonde were honored to accept.",
    "Velen saw a vision of his people twisted into demons and refused. He fled with a few hundred followers aboard the naaru ship Genedar. Talgath, an old friend of Velen, betrayed the escape, and Velen's son was taken. Sargeras then poured fel energy into the eredar who stayed. Their minds filled with fanatical whispers, and their bodies changed. The draenei began calling them man'ari, meaning unnatural beings.",
    "The date is uncertain. Older sources say the draenei had been fleeing for 25,000 years. The more recent short story Bringer of the Light places Sargeras's offer about 13,000 years ago."
  ]],
  ["Lords of the Burning Legion", [
    "The eredar were the first people to pledge themselves to Sargeras, and they became the commanders of his Burning Legion. Argus became the Legion's fortress, and the eredar tongue, Eredun, became its common language. Kil'jaeden, called the Deceiver, specialized in corrupting other peoples. Archimonde, called the Defiler, led the Legion's armies. Man'ari eredar served as warlocks, generals and enforcers on countless burned worlds. Most man'ari have red skin and fel-green eyes, and some changed further into hulking wrathguard or winged doommaidens.",
    "About 10,000 years before the Dark Portal, the Highborne elves of Azeroth called the Legion into their world. Archimonde led the invasion and killed the demigod stag Malorne before the Legion was thrown back in the War of the Ancients. Kil'jaeden, meanwhile, never stopped hunting Velen. Many man'ari secretly came to hate the Legion's slaughter, but they kept serving, because Kil'jaeden could sense doubt in their minds and punished it as betrayal."
  ]],
  ["Shadows Over Azeroth", [
    "About twelve years before the Dark Portal, Talgath found the draenei on Draenor. Kil'jaeden used the orcs there to slaughter them and then aimed the orcs at Azeroth. After the orcs lost, he took the spirit of their old shaman Ner'zhul and made him the Lich King, whose undead Scourge prepared Azeroth for the Legion. In the Third War, Archimonde invaded Kalimdor, but he was destroyed at Mount Hyjal when the night elves unleashed the power of their World Tree.",
    "Kil'jaeden tried again in The Burning Crusade. He used the fallen blood elf prince Kael'thas to turn the Sunwell into a gateway, but Azeroth's heroes banished him back into the Nether. In Warlords of Draenor, Archimonde led the Legion on the alternate Draenor and was killed there as well, after flinging Gul'dan into the main timeline to start a new invasion."
  ]],
  ["The Fall of the Legion", [
    "The Legion's third invasion began in Legion. The man'ari general Rakeesh attacked the draenei capital, the Exodar, and Velen realized the demon was his own son. Kil'jaeden fought Azeroth's heroes aboard his command ship in the Nether near Argus and was killed. Before he died, he admitted he envied Velen's faith, and Velen forgave him. Illidan Stormrage then pulled Argus close to Azeroth.",
    "Azeroth's forces and the Army of the Light invaded the eredar homeworld. Velen's forces killed Talgath in Eredath. At Antorus, the Burning Throne, heroes defeated the Legion's high command and freed the imprisoned titans, who sealed Sargeras away. The Burning Legion's long crusade was broken, though demons still lurked on Argus afterward."
  ]],
  ["The Penitents and Today", [
    "After the Legion's fall, some man'ari sought redemption. A band called the Penitents, led by Arzal'kal, fought Legion remnants on Argus beside the krokul, the abandoned draenei of the planet. In Dragonflight, Arzal'kal proved himself to Velen by recovering the Brilliant Star, a shard of the Ata'mal crystal. Velen invited the Penitents to stand with the draenei. Arzal'kal took back his old name, Arzaal, and the Penitents attended the Tishamaat, an old eredar rite revived at the Exodar. Most chose to stay on Argus so their presence would not upset the draenei of Azeroth, though some came to Azeroth to fight beside the Alliance.",
    "As of Midnight, the eredar are a people split three ways. Most are still demons, and Legion remnants still fight on Argus. A few redeemed man'ari live among the draenei or the far-flung Nethersent, and some of those defectors were among the people captured in the Voidstorm and later rescued. The rest, the draenei and the Lightforged, still carry the old eredar ways of crystal craft, long memory and the hope that their divided people might one day be whole."
  ]]
];
